<?php

/**
 * BaseTask
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property enum $type
 * @property string $token
 * @property integer $priority
 * @property enum $status
 * @property string $content
 * 
 * @method integer getId()       Returns the current record's "id" value
 * @method enum    getType()     Returns the current record's "type" value
 * @method string  getToken()    Returns the current record's "token" value
 * @method integer getPriority() Returns the current record's "priority" value
 * @method enum    getStatus()   Returns the current record's "status" value
 * @method string  getContent()  Returns the current record's "content" value
 * @method Task    setId()       Sets the current record's "id" value
 * @method Task    setType()     Sets the current record's "type" value
 * @method Task    setToken()    Sets the current record's "token" value
 * @method Task    setPriority() Sets the current record's "priority" value
 * @method Task    setStatus()   Sets the current record's "status" value
 * @method Task    setContent()  Sets the current record's "content" value
 * 
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTask extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('task');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('type', 'enum', 20, array(
             'type' => 'enum',
             'length' => 20,
             'values' => 
             array(
              0 => 'project.init',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('priority', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'comment' => 'Приоритет',
             'length' => 4,
             ));
        $this->hasColumn('status', 'enum', 10, array(
             'type' => 'enum',
             'length' => 10,
             'values' => 
             array(
              0 => 'run',
              1 => 'pause',
              2 => 'fail',
              3 => 'success',
             ),
             'notnull' => true,
             'default' => 'run',
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));

        $this->option('comment', 'Задача');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}