<?php

/**
 * BaseUserDelayedProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $product_id
 * @property boolean $is_wished
 * @property User $User
 * @property Product $Product
 * 
 * @method integer            getUserId()     Returns the current record's "user_id" value
 * @method integer            getProductId()  Returns the current record's "product_id" value
 * @method boolean            getIsWished()   Returns the current record's "is_wished" value
 * @method User               getUser()       Returns the current record's "User" value
 * @method Product            getProduct()    Returns the current record's "Product" value
 * @method UserDelayedProduct setUserId()     Sets the current record's "user_id" value
 * @method UserDelayedProduct setProductId()  Sets the current record's "product_id" value
 * @method UserDelayedProduct setIsWished()   Sets the current record's "is_wished" value
 * @method UserDelayedProduct setUser()       Sets the current record's "User" value
 * @method UserDelayedProduct setProduct()    Sets the current record's "Product" value
 * 
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserDelayedProduct extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_delayed_product');
        $this->hasColumn('user_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('product_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('is_wished', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));

        $this->option('comment', 'Отложенные товары пользователя');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}