<?php

/**
 * BaseRegion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $root_id
 * @property integer $lft
 * @property integer $rgt
 * @property integer $level
 * @property string $token
 * @property string $name
 * @property set $type
 * @property Doctrine_Collection $CerviceCenter
 * @property Doctrine_Collection $Stock
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method integer             getRootId()        Returns the current record's "root_id" value
 * @method integer             getLft()           Returns the current record's "lft" value
 * @method integer             getRgt()           Returns the current record's "rgt" value
 * @method integer             getLevel()         Returns the current record's "level" value
 * @method string              getToken()         Returns the current record's "token" value
 * @method string              getName()          Returns the current record's "name" value
 * @method set                 getType()          Returns the current record's "type" value
 * @method Doctrine_Collection getCerviceCenter() Returns the current record's "CerviceCenter" collection
 * @method Doctrine_Collection getStock()         Returns the current record's "Stock" collection
 * @method Region              setId()            Sets the current record's "id" value
 * @method Region              setRootId()        Sets the current record's "root_id" value
 * @method Region              setLft()           Sets the current record's "lft" value
 * @method Region              setRgt()           Sets the current record's "rgt" value
 * @method Region              setLevel()         Sets the current record's "level" value
 * @method Region              setToken()         Sets the current record's "token" value
 * @method Region              setName()          Sets the current record's "name" value
 * @method Region              setType()          Sets the current record's "type" value
 * @method Region              setCerviceCenter() Sets the current record's "CerviceCenter" collection
 * @method Region              setStock()         Sets the current record's "Stock" collection
 * 
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegion extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('region');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('root_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('lft', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('rgt', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('level', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('type', 'set', 10, array(
             'type' => 'set',
             'length' => 10,
             'values' => 
             array(
              0 => 'country',
              1 => 'area',
              2 => 'city',
             ),
             'notnull' => true,
             'comment' => 'Тип региона: страна, административная единица, город',
             ));

        $this->option('comment', 'Регион');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CerviceCenter', array(
             'local' => 'id',
             'foreign' => 'region_id'));

        $this->hasMany('Shop as Stock', array(
             'local' => 'id',
             'foreign' => 'region_id'));

        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             'rootColumnName' => 'root_id',
             ));
        $this->actAs($nestedset0);
    }
}