<?php

/**
 * BaseProductRatingTypeProperty
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $type_id
 * @property string $token
 * @property string $name
 * @property integer $position
 * @property ProductRatingType $Type
 * @property Doctrine_Collection $ProductRatingTypeProperty
 * 
 * @method integer                   getId()                        Returns the current record's "id" value
 * @method integer                   getTypeId()                    Returns the current record's "type_id" value
 * @method string                    getToken()                     Returns the current record's "token" value
 * @method string                    getName()                      Returns the current record's "name" value
 * @method integer                   getPosition()                  Returns the current record's "position" value
 * @method ProductRatingType         getType()                      Returns the current record's "Type" value
 * @method Doctrine_Collection       getProductRatingTypeProperty() Returns the current record's "ProductRatingTypeProperty" collection
 * @method ProductRatingTypeProperty setId()                        Sets the current record's "id" value
 * @method ProductRatingTypeProperty setTypeId()                    Sets the current record's "type_id" value
 * @method ProductRatingTypeProperty setToken()                     Sets the current record's "token" value
 * @method ProductRatingTypeProperty setName()                      Sets the current record's "name" value
 * @method ProductRatingTypeProperty setPosition()                  Sets the current record's "position" value
 * @method ProductRatingTypeProperty setType()                      Sets the current record's "Type" value
 * @method ProductRatingTypeProperty setProductRatingTypeProperty() Sets the current record's "ProductRatingTypeProperty" collection
 * 
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductRatingTypeProperty extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_rating_type_property');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('type_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('position', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'comment' => 'Порядок сортировки',
             'length' => 4,
             ));

        $this->option('comment', 'Свойства типа рейтинга товара');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProductRatingType as Type', array(
             'local' => 'type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('UserProductRating as ProductRatingTypeProperty', array(
             'local' => 'id',
             'foreign' => 'property_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}