<?php

/**
 * BaseSlot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property enum $type
 * @property string $token
 * @property string $name
 * @property Doctrine_Collection $Banner
 * 
 * @method integer             getId()     Returns the current record's "id" value
 * @method enum                getType()   Returns the current record's "type" value
 * @method string              getToken()  Returns the current record's "token" value
 * @method string              getName()   Returns the current record's "name" value
 * @method Doctrine_Collection getBanner() Returns the current record's "Banner" collection
 * @method Slot                setId()     Sets the current record's "id" value
 * @method Slot                setType()   Sets the current record's "type" value
 * @method Slot                setToken()  Sets the current record's "token" value
 * @method Slot                setName()   Sets the current record's "name" value
 * @method Slot                setBanner() Sets the current record's "Banner" collection
 * 
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSlot extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('slot');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('type', 'enum', 20, array(
             'type' => 'enum',
             'length' => 20,
             'values' => 
             array(
              0 => 'menu',
              1 => 'banner',
             ),
             'notnull' => true,
             'comment' => 'тип, или сущность',
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'название',
             'length' => 255,
             ));

        $this->option('comment', 'Слот');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Banner', array(
             'local' => 'id',
             'foreign' => 'slot_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}