<?php

/**
 * BaseProductGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Property
 * @property Doctrine_Collection $Product
 * @property Doctrine_Collection $ProductGroupRelation
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method string              getName()                 Returns the current record's "name" value
 * @method Doctrine_Collection getProperty()             Returns the current record's "Property" collection
 * @method Doctrine_Collection getProduct()              Returns the current record's "Product" collection
 * @method Doctrine_Collection getProductGroupRelation() Returns the current record's "ProductGroupRelation" collection
 * @method ProductGroup        setId()                   Sets the current record's "id" value
 * @method ProductGroup        setName()                 Sets the current record's "name" value
 * @method ProductGroup        setProperty()             Sets the current record's "Property" collection
 * @method ProductGroup        setProduct()              Sets the current record's "Product" collection
 * @method ProductGroup        setProductGroupRelation() Sets the current record's "ProductGroupRelation" collection
 * 
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductGroup extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_group');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('comment', 'Группировка товаров');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProductProperty as Property', array(
             'refClass' => 'ProductGroupPropertyRelation',
             'local' => 'product_group_id',
             'foreign' => 'product_property_id'));

        $this->hasMany('Product', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $this->hasMany('ProductGroupPropertyRelation as ProductGroupRelation', array(
             'local' => 'id',
             'foreign' => 'product_group_id'));
    }
}