<?php

/**
 * BaseGuardGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $User
 * @property Doctrine_Collection $Permission
 * @property Doctrine_Collection $GuardGroupPermission
 * @property Doctrine_Collection $GuardUserGroup
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method string              getName()                 Returns the current record's "name" value
 * @method string              getDescription()          Returns the current record's "description" value
 * @method Doctrine_Collection getUser()                 Returns the current record's "User" collection
 * @method Doctrine_Collection getPermission()           Returns the current record's "Permission" collection
 * @method Doctrine_Collection getGuardGroupPermission() Returns the current record's "GuardGroupPermission" collection
 * @method Doctrine_Collection getGuardUserGroup()       Returns the current record's "GuardUserGroup" collection
 * @method GuardGroup          setId()                   Sets the current record's "id" value
 * @method GuardGroup          setName()                 Sets the current record's "name" value
 * @method GuardGroup          setDescription()          Sets the current record's "description" value
 * @method GuardGroup          setUser()                 Sets the current record's "User" collection
 * @method GuardGroup          setPermission()           Sets the current record's "Permission" collection
 * @method GuardGroup          setGuardGroupPermission() Sets the current record's "GuardGroupPermission" collection
 * @method GuardGroup          setGuardUserGroup()       Sets the current record's "GuardUserGroup" collection
 * 
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGuardGroup extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('guard_group');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));

        $this->option('comment', 'Группа');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('GuardUser as User', array(
             'refClass' => 'GuardUserGroup',
             'local' => 'group_id',
             'foreign' => 'user_id'));

        $this->hasMany('GuardPermission as Permission', array(
             'refClass' => 'GuardGroupPermission',
             'local' => 'group_id',
             'foreign' => 'permission_id'));

        $this->hasMany('GuardGroupPermission', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $this->hasMany('GuardUserGroup', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}