<?php

/**
 * BaseGuardUserPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $permission_id
 * @property GuardUser $User
 * @property GuardPermission $Permission
 * 
 * @method integer             getUserId()        Returns the current record's "user_id" value
 * @method integer             getPermissionId()  Returns the current record's "permission_id" value
 * @method GuardUser           getUser()          Returns the current record's "User" value
 * @method GuardPermission     getPermission()    Returns the current record's "Permission" value
 * @method GuardUserPermission setUserId()        Sets the current record's "user_id" value
 * @method GuardUserPermission setPermissionId()  Sets the current record's "permission_id" value
 * @method GuardUserPermission setUser()          Sets the current record's "User" value
 * @method GuardUserPermission setPermission()    Sets the current record's "Permission" value
 * 
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGuardUserPermission extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('guard_user_permission');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('permission_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('GuardPermission as Permission', array(
             'local' => 'permission_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}