<?php

/**
 * BaseStock
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $token
 * @property string $name
 * @property enum $type
 * @property integer $region_id
 * @property integer $shop_id
 * @property Region $Region
 * @property Shop $Shop
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method string  getToken()     Returns the current record's "token" value
 * @method string  getName()      Returns the current record's "name" value
 * @method enum    getType()      Returns the current record's "type" value
 * @method integer getRegionId()  Returns the current record's "region_id" value
 * @method integer getShopId()    Returns the current record's "shop_id" value
 * @method Region  getRegion()    Returns the current record's "Region" value
 * @method Shop    getShop()      Returns the current record's "Shop" value
 * @method Stock   setId()        Sets the current record's "id" value
 * @method Stock   setToken()     Sets the current record's "token" value
 * @method Stock   setName()      Sets the current record's "name" value
 * @method Stock   setType()      Sets the current record's "type" value
 * @method Stock   setRegionId()  Sets the current record's "region_id" value
 * @method Stock   setShopId()    Sets the current record's "shop_id" value
 * @method Stock   setRegion()    Sets the current record's "Region" value
 * @method Stock   setShop()      Sets the current record's "Shop" value
 * 
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStock extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stock');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('type', 'enum', 10, array(
             'type' => 'enum',
             'length' => 10,
             'values' => 
             array(
              0 => 'main',
              1 => 'region',
              2 => 'shop',
              3 => 'provider',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('region_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('shop_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 20,
             ));

        $this->option('comment', 'Склад');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Region', array(
             'local' => 'region_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Shop', array(
             'local' => 'shop_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));
    }
}