<?php

/**
 * BaseNewsProductCategoryRelation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $news_id
 * @property integer $product_category_id
 * @property News $News
 * @property ProductCategory $ProductCategory
 * 
 * @method integer                     getNewsId()              Returns the current record's "news_id" value
 * @method integer                     getProductCategoryId()   Returns the current record's "product_category_id" value
 * @method News                        getNews()                Returns the current record's "News" value
 * @method ProductCategory             getProductCategory()     Returns the current record's "ProductCategory" value
 * @method NewsProductCategoryRelation setNewsId()              Sets the current record's "news_id" value
 * @method NewsProductCategoryRelation setProductCategoryId()   Sets the current record's "product_category_id" value
 * @method NewsProductCategoryRelation setNews()                Sets the current record's "News" value
 * @method NewsProductCategoryRelation setProductCategory()     Sets the current record's "ProductCategory" value
 * 
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNewsProductCategoryRelation extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('news_product_category_relation');
        $this->hasColumn('news_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('product_category_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 20,
             ));

        $this->option('comment', 'Связь новости с категорией товаров');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('News', array(
             'local' => 'news_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ProductCategory', array(
             'local' => 'product_category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}