<?php

/**
 * BaseServiceCategoryProductTypeReference
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $product_type_id
 * @property ServiceCategory $ServiceCategory
 * @property ProductType $ProductType
 * 
 * @method integer                             getCategoryId()      Returns the current record's "category_id" value
 * @method integer                             getProductTypeId()   Returns the current record's "product_type_id" value
 * @method ServiceCategory                     getServiceCategory() Returns the current record's "ServiceCategory" value
 * @method ProductType                         getProductType()     Returns the current record's "ProductType" value
 * @method ServiceCategoryProductTypeReference setCategoryId()      Sets the current record's "category_id" value
 * @method ServiceCategoryProductTypeReference setProductTypeId()   Sets the current record's "product_type_id" value
 * @method ServiceCategoryProductTypeReference setServiceCategory() Sets the current record's "ServiceCategory" value
 * @method ServiceCategoryProductTypeReference setProductType()     Sets the current record's "ProductType" value
 * 
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServiceCategoryProductTypeReference extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('service_category_product_type_reference');
        $this->hasColumn('category_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('product_type_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 20,
             ));

        $this->option('comment', 'Связь категории услуги F1 и типа товара');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ServiceCategory', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('ProductType', array(
             'local' => 'product_type_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));
    }
}