<?php

/**
 * BaseProductPhoto3D
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $resource
 * @property integer $product_id
 * @property integer $position
 * @property Product $Product
 * 
 * @method integer        getId()         Returns the current record's "id" value
 * @method string         getName()       Returns the current record's "name" value
 * @method string         getResource()   Returns the current record's "resource" value
 * @method integer        getProductId()  Returns the current record's "product_id" value
 * @method integer        getPosition()   Returns the current record's "position" value
 * @method Product        getProduct()    Returns the current record's "Product" value
 * @method ProductPhoto3D setId()         Sets the current record's "id" value
 * @method ProductPhoto3D setName()       Sets the current record's "name" value
 * @method ProductPhoto3D setResource()   Sets the current record's "resource" value
 * @method ProductPhoto3D setProductId()  Sets the current record's "product_id" value
 * @method ProductPhoto3D setPosition()   Sets the current record's "position" value
 * @method ProductPhoto3D setProduct()    Sets the current record's "Product" value
 * 
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductPhoto3D extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_photo3_d');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('resource', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('product_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('position', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Порядок отображения',
             'length' => 4,
             ));

        $this->option('comment', '3D фото товара');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $corable0 = new Doctrine_Template_Corable(array(
             'push' => 'disable',
             ));
        $this->actAs($timestampable0);
        $this->actAs($corable0);
    }
}