<?php

/**
 * BaseProductPhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $resource
 * @property integer $product_id
 * @property boolean $view_show
 * @property boolean $view_list
 * @property Product $Product
 * 
 * @method integer      getId()         Returns the current record's "id" value
 * @method string       getName()       Returns the current record's "name" value
 * @method string       getResource()   Returns the current record's "resource" value
 * @method integer      getProductId()  Returns the current record's "product_id" value
 * @method boolean      getViewShow()   Returns the current record's "view_show" value
 * @method boolean      getViewList()   Returns the current record's "view_list" value
 * @method Product      getProduct()    Returns the current record's "Product" value
 * @method ProductPhoto setId()         Sets the current record's "id" value
 * @method ProductPhoto setName()       Sets the current record's "name" value
 * @method ProductPhoto setResource()   Sets the current record's "resource" value
 * @method ProductPhoto setProductId()  Sets the current record's "product_id" value
 * @method ProductPhoto setViewShow()   Sets the current record's "view_show" value
 * @method ProductPhoto setViewList()   Sets the current record's "view_list" value
 * @method ProductPhoto setProduct()    Sets the current record's "Product" value
 * 
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductPhoto extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_photo');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('resource', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('product_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('view_show', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Показывать фото в карточке товара?',
             ));
        $this->hasColumn('view_list', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'показывать фото в списке товаров?',
             ));

        $this->option('comment', 'Фото товара');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $corable0 = new Doctrine_Template_Corable(array(
             'push' => 'disable',
             ));
        $this->actAs($timestampable0);
        $this->actAs($corable0);
    }
}