<?php

/**
 * BaseSimilarProductGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $product_type_id
 * @property string $name
 * @property string $products
 * @property integer $match
 * @property ProductType $ProductType
 * @property Doctrine_Collection $Property
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method integer             getProductTypeId()   Returns the current record's "product_type_id" value
 * @method string              getName()            Returns the current record's "name" value
 * @method string              getProducts()        Returns the current record's "products" value
 * @method integer             getMatch()           Returns the current record's "match" value
 * @method ProductType         getProductType()     Returns the current record's "ProductType" value
 * @method Doctrine_Collection getProperty()        Returns the current record's "Property" collection
 * @method SimilarProductGroup setId()              Sets the current record's "id" value
 * @method SimilarProductGroup setProductTypeId()   Sets the current record's "product_type_id" value
 * @method SimilarProductGroup setName()            Sets the current record's "name" value
 * @method SimilarProductGroup setProducts()        Sets the current record's "products" value
 * @method SimilarProductGroup setMatch()           Sets the current record's "match" value
 * @method SimilarProductGroup setProductType()     Sets the current record's "ProductType" value
 * @method SimilarProductGroup setProperty()        Sets the current record's "Property" collection
 * 
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSimilarProductGroup extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('similar_product_group');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('product_type_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('products', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'Список id товаров через запятую, для формирования списка аналогичных товаров',
             ));
        $this->hasColumn('match', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'comment' => 'Количество совпадающих параметров у товаров для учета их как аналогичных',
             'length' => 4,
             ));

        $this->option('comment', 'Группа аналогичного товара');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProductType', array(
             'local' => 'product_type_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('SimilarProductProperty as Property', array(
             'local' => 'id',
             'foreign' => 'group_id'));
    }
}