<?php

/**
 * BaseNewsProductRelation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $news_id
 * @property integer $product_id
 * @property News $News
 * @property Product $Product
 * 
 * @method integer             getNewsId()     Returns the current record's "news_id" value
 * @method integer             getProductId()  Returns the current record's "product_id" value
 * @method News                getNews()       Returns the current record's "News" value
 * @method Product             getProduct()    Returns the current record's "Product" value
 * @method NewsProductRelation setNewsId()     Sets the current record's "news_id" value
 * @method NewsProductRelation setProductId()  Sets the current record's "product_id" value
 * @method NewsProductRelation setNews()       Sets the current record's "News" value
 * @method NewsProductRelation setProduct()    Sets the current record's "Product" value
 * 
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNewsProductRelation extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('news_product_relation');
        $this->hasColumn('news_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('product_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 20,
             ));

        $this->option('comment', 'Связь новости с продуктом');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('News', array(
             'local' => 'news_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}