<?php

/**
 * BaseProductPriceList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property boolean $is_default
 * @property boolean $is_active
 * @property Doctrine_Collection $Price
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getName()       Returns the current record's "name" value
 * @method boolean             getIsDefault()  Returns the current record's "is_default" value
 * @method boolean             getIsActive()   Returns the current record's "is_active" value
 * @method Doctrine_Collection getPrice()      Returns the current record's "Price" collection
 * @method ProductPriceList    setId()         Sets the current record's "id" value
 * @method ProductPriceList    setName()       Sets the current record's "name" value
 * @method ProductPriceList    setIsDefault()  Sets the current record's "is_default" value
 * @method ProductPriceList    setIsActive()   Sets the current record's "is_active" value
 * @method ProductPriceList    setPrice()      Sets the current record's "Price" collection
 * 
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductPriceList extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_price_list');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_default', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Цена по-умолчанию для всех регионов?',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Цена по-умолчанию для всех регионов?',
             ));

        $this->option('comment', 'Прайс-листы');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProductPrice as Price', array(
             'local' => 'id',
             'foreign' => 'product_price_list_id'));

        $corable0 = new Doctrine_Template_Corable(array(
             'push' => 'disable',
             ));
        $this->actAs($corable0);
    }
}