<?php

/**
 * BaseProductHelperQuestion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $helper_id
 * @property string $name
 * @property boolean $is_active
 * @property integer $position
 * @property ProductHelper $Helper
 * @property Doctrine_Collection $Answer
 * 
 * @method integer               getId()        Returns the current record's "id" value
 * @method integer               getHelperId()  Returns the current record's "helper_id" value
 * @method string                getName()      Returns the current record's "name" value
 * @method boolean               getIsActive()  Returns the current record's "is_active" value
 * @method integer               getPosition()  Returns the current record's "position" value
 * @method ProductHelper         getHelper()    Returns the current record's "Helper" value
 * @method Doctrine_Collection   getAnswer()    Returns the current record's "Answer" collection
 * @method ProductHelperQuestion setId()        Sets the current record's "id" value
 * @method ProductHelperQuestion setHelperId()  Sets the current record's "helper_id" value
 * @method ProductHelperQuestion setName()      Sets the current record's "name" value
 * @method ProductHelperQuestion setIsActive()  Sets the current record's "is_active" value
 * @method ProductHelperQuestion setPosition()  Sets the current record's "position" value
 * @method ProductHelperQuestion setHelper()    Sets the current record's "Helper" value
 * @method ProductHelperQuestion setAnswer()    Sets the current record's "Answer" collection
 * 
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductHelperQuestion extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_helper_question');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('helper_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('position', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'comment' => 'Порядок сортировки',
             'length' => 4,
             ));

        $this->option('comment', 'Вопрос для помошника выбора товара');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProductHelper as Helper', array(
             'local' => 'helper_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ProductHelperAnswer as Answer', array(
             'local' => 'id',
             'foreign' => 'question_id'));
    }
}