<?php

/**
 * BasePaymentMethod
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $core_id
 * @property string $token
 * @property string $name
 * @property string $description
 * @property boolean $is_active
 * @property boolean $is_legal
 * @property boolean $is_personal
 * @property Doctrine_Collection $Order
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getCoreId()      Returns the current record's "core_id" value
 * @method string              getToken()       Returns the current record's "token" value
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method boolean             getIsActive()    Returns the current record's "is_active" value
 * @method boolean             getIsLegal()     Returns the current record's "is_legal" value
 * @method boolean             getIsPersonal()  Returns the current record's "is_personal" value
 * @method Doctrine_Collection getOrder()       Returns the current record's "Order" collection
 * @method PaymentMethod       setId()          Sets the current record's "id" value
 * @method PaymentMethod       setCoreId()      Sets the current record's "core_id" value
 * @method PaymentMethod       setToken()       Sets the current record's "token" value
 * @method PaymentMethod       setName()        Sets the current record's "name" value
 * @method PaymentMethod       setDescription() Sets the current record's "description" value
 * @method PaymentMethod       setIsActive()    Sets the current record's "is_active" value
 * @method PaymentMethod       setIsLegal()     Sets the current record's "is_legal" value
 * @method PaymentMethod       setIsPersonal()  Sets the current record's "is_personal" value
 * @method PaymentMethod       setOrder()       Sets the current record's "Order" collection
 * 
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePaymentMethod extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('payment_method');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('core_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => false,
             'comment' => 'ид записи в Core',
             'length' => 20,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'length' => 500,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Способ оплаты активен?',
             ));
        $this->hasColumn('is_legal', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Этот способ оплаты доступен для юр. лиц?',
             ));
        $this->hasColumn('is_personal', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Этот способ оплаты доступен для физ. лиц?',
             ));

        $this->option('comment', 'Способ оплаты');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Order', array(
             'local' => 'id',
             'foreign' => 'payment_method_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $corable0 = new Doctrine_Template_Corable(array(
             'push' => 'disable',
             ));
        $this->actAs($timestampable0);
        $this->actAs($corable0);
    }
}