<?php

/**
 * BaseDeliveryPeriod
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $delivery_type_id
 * @property string $name
 * @property DeliveryType $DeliveryType
 * @property Doctrine_Collection $Order
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method integer             getDeliveryTypeId()   Returns the current record's "delivery_type_id" value
 * @method string              getName()             Returns the current record's "name" value
 * @method DeliveryType        getDeliveryType()     Returns the current record's "DeliveryType" value
 * @method Doctrine_Collection getOrder()            Returns the current record's "Order" collection
 * @method DeliveryPeriod      setId()               Sets the current record's "id" value
 * @method DeliveryPeriod      setDeliveryTypeId()   Sets the current record's "delivery_type_id" value
 * @method DeliveryPeriod      setName()             Sets the current record's "name" value
 * @method DeliveryPeriod      setDeliveryType()     Sets the current record's "DeliveryType" value
 * @method DeliveryPeriod      setOrder()            Sets the current record's "Order" collection
 * 
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDeliveryPeriod extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('delivery_period');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('delivery_type_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));

        $this->option('comment', 'Периоды времени для доставки');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DeliveryType', array(
             'local' => 'delivery_type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Order', array(
             'local' => 'id',
             'foreign' => 'delivery_period_id'));

        $corable0 = new Doctrine_Template_Corable(array(
             'push' => 'disable',
             ));
        $this->actAs($corable0);
    }
}