<?php

/**
 * BaseShop
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $token
 * @property string $name
 * @property integer $region_id
 * @property Region $Region
 * @property Doctrine_Collection $Stock
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getToken()     Returns the current record's "token" value
 * @method string              getName()      Returns the current record's "name" value
 * @method integer             getRegionId()  Returns the current record's "region_id" value
 * @method Region              getRegion()    Returns the current record's "Region" value
 * @method Doctrine_Collection getStock()     Returns the current record's "Stock" collection
 * @method Shop                setId()        Sets the current record's "id" value
 * @method Shop                setToken()     Sets the current record's "token" value
 * @method Shop                setName()      Sets the current record's "name" value
 * @method Shop                setRegionId()  Sets the current record's "region_id" value
 * @method Shop                setRegion()    Sets the current record's "Region" value
 * @method Shop                setStock()     Sets the current record's "Stock" collection
 * 
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShop extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shop');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('region_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 20,
             ));

        $this->option('comment', 'Магазин');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Region', array(
             'local' => 'region_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('Stock', array(
             'local' => 'id',
             'foreign' => 'shop_id'));
    }
}