<?php

/**
 * BaseGuardGroupPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $group_id
 * @property integer $permission_id
 * @property GuardGroup $Group
 * @property GuardPermission $Permission
 * 
 * @method integer              getGroupId()       Returns the current record's "group_id" value
 * @method integer              getPermissionId()  Returns the current record's "permission_id" value
 * @method GuardGroup           getGroup()         Returns the current record's "Group" value
 * @method GuardPermission      getPermission()    Returns the current record's "Permission" value
 * @method GuardGroupPermission setGroupId()       Sets the current record's "group_id" value
 * @method GuardGroupPermission setPermissionId()  Sets the current record's "permission_id" value
 * @method GuardGroupPermission setGroup()         Sets the current record's "Group" value
 * @method GuardGroupPermission setPermission()    Sets the current record's "Permission" value
 * 
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGuardGroupPermission extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('guard_group_permission');
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('permission_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GuardGroup as Group', array(
             'local' => 'group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('GuardPermission as Permission', array(
             'local' => 'permission_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}