<?php

/**
 * Banner
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Banner extends BaseBanner
{
  public function preSave($event)
  {
    parent::preSave($event); // important!

    $record = $event->getInvoker();

    if (empty($record->token))
    {
      $record->token = uniqid();
    }
  }
}
