<?php

/**
 * Banner
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Banner extends BaseBanner
{
  public function preSave($event)
  {
    parent::preSave($event); // important!

    $record = $event->getInvoker();

    if (empty($record->token))
    {
      $record->token = uniqid();
    }
  }

  public function importFromCore(array $data)
  {
    parent::importFromCore($data);

    if (!empty($data['item_list']))
    {
      $existing = array(); // существуюшие элементы
      foreach ($this->Item as $index => $bannerItem)
      {
        $existing[$bannerItem->core_id] = $index;
      }

      $new = array(); // новые элементы
      foreach ($data['item_list'] as $relationData)
      {
        $new[] = $relationData['id'];

        $index = array_key_exists($relationData['id'], $existing) ? $existing[$relationData['id']] : false;

        if (false !== $index)
        {
          $this->Item[$index]->importFromCore($relationData);
        }
        else {
          $bannerItem = new BannerItem();
          $bannerItem->importFromCore($relationData);
          $this->Item[] = $bannerItem;
        }
      }

      $unlink = array_diff(array_keys($existing), $new);
      $unlink = count($unlink) ? BannerItemTable::getInstance()->getIdsByCoreIds($unlink) : array();
      if ($this->id && count($unlink))
      {
        $q = Doctrine_Query::create()
           ->delete('BannerItem')
           ->andWhereIn('id', $unlink)
        ;
        $deleted = $q->execute();
      }
    }
  }
}
