<?php

/**
 * BannerTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BannerTable extends myDoctrineTable
{

  /**
   * Returns an instance of this class.
   *
   * @return object BannerTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Banner');
  }

  public function getCoreMapping()
  {
    return array(
      'id'          => 'core_id',
      'name'        => 'name',
      'is_active'   => 'is_active',
      'is_dummy'    => 'is_dummy',
      'media_image' => 'image',
      'start'       => 'start_at',
      'finish'      => 'end_at',
      'position'    => 'position',
    );
  }

  public function getListBySlot(Slot $slot, array $params = array())
  {
    $this->applyDefaultParameters($params);

    $q = $this->createBaseQuery($params);

    $q->addWhere('banner.slot_id = ?', $slot->id)
      ->orderBy('banner.position')
    ;

    $this->setQueryParameters($q, $params);

    $ids = $this->getIdsByQuery($q);

    return $this->createListByIds($ids, $params);
  }
}