<?php

/**
 * BannerItemTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BannerItemTable extends myDoctrineTable
{

  /**
   * Returns an instance of this class.
   *
   * @return object BannerItemTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('BannerItem');
  }

  public function getCoreMapping()
  {
    return array(
      'id'           => 'core_id',
      'item_type_id' => array('name' => 'type', 'mapping' => array(1 => 'product')),
      'position'     => 'position',
    );
  }

  public function getCacheTags($record)
  {
    /*$tags = array();
    if (!empty($record['id']))
    {
      $tags[] = "banner-{$record['banner_id']}";
    }

    return $tags;*/
    return array();
  }

  public function getCacheEraserKeys($record, $action = null)
  {
    /*return array(
      'banner-'.$record['banner_id'],
    );*/
    return array();
  }
}