<?php

/**
 * UserAddress
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Callback extends BaseCallback
{
/*
  public function save()
  {
    $data = Core::getInstance()->createCallback($this->getData());
    return $data;
  }

*/
    
    /*
public function save(Doctrine_Connection $conn = null) {
    parent::save($conn);
    
    //отправляем запрос на сохранение в ядро
    print_r($this->getData());
    exit();
    $data = Core::getInstance()->createCallback($this->getData());
    
    //отправляем письмо администратору
    $mailer = Swift_Mailer::newInstance(Swift_MailTransport::newInstance());
    $message = Swift_Message::newInstance( $this->getValue('theme') )
             ->setFrom(array($this->getValue('emeil') => $this->getValue('name')))
             ->setTo(array('olga--tru@yandex.ru' => 'site admin'))
             ->setBody('Вопрос на сайте!', 'text/html');
    $res = $mailer->send($message);
        
    //return $data;
}
*/
    
  public function exportToCore()
  {
    $data = parent::exportToCore();

    return $data;
  }    
}
