<?php

/**
 * CallbackTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CallbackTable extends myDoctrineTable
{

  /**
   * Returns an instance of this class.
   *
   * @return object CallbackTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Callback');
  }

}