<?php

/**
 * DeliveryPeriodTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeliveryPeriodTable extends myDoctrineTable
{
  /**
   * Returns an instance of this class.
   *
   * @return object DeliveryPeriodTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('DeliveryPeriod');
  }

  public function getCoreMapping()
  {
    return array(
      'id'               => 'core_id',
      'name'             => 'name',

      'delivery_type_id' => array('rel' => 'DeliveryType'),
    );
  }
}