<?php

/**
 * DeliveryTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeliveryTypeTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeliveryTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DeliveryType');
    }
}