<?php

/**
 * GuardGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GuardGroupTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object GuardGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GuardGroup');
    }
}