<?php

/**
 * GuardUserGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GuardUserGroupTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object GuardUserGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GuardUserGroup');
    }
}