<?php

/**
 * GuardRememberKeyTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GuardRememberKeyTable extends myDoctrineTable
{

  /**
   * Returns an instance of this class.
   *
   * @return object GuardRememberKeyTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('GuardRememberKey');
  }

}