<?php

/**
 * IpadActionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IpadActionTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object IpadActionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IpadAction');
    }
}