<?php

/**
 * NewsProductRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsProductRelationTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewsProductRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NewsProductRelation');
    }
}
