<?php

/**
 * OrderProductRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrderProductRelationTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrderProductRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrderProductRelation');
    }
}