<?php

/**
 * OrderTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrderTable extends myDoctrineTable
{

  /**
   * Returns an instance of this class.
   *
   * @return object OrderTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Order');
  }

  public function getDefaultParameters()
  {
    return array(
      'with_products' => false,
    );
  }

  public function createBaseQuery(array $params = array())
  {
    $this->applyDefaultParameters($params);

    $q = $this->createQuery('order');

    if ($params['with_products'])
    {
      $q->leftJoin('order.ProductRelation orderProductRelation')
        ->addOrderBy('orderProductRelation.position')
      ;
    }

    return $q;
  }

  public function getById($id, array $params = array())
  {
    $this->applyDefaultParameters($params);

    $q = $this->createBaseQuery($params);

    $this->setQueryParameters($q, $params);

    $q->addWhere('order.id = ?', $id);
    $q->useResultCache(true, null, $this->getRecordQueryHash($id, $params));

    $record = $q->fetchOne();
    if (!$record)
    {
      return $record;
    }

    if ($params['with_products'])
    {
      foreach ($record['ProductRelation'] as $productRelation)
      {
        $productRelation['Product'] = ProductTable::getInstance()->getById($productRelation['product_id']);
      }
    }

    return $record;
  }

  public function getForRoute(array $params)
  {
    $id = isset($params['order']) ? $this->getIdBy('token', $params['order']) : null;

    return $this->getById($id, array(
      'with_products' => true,
    ));
  }

  public function getListByUser($user_id, array $params = array())
  {
    $this->applyDefaultParameters($params);

    $q = $this->createBaseQuery($params);

    $q->addWhere('order.user_id = ?', $user_id);

    $this->setQueryParameters($q, $params);

    $ids = $this->getIdsByQuery($q);

    return $this->createListByIds($ids, $params);
  }
}