<?php

/**
 * OrderTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrderTable extends myDoctrineTable
{

  /**
   * Returns an instance of this class.
   *
   * @return object OrderTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Order');
  }

  public function getDefaultParameters()
  {
    return array(
      'with_products' => false,
    );
  }

  public function createBaseQuery(array $params = array())
  {
    $this->applyDefaultParameters($params);

    $q = $this->createQuery('order');

    if ($params['with_products'])
    {
      $q->leftJoin('order.ProductRelation orderProductRelation')
        ->addOrderBy('orderProductRelation.position')
      ;
    }

    return $q;
  }

  public function getById($id, array $params = array())
  {
    $this->applyDefaultParameters($params);

    $q = $this->createBaseQuery($params);

    $this->setQueryParameters($q, $params);

    $q->addWhere('order.id = ?', $id);
    $q->useResultCache(true, null, $this->getRecordQueryHash($id, $params));

    $record = $q->fetchOne();
    if (!$record)
    {
      return $record;
    }

    if ($params['with_products'])
    {
      foreach ($record['ProductRelation'] as $productRelation)
      {
        $productRelation['Product'] = ProductTable::getInstance()->getById($productRelation['product_id']);
      }
    }

    return $record;
  }

  public function getByToken($token, array $params = array())
  {
    //TODO: тут должен быть вразумительный поиск по token

    $this->applyDefaultParameters($params);

    $q = $this->createBaseQuery($params);

    $this->setQueryParameters($q, $params);

    $q->addWhere('order.token = ?', $token);
    $q->useResultCache(true, null, $this->getRecordQueryHash($token, $params));

    $record = $q->fetchOne();
    if (!$record)
    {
      return $record;
    }

    if ($params['with_products'])
    {
      foreach ($record['ProductRelation'] as $productRelation)
      {
        $productRelation['Product'] = ProductTable::getInstance()->getById($productRelation['product_id']);
      }
    }

    return $record;
  }

  public function getForRoute(array $params)
  {
    $id = isset($params['order']) ? $this->getIdBy('token', $params['order']) : null;

    return $this->getById($id, array(
      'with_products' => true,
    ));
  }

  public function getListByUser($user_id, array $params = array())
  {
    $this->applyDefaultParameters($params);

    $q = $this->createBaseQuery($params);

    $q->addWhere('order.user_id = ?', $user_id);

    $this->setQueryParameters($q, $params);

    $ids = $this->getIdsByQuery($q);

    return $this->createListByIds($ids, $params);
  }

  public function getCoreMapping()
  {
    return array(
      'id'                => 'core_id',
      'type_id'           => 'type_id',
      'is_legal'          => 'is_legal',
      'last_name'         => 'recipient_last_name',
      'first_name'        => 'recipient_first_name',
      'middle_name'       => 'recipient_middle_name',
      'mobile'            => 'recipient_phonenumbers',
      'is_receive_sms'    => 'is_receive_sms',
      'payment_status_id' => 'payment_status_id',
      'payment_detail'    => 'payment_details',
      'sum'               => 'sum',
      'is_delivery'       => 'is_delivery',
      'delivery_date'     => 'delivered_at',
      'address'           => 'address',
      'zip_code'          => 'zip_code',
      'is_gift'           => 'is_gift',
      'extra'             => 'extra',
      'ip'                => 'ip',
      'is_paid_delivery'  => 'is_paid_delivery',
/*      '' => '',
      '' => '',
      '' => '',
      '' => '',
      '' => '',
      '' => '',
      '' => '',
      '' => '',
      '' => '',
      '' => '',
      '' => '',
      '' => '',
      "first_name"      => "recipient_first_name",
      "last_name"       => "recipient_last_name",
      "middle_name"     => "recipient_middle_name",
      "sum"             => "sum",
      "address"         => "address",*/
    );
  }
}