<?php

/**
 * OrderProductRelation
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class OrderProductRelation extends BaseOrderProductRelation
{
  public function getFormattedPrice()
  {
    return number_format($this->price, 0, ',', ' ').' руб';
  }
}
