<?php

/**
 * PaymentMethod
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PaymentMethod extends BasePaymentMethod
{
  public function getChoiseForOrder()
  {
    return array('label' => $this->name, 'description' => $this->description, );
  }

}
