<?php

/**
 * ProductPropertyOptionTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductPropertyOptionTable extends myDoctrineTable
{

  /**
   * Returns an instance of this class.
   *
   * @return object ProductPropertyOptionTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ProductPropertyOption');
  }

  public function getCoreMapping()
  {
    return array(
      'id'          => 'core_id',
      'name'        => 'name',
    );
  }
}