<?php

/**
 * ProductState
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductState extends BaseProductState
{
  public function importFromCore(array $data)
  {
    parent::importFromCore($data);

    //есть на складе, если есть хоть где-нибудь
    $this->is_instock = $data['is_shop'] || $data['is_store'] || $data['is_supplier'];

    //карточка товара доступна всегда по прямой ссылке
    $this->view_show = 1;

    //в списке товара показывать только если есть картинка и цена
    $this->view_list = $data['is_image'] && $data['is_price'] && $this->is_instock;
  }
}
