<?php

/**
 * ProductHelperQuestionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductHelperQuestionTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductHelperQuestionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductHelperQuestion');
    }
}