<?php

/**
 * ProductCategoryLinkTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductCategoryLinkTable extends myDoctrineTable
{

  /**
   * Returns an instance of this class.
   *
   * @return object ProductCategoryLinkTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ProductCategoryLink');
  }

  public function getQueryRootAlias()
  {
    return 'productCategoryLink';
  }

  public function getListByCategory(ProductCategory $category, array $params = array())
  {
    $key = $this->getQueryHash("productCategory-{$category['id']}/productCategoryLink-all", $params);

    $return = $this->getCachedByKey($key);
    if (!$return)
    {
      $q = $this->createBaseQuery($params);

      $q->addWhere('productCategoryLink.product_category_id = ?', $category['id']);

      $this->setQueryParameters($q, $params);

      $ids = $this->getIdsByQuery($q, $params);

      $return = $this->createListByIds($ids, $params);
      if ($this->isCacheEnabled())
      {
        $this->getCache()->set($key, $return, 259200); // обновить кеш через 3 дня
        $this->getCache()->addTag("productCategory-{$category['id']}", $key);
        foreach ($ids as $id)
        {
          $this->getCache()->addTag("productCategoryLink-{$id}", $key);
        }
      }
    }

    return $return;
  }
}