<?php

/**
 * ProductCommentTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductCommentTable extends myDoctrineTable
{

  /**
   * Returns an instance of this class.
   *
   * @return object ProductCommentTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ProductComment');
  }

  public function getDefaultParameters()
  {
    return array(
      'order' => 'created_at DESC',
    );
  }

  public function createBaseQuery(array $params = array())
  {
    $this->applyDefaultParameters($params);

    $q = $this->createQuery('productComment');

    return $q;
  }

  public function getListByProduct(Product $product, array $params = array())
  {
    $this->applyDefaultParameters($params);

    $q = $this->createBaseQuery($params);

    $q->where('productComment.product_id = ?', $product->id)
      //->useResultCache(true, null, $this->getQueryHash("product-{$product->id}/productComment-all", $params))
    ;

    $this->setQueryParameters($q, $params);

    $ids = $this->getIdsByQuery($q);

    return $this->createListByIds($ids, $params);
  }

  public function getListByUser(User $user, array $params = array())
  {
    $this->applyDefaultParameters($params);

    $q = $this->createBaseQuery($params);

    $q->where('productComment.user_id = ?', $user->id);

    $this->setQueryParameters($q, $params);

    $ids = $this->getIdsByQuery($q);

    return $this->createListByIds($ids, $params);
  }
}