<?php

/**
 * ProductLine
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductLine extends BaseProductLine
{
  public function toParams()
  {
    return array(
      'line' => $this->token,
    );
  }

  public function importFromCore(array $data)
  {
    parent::importFromCore($data);

    $this->token = empty($this->token) ? (uniqid().'-'.myToolkit::urlize($this->name)) : $this->token;
  }

  public function getCount()
  {
    return $this->getTable()->getProductCountById($this->id);
  }
}
