<?php

/**
 * ProductCategory
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductCategory extends BaseProductCategory
{

  public function __toString()
  {
    return (string) $this->name;
  }

  public function toParams()
  {
    return array(
      'productCategory' => $this->token,
    );
  }

  public function countProduct()
  {
    return ProductTable::getInstance()->countByCategory($this);
  }

  public function getPreviewProduct()
  {
    return ProductTable::getInstance()->getByCategory($this);
  }

  public function getSubCategories()
  {
    return ProductCategoryTable::getInstance()->getSubList(array('root_id' => $this->root_id));
  }
/**
 *
 * @return TagGroup Collection
 */
  public function getTagGroupForFilter()
  {
    //делаем список тэгов без учета тегов без товаров
    $categoryTable = ProductCategoryTable::getInstance();

    //берем только тэги, у которых есть продукты
    $tagIds = $categoryTable->getTagIds($this);

    if (!is_array($tagIds))
    {
      $tagIds = array($tagIds);
    }

    //возвращаем тэги, отсортированные в правильном порядке
    return $this->getTagGroupByIdWithOrder($tagIds);
  }
/**
 *
 * @return FilterGroup Collection
 */
  public function getFilterGroupForFilter()
  {
    //делаем список тэгов без учета тегов без товаров
    $categoryTable = ProductCategoryTable::getInstance();

    //берем property_id и option_id, которые существуют в этой категории
    $properties = ProductPropertyTable::getInstance()->getForFilter($this);

    //формируем новую коллекцию групп тегов только с рабочими тэгами
    $newFilter = ProductFilterTable::getInstance()->createList();

    $propertyIds = array();
    foreach ($properties as $key => $property)
    {
      $propertyIds[$property['id']] = $key;
    }

    foreach ($this->FilterGroup->Filter as $filter)
    {
      if (isset($propertyIds[$filter->property_id]))
      {
        $filter['Property'] = $properties[$propertyIds[$filter->property_id]];
        $newFilter[] = $filter;
      }
    }

    return $newFilter;
  }

  public function getDescendantIds()
  {
    return $this->getTable()->getDescendatIds($this);
  }

  
  public function getUrl(){
      return '/catalog/' . $this->token;
  }
  
  public function getTagGroupByIdWithOrder(array $ids = array())
  {
    if (!count($ids))
    {
      return array();
    }

    $q = TagGroupTable::getInstance()->createBaseQuery();
    $q->innerJoin('tagGroup.ProductCategory productCategory WITH productCategory.id = ?', $this->id)
      ->innerJoin('tagGroup.Tag tag')
      ->andWhereIn('tag.id', $ids)
      ->orderBy('tagGroup.position, FIELD(tag.id, '.implode(',', $ids).')')
    ;

    return  $q->execute();

  }

  public function getPhotoUrl($view = 0)
  {
    $urls = sfConfig::get('app_category_photo_url');

    return $this->getPhoto() ? $urls[$view].$this->getPhoto() : null;
  }


}
