<?php

/**
 * ProductFilterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductFilterTable extends myDoctrineTable
{

  /**
   * Returns an instance of this class.
   *
   * @return object ProductFilterTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ProductFilter');
  }
}