<?php

/**
 * ProductStateTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductStateTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductState');
    }

  public function getCoreMapping()
  {
    return array(
      'id'          => 'core_id',
      'is_price'    => 'is_price',
      'is_shop'     => 'is_shop',
      'is_store'    => 'is_store',
      'is_supplier' => 'is_supplied',
      'status_id'   => 'status_id',

      'geo_id'      => array('rel' => 'Region'),
      'product_id'  => array('rel' => 'Product'),
    );
  }
}