<?php

/**
 * ProductModelPropertyRelationTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductModelPropertyRelationTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductModelPropertyRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductModelPropertyRelation');
    }

    public function getCoreMapping()
    {
      return array(
        'is_image'    => 'is_image',
        'position'    => 'position',

        'property_id' => array('rel' => 'ProductProperty'),
      );
    }
}