<?php

/**
 * ProductPropertyRelationTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductPropertyRelationTable extends myDoctrineTable
{

  /**
   * Returns an instance of this class.
   *
   * @return object ProductPropertyRelationTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ProductPropertyRelation');
  }

  public function getValueFieldByType($type)
  {
    $field = null;

    switch ($type)
    {
      case 'select':
        $field = 'option_id';
        break;
      case 'string':
        $field = 'value_string';
        break;
      case 'integer':
        //$field = 'value_integer';
        $field = 'value_float';
        break;
      case 'float':
        $field = 'value_float';
        break;
      case 'text':
        $field = 'value_text';
        break;
      case 'boolean':
        $field = 'value_boolean';
        break;
      default:
        $field = 'value';
        break;
    }

    return $field;
  }

  public function getRealValue($productPropertyRelation)
  {
    $property = ProductPropertyTable::getInstance()->getById($productPropertyRelation['property_id'], array('with_options' => false, 'hydrate_array' => true));
    $field = $this->getValueFieldByType($property['type']);

    return $productPropertyRelation[$field];
  }

  public function getCacheEraserKeys($record, $action = null)
  {
    $return = array();

    /*
    $q = ProductTable::getInstance()->createQuery('product')
      ->select('product.core_id')
      ->innerJoin('product.PropertyRelation productPropertyRelation')
      ->where('productPropertyRelation.property_id = ?', $record->id)
      ->setHydrationMode(Doctrine_Core::HYDRATE_SINGLE_SCALAR)
    ;

    $ids = $q->execute();
    if (!is_array($ids))
    {
      $ids = array($ids);
    }

    foreach ($ids as $id)
    {
      $return[] = "product-{$id}";
    }
    */

    return $return;
  }
}
