<?php

/**
 * ProductPrice
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductPrice extends BaseProductPrice
{
  public function importFromCore(array $data)
  {
    parent::importFromCore($data);

    $this->product_id = ProductTable::getInstance()->getIdByCoreId($data['product_id']);
    $this->product_price_list_id = ProductPriceListTable::getInstance()->getIdByCoreId($data['price_list_id']);
  }
}
