<?php

/**
 * ProductPriceTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductPriceTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductPriceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductPrice');
    }
}