<?php

/**
 * ProductCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductCommentTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductComment');
    }
}