<?php

/**
 * ProductPropertyRelation
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductPropertyRelation extends BaseProductPropertyRelation
{
  public function construct()
  {
    parent::construct();

    $this->mapValue('type', null);
  }

  public function getRealValue()
  {
    return $this->getTable()->getRealValue($this);
  }

  public function setRealValue($value)
  {
    $property = ProductPropertyTable::getInstance()->getById($this->property_id, array('with_options' => false));
    $field = $this->getTable()->getValueFieldByType($property->type);

    if ('boolean' == $property->type)
    {
      $realValue = null;
      $showValue = null;
      if ((true === $value) || ('true' === $value))
      {
        $realValue = true;
        $showValue = 'да';
      }
      if ((false === $value) || ('false' === $value))
      {
        $realValue = false;
        $showValue = 'нет';
      }

      $this->set($field, $realValue);
      $this->value = $showValue;
    }
    else {
      $this->set($field, $value);
    }
  }

  public function getFormattedValue()
  {

  }
}
