<?php

/**
 * ProductPropertyGroupTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductPropertyGroupTable extends myDoctrineTable
{

  /**
   * Returns an instance of this class.
   *
   * @return object ProductPropertyGroupTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ProductPropertyGroup');
  }

  public function getCoreMapping()
  {
    return array(
      'id'       => 'core_id',
      'name'     => 'name',
    );
  }
}