<?php

/**
 * ProductCategoryProductLineRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductCategoryProductLineRelationTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductCategoryProductLineRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductCategoryProductLineRelation');
    }
}