<?php

/**
 * ProductLineTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductLineTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductLineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductLine');
    }

  public function getCoreMapping()
  {
    return array(
      'id'          => 'core_id',
      'name'        => 'name',
      'media_image' => 'photo',
    );
  }
}