<?php

/**
 * ProductFilterTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductFilterTable extends myDoctrineTable
{

  /**
   * Returns an instance of this class.
   *
   * @return object ProductFilterTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ProductFilter');
  }

  public function getListByGroup(ProductFilterGroup $group, array $params = array())
  {
    $this->applyDefaultParameters($params, array());

    $q = $this->createBaseQuery($params);

    $q->where('productFilter.group_id = ?', $group->id);

    $this->setQueryParameters($q, $params);

    $ids = $this->getIdsByQuery($q, $params, 'productFilterGroup-'.$group->id.'/productFilter-ids');

    return $this->createListByIds($ids, $params);
}
  public function getCoreMapping()
  {
    return array(

      'id'          => 'core_id',
      'name'        => 'name',
      'is_multiple' => 'is_multiple',
      'position'    => 'position',
      'min'         => 'value_min',
      'max'         => 'value_max',

      'property_id' => array('rel' => 'Property'),
    );
  }
}
