<?php

/**
 * ProductPhoto3DTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductPhoto3DTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductPhoto3DTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductPhoto3D');
    }
}