<?php

/**
 * ProductPropertyOptionTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductPropertyOptionTable extends myDoctrineTable
{

  /**
   * Returns an instance of this class.
   *
   * @return object ProductPropertyOptionTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ProductPropertyOption');
  }

  public function getCoreMapping()
  {
    return array(
      'id'   => 'core_id',
      'name' => 'value',
    );
  }

  public function getCacheEraserKeys($record, $action = null)
  {
    $return = array();

    /*
    $q = ProductTable::getInstance()->createQuery('product')
      ->select('product.core_id')
      ->innerJoin('product.PropertyRelation productPropertyRelation')
      ->where('productPropertyRelation.option_id = ?', $record->id)
      ->setHydrationMode(Doctrine_Core::HYDRATE_SINGLE_SCALAR)
    ;

    $ids = $q->execute();
    if (!is_array($ids))
    {
      $ids = array($ids);
    }

    foreach ($ids as $id)
    {
      $return[] = "product-{$id}";
    }
    */


    return $return;
  }
}