<?php

/**
 * ProductPropertyRelation
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductPropertyRelation extends BaseProductPropertyRelation
{
  public function getRealValue()
  {
    switch ($this->Property->type):
      case 'select':
        /*if ($this->Property->is_multiple)
        {
          $value = array();
          foreach ($this->getOption() as $option)
          {
            $value[] = $option;
          }
        }
        else
        {*/
          $value = $this->option_id;
        //}
      break;
      case 'string':
        $value = is_null($this->value_string) ? $this->value : $this->value_string;
      break;
      case 'integer':
        $value = is_null($this->value_integer) ? $this->value : $this->value_integer;
      break;
      case 'float':
        $value = is_null($this->value_float) ? $this->value : $this->value_float;
      break;
      case 'text':
        $value = is_null($this->value_text) ? $this->value : $this->value_text;
      break;
      default:
        $value = $this->value;
      break;
    endswitch;

    return $value;
  }
  public function getFormattedValue()
  {

  }
}
