<?php

/**
 * ProductPropertyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductPropertyTable extends myDoctrineTable
{

  /**
   * Returns an instance of this class.
   *
   * @return object ProductPropertyTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ProductProperty');
  }

  public function getById($id, array $params = array())
  {
    $q = $this->createBaseQuery($params);

    $this->setQueryParameters($q);
    
    $q->leftJoin('productProperty.Option productPropertyOption')
      ->addWhere('productProperty.id = ?', $id)
      ->addOrderBy('productPropertyOption.position')
    ;
    $q->useResultCache(true, null, $this->getRecordHash($id, $params));
    
    $record = $q->fetchOne();
    
    return $record;
  }
}