<?php

/**
 * ProductCategory
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductCategory extends BaseProductCategory
{
  public function construct()
  {
    $this->mapValue('product_count', null);
  }

  public function __toString()
  {
    return (string) $this->name;
  }

  public function toParams()
  {
    return array(
      'productCategory' => $this->token_prefix ? ($this->token_prefix.'/'.$this->token) : $this->token,
    );
  }

  public function getRootCategory(array $params = array())
  {
	  return $this->getTable()->getRootRecord($this, $params);
  }

  public function importFromCore(array $data)
  {
    parent::importFromCore($data);

    $link = trim(preg_replace('/^\/catalog/', '', $data['link']), '/');
    $v = explode('/', $link);
    $this->token = array_pop($v);
    $this->token_prefix = count($v) ? array_shift($v) : null;

    $this->photo = !empty($data['media_image']) ? $data['media_image'] : 'default.jpg';

    //Импорт фильтров для категории
    $filterGroup = $this->getFilterGroup();
    if (empty($filterGroup))
    {
      $filterGroup = new ProductFilterGroup();
    }

    $filterGroup->importFromCore($data);

    $this->FilterGroup = $filterGroup;

    //Импорт тэгов для категории
    $tag_group_ids = array();
    foreach ($this->TagGroupRelation as $tagGroupRelation)
    {
      if (!empty($tagGroupRelation['core_id']))
      {
        $tag_group_ids['core_id-'.$tagGroupRelation['core_id']] = $tagGroupRelation['tag_group_id'];
      }
      else
      {
        $tag_group_ids[] = $tagGroupRelation['tag_group_id'];
      }
    }
    if (!empty($data['filter_tag_group']))
    {
      foreach ($data['filter_tag_group'] as $relationData)
      {
        unset($tag_group_ids['core_id-'.$relationData['id']]);
        $tagGroupProductCategoryRelation = TagGroupProductCategoryRelationTable::getInstance()->getByCoreId($relationData['id']);
        if (!$tagGroupProductCategoryRelation)
        {
          $tagGroupProductCategoryRelation = new TagGroupProductCategoryRelation();
        }

        $tagGroupProductCategoryRelation->importFromCore($relationData);
        $this->TagGroupRelation[] = $tagGroupProductCategoryRelation;
      }
    }

    //Удаляю все, что лишнее
    if ($this->id && count($tag_group_ids))
    {
      $q = Doctrine_Query::create()
        ->delete('TagGroupProductCategoryRelation ')
        ->where('product_category_id = ?', $this->id)
        ->andWhereIn('tag_group_id', array_values($tag_group_ids))
        ;

        $deleted = $q->execute();
    }

  }

  public function countProduct(array $params = array())
  {
    return ProductTable::getInstance()->countByCategory($this, $params);
  }

  public function getPreviewProduct()
  {
    return ProductTable::getInstance()->getByCategory($this);
  }

  public function getSubCategories()
  {
    return ProductCategoryTable::getInstance()->getSubList(array('root_id' => $this->root_id));
  }

  public function getChildList(array $params = array())
  {
    return ProductCategoryTable::getInstance()->getChildList($this, $params);
  }

  public function getLinkList(array $params = array())
  {
    return ProductCategoryLinkTable::getInstance()->getListByCategory($this, $params);
  }
/**
 *
 * @return TagGroup Collection
 */
  public function getTagGroupForFilter()
  {
    //делаем список тэгов без учета тегов без товаров
    $categoryTable = ProductCategoryTable::getInstance();

    //берем только тэги, у которых есть продукты
    $tagIds = $categoryTable->getTagIds($this);

    if (!is_array($tagIds))
    {
      $tagIds = array($tagIds);
    }

    //возвращаем тэги, отсортированные в правильном порядке
    return $this->getTagGroupByIdWithOrder($tagIds);
  }
/**
 *
 * @return FilterGroup Collection
 */
  public function getFilterGroupForFilter()
  {
    //делаем список тэгов без учета тегов без товаров
    $categoryTable = ProductCategoryTable::getInstance();

    //берем property_id и option_id, которые существуют в этой категории
    $properties = ProductPropertyTable::getInstance()->getForFilter($this);

    //формируем новую коллекцию групп тегов только с рабочими тэгами
    $newFilter = ProductFilterTable::getInstance()->createList();

    $propertyIds = array();
    foreach ($properties as $key => $property)
    {
      $propertyIds[$property['id']] = $key;
    }

    foreach ($this->FilterGroup->getFilterList(array('order' => 'productFilter.position')) as $filter)
    {
      if (false
        || (('choice' == $filter->type) && isset($propertyIds[$filter->property_id]))
        || ('choice' != $filter->type)
      ) {
        if (isset($propertyIds[$filter->property_id]))
        {
          $filter['Property'] = $properties[$propertyIds[$filter->property_id]];
        }

        $newFilter[] = $filter;
      }
    }

    return $newFilter;
  }

  public function getDescendantIds(array $params = array())
  {
    return $this->getTable()->getDescendatIds($this, $params);
  }

  public function getAncestorIds(array $params = array())
  {
    return $this->getTable()->getAncestorIds($this, $params);
  }


  // TODO: удалить, роутинг для чего нужен?
  public function getUrl(){
      return '/catalog/' . $this->token;
  }

  public function getTagGroupByIdWithOrder(array $ids = array())
  {
    if (!count($ids))
    {
      return array();
    }

    $q = TagGroupTable::getInstance()->createBaseQuery();
    $q->innerJoin('tagGroup.ProductCategoryRelation productCategoryRelation WITH productCategoryRelation.product_category_id = ?', $this->id)
      ->innerJoin('tagGroup.Tag tag')
      ->andWhereIn('tag.id', $ids)
      ->orderBy('productCategoryRelation.position, FIELD(tag.id, '.implode(',', $ids).')')
    ;

    return  $q->execute();
  }

  public function getPhotoUrl($view = 0)
  {
    $urls = sfConfig::get('app_category_photo_url');

    return $this->getPhoto() ? $urls[$view].$this->getPhoto() : null;
  }

  public function getVariation()
  {
    $variation = mb_strtolower($this->name, 'utf-8');
    switch ($variation)
    {
      case 'мебель':
        $variation = 'мебели';
        break;
      case 'бытовая техника':
        $variation = 'бытовой технике';
        break;
      case 'товары для дома':
        $variation = 'товарах для дома';
        break;
      case 'товары для детей':
        $variation = 'товарах для детей';
        break;
      case 'сделай сам (инструменты)':
        $variation = 'сделай сам (инструменты)';
        break;
      case 'электроника':
        $variation = 'электронике';
        break;
      case 'украшения и часы':
        $variation = 'украшениях и часах';
        break;
      case 'спорт':
        $variation = 'спорте';
        break;
      case 'подарки':
        $variation = 'подарках';
        break;
    }

    return $variation;
  }

}
