<?php

/**
 * ProductLineTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductLineTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductLineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductLine');
    }

  public function getCoreMapping()
  {
    return array(
      'id'          => 'core_id',
      'name'        => 'name',
      'media_image' => 'photo',
    );
  }

  public function getForRoute(array $params)
  {
    $id = isset($params['line']) ? $this->getIdBy('token', $params['line']) : null;

    return $this->getById($id, array());
  }

  public function getProductCountById($id)
  {
    $q = ProductTable::getInstance()->createBaseQuery(array('view' => 'list', ));
    $q->addWhere('product.line_id = ?', $id);

    //$q->useResultCache(true, null, $this->getTable()->getRecordQueryHash('productLine-count'.$id));

    return $q->count();
  }
}