<?php

/**
 * ProductPrice
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductPrice extends BaseProductPrice
{
  public function importFromCore(array $data)
  {
    parent::importFromCore($data);

    /*$product = ProductTable::getInstance()->getByCoreId($data['product_id']);
    if (!$product)
    {
      return false;
    }

    $view_list = $product->view_list;

    if (0 == $data['price'] && 1 == $data['price_list_id'])
    {
      $view_list = 0;
    }
    elseif ($data['price'] > 0 && 1 == $data['price_list_id'])
    {
      if ('default.jpg' == $product->main_photo)
      {
        $view_list = 0;
      }
      else
      {
        $view_list = 1;
      }
    }

    if ($product->view_list != $view_list)
    {
      $product->view_list = $view_list;
      $product->save();
    }*/
  }

  public function preSave($event)
  {
    $invoker = $event->getInvoker();

    // If record has been modified adds keys to nginx file
    if ($invoker->isModified(true) && ($invoker->getTable() instanceof myDoctrineTable)) {
      CacheEraser::getInstance()->erase($invoker->getTable()->getCacheEraserKeys($invoker, 'save'), false, 'product_price changed');
    }
  }

  public function preDelete($event)
  {
    $invoker = $event->getInvoker();

    $this->deleteResultCache($invoker);

    CacheEraser::getInstance()->erase($this->getTable()->getCacheEraserKeys($invoker, 'delete'), false, 'product_price deleted');
  }

}
