<?php

/**
 * ProductPropertyRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductPropertyRelationTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductPropertyRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductPropertyRelation');
    }
}