<?php

/**
 * ProductRatingTypeTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductRatingTypeTable extends myDoctrineTable
{

  /**
   * Returns an instance of this class.
   *
   * @return object ProductRatingTypeTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ProductRatingType');
  }

  public function createBaseQuery(array $params = array())
  {
    $this->applyDefaultParameters($params);

    $q = $this->createQuery('productRatingType');

    $q->leftJoin('productRatingType.Property productRatingTypeProperty')
      ->addOrderBy('productRatingTypeProperty.position')
    ;

    return $q;
  }

  public function getRecordById($id, array $params = array())
  {
    $q = $this->createBaseQuery($params);

    $this->setQueryParameters($q, $params);

    $q->addWhere('productRatingType.id = ?', $id);
    //$q->useResultCache(true, null, $this->getRecordQueryHash($id, $params));

    return $q->fetchOne();
  }
}