<?php

/**
 * ProductStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductStatusTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductStatus');
    }
}