<?php

/**
 * ProductFilterGroupTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductFilterGroupTable extends myDoctrineTable
{
  /**
   * Returns an instance of this class.
   *
   * @return object ProductFilterGroupTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ProductFilterGroup');
  }

  /*
  public function getCoreMapping()
  {
    return array(
      'filter_property' => array('rel' => 'Filter'),
    );
  }
  */

  public function getRecordById($id, array $params = array())
  {
    $this->applyDefaultParameters($params);

    $q = $this->createBaseQuery($params);

    $q->leftJoin('productFilterGroup.Filter productFilter')
      ->addOrderBy('productFilter.position')
    ;

    $q->leftJoin('productFilter.Property productProperty');

    $this->setQueryParameters($q);

    $q->whereId($id);

    $list = $q->execute();
    /*
    foreach ($list as $i => $record)
    {
      /*
      foreach ($record['Filter'] as $productFilter)
      {
        //$productFilter['Property'] = ProductPropertyTable::getInstance()->getById($productFilter['property_id']);
      }

      if (is_array($record))
      {
        $list[$i] = $record;
      }
    }
    */

    return $this->getResult($list, is_scalar($id));
  }
}