<?php

/**
 * ProductHelperTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductHelperTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductHelperTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductHelper');
    }
}