<?php

/**
 * ProductPhoto3DTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductPhoto3DTable extends myDoctrineTable
{
  /**
   * Returns an instance of this class.
   *
   * @return object ProductPhoto3DTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('ProductPhoto3D');
  }

  public function getCoreMapping()
  {
    return array(
      'id'      => 'core_id',
      'name'    => 'name',
      'source'  => 'resource',
      'item_id' => array('rel' => 'Product', ),
    );
  }

  public function getByProduct(Product $product)
  {
	  $q = $this->createBaseQuery()->where('product_id = ?', $product->id);

	  return $q->execute();
  }

  public function getCacheEraserKeys($record, $action = null)
  {
    $return = array();

    /*
    $q = ProductTable::getInstance()->createQuery('product')
      ->select('product.core_id')
      ->innerJoin('product.Photo3D photo3d')
      ->where('photo3d.product_id = ?', $record->id)
      ->setHydrationMode(Doctrine_Core::HYDRATE_SINGLE_SCALAR)
    ;

    $ids = $q->execute();
    if (!is_array($ids))
    {
      $ids = array($ids);
    }

    foreach ($ids as $id)
    {
      $return[] = "product-{$id}";
    }
    */

    return $return;
  }
}