<?php

/**
 * QrcodeTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QrcodeTable extends myDoctrineTable
{

  /**
   * Returns an instance of this class.
   *
   * @return object QrcodeTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Qrcode');
  }

  public function getCoreMapping()
  {
    return array(
      'id'   => 'core_id',
      'hash' => 'token',
    );
  }

  public function getTypeByCoreId($coreId)
  {
    $models = array(
      1 => 'product',
    );

    return array_key_exists($coreId, $models) ? $models[$coreId] : false;
  }
}