<?php

/**
 * RegionTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegionTable extends myDoctrineTable
{

  /**
   * Returns an instance of this class.
   *
   * @return object RegionTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Region');
  }

  public function getDefault()
  {
    return $this->createBaseQuery()
      ->where('region.token = ?', 'moscow')
      ->fetchOne()
    ;
  }
}