<?php

/**
 * ServiceCategoryTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServiceCategoryTable extends myDoctrineTable
{
  /**
   * Returns an instance of this class.
   *
   * @return object ServiceCategoryTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('ServiceCategory');
  }

  public function getForRoute(array $params)
  {
    $id = isset($params['serviceCategory']) ? $this->getIdBy('token', $params['serviceCategory']) : null;

    return $this->getById($id);
  }

}