<?php

/**
 * ServicePriceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServicePriceTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServicePriceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServicePrice');
    }
    
    public function getCoreMapping()
    {
      return array(
        'id'            => 'core_id',
        'price'         => 'price',

        'service_id'    => array('rel' => 'Service'),
        'product_id'    => array('rel' => 'Product'),
        'price_list_id' => array('rel' => 'PriceList'),
      );
    }
  
}