<?php

/**
 * ServiceProductRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServiceProductRelationTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServiceProductRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServiceProductRelation');
    }
    
    public function getCoreMapping()
    {
        return array(
          'service_id'  => 'service_id',
          'product_id'  => 'product_id',
        );
    }      
}