<?php

/**
 * Service
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Service extends BaseService
{

  public function toParams()
  {
    return array(
      'service' => $this->token,
    );
  }

  public function importFromCore(array $data)
  {
    parent::importFromCore($data);

    // теги
    if (!empty($data['category'])) foreach ($data['category'] as $relationData)
    {
      $relation = new ServiceCategoryRelation();
      $relation->fromArray(array(
        'category_id' => ServiceCategoryTable::getInstance()->getIdByCoreId($relationData['id']),
      ));
      $this->CategoryRelation[] = $relation;
    }
  }

  public function getPriceByRegion(Region $region = NULL)
  {
      if (!$region){
          $region = RegionTable::getInstance()->getDefault();
      }
	  $q = ServicePriceTable::getInstance()->createBaseQuery();
	  $q->select('price')
	    ->addWhere('service_id = ?', $this->id)
        #->addWhere('region_id = ?', $region->id)
                ;
	  return $q->fetchOne(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
  }
  public function getFormattedPrice()
  {
    return number_format($this->price, 0, ',', ' ');
  }  
  
  public function getCatalogParent(){
    $result = ServiceCategoryTable::getInstance()
            ->createQuery('sc')
            ->innerJoin('sc.ServiceRelation as rel on sc.id=rel.category_id')
            ->where('rel.service_id = ? AND sc.level = ?', array($this->id, 2) );
    $result =  $result->fetchArray();

    #print_r( $result );
    if (isset($result[0])) {
        return $result[0];
    } else {
        return false;            
    }      
  }

}
