<?php

/**
 * ServiceTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServiceTable extends myDoctrineTable
{
  /**
   * Returns an instance of this class.
   *
   * @return object ServiceTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('Service');
  }
  /* TODO добавить условие выборки по региону */
  public function getListByProduct(Product $product, array $params = array())
  {
    $this->applyDefaultParameters($params);

    $q = $this->createBaseQuery($params);

    $q->innerJoin('service.Category category')
      ->innerJoin('category.ProductTypeRelation productTypeRelation')
      ->andWhere('productTypeRelation.product_type_id=?', array($product->type_id))
      ->innerJoin('service.Price price') ;

    $this->setQueryParameters($q, $params);

    return $q->execute();
  }

  public function getForRoute(array $params)
  {
    $id = isset($params['service']) ? $this->getIdBy('token', $params['service']) : null;

    return $this->getById($id);
  }

}