<?php

/**
 * ServiceCategory
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ServiceCategory extends BaseServiceCategory
{

  public function getServiceList(array $params = array())
  {
    $result = ServiceTable::getInstance()->getListByCategory($this->id, $params);

    return $result;
  }

  public function toParams()
  {
    return array(
      'serviceCategory' => $this->token,
    );
  }
}
