<?php

/**
 * ShopPhoto
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ShopPhoto extends BaseShopPhoto
{
  public function getPhotoUrl($view = 0)
  {
    $urls = sfConfig::get('app_shop_photo_url');

    return $this->resource ? $urls[$view].$this->resource : null;
  }
}
