<?php

/**
 * Shop
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Shop extends BaseShop
{
  public function toParams()
  {
    return array(
      'shop' => $this->token,
    );
  }

  public function importFromCore(array $data)
  {
    parent::importFromCore($data);

    $this->token = empty($this->token) ? myToolkit::urlize($this->name) : $this->token;
    //$this->region_id = RegionTable::getInstance()->getIdByCoreId($data['geo_id']);
  }
}
