<?php

/**
 * ShopTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopTable extends myDoctrineTable
{

  /**
   * Returns an instance of this class.
   *
   * @return object ShopTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Shop');
  }

  public function getCoreMapping()
  {
    return array(
      'id'            => 'core_id',
      'name'          => 'name',
      'description'   => 'description',
      'working_time'  => 'regime',
      'phone'         => 'phonenumbers',
      'address'       => 'address',
      'coord_long'    => 'longitude',
      'coord_lat'     => 'latitude',
      'way_walk'      => 'way_walk',
      'way_auto'      => 'way_auto',
    );
  }

  public function createBaseQuery(array $params = array())
  {
    $this->applyDefaultParameters($params);

    $q = $this->createQuery('shop');

    $q->addWhere('shop.is_active = ?', 1);

    return $q;
  }

  public function getDefaultParameters()
  {
    $region = $this->getParameter('region');

    return array(
      'region_id' => $region ? $region['id'] : null,
    );
  }

  public function getForRoute(array $params)
  {
    $id = isset($params['shop']) ? $this->getIdBy('token', $params['shop']) : null;

    return $this->getById($id);
  }

  public function getListByProduct($product_id, array $params = array())
  {
    $this->applyDefaultParameters($params, array(
      'include_empty' => false,
    ));

    $q = $this->createBaseQuery($params);

    $q->leftJoin('shop.ProductRelation stockProductRelation')
      ->addWhere('stockProductRelation.product_id = ? AND stockProductRelation.stock_id IS NULL', $product_id)
      ->addWhere('shop.is_active = ?', 1);
    ;

    if ($params['region_id'])
    {
      $q->addWhere('shop.region_id = ?', $params['region_id']);
    }

    $q->select('shop.token, shop.name, shop.region_id, shop.address, SUM(stockProductRelation.quantity) AS product_quantity')
      ->groupBy('shop.token, shop.name, shop.region_id, shop.address')
    ;

    if (false == $params['include_empty'])
    {
      $q->having('product_quantity > 0');
    }

    $this->setQueryParameters($q, $params);

    return $q->execute();
  }

  public function getListByRegion($region, array $params = array())
  {
    $this->applyDefaultParameters($params);

    $q = $this->createBaseQuery($params);

    $q->addWhere('shop.region_id = ?', $region instanceof Region ? $region->id : $region)
      ->addWhere('shop.is_active = ?', 1);

    $this->setQueryParameters($q, $params);

    return $q->execute();
  }

  public function setQueryParameters(Doctrine_Query $q, array $params = null)
  {
    parent::setQueryParameters($q, $params);

    if (isset($params['region_id']))
    {
      $q->andWhere('shop.region_id = ?', $params['region_id']);
    }
  }
  /**
   *
   * @return Shop
   */
  public function getMainShop()
  {
      $q = $this->createBaseQuery();
      return $q->fetchOne();
  }
}