<?php

/**
 * SimilarProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SimilarProductTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SimilarProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SimilarProduct');
    }
}