<?php

/**
 * StockProductRelation
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class StockProductRelation extends BaseStockProductRelation
{
  public function importFromCore(array $data)
  {
    parent::importFromCore($data);

    if (!empty($data['store_id']))
    {
      $product = ProductTable::getInstance()->getByCoreId($data['product_id']);
      if ($product)
      {
        $product->is_instock = !empty($data['is_supplier']) || ($data['quantity'] > 0);
        $product->save();
      }
    }
  }
}
