<?php

/**
 * StockProductRelation
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class StockProductRelation extends BaseStockProductRelation
{
  public function importFromCore(array $data)
  {
    parent::importFromCore($data);

    /*
    $conn = Doctrine_Manager::getInstance()->connection();

    $product = ProductTable::getInstance()->getByCoreId($data['product_id']);
    if (!$product)
    {
      return false;
    }

    $addWhere = "";

    $is_instock = $product->is_instock;

    if (!empty($data['store_id']) && 1 == $data['store_id'])
    {
      $is_instock = !empty($data['is_supplier']) || ($data['quantity'] > 0);
      $addWhere = " AND NOT (`stock_id` = ".$this->stock_id." AND `shop_id` IS NULL) ";
    }

    if (!empty($data['shop_id']))
    {
      $this->quantity = $data['quantity'] + $data['quantity_showroom'];
      $is_instock = $this->quantity > 0;
      $addWhere = " AND NOT (`stock_id` IS NULL AND `shop_id` = ".$this->shop_id.") ";
    }

    if (!$is_instock)
    {
      //если на текущем складе пропал товар, то проверяю все склады, которые уже есть в системе
      $sql = "SELECT SUM(IF(`is_supplied` = 1, 1, IF(`stock_id` = 1 AND `quantity` > 0, 1, IF(`shop_id` IS NOT NULL AND `quantity` > 0, 1, 0)))) > 0 FROM `stock_product_relation` WHERE `product_id` = ?".$addWhere."GROUP BY `product_id`";

      $result = $conn->fetchOne($sql, array($this->product_id));
      if (!$result)
      {
        $result = 0;
      }

      $is_instock = $result;
    }

    if ($product->is_instock != $is_instock)
    {
      $product->is_instock = $is_instock;
      $product->save();
    }
    */
  }
}
