<?php

/**
 * TagGroup
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TagGroup extends BaseTagGroup
{
  public function importFromCore(array $data)
  {
    parent::importFromCore($data);

    $this->type = $data['is_gift'] ? 'gift' : null;


    $this->token = empty($this->token) ? (uniqid().'-'.myToolkit::urlize($this->name)) : $this->token;
    // Теги
    /*
    if (!empty($data['tag']))
    {
      foreach ($data['tag'] as $relationData)
      {
        $relation = new TagGroupRelation();
        $relation->fromArray(array(
          'group_id' => $this->id,
          'tag_id'   => TagTable::getInstance()->getIdByCoreId($relationData['id']),
        ));
        $this->TagRelation[] = $relation;
      }
    }
    */
  }
}
