<?php

/**
 * TagGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TagGroupTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TagGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TagGroup');
    }
}