<?php

/**
 * TagGroupProductTypeRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TagGroupProductTypeRelationTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TagGroupProductTypeRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TagGroupProductTypeRelation');
    }
}