<?php

/**
 * Task
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Task extends BaseTask
{
  public function __destruct()
  {
    if (!empty($this['id']))
    {
      $this->setDefaultPriority();
      $this->save();
    }
  }

  public function preSave($event)
  {
    $record = $event->getInvoker();

    if (!$record->exists())
    {
      $record->setDefaultPriority();
    }
  }

  public function toParams()
  {
    return array(
      'id' => $this->id,
    );
  }

  public function setContentData($value)
  {
    if (!is_array($value))
    {
      $arg2 = func_get_arg(1);

      $value = array(
        $value => $arg2,
      );
    }

    $content = $this->getContentData();
    foreach ($value as $k => $v)
    {
      $content[$k] = $v;
    }

    $this->content = sfYaml::dump($content);
  }

  public function getContentData($name = null)
  {
    $value = sfYaml::load($this->content);

    return null == $name ? $value : $value[$name];
  }


  public function setErrorData($value)
  {
    $error = $this->getErrorData();
    $error[] = $value;

    $error = array_unique($error);

    $this->error = sfYaml::dump($error);
  }

  public function getErrorData($name = null)
  {
    $value = sfYaml::load($this->error);

    return null == $name ? $value : $value[$name];
  }

  public function setDefaultPriority()
  {
    $this->priority = $this->getTable()->getPriorityByType($this->type);
  }
}
