<?php

/**
 * Task
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Task extends BaseTask
{
  public function __destruct()
  {
    if (!empty($this['id']))
    {
      $this->setDefaultPriority();
      $this->save();
    }
  }

  public function preSave($event)
  {
    $record = $event->getInvoker();

    if (!$record->exists())
    {
      $record->setDefaultPriority();
    }
  }

  public function setContentData($value)
  {
    if (!is_array($value))
    {
      $arg2 = func_get_arg(1);

      $value = array(
        $value => $arg2,
      );
    }

    $content = sfYaml::load($this->content);

    if (!is_array($value))
    {
      //$value = array($value => func_get_arg(1));
    }

    foreach ($value as $k => $v)
    {
      $content[$k] = $v;
    }

    $this->content = sfYaml::dump($content);
  }

  public function getContentData($name = null)
  {
    $content = sfYaml::load($this->content);

    return null == $name ? $content : $content[$name];
  }

  public function setDefaultPriority()
  {
    $this->priority = $this->getTable()->getPriorityByType($this->type);
  }
}
