<?php

/**
 * UserDelayedProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserDelayedProduct extends BaseUserDelayedProduct
{
    
    /**
     * Получает список отложенных товаров пользователя
     * @param integer $user_id
     * @return array 
     */
    public function getUserDelayProducts($user_id){
        $table = $this->getTable()->getQueryObject();
        $list = $table->where('user_id=?',$user_id)->fetchArray();
        return $list;
    }
}
