<?php

/**
 * User
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User extends BaseUser
{
  public function hasProductRating($product_id)
  {
    $q = UserProductRatingTable::getInstance()->createBaseQuery();

    $q->select('userProductRating.product_id')
      ->addWhere('userProductRating.user_id = ? AND userProductRating.product_id = ?', array($this->id, $product_id))
      ->setHydrationMode(Doctrine_Core::HYDRATE_SINGLE_SCALAR)
    ;

    return false != $q->fetchOne();
  }

  public function getProductRatingByProduct($product_id)
  {
    $q = UserProductRatingTable::getInstance()->createBaseQuery();

    $q->addWhere('userProductRating.user_id = ? AND userProductRating.product_id = ?', array($this->id, $product_id));

    return $q->fetchOne();
  }
}
