<?php

/**
 * UserDelayedProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserDelayedProductTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserDelayedProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserDelayedProduct');
    }
}