<?php

/**
 * UserProductRating
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserProductRating extends BaseUserProductRating
{
	public function exportToCore()
	{
		$data = parent::exportToCore();

		$data['user_id'] = $this->User->core_id;
		$data['product_id'] = $this->Product->core_id;
		//$data['property_id'] = $this->Property->core_id;
		$data['criterion_id'] = $this->Property->core_id;
		$data['ip'] = $_SERVER['REMOTE_ADDR'];
		//$data['ip'] = sfContext::getInstance()->getUser()->getIp();

		return $data;
	}
	
//  public function postSave($event)
//  {
//    $rating = $this->getTable()->createBaseQuery()
//      ->select('AVG(userProductRating.value) AS rating')
//      ->addWhere('userProductRating.product_id = ?', $event->getInvoker()->product_id)
//      ->setHydrationMode(Doctrine_Core::HYDRATE_SINGLE_SCALAR)
//      ->fetchOne()
//    ;
//
//    $product = ProductTable::getInstance()->getById($event->getInvoker()->product_id, array('select' => 'product.id, product.rating'));
//    if ($product)
//    {
//      $product->rating = $rating;
//      $product->save();
//    }
//
//    parent::postSave($event);
//  }
}
