<?php

/**
 * UserProductRatingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserProductRatingTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserProductRatingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserProductRating');
    }
}