<?php

/**
 * UserProductRatingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserProductRatingTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserProductRatingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserProductRating');
    }
	
	public function getByProductAndUser(Product $product, GuardUser $user)
	{
		$q = $this->createBaseQuery();
		$q->innerJoin('userProductRating.Property property');
		$q->andWhere('user_id = ?', $user->id);
		$q->andWhere('product_id = ?', $product->id);
		
		//$this->setQueryParameters($q, $params);

		return $q->fetchArray();
	}
}