<?php

/**
 * UserProductNotice
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    enter
 * @subpackage model
 * @author     Связной Маркет
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserProductNotice extends BaseUserProductNotice
{


  public function exportToCore()
  {
    $data = array(
      'email'       => $this->email,
      'type'        => $this->type,
      'user_id'     => $this->user_id,
      'product_ip'  => $this->product_id,
    );
    foreach ($data as $key => $value)
    {
      if (empty($value))
      {
        unset($data[$key]);
      }
    }
    return $data;
  }
}
