<?php

/**
 * UserTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTable extends GuardUserTable
{

  /**
   * Returns an instance of this class.
   *
   * @return object UserTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('User');
  }

  public function getCoreMapping()
  {
    return array(
      'id'          => 'core_id',
      'first_name'  => 'first_name',
      'last_name'   => 'last_name',
      'middle_name' => 'middle_name',
      'email'       => 'email',
      'mobile'      => 'phonenumber',
//      'sex'         => 'sex',
//      'password'    => 'password',
    );
  }
  
}