<?php

/**
 * UserTagTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTagTable extends myDoctrineTable
{

  /**
   * Returns an instance of this class.
   *
   * @return object UserTagTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('UserTag');
  }

  public function getListByUser($user_id, array $params = array())
  {
    $this->applyDefaultParameters($params);

    $q = $this->createBaseQuery($params);

    $q->addWhere('userTag.user_id = ?', $user_id);

    $this->setQueryParameters($q, $params);

    $ids = $this->getIdsByQuery($q);

    return $this->createListByIds($ids, $params);
  }

  public function getListByProduct($product_id, array $params = array())
  {
    $this->applyDefaultParameters($params, array(
      'user_id' => false,
    ));

    $q = $this->createBaseQuery($params);

    $q->innerJoin('userTag.ProductRelation userTagProductRelation')
      ->addWhere('userTagProductRelation.product_id = ?', $product_id)
    ;

    if ($params['user_id'])
    {
      $q->addWhere('userTag.user_id = ?', $params['user_id']);
    }

    $this->setQueryParameters($q, $params);

    $ids = $this->getIdsByQuery($q);

    return $this->createListByIds($ids, $params);
  }

  public function getCoreMapping()
  {
    return array(
      'id'          => 'core_id',
    );
  }
}