<?php

/**
 * UserAddressTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserAddressTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserAddressTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserAddress');
    }
}