# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
dev_green:
  core:
    config:
      api_url: 'http://62.231.27.40/v1/json'
      consumer_key: site
      signature: test