# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

api:
  url:   /api
  param: { module: api, action: index }

api_log:
  url:   /api/log
  param: { module: api, action: log }

task:
  class: sfDoctrineRouteCollection
  options:
    model:                Task
    module:               task
    prefix_path:          /task
    column:               id
    with_wildcard_routes: true
    #actions:              [ list, new, create, edit, update, delete ]
    collection_actions:   { init: get }