# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

default_init:
  url:   /initialize
  param: { module: default, action: init }

api:
  url:   /api
  param: { module: api, action: index }

api_log:
  url:   /api/log
  param: { module: api, action: log }