indexSuccess:
  stylesheets:
    - jquery.autocomplete.css
    - jquery-ui-custom/jquery-ui-custom.css
    - colorbox/colorbox.css
    
  javascripts:
    - jquery.mousewheel.min.js
    #- shelf/watch3d.js
    - watch3dv2.min.js
    - productcard.js
    - app.order.js
    - prettyCheckboxes.js
    - jquery.form.js
    - typewriter.js
    - shelf/jquery.autocomplete-dev.js
    - jquery.scrollto.js
    - main.js
    - app.product.js
