indexSuccess:
  stylesheets:
    - jquery.autocomplete.css
    - jquery-ui-custom/jquery-ui-custom.css
    - colorbox/colorbox.css
    
  javascripts:
    #ivn- jquery.mousewheel.min.js
    #- shelf/watch3d.js
    - watch3dv2.min.js
    - productcard.js
    - app.order.js
    #ivn- prettyCheckboxes.js
    #ivn- jquery.form.js
    #ivn- typewriter.js
    - shelf/jquery.autocomplete-dev.js
    #ivn- jquery.scrollto.js
    - main.js
    - app.product.js
