all:
  layout: order_
  stylesheets:
#    - jquery-ui-1.8.20.custom.css
    - http://direct-credit.ru/widget/styles/style_4427.css
    - http://direct-credit.ru/widget/style.css
index:
  layout: layout
