# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories

prod:
  logger:
    class:   sfNoLogger
    param:
      level:   err
      loggers: ~

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  response:
    class: sfWebResponse
    param:
      send_http_headers: false

  mailer:
    param:
      delivery_strategy: none

dev:
  mailer:
    param:
      delivery_strategy: none
  logger:
    param:
      level: err

all:
  routing:
    class: myPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  view_cache_manager:
    class: myViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true

  request:
    class: myWebRequest

  storage:
    class: sfSessionStorage
    param:
      auto_start: true
      session_name: enter
      session_cookie_lifetime: 15552000

  user:
    class: myUser
    param:
      timeout: 15552000 # 180 дней

  view_cache:
    class: sfRediskaCache
    param:
      lifetime: 604800
      prefix: 'view:'

  logger:
    param:
      loggers:
        sf_web_debug:
          class: sfWebDebugLogger
          param:
            level: debug
            condition:       %SF_WEB_DEBUG%
            xdebug_logging:  false
            web_debug_class: myWebDebug
