# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/12-Filters

rendering: ~
security:  ~

welcome:
  class: WelcomeFilter
  param:
    excluded_env: [ alpha ] # live and prod are hardcoded

CityRedirect:
  class: CityRedirectFilter

# insert your own filters here

cache:     ~
execution: ~
