# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# product
#
# product catalog
productCatalog:
  url:   /catalog
  param: { module: productCatalog, action: index }
#
# product catalog by category
productCatalog_category:
  url:   /catalog/:productCategory
  param: { module: productCatalog, action: category }
  class:   myProductCatalogRoute
  options: { model: ProductCategory, type: object, method: getForRoute }
#
# product catalog by category and creator
productCatalog_creator:
  url:   /catalog/:productCategory/:creator
  param: { module: productCatalog, action: creator }
  class:   myProductCatalogRoute
  options: { model: ProductCategory, type: object, method: getForRoute }
#
# product card
productCard:
  url:   /products/:product
  param: { module: productCard, action: index }
  class:   myDoctrineRoute
  options: { model: Product, type: object, method: getForRoute }
#
# product comment
productComment:
  url:   /products/:product/comments
  param: { module: productComment, action: index }
#
# news list by year
newsCategory_year:
  url:   /news/:newsCategory/:year
  param: { module: newsCategory, action: year }
  class:   myNewsRoute
  options: { model: NewsCategory, type: object, method: getForRoute }
#
# news list by month
newsCategory_month:
  url:   /news/:newsCategory/:year/:month
  param: { module: newsCategory, action: month }
  class:   myNewsRoute
  options: { model: NewsCategory, type: object, method: getForRoute }
#
# news
news_show:
  url:   /news/:newsCategory/:year/:month/:news
  param: { module: news, action: show }
  class:   myNewsRoute
  options: { model: News, type: object, method: getForRoute }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
