# default rules
homepage:
  url:   /
  param: { module: default, action: index }


# Каталог товаров
#
# product catalog
productCatalog:
  url:   /catalog
  param: { module: productCatalog, action: index }
#
# product catalog filter
productCatalog_filter:
  url:   /catalog/:productCategory/_filter
  param: { module: productCatalog, action: filter }
  class:   myProductCatalogRoute
  options: { model: ProductCategory, type: object, method: getForRoute }
#
# product catalog by category
productCatalog_category:
  url:   /catalog/:productCategory
  param: { module: productCatalog, action: category }
  class:   myProductCatalogRoute
  options: { model: ProductCategory, type: object, method: getForRoute }
#
# product catalog by category and creator
productCatalog_creator:
  url:   /catalog/:productCategory/:creator
  param: { module: productCatalog, action: creator }
  class:   myProductCatalogRoute
  options: { model: ProductCategory, type: object, method: getForRoute }

# Карточка товара
#
# product card
productCard:
  url:   /products/:product
  param: { module: productCard, action: index }
  class:   myDoctrineRoute
  options: { model: Product, type: object, method: getForRoute }
#
# product comment
productComment:
  url:   /products/:product/comments
  param: { module: productComment, action: index }


# Пользователь
#
# user
user:
  url:   /private/
  param: { module: user, action: index }
#
# user signin
user_signin:
  url:   /login
  param: { module: user, action: signin }
#
# user signout
user_signout:
  url:   /logout
  param: { module: user, action: signout }
#
# user password
user_password:
  url:   /request-password
  param: { module: user, action: password }


# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
