all:
  metas:
    title: Enter - это выход!

  stylesheets:
    - -*
    - skin/inner.css?2012-10-01

  javascripts:
    - -*
    - jquery-1.6.4.min.js

  layout: main

indexSuccess:
  metas:
    description: "Enter - новый способ покупать. Любой из 20000 товаров нашего ассортимента можно купить где угодно, как угодно и когда угодно. Наша миссия: дарить время для настоящего. Честно. С любовью. Как для себя."

welcomeSuccess:
  metas:
    title: You can Enter
    description: "Enter - новый способ покупать. Любой из 20000 товаров нашего ассортимента можно купить где угодно, как угодно и когда угодно. Наша миссия: дарить время для настоящего. Честно. С любовью. Как для себя."

  javascripts:
    - -*

  stylesheets:
    - -*
    - skin/entry.css

  layout: welcome