all:
  stylesheets:
    - -*
    - skin/main.css

  javascripts:
    - -*
    - jquery-1.6.4.min.js

  layout: main

welcomeSuccess:
  metas:
    title: You can Enter

  javascripts:
    - -*

  stylesheets:
    - -*
    - skin/entry.css

  layout: welcome