var checkboxHeight="14",radioHeight="20",selectWidth="190";document.write('<style type="text/css">input.styled { display: none; } select.styled { position: relative; width: '+selectWidth+"px; opacity: 0; filter: alpha(opacity=0); z-index: 5; } .styled.disabled { opacity: 0.5; filter: alpha(opacity=50); }</style>");
var Custom={init:function(){var e=document.getElementsByTagName("input"),g=[],c,f;for(a=0;a<e.length;a++)if((e[a].type=="checkbox"||e[a].type=="radio")&&e[a].className=="styled"){g[a]=document.createElement("span");g[a].className=e[a].type;if(e[a].checked==true)position=e[a].type=="checkbox"?"0 -"+checkboxHeight*2+"px":"0 -"+radioHeight*2+"px",g[a].style.backgroundPosition=position;e[a].parentNode.insertBefore(g[a],e[a]);e[a].onchange=Custom.clear;e[a].getAttribute("disabled")?g[a].className=g[a].className+=
" disabled":(g[a].onmousedown=Custom.pushed,g[a].onmouseup=Custom.check)}e=document.getElementsByTagName("select");for(a=0;a<e.length;a++)if(e[a].className=="styled"){f=e[a].getElementsByTagName("option");c=f[0]?f[0].innerHTML:"-";c=document.createTextNode(c);for(b=0;b<f.length;b++)f[b].selected==true&&(c=document.createTextNode(f[b].innerHTML));g[a]=document.createElement("span");g[a].className="select";g[a].id="select"+e[a].name;g[a].appendChild(c);e[a].parentNode.insertBefore(g[a],e[a]);e[a].getAttribute("disabled")?
e[a].previousSibling.className=e[a].previousSibling.className+=" disabled":e[a].onchange=Custom.choose}document.onmouseup=Custom.clear},pushed:function(){element=this.nextSibling;this.style.backgroundPosition=element.checked==true&&element.type=="checkbox"?"0 -"+checkboxHeight*3+"px":element.checked==true&&element.type=="radio"?"0 -"+radioHeight*3+"px":element.checked!=true&&element.type=="checkbox"?"0 -"+checkboxHeight+"px":"0 -"+radioHeight+"px"},check:function(){element=this.nextSibling;if(element.checked==
true&&element.type=="checkbox")this.style.backgroundPosition="0 0",element.checked=false;else{if(element.type=="checkbox")this.style.backgroundPosition="0 -"+checkboxHeight*2+"px";else{this.style.backgroundPosition="0 -"+radioHeight*2+"px";group=this.nextSibling.name;inputs=document.getElementsByTagName("input");for(a=0;a<inputs.length;a++)if(inputs[a].name==group&&inputs[a]!=this.nextSibling)inputs[a].previousSibling.style.backgroundPosition="0 0"}element.checked=true}},clear:function(){inputs=document.getElementsByTagName("input");
for(var e=0;e<inputs.length;e++)if(inputs[e].type=="checkbox"&&inputs[e].checked==true&&inputs[e].className=="styled")inputs[e].previousSibling.style.backgroundPosition="0 -"+checkboxHeight*2+"px";else if(inputs[e].type=="checkbox"&&inputs[e].className=="styled")inputs[e].previousSibling.style.backgroundPosition="0 0";else if(inputs[e].type=="radio"&&inputs[e].checked==true&&inputs[e].className=="styled")inputs[e].previousSibling.style.backgroundPosition="0 -"+radioHeight*2+"px";else if(inputs[e].type==
"radio"&&inputs[e].className=="styled")inputs[e].previousSibling.style.backgroundPosition="0 0"},choose:function(){option=this.getElementsByTagName("option");for(d=0;d<option.length;d++)if(option[d].selected==true)document.getElementById("select"+this.name).innerHTML=option[d].innerHTML}};window.onload=Custom.init;(function(e,g){function c(c,h){var g=c.nodeName.toLowerCase();if("area"===g){var g=c.parentNode,n=g.name;if(!c.href||!n||g.nodeName.toLowerCase()!=="map")return false;g=e("img[usemap=#"+n+"]")[0];return!!g&&f(g)}return(/input|select|textarea|button|object/.test(g)?!c.disabled:"a"==g?c.href||h:h)&&f(c)}function f(c){return!e(c).parents().andSelf().filter(function(){return e.curCSS(this,"visibility")==="hidden"||e.expr.filters.hidden(this)}).length}e.ui=e.ui||{};e.ui.version||(e.extend(e.ui,{version:"@VERSION",
keyCode:{ALT:18,BACKSPACE:8,CAPS_LOCK:20,COMMA:188,COMMAND:91,COMMAND_LEFT:91,COMMAND_RIGHT:93,CONTROL:17,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,MENU:93,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,WINDOWS:91}}),e.fn.extend({propAttr:e.fn.prop||e.fn.attr,_focus:e.fn.focus,focus:function(c,h){return typeof c==="number"?this.each(function(){var f=
this;setTimeout(function(){e(f).focus();h&&h.call(f)},c)}):this._focus.apply(this,arguments)},scrollParent:function(){var c;c=e.browser.msie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(e.curCSS(this,"position",1))&&/(auto|scroll)/.test(e.curCSS(this,"overflow",1)+e.curCSS(this,"overflow-y",1)+e.curCSS(this,"overflow-x",1))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(e.curCSS(this,
"overflow",1)+e.curCSS(this,"overflow-y",1)+e.curCSS(this,"overflow-x",1))}).eq(0);return/fixed/.test(this.css("position"))||!c.length?e(document):c},zIndex:function(c){if(c!==g)return this.css("zIndex",c);if(this.length)for(var c=e(this[0]),h;c.length&&c[0]!==document;){h=c.css("position");if(h==="absolute"||h==="relative"||h==="fixed")if(h=parseInt(c.css("zIndex"),10),!isNaN(h)&&h!==0)return h;c=c.parent()}return 0},disableSelection:function(){return this.bind((e.support.selectstart?"selectstart":
"mousedown")+".ui-disableSelection",function(e){e.preventDefault()})},enableSelection:function(){return this.unbind(".ui-disableSelection")}}),e.each(["Width","Height"],function(c,h){function f(c,p,o,h){e.each(n,function(){p-=parseFloat(e.curCSS(c,"padding"+this,true))||0;o&&(p-=parseFloat(e.curCSS(c,"border"+this+"Width",true))||0);h&&(p-=parseFloat(e.curCSS(c,"margin"+this,true))||0)});return p}var n=h==="Width"?["Left","Right"]:["Top","Bottom"],j=h.toLowerCase(),m={innerWidth:e.fn.innerWidth,innerHeight:e.fn.innerHeight,
outerWidth:e.fn.outerWidth,outerHeight:e.fn.outerHeight};e.fn["inner"+h]=function(c){return c===g?m["inner"+h].call(this):this.each(function(){e(this).css(j,f(this,c)+"px")})};e.fn["outer"+h]=function(c,p){return typeof c!=="number"?m["outer"+h].call(this,c):this.each(function(){e(this).css(j,f(this,c,true,p)+"px")})}}),e.extend(e.expr[":"],{data:function(c,h,f){return!!e.data(c,f[3])},focusable:function(f){return c(f,!isNaN(e.attr(f,"tabindex")))},tabbable:function(f){var h=e.attr(f,"tabindex"),
g=isNaN(h);return(g||h>=0)&&c(f,!g)}}),e(function(){var c=document.body,h=c.appendChild(h=document.createElement("div"));e.extend(h.style,{minHeight:"100px",height:"auto",padding:0,borderWidth:0});e.support.minHeight=h.offsetHeight===100;e.support.selectstart="onselectstart"in h;c.removeChild(h).style.display="none"}),e.extend(e.ui,{plugin:{add:function(c,h,f){var c=e.ui[c].prototype,g;for(g in f)c.plugins[g]=c.plugins[g]||[],c.plugins[g].push([h,f[g]])},call:function(e,c,f){if((c=e.plugins[c])&&
e.element[0].parentNode)for(var g=0;g<c.length;g++)e.options[c[g][0]]&&c[g][1].apply(e.element,f)}},contains:function(e,c){return document.compareDocumentPosition?e.compareDocumentPosition(c)&16:e!==c&&e.contains(c)},hasScroll:function(c,h){if(e(c).css("overflow")==="hidden")return false;var f=h&&h==="left"?"scrollLeft":"scrollTop",g=false;if(c[f]>0)return true;c[f]=1;g=c[f]>0;c[f]=0;return g},isOverAxis:function(e,c,f){return e>c&&e<c+f},isOver:function(c,h,f,g,j,m){return e.ui.isOverAxis(c,f,j)&&
e.ui.isOverAxis(h,g,m)}}))})(jQuery);(function(e,g){if(e.cleanData){var c=e.cleanData;e.cleanData=function(f){for(var h=0,g;(g=f[h])!=null;h++)try{e(g).triggerHandler("remove")}catch(n){}c(f)}}else{var f=e.fn.remove;e.fn.remove=function(c,h){return this.each(function(){h||(!c||e.filter(c,[this]).length)&&e("*",this).add([this]).each(function(){try{e(this).triggerHandler("remove")}catch(c){}});return f.call(e(this),c,h)})}}e.widget=function(c,h,f){var g=c.split(".")[0],j,c=c.split(".")[1];j=g+"-"+c;if(!f)f=h,h=e.Widget;e.expr[":"][j]=
function(h){return!!e.data(h,c)};e[g]=e[g]||{};e[g][c]=function(e,c){arguments.length&&this._createWidget(e,c)};h=new h;h.options=e.extend(true,{},h.options);e[g][c].prototype=e.extend(true,h,{namespace:g,widgetName:c,widgetEventPrefix:e[g][c].prototype.widgetEventPrefix||c,widgetBaseClass:j},f);e.widget.bridge(c,e[g][c])};e.widget.bridge=function(c,h){e.fn[c]=function(f){var n=typeof f==="string",j=Array.prototype.slice.call(arguments,1),m=this,f=!n&&j.length?e.extend.apply(null,[true,f].concat(j)):
f;if(n&&f.charAt(0)==="_")return m;n?this.each(function(){var h=e.data(this,c),p=h&&e.isFunction(h[f])?h[f].apply(h,j):h;if(p!==h&&p!==g)return m=p,false}):this.each(function(){var g=e.data(this,c);g?g.option(f||{})._init():e.data(this,c,new h(f,this))});return m}};e.Widget=function(e,c){arguments.length&&this._createWidget(e,c)};e.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",options:{disabled:false},_createWidget:function(c,h){e.data(h,this.widgetName,this);this.element=e(h);this.options=
e.extend(true,{},this.options,this._getCreateOptions(),c);var f=this;this.element.bind("remove."+this.widgetName,function(){f.destroy()});this._create();this._trigger("create");this._init()},_getCreateOptions:function(){return e.metadata&&e.metadata.get(this.element[0])[this.widgetName]},_create:function(){},_init:function(){},destroy:function(){this.element.unbind("."+this.widgetName).removeData(this.widgetName);this.widget().unbind("."+this.widgetName).removeAttr("aria-disabled").removeClass(this.widgetBaseClass+
"-disabled ui-state-disabled")},widget:function(){return this.element},option:function(c,h){var f=c;if(arguments.length===0)return e.extend({},this.options);if(typeof c==="string"){if(h===g)return this.options[c];f={};f[c]=h}this._setOptions(f);return this},_setOptions:function(c){var h=this;e.each(c,function(e,c){h._setOption(e,c)});return this},_setOption:function(e,c){this.options[e]=c;e==="disabled"&&this.widget()[c?"addClass":"removeClass"](this.widgetBaseClass+"-disabled ui-state-disabled").attr("aria-disabled",
c);return this},enable:function(){return this._setOption("disabled",false)},disable:function(){return this._setOption("disabled",true)},_trigger:function(c,h,f){var g=this.options[c],h=e.Event(h);h.type=(c===this.widgetEventPrefix?c:this.widgetEventPrefix+c).toLowerCase();f=f||{};if(h.originalEvent)for(var c=e.event.props.length,j;c;)j=e.event.props[--c],h[j]=h.originalEvent[j];this.element.trigger(h,f);return!(e.isFunction(g)&&g.call(this.element[0],h,f)===false||h.isDefaultPrevented())}}})(jQuery);(function(e){var g=false;e(document).mouseup(function(){g=false});e.widget("ui.mouse",{options:{cancel:":input,option",distance:1,delay:0},_mouseInit:function(){var c=this;this.element.bind("mousedown."+this.widgetName,function(e){return c._mouseDown(e)}).bind("click."+this.widgetName,function(f){if(true===e.data(f.target,c.widgetName+".preventClickEvent"))return e.removeData(f.target,c.widgetName+".preventClickEvent"),f.stopImmediatePropagation(),false});this.started=false},_mouseDestroy:function(){this.element.unbind("."+
this.widgetName)},_mouseDown:function(c){if(!g){this._mouseStarted&&this._mouseUp(c);this._mouseDownEvent=c;var f=this,i=c.which==1,h=typeof this.options.cancel=="string"&&c.target.nodeName?e(c.target).closest(this.options.cancel).length:false;if(!i||h||!this._mouseCapture(c))return true;this.mouseDelayMet=!this.options.delay;if(!this.mouseDelayMet)this._mouseDelayTimer=setTimeout(function(){f.mouseDelayMet=true},this.options.delay);if(this._mouseDistanceMet(c)&&this._mouseDelayMet(c)&&(this._mouseStarted=
this._mouseStart(c)!==false,!this._mouseStarted))return c.preventDefault(),true;true===e.data(c.target,this.widgetName+".preventClickEvent")&&e.removeData(c.target,this.widgetName+".preventClickEvent");this._mouseMoveDelegate=function(e){return f._mouseMove(e)};this._mouseUpDelegate=function(e){return f._mouseUp(e)};e(document).bind("mousemove."+this.widgetName,this._mouseMoveDelegate).bind("mouseup."+this.widgetName,this._mouseUpDelegate);c.preventDefault();return g=true}},_mouseMove:function(c){if(e.browser.msie&&
!(document.documentMode>=9)&&!c.button)return this._mouseUp(c);if(this._mouseStarted)return this._mouseDrag(c),c.preventDefault();if(this._mouseDistanceMet(c)&&this._mouseDelayMet(c))(this._mouseStarted=this._mouseStart(this._mouseDownEvent,c)!==false)?this._mouseDrag(c):this._mouseUp(c);return!this._mouseStarted},_mouseUp:function(c){e(document).unbind("mousemove."+this.widgetName,this._mouseMoveDelegate).unbind("mouseup."+this.widgetName,this._mouseUpDelegate);if(this._mouseStarted)this._mouseStarted=
false,c.target==this._mouseDownEvent.target&&e.data(c.target,this.widgetName+".preventClickEvent",true),this._mouseStop(c);return false},_mouseDistanceMet:function(e){return Math.max(Math.abs(this._mouseDownEvent.pageX-e.pageX),Math.abs(this._mouseDownEvent.pageY-e.pageY))>=this.options.distance},_mouseDelayMet:function(){return this.mouseDelayMet},_mouseStart:function(){},_mouseDrag:function(){},_mouseStop:function(){},_mouseCapture:function(){return true}})})(jQuery);(function(e){e.ui=e.ui||{};var g=/left|center|right/,c=/top|center|bottom/,f=e.fn.position,i=e.fn.offset;e.fn.position=function(h){if(!h||!h.of)return f.apply(this,arguments);var h=e.extend({},h),l=e(h.of),i=l[0],j=(h.collision||"flip").split(" "),m=h.offset?h.offset.split(" "):[0,0],k,p,o;i.nodeType===9?(k=l.width(),p=l.height(),o={top:0,left:0}):i.setTimeout?(k=l.width(),p=l.height(),o={top:l.scrollTop(),left:l.scrollLeft()}):i.preventDefault?(h.at="left top",k=p=0,o={top:h.of.pageY,left:h.of.pageX}):
(k=l.outerWidth(),p=l.outerHeight(),o=l.offset());e.each(["my","at"],function(){var e=(h[this]||"").split(" ");e.length===1&&(e=g.test(e[0])?e.concat(["center"]):c.test(e[0])?["center"].concat(e):["center","center"]);e[0]=g.test(e[0])?e[0]:"center";e[1]=c.test(e[1])?e[1]:"center";h[this]=e});j.length===1&&(j[1]=j[0]);m[0]=parseInt(m[0],10)||0;m.length===1&&(m[1]=m[0]);m[1]=parseInt(m[1],10)||0;h.at[0]==="right"?o.left+=k:h.at[0]==="center"&&(o.left+=k/2);h.at[1]==="bottom"?o.top+=p:h.at[1]==="center"&&
(o.top+=p/2);o.left+=m[0];o.top+=m[1];return this.each(function(){var c=e(this),f=c.outerWidth(),g=c.outerHeight(),i=parseInt(e.curCSS(this,"marginLeft",true))||0,l=parseInt(e.curCSS(this,"marginTop",true))||0,n=f+i+(parseInt(e.curCSS(this,"marginRight",true))||0),u=g+l+(parseInt(e.curCSS(this,"marginBottom",true))||0),w=e.extend({},o),y;h.my[0]==="right"?w.left-=f:h.my[0]==="center"&&(w.left-=f/2);h.my[1]==="bottom"?w.top-=g:h.my[1]==="center"&&(w.top-=g/2);w.left=Math.round(w.left);w.top=Math.round(w.top);
y={left:w.left-i,top:w.top-l};e.each(["left","top"],function(c,o){if(e.ui.position[j[c]])e.ui.position[j[c]][o](w,{targetWidth:k,targetHeight:p,elemWidth:f,elemHeight:g,collisionPosition:y,collisionWidth:n,collisionHeight:u,offset:m,my:h.my,at:h.at})});e.fn.bgiframe&&c.bgiframe();c.offset(e.extend(w,{using:h.using}))})};e.ui.position={fit:{left:function(c,f){var g=e(window),g=f.collisionPosition.left+f.collisionWidth-g.width()-g.scrollLeft();c.left=g>0?c.left-g:Math.max(c.left-f.collisionPosition.left,
c.left)},top:function(c,f){var g=e(window),g=f.collisionPosition.top+f.collisionHeight-g.height()-g.scrollTop();c.top=g>0?c.top-g:Math.max(c.top-f.collisionPosition.top,c.top)}},flip:{left:function(c,f){if(f.at[0]!=="center"){var g=e(window),g=f.collisionPosition.left+f.collisionWidth-g.width()-g.scrollLeft(),i=f.my[0]==="left"?-f.elemWidth:f.my[0]==="right"?f.elemWidth:0,m=f.at[0]==="left"?f.targetWidth:-f.targetWidth,k=-2*f.offset[0];c.left+=f.collisionPosition.left<0?i+m+k:g>0?i+m+k:0}},top:function(c,
f){if(f.at[1]!=="center"){var g=e(window),g=f.collisionPosition.top+f.collisionHeight-g.height()-g.scrollTop(),i=f.my[1]==="top"?-f.elemHeight:f.my[1]==="bottom"?f.elemHeight:0,m=f.at[1]==="top"?f.targetHeight:-f.targetHeight,k=-2*f.offset[1];c.top+=f.collisionPosition.top<0?i+m+k:g>0?i+m+k:0}}}};if(!e.offset.setOffset)e.offset.setOffset=function(c,f){if(/static/.test(e.curCSS(c,"position")))c.style.position="relative";var g=e(c),i=g.offset(),m=parseInt(e.curCSS(c,"top",true),10)||0,k=parseInt(e.curCSS(c,
"left",true),10)||0,i={top:f.top-i.top+m,left:f.left-i.left+k};"using"in f?f.using.call(c,i):g.css(i)},e.fn.offset=function(c){var f=this[0];return!f||!f.ownerDocument?null:c?this.each(function(){e.offset.setOffset(this,c)}):i.call(this)}})(jQuery);(function(e){var g=0;e.widget("ui.autocomplete",{options:{appendTo:"body",autoFocus:false,delay:300,minLength:1,position:{my:"left top",at:"left bottom",collision:"none"},source:null},pending:0,_create:function(){var c=this,f=this.element[0].ownerDocument,g;this.element.addClass("ui-autocomplete-input").attr("autocomplete","off").attr({role:"textbox","aria-autocomplete":"list","aria-haspopup":"true"}).bind("keydown.autocomplete",function(f){if(!c.options.disabled&&!c.element.propAttr("readOnly")){g=
false;var l=e.ui.keyCode;switch(f.keyCode){case l.PAGE_UP:c._move("previousPage",f);break;case l.PAGE_DOWN:c._move("nextPage",f);break;case l.UP:c._move("previous",f);f.preventDefault();break;case l.DOWN:c._move("next",f);f.preventDefault();break;case l.ENTER:case l.NUMPAD_ENTER:c.menu.active&&(g=true,f.preventDefault());case l.TAB:if(!c.menu.active)break;c.menu.select(f);break;case l.ESCAPE:c.element.val(c.term);c.close(f);break;default:clearTimeout(c.searching),c.searching=setTimeout(function(){if(c.term!=
c.element.val())c.selectedItem=null,c.search(null,f)},c.options.delay)}}}).bind("keypress.autocomplete",function(e){g&&(g=false,e.preventDefault())}).bind("focus.autocomplete",function(){if(!c.options.disabled)c.selectedItem=null,c.previous=c.element.val()}).bind("blur.autocomplete",function(e){if(!c.options.disabled)clearTimeout(c.searching),c.closing=setTimeout(function(){c.close(e);c._change(e)},150)});this._initSource();this.response=function(){return c._response.apply(c,arguments)};this.menu=
e("<ul></ul>").addClass("ui-autocomplete").appendTo(e(this.options.appendTo||"body",f)[0]).mousedown(function(f){var g=c.menu.element[0];e(f.target).closest(".ui-menu-item").length||setTimeout(function(){e(document).one("mousedown",function(f){f.target!==c.element[0]&&f.target!==g&&!e.ui.contains(g,f.target)&&c.close()})},1);setTimeout(function(){clearTimeout(c.closing)},13)}).menu({focus:function(e,f){var g=f.item.data("item.autocomplete");false!==c._trigger("focus",e,{item:g})&&/^key/.test(e.originalEvent.type)&&
c.element.val(g.value)},selected:function(e,g){var i=g.item.data("item.autocomplete"),j=c.previous;if(c.element[0]!==f.activeElement)c.element.focus(),c.previous=j,setTimeout(function(){c.previous=j;c.selectedItem=i},1);false!==c._trigger("select",e,{item:i})&&c.element.val(i.value);c.term=c.element.val();c.close(e);c.selectedItem=i},blur:function(){c.menu.element.is(":visible")&&c.element.val()!==c.term&&c.element.val(c.term)}}).zIndex(this.element.zIndex()+1).css({top:0,left:0}).hide().data("menu");
e.fn.bgiframe&&this.menu.element.bgiframe()},destroy:function(){this.element.removeClass("ui-autocomplete-input").removeAttr("autocomplete").removeAttr("role").removeAttr("aria-autocomplete").removeAttr("aria-haspopup");this.menu.element.remove();e.Widget.prototype.destroy.call(this)},_setOption:function(c,f){e.Widget.prototype._setOption.apply(this,arguments);c==="source"&&this._initSource();c==="appendTo"&&this.menu.element.appendTo(e(f||"body",this.element[0].ownerDocument)[0]);c==="disabled"&&
f&&this.xhr&&this.xhr.abort()},_initSource:function(){var c=this,f,i;e.isArray(this.options.source)?(f=this.options.source,this.source=function(c,g){g(e.ui.autocomplete.filter(f,c.term))}):typeof this.options.source==="string"?(i=this.options.source,this.source=function(f,l){c.xhr&&c.xhr.abort();c.xhr=e.ajax({url:i,data:f,dataType:"json",autocompleteRequest:++g,success:function(e){this.autocompleteRequest===g&&l(e)},error:function(){this.autocompleteRequest===g&&l([])}})}):this.source=this.options.source},
search:function(e,f){e=e!=null?e:this.element.val();this.term=this.element.val();if(e.length<this.options.minLength)return this.close(f);clearTimeout(this.closing);return this._trigger("search",f)===false?void 0:this._search(e)},_search:function(e){this.pending++;this.element.addClass("ui-autocomplete-loading");this.source({term:e},this.response)},_response:function(e){!this.options.disabled&&e&&e.length?(e=this._normalize(e),this._suggest(e),this._trigger("open")):this.close();this.pending--;this.pending||
this.element.removeClass("ui-autocomplete-loading")},close:function(e){clearTimeout(this.closing);this.menu.element.is(":visible")&&(this.menu.element.hide(),this.menu.deactivate(),this._trigger("close",e))},_change:function(e){this.previous!==this.element.val()&&this._trigger("change",e,{item:this.selectedItem})},_normalize:function(c){return c.length&&c[0].label&&c[0].value?c:e.map(c,function(c){return typeof c==="string"?{label:c,value:c}:e.extend({label:c.label||c.value,value:c.value||c.label},
c)})},_suggest:function(c){var f=this.menu.element.empty().zIndex(this.element.zIndex()+1);this._renderMenu(f,c);this.menu.deactivate();this.menu.refresh();f.show();this._resizeMenu();f.position(e.extend({of:this.element},this.options.position));this.options.autoFocus&&this.menu.next(new e.Event("mouseover"))},_resizeMenu:function(){var e=this.menu.element;e.outerWidth(Math.max(e.width("").outerWidth(),this.element.outerWidth()))},_renderMenu:function(c,f){var g=this;e.each(f,function(e,f){g._renderItem(c,
f)})},_renderItem:function(c,f){return e("<li></li>").data("item.autocomplete",f).append(e("<a></a>").text(f.label)).appendTo(c)},_move:function(e,f){if(this.menu.element.is(":visible"))if(this.menu.first()&&/^previous/.test(e)||this.menu.last()&&/^next/.test(e))this.element.val(this.term),this.menu.deactivate();else this.menu[e](f);else this.search(null,f)},widget:function(){return this.menu.element}});e.extend(e.ui.autocomplete,{escapeRegex:function(e){return e.replace(/[-[\]{}()*+?.,\\^$|#\s]/g,
"\\$&")},filter:function(c,f){var g=RegExp(e.ui.autocomplete.escapeRegex(f),"i");return e.grep(c,function(e){return g.test(e.label||e.value||e)})}})})(jQuery);
(function(e){e.widget("ui.menu",{_create:function(){var g=this;this.element.addClass("ui-menu ui-widget ui-widget-content ui-corner-all").attr({role:"listbox","aria-activedescendant":"ui-active-menuitem"}).click(function(c){e(c.target).closest(".ui-menu-item a").length&&(c.preventDefault(),g.select(c))});this.refresh()},refresh:function(){var g=this;this.element.children("li:not(.ui-menu-item):has(a)").addClass("ui-menu-item").attr("role","menuitem").children("a").addClass("ui-corner-all").attr("tabindex",
-1).mouseenter(function(c){g.activate(c,e(this).parent())}).mouseleave(function(){g.deactivate()})},activate:function(e,c){this.deactivate();if(this.hasScroll()){var f=c.offset().top-this.element.offset().top,i=this.element.scrollTop(),h=this.element.height();f<0?this.element.scrollTop(i+f):f>=h&&this.element.scrollTop(i+f-h+c.height())}this.active=c.eq(0).children("a").addClass("ui-state-hover").attr("id","ui-active-menuitem").end();this._trigger("focus",e,{item:c})},deactivate:function(){if(this.active)this.active.children("a").removeClass("ui-state-hover").removeAttr("id"),
this._trigger("blur"),this.active=null},next:function(e){this.move("next",".ui-menu-item:first",e)},previous:function(e){this.move("prev",".ui-menu-item:last",e)},first:function(){return this.active&&!this.active.prevAll(".ui-menu-item").length},last:function(){return this.active&&!this.active.nextAll(".ui-menu-item").length},move:function(e,c,f){this.active?(e=this.active[e+"All"](".ui-menu-item").eq(0),e.length?this.activate(f,e):this.activate(f,this.element.children(c))):this.activate(f,this.element.children(c))},
nextPage:function(g){if(this.hasScroll())if(!this.active||this.last())this.activate(g,this.element.children(".ui-menu-item:first"));else{var c=this.active.offset().top,f=this.element.height(),i=this.element.children(".ui-menu-item").filter(function(){var g=e(this).offset().top-c-f+e(this).height();return g<10&&g>-10});i.length||(i=this.element.children(".ui-menu-item:last"));this.activate(g,i)}else this.activate(g,this.element.children(".ui-menu-item").filter(!this.active||this.last()?":first":":last"))},
previousPage:function(g){if(this.hasScroll())if(!this.active||this.first())this.activate(g,this.element.children(".ui-menu-item:last"));else{var c=this.active.offset().top,f=this.element.height();result=this.element.children(".ui-menu-item").filter(function(){var g=e(this).offset().top-c+f-e(this).height();return g<10&&g>-10});result.length||(result=this.element.children(".ui-menu-item:first"));this.activate(g,result)}else this.activate(g,this.element.children(".ui-menu-item").filter(!this.active||
this.first()?":last":":first"))},hasScroll:function(){return this.element.height()<this.element[e.fn.prop?"prop":"attr"]("scrollHeight")},select:function(e){this._trigger("selected",e,{item:this.active})}})})(jQuery);(function(e){e.widget("ui.slider",e.ui.mouse,{widgetEventPrefix:"slide",options:{animate:false,distance:0,max:100,min:0,orientation:"horizontal",range:false,step:1,value:0,values:null},_create:function(){var g=this,c=this.options,f=this.element.find(".ui-slider-handle").addClass("ui-state-default ui-corner-all"),i=c.values&&c.values.length||1,h=[];this._mouseSliding=this._keySliding=false;this._animateOff=true;this._handleIndex=null;this._detectOrientation();this._mouseInit();this.element.addClass("ui-slider ui-slider-"+
this.orientation+" ui-widget ui-widget-content ui-corner-all"+(c.disabled?" ui-slider-disabled ui-disabled":""));this.range=e([]);if(c.range){if(c.range===true){if(!c.values)c.values=[this._valueMin(),this._valueMin()];if(c.values.length&&c.values.length!==2)c.values=[c.values[0],c.values[0]]}this.range=e("<div></div>").appendTo(this.element).addClass("ui-slider-range ui-widget-header"+(c.range==="min"||c.range==="max"?" ui-slider-range-"+c.range:""))}for(var l=f.length;l<i;l+=1)h.push("<a class='ui-slider-handle ui-state-default ui-corner-all' href='#'></a>");
this.handles=f.add(e(h.join("")).appendTo(g.element));this.handle=this.handles.eq(0);this.handles.add(this.range).filter("a").click(function(e){e.preventDefault()}).hover(function(){c.disabled||e(this).addClass("ui-state-hover")},function(){e(this).removeClass("ui-state-hover")}).focus(function(){c.disabled?e(this).blur():(e(".ui-slider .ui-state-focus").removeClass("ui-state-focus"),e(this).addClass("ui-state-focus"))}).blur(function(){e(this).removeClass("ui-state-focus")});this.handles.each(function(c){e(this).data("index.ui-slider-handle",
c)});this.handles.keydown(function(c){var f=true,h=e(this).data("index.ui-slider-handle"),i,p,o;if(!g.options.disabled){switch(c.keyCode){case e.ui.keyCode.HOME:case e.ui.keyCode.END:case e.ui.keyCode.PAGE_UP:case e.ui.keyCode.PAGE_DOWN:case e.ui.keyCode.UP:case e.ui.keyCode.RIGHT:case e.ui.keyCode.DOWN:case e.ui.keyCode.LEFT:if(f=false,!g._keySliding&&(g._keySliding=true,e(this).addClass("ui-state-active"),i=g._start(c,h),i===false))return}o=g.options.step;i=g.options.values&&g.options.values.length?
p=g.values(h):p=g.value();switch(c.keyCode){case e.ui.keyCode.HOME:p=g._valueMin();break;case e.ui.keyCode.END:p=g._valueMax();break;case e.ui.keyCode.PAGE_UP:p=g._trimAlignValue(i+(g._valueMax()-g._valueMin())/5);break;case e.ui.keyCode.PAGE_DOWN:p=g._trimAlignValue(i-(g._valueMax()-g._valueMin())/5);break;case e.ui.keyCode.UP:case e.ui.keyCode.RIGHT:if(i===g._valueMax())return;p=g._trimAlignValue(i+o);break;case e.ui.keyCode.DOWN:case e.ui.keyCode.LEFT:if(i===g._valueMin())return;p=g._trimAlignValue(i-
o)}g._slide(c,h,p);return f}}).keyup(function(c){var f=e(this).data("index.ui-slider-handle");if(g._keySliding)g._keySliding=false,g._stop(c,f),g._change(c,f),e(this).removeClass("ui-state-active")});this._refreshValue();this._animateOff=false},destroy:function(){this.handles.remove();this.range.remove();this.element.removeClass("ui-slider ui-slider-horizontal ui-slider-vertical ui-slider-disabled ui-widget ui-widget-content ui-corner-all").removeData("slider").unbind(".slider");this._mouseDestroy();
return this},_mouseCapture:function(g){var c=this.options,f,i,h,l,n;if(c.disabled)return false;this.elementSize={width:this.element.outerWidth(),height:this.element.outerHeight()};this.elementOffset=this.element.offset();f=this._normValueFromMouse({x:g.pageX,y:g.pageY});i=this._valueMax()-this._valueMin()+1;l=this;this.handles.each(function(c){var g=Math.abs(f-l.values(c));i>g&&(i=g,h=e(this),n=c)});c.range===true&&this.values(1)===c.min&&(n+=1,h=e(this.handles[n]));if(this._start(g,n)===false)return false;
this._mouseSliding=true;l._handleIndex=n;h.addClass("ui-state-active").focus();c=h.offset();this._clickOffset=!e(g.target).parents().andSelf().is(".ui-slider-handle")?{left:0,top:0}:{left:g.pageX-c.left-h.width()/2,top:g.pageY-c.top-h.height()/2-(parseInt(h.css("borderTopWidth"),10)||0)-(parseInt(h.css("borderBottomWidth"),10)||0)+(parseInt(h.css("marginTop"),10)||0)};this.handles.hasClass("ui-state-hover")||this._slide(g,n,f);return this._animateOff=true},_mouseStart:function(){return true},_mouseDrag:function(e){var c=
this._normValueFromMouse({x:e.pageX,y:e.pageY});this._slide(e,this._handleIndex,c);return false},_mouseStop:function(e){this.handles.removeClass("ui-state-active");this._mouseSliding=false;this._stop(e,this._handleIndex);this._change(e,this._handleIndex);this._clickOffset=this._handleIndex=null;return this._animateOff=false},_detectOrientation:function(){this.orientation=this.options.orientation==="vertical"?"vertical":"horizontal"},_normValueFromMouse:function(e){var c;this.orientation==="horizontal"?
(c=this.elementSize.width,e=e.x-this.elementOffset.left-(this._clickOffset?this._clickOffset.left:0)):(c=this.elementSize.height,e=e.y-this.elementOffset.top-(this._clickOffset?this._clickOffset.top:0));c=e/c;c>1&&(c=1);c<0&&(c=0);this.orientation==="vertical"&&(c=1-c);e=this._valueMax()-this._valueMin();return this._trimAlignValue(this._valueMin()+c*e)},_start:function(e,c){var f={handle:this.handles[c],value:this.value()};if(this.options.values&&this.options.values.length)f.value=this.values(c),
f.values=this.values();return this._trigger("start",e,f)},_slide:function(e,c,f){var i;if(this.options.values&&this.options.values.length){i=this.values(c?0:1);if(this.options.values.length===2&&this.options.range===true&&(c===0&&f>i||c===1&&f<i))f=i;f!==this.values(c)&&(i=this.values(),i[c]=f,e=this._trigger("slide",e,{handle:this.handles[c],value:f,values:i}),this.values(c?0:1),e!==false&&this.values(c,f,true))}else f!==this.value()&&(e=this._trigger("slide",e,{handle:this.handles[c],value:f}),
e!==false&&this.value(f))},_stop:function(e,c){var f={handle:this.handles[c],value:this.value()};if(this.options.values&&this.options.values.length)f.value=this.values(c),f.values=this.values();this._trigger("stop",e,f)},_change:function(e,c){if(!this._keySliding&&!this._mouseSliding){var f={handle:this.handles[c],value:this.value()};if(this.options.values&&this.options.values.length)f.value=this.values(c),f.values=this.values();this._trigger("change",e,f)}},value:function(e){if(arguments.length)this.options.value=
this._trimAlignValue(e),this._refreshValue(),this._change(null,0);else return this._value()},values:function(g,c){var f,i,h;if(arguments.length>1)this.options.values[g]=this._trimAlignValue(c),this._refreshValue(),this._change(null,g);else if(arguments.length)if(e.isArray(arguments[0])){f=this.options.values;i=arguments[0];for(h=0;h<f.length;h+=1)f[h]=this._trimAlignValue(i[h]),this._change(null,h);this._refreshValue()}else return this.options.values&&this.options.values.length?this._values(g):this.value();
else return this._values()},_setOption:function(g,c){var f,i=0;if(e.isArray(this.options.values))i=this.options.values.length;e.Widget.prototype._setOption.apply(this,arguments);switch(g){case "disabled":c?(this.handles.filter(".ui-state-focus").blur(),this.handles.removeClass("ui-state-hover"),this.handles.propAttr("disabled",true),this.element.addClass("ui-disabled")):(this.handles.propAttr("disabled",false),this.element.removeClass("ui-disabled"));break;case "orientation":this._detectOrientation();
this.element.removeClass("ui-slider-horizontal ui-slider-vertical").addClass("ui-slider-"+this.orientation);this._refreshValue();break;case "value":this._animateOff=true;this._refreshValue();this._change(null,0);this._animateOff=false;break;case "values":this._animateOff=true;this._refreshValue();for(f=0;f<i;f+=1)this._change(null,f);this._animateOff=false}},_value:function(){var e=this.options.value;return e=this._trimAlignValue(e)},_values:function(e){var c,f;if(arguments.length)c=this.options.values[e],
c=this._trimAlignValue(c);else{c=this.options.values.slice();for(f=0;f<c.length;f+=1)c[f]=this._trimAlignValue(c[f])}return c},_trimAlignValue:function(e){if(e<=this._valueMin())return this._valueMin();if(e>=this._valueMax())return this._valueMax();var c=this.options.step>0?this.options.step:1,f=(e-this._valueMin())%c;e-=f;Math.abs(f)*2>=c&&(e+=f>0?c:-c);return parseFloat(e.toFixed(5))},_valueMin:function(){return this.options.min},_valueMax:function(){return this.options.max},_refreshValue:function(){var g=
this.options.range,c=this.options,f=this,i=!this._animateOff?c.animate:false,h,l={},n,j,m,k;if(this.options.values&&this.options.values.length)this.handles.each(function(p){h=(f.values(p)-f._valueMin())/(f._valueMax()-f._valueMin())*100;l[f.orientation==="horizontal"?"left":"bottom"]=h+"%";e(this).stop(1,1)[i?"animate":"css"](l,c.animate);if(f.options.range===true)if(f.orientation==="horizontal"){if(p===0)f.range.stop(1,1)[i?"animate":"css"]({left:h+"%"},c.animate);if(p===1)f.range[i?"animate":"css"]({width:h-
n+"%"},{queue:false,duration:c.animate})}else{if(p===0)f.range.stop(1,1)[i?"animate":"css"]({bottom:h+"%"},c.animate);if(p===1)f.range[i?"animate":"css"]({height:h-n+"%"},{queue:false,duration:c.animate})}n=h});else{j=this.value();m=this._valueMin();k=this._valueMax();h=k!==m?(j-m)/(k-m)*100:0;l[f.orientation==="horizontal"?"left":"bottom"]=h+"%";this.handle.stop(1,1)[i?"animate":"css"](l,c.animate);if(g==="min"&&this.orientation==="horizontal")this.range.stop(1,1)[i?"animate":"css"]({width:h+"%"},
c.animate);if(g==="max"&&this.orientation==="horizontal")this.range[i?"animate":"css"]({width:100-h+"%"},{queue:false,duration:c.animate});if(g==="min"&&this.orientation==="vertical")this.range.stop(1,1)[i?"animate":"css"]({height:h+"%"},c.animate);if(g==="max"&&this.orientation==="vertical")this.range[i?"animate":"css"]({height:100-h+"%"},{queue:false,duration:c.animate})}}});e.extend(e.ui.slider,{version:"@VERSION"})})(jQuery);jQuery.effects||function(e,g){function c(c){var o;return c&&c.constructor==Array&&c.length==3?c:(o=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(c))?[parseInt(o[1],10),parseInt(o[2],10),parseInt(o[3],10)]:(o=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(c))?[parseFloat(o[1])*2.55,parseFloat(o[2])*2.55,parseFloat(o[3])*2.55]:(o=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(c))?[parseInt(o[1],16),parseInt(o[2],
16),parseInt(o[3],16)]:(o=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(c))?[parseInt(o[1]+o[1],16),parseInt(o[2]+o[2],16),parseInt(o[3]+o[3],16)]:/rgba\(0, 0, 0, 0\)/.exec(c)?j.transparent:j[e.trim(c).toLowerCase()]}function f(){var e=document.defaultView?document.defaultView.getComputedStyle(this,null):this.currentStyle,c={},f,g;if(e&&e.length&&e[0]&&e[e[0]])for(var h=e.length;h--;)f=e[h],typeof e[f]=="string"&&(g=f.replace(/\-(\w)/g,function(e,c){return c.toUpperCase()}),c[g]=e[f]);else for(f in e)typeof e[f]===
"string"&&(c[f]=e[f]);return c}function i(c){var o,f;for(o in c)f=c[o],(f==null||e.isFunction(f)||o in k||/scrollbar/.test(o)||!/color/i.test(o)&&isNaN(parseFloat(f)))&&delete c[o];return c}function h(e,c){var f={_:0},g;for(g in c)e[g]!=c[g]&&(f[g]=c[g]);return f}function l(c,f,g,h){if(typeof c=="object")h=f,g=null,f=c,c=f.effect;e.isFunction(f)&&(h=f,g=null,f={});if(typeof f=="number"||e.fx.speeds[f])h=g,g=f,f={};e.isFunction(g)&&(h=g,g=null);f=f||{};g=g||f.duration;g=e.fx.off?0:typeof g=="number"?
g:g in e.fx.speeds?e.fx.speeds[g]:e.fx.speeds._default;h=h||f.complete;return[c,f,g,h]}function n(c){return!c||typeof c==="number"||e.fx.speeds[c]?true:typeof c==="string"&&!e.effects[c]?true:false}e.effects={};e.each("backgroundColor,borderBottomColor,borderLeftColor,borderRightColor,borderTopColor,borderColor,color,outlineColor".split(","),function(f,o){e.fx.step[o]=function(f){if(!f.colorInit){var p;p=f.elem;var g=o,h;do{h=e.curCSS(p,g);if(h!=""&&h!="transparent"||e.nodeName(p,"body"))break;g=
"backgroundColor"}while(p=p.parentNode);p=c(h);f.start=p;f.end=c(f.end);f.colorInit=true}f.elem.style[o]="rgb("+Math.max(Math.min(parseInt(f.pos*(f.end[0]-f.start[0])+f.start[0],10),255),0)+","+Math.max(Math.min(parseInt(f.pos*(f.end[1]-f.start[1])+f.start[1],10),255),0)+","+Math.max(Math.min(parseInt(f.pos*(f.end[2]-f.start[2])+f.start[2],10),255),0)+")"}});var j={aqua:[0,255,255],azure:[240,255,255],beige:[245,245,220],black:[0,0,0],blue:[0,0,255],brown:[165,42,42],cyan:[0,255,255],darkblue:[0,
0,139],darkcyan:[0,139,139],darkgrey:[169,169,169],darkgreen:[0,100,0],darkkhaki:[189,183,107],darkmagenta:[139,0,139],darkolivegreen:[85,107,47],darkorange:[255,140,0],darkorchid:[153,50,204],darkred:[139,0,0],darksalmon:[233,150,122],darkviolet:[148,0,211],fuchsia:[255,0,255],gold:[255,215,0],green:[0,128,0],indigo:[75,0,130],khaki:[240,230,140],lightblue:[173,216,230],lightcyan:[224,255,255],lightgreen:[144,238,144],lightgrey:[211,211,211],lightpink:[255,182,193],lightyellow:[255,255,224],lime:[0,
255,0],magenta:[255,0,255],maroon:[128,0,0],navy:[0,0,128],olive:[128,128,0],orange:[255,165,0],pink:[255,192,203],purple:[128,0,128],violet:[128,0,128],red:[255,0,0],silver:[192,192,192],white:[255,255,255],yellow:[255,255,0],transparent:[255,255,255]},m=["add","remove","toggle"],k={border:1,borderBottom:1,borderColor:1,borderLeft:1,borderRight:1,borderTop:1,borderWidth:1,margin:1,padding:1};e.effects.animateClass=function(c,o,g,s){e.isFunction(g)&&(s=g,g=null);return this.queue(function(){var r=
e(this),k=r.attr("style")||" ",l=i(f.call(this)),j,n=r.attr("class");e.each(m,function(e,f){if(c[f])r[f+"Class"](c[f])});j=i(f.call(this));r.attr("class",n);r.animate(h(l,j),{queue:false,duration:o,easing:g,complete:function(){e.each(m,function(e,f){if(c[f])r[f+"Class"](c[f])});typeof r.attr("style")=="object"?(r.attr("style").cssText="",r.attr("style").cssText=k):r.attr("style",k);s&&s.apply(this,arguments);e.dequeue(this)}})})};e.fn.extend({_addClass:e.fn.addClass,addClass:function(c,f,g,h){return f?
e.effects.animateClass.apply(this,[{add:c},f,g,h]):this._addClass(c)},_removeClass:e.fn.removeClass,removeClass:function(c,f,g,h){return f?e.effects.animateClass.apply(this,[{remove:c},f,g,h]):this._removeClass(c)},_toggleClass:e.fn.toggleClass,toggleClass:function(c,f,h,s,i){return typeof f=="boolean"||f===g?h?e.effects.animateClass.apply(this,[f?{add:c}:{remove:c},h,s,i]):this._toggleClass(c,f):e.effects.animateClass.apply(this,[{toggle:c},f,h,s])},switchClass:function(c,f,g,h,i){return e.effects.animateClass.apply(this,
[{add:f,remove:c},g,h,i])}});e.extend(e.effects,{version:"@VERSION",save:function(e,c){for(var f=0;f<c.length;f++)c[f]!==null&&e.data("ec.storage."+c[f],e[0].style[c[f]])},restore:function(e,c){for(var f=0;f<c.length;f++)c[f]!==null&&e.css(c[f],e.data("ec.storage."+c[f]))},setMode:function(e,c){c=="toggle"&&(c=e.is(":hidden")?"show":"hide");return c},getBaseline:function(e,c){var f,g;switch(e[0]){case "top":f=0;break;case "middle":f=0.5;break;case "bottom":f=1;break;default:f=e[0]/c.height}switch(e[1]){case "left":g=
0;break;case "center":g=0.5;break;case "right":g=1;break;default:g=e[1]/c.width}return{x:g,y:f}},createWrapper:function(c){if(c.parent().is(".ui-effects-wrapper"))return c.parent();var f={width:c.outerWidth(true),height:c.outerHeight(true),"float":c.css("float")},g=e("<div></div>").addClass("ui-effects-wrapper").css({fontSize:"100%",background:"transparent",border:"none",margin:0,padding:0}),h=document.activeElement;c.wrap(g);(c[0]===h||e.contains(c[0],h))&&e(h).focus();g=c.parent();c.css("position")==
"static"?(g.css({position:"relative"}),c.css({position:"relative"})):(e.extend(f,{position:c.css("position"),zIndex:c.css("z-index")}),e.each(["top","left","bottom","right"],function(e,g){f[g]=c.css(g);isNaN(parseInt(f[g],10))&&(f[g]="auto")}),c.css({position:"relative",top:0,left:0,right:"auto",bottom:"auto"}));return g.css(f).show()},removeWrapper:function(c){var f,g=document.activeElement;return c.parent().is(".ui-effects-wrapper")?(f=c.parent().replaceWith(c),(c[0]===g||e.contains(c[0],g))&&e(g).focus(),
f):c},setTransition:function(c,f,g,h){h=h||{};e.each(f,function(e,f){unit=c.cssUnit(f);unit[0]>0&&(h[f]=unit[0]*g+unit[1])});return h}});e.fn.extend({effect:function(c,f,g,h){var i=l.apply(this,arguments),k={options:i[1],duration:i[2],callback:i[3]},i=k.options.mode,j=e.effects[c];return e.fx.off||!j?i?this[i](k.duration,k.callback):this.each(function(){k.callback&&k.callback.call(this)}):j.call(this,k)},_show:e.fn.show,show:function(e){if(n(e))return this._show.apply(this,arguments);else{var c=l.apply(this,
arguments);c[1].mode="show";return this.effect.apply(this,c)}},_hide:e.fn.hide,hide:function(e){if(n(e))return this._hide.apply(this,arguments);else{var c=l.apply(this,arguments);c[1].mode="hide";return this.effect.apply(this,c)}},__toggle:e.fn.toggle,toggle:function(c){if(n(c)||typeof c==="boolean"||e.isFunction(c))return this.__toggle.apply(this,arguments);else{var f=l.apply(this,arguments);f[1].mode="toggle";return this.effect.apply(this,f)}},cssUnit:function(c){var f=this.css(c),g=[];e.each(["em",
"px","%","pt"],function(e,c){f.indexOf(c)>0&&(g=[parseFloat(f),c])});return g}});e.easing.jswing=e.easing.swing;e.extend(e.easing,{def:"easeOutQuad",swing:function(c,f,g,h,i){return e.easing[e.easing.def](c,f,g,h,i)},easeInQuad:function(e,c,f,g,h){return g*(c/=h)*c+f},easeOutQuad:function(e,c,f,g,h){return-g*(c/=h)*(c-2)+f},easeInOutQuad:function(e,c,f,g,h){return(c/=h/2)<1?g/2*c*c+f:-g/2*(--c*(c-2)-1)+f},easeInCubic:function(e,c,f,g,h){return g*(c/=h)*c*c+f},easeOutCubic:function(e,c,f,g,h){return g*
((c=c/h-1)*c*c+1)+f},easeInOutCubic:function(e,c,f,g,h){return(c/=h/2)<1?g/2*c*c*c+f:g/2*((c-=2)*c*c+2)+f},easeInQuart:function(e,c,f,g,h){return g*(c/=h)*c*c*c+f},easeOutQuart:function(e,c,f,g,h){return-g*((c=c/h-1)*c*c*c-1)+f},easeInOutQuart:function(e,c,f,g,h){return(c/=h/2)<1?g/2*c*c*c*c+f:-g/2*((c-=2)*c*c*c-2)+f},easeInQuint:function(e,c,f,g,h){return g*(c/=h)*c*c*c*c+f},easeOutQuint:function(e,c,f,g,h){return g*((c=c/h-1)*c*c*c*c+1)+f},easeInOutQuint:function(e,c,f,g,h){return(c/=h/2)<1?g/2*
c*c*c*c*c+f:g/2*((c-=2)*c*c*c*c+2)+f},easeInSine:function(e,c,f,g,h){return-g*Math.cos(c/h*(Math.PI/2))+g+f},easeOutSine:function(e,c,f,g,h){return g*Math.sin(c/h*(Math.PI/2))+f},easeInOutSine:function(e,c,f,g,h){return-g/2*(Math.cos(Math.PI*c/h)-1)+f},easeInExpo:function(e,c,f,g,h){return c==0?f:g*Math.pow(2,10*(c/h-1))+f},easeOutExpo:function(e,c,f,g,h){return c==h?f+g:g*(-Math.pow(2,-10*c/h)+1)+f},easeInOutExpo:function(e,c,f,g,h){return c==0?f:c==h?f+g:(c/=h/2)<1?g/2*Math.pow(2,10*(c-1))+f:g/
2*(-Math.pow(2,-10*--c)+2)+f},easeInCirc:function(e,c,f,g,h){return-g*(Math.sqrt(1-(c/=h)*c)-1)+f},easeOutCirc:function(c,e,f,g,h){return g*Math.sqrt(1-(e=e/h-1)*e)+f},easeInOutCirc:function(e,c,f,g,h){return(c/=h/2)<1?-g/2*(Math.sqrt(1-c*c)-1)+f:g/2*(Math.sqrt(1-(c-=2)*c)+1)+f},easeInElastic:function(c,e,f,g,h){var c=1.70158,i=0,k=g;if(e==0)return f;if((e/=h)==1)return f+g;i||(i=h*0.3);k<Math.abs(g)?(k=g,c=i/4):c=i/(2*Math.PI)*Math.asin(g/k);return-(k*Math.pow(2,10*(e-=1))*Math.sin((e*h-c)*2*Math.PI/
i))+f},easeOutElastic:function(c,e,f,g,h){var c=1.70158,i=0,k=g;if(e==0)return f;if((e/=h)==1)return f+g;i||(i=h*0.3);k<Math.abs(g)?(k=g,c=i/4):c=i/(2*Math.PI)*Math.asin(g/k);return k*Math.pow(2,-10*e)*Math.sin((e*h-c)*2*Math.PI/i)+g+f},easeInOutElastic:function(c,e,f,g,h){var c=1.70158,i=0,k=g;if(e==0)return f;if((e/=h/2)==2)return f+g;i||(i=h*0.3*1.5);k<Math.abs(g)?(k=g,c=i/4):c=i/(2*Math.PI)*Math.asin(g/k);return e<1?-0.5*k*Math.pow(2,10*(e-=1))*Math.sin((e*h-c)*2*Math.PI/i)+f:k*Math.pow(2,-10*
(e-=1))*Math.sin((e*h-c)*2*Math.PI/i)*0.5+g+f},easeInBack:function(c,e,f,h,i,k){k==g&&(k=1.70158);return h*(e/=i)*e*((k+1)*e-k)+f},easeOutBack:function(e,c,f,h,i,k){k==g&&(k=1.70158);return h*((c=c/i-1)*c*((k+1)*c+k)+1)+f},easeInOutBack:function(c,e,f,h,i,k){k==g&&(k=1.70158);return(e/=i/2)<1?h/2*e*e*(((k*=1.525)+1)*e-k)+f:h/2*((e-=2)*e*(((k*=1.525)+1)*e+k)+2)+f},easeInBounce:function(c,f,g,h,i){return h-e.easing.easeOutBounce(c,i-f,0,h,i)+g},easeOutBounce:function(e,c,f,g,h){return(c/=h)<1/2.75?
g*7.5625*c*c+f:c<2/2.75?g*(7.5625*(c-=1.5/2.75)*c+0.75)+f:c<2.5/2.75?g*(7.5625*(c-=2.25/2.75)*c+0.9375)+f:g*(7.5625*(c-=2.625/2.75)*c+0.984375)+f},easeInOutBounce:function(c,f,g,h,i){return f<i/2?e.easing.easeInBounce(c,f*2,0,h,i)*0.5+g:e.easing.easeOutBounce(c,f*2-i,0,h,i)*0.5+h*0.5+g}})}(jQuery);(function(e){e.effects.transfer=function(g){return this.queue(function(){var c=e(this),f=e(g.options.to),i=f.offset(),f={top:i.top,left:i.left,height:f.innerHeight(),width:f.innerWidth()},i=c.offset(),h=e('<div class="ui-effects-transfer"></div>').appendTo(document.body).addClass(g.options.className).css({top:i.top,left:i.left,height:c.innerHeight(),width:c.innerWidth(),position:"absolute"}).animate(f,g.duration,g.options.easing,function(){h.remove();g.callback&&g.callback.apply(c[0],arguments);c.dequeue()})})}})(jQuery);(function(e){e.effects.blind=function(g){return this.queue(function(){var c=e(this),f=["position","top","bottom","left","right"],i=e.effects.setMode(c,g.options.mode||"hide"),h=g.options.direction||"vertical";e.effects.save(c,f);c.show();var l=e.effects.createWrapper(c).css({overflow:"hidden"}),n=h=="vertical"?"height":"width",h=h=="vertical"?l.height():l.width();i=="show"&&l.css(n,0);var j={};j[n]=i=="show"?h:0;l.animate(j,g.duration,g.options.easing,function(){i=="hide"&&c.hide();e.effects.restore(c,
f);e.effects.removeWrapper(c);g.callback&&g.callback.apply(c[0],arguments);c.dequeue()})})}})(jQuery);(function(e){e.fn.lightbox_me=function(g){return this.each(function(){function c(c){var f=e(window).height()-80;f<500&&(f=500);c.css("height",f)}function f(c){k[j.disappearEffect](j.lightboxDisappearSpeed,function(){c&&i();j.destroyOnClose?k.remove():k.hide();j.reallyBig&&e(".bPopupWrap").remove();k.find(j.closeSelector).unbind("click");k.unbind(".lme");e(window).unbind("scroll",n);e(window).unbind("resize",n)})}function i(){m.fadeOut(j.overlayDisappearSpeed,function(){e(window).unbind("resize",h);
m.remove();m.unbind("click");j.onClose()})}function h(){e(window).height()<e(document).height()?m.css({height:e(document).height()+"px"}):(m.css({height:"100%"}),o&&e("html,body").css("height","100%"))}function l(c){var e=c[0].style,f=window.pageYOffset;if(!f)f=document.documentElement.scrollTop;c.css({position:"absolute",top:(f+40)*1+"px",marginTop:0});o&&e.removeExpression("top")}function n(){var c=k[0].style;if(k.height()+80>=e(window).height()&&(k.css("position")!="absolute"||o)){var f=e(document).scrollTop()+
40;k.css({position:"absolute",top:f+"px",marginTop:0});o&&c.removeExpression("top")}else if(k.height()+80<e(window).height())o?(c.position="absolute",j.centered?(c.setExpression("top",'(document.documentElement.clientHeight || document.body.clientHeight) / 2 - (this.offsetHeight / 2) + (blah = document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop) + "px"'),c.marginTop=0):(f=j.modalCSS&&j.modalCSS.top?parseInt(j.modalCSS.top):0,c.setExpression("top","((blah = document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop) + "+
f+') + "px"'))):j.centered?k.css({position:"fixed",top:"50%",marginTop:k.outerHeight()/2*-1}):k.css({position:"fixed"}).css(j.modalCSS)}var j=e.extend({},e.fn.lightbox_me.defaults,g),m=e("div."+j.classPrefix+"_overlay"),k=e(this),p=e("iframe#lb_iframe"),o=e.browser.msie&&e.browser.version<7;m.length>0?m[0].removeModal():m=e('<div class="'+j.classPrefix+'_overlay" style="display:none;"/>');p=p.length>0?p:p=e('<iframe id="lb_iframe" style="z-index: '+(j.zIndex+1)+'; display: none; border: none; margin: 0; padding: 0; position: absolute; width: 100%; height: 100%; top: 0; left: 0;"/>');
if(o){var v=/^https/i.test(window.location.href||"")?"javascript:false":"about:blank";p.attr("src",v);e("body").append(p)}j.reallyBig?e("body").append(e("<div>").addClass("bPopupWrap").append(k)).append(m):e("body").append(k).append(m);j.reallyBig?(k.css({marginLeft:"50px",marginRight:"50px"}),l(k.parent()),c(k)):(n(),k.css({left:"50%",marginLeft:k.outerWidth()/2*-1,zIndex:j.zIndex+3}));h();m.css({position:"fixed",width:"100%",height:"100%",top:0,left:0,zIndex:j.zIndex+2}).css(j.overlayCSS);if(m.is(":hidden"))m.fadeIn(j.overlaySpeed,
function(){k[j.appearEffect](j.lightboxSpeed,function(){h();j.onLoad()})});else k[j.appearEffect](j.lightboxSpeed,function(){h();j.onLoad()});e(window).resize(h).resize(function(){j.reallyBig?l(k.parent()):n()}).resize(function(){j.reallyBig&&c(k)}).scroll(function(){j.reallyBig||n()}).keydown(function(c){(c.keyCode==27||c.DOM_VK_ESCAPE==27&&c.which==0)&&j.closeEsc&&f(true)});k.find(j.closeSelector).click(function(){f(true);return false});m.click(function(c){c.preventDefault();return false});setTimeout(function(){m.click(function(){if(j.closeClick)return f(true),
false})},500);k.bind("close.lme",function(){f(true)});k.bind("resize.lme",function(){j.reallyBig?l(k.parent()):n()});m[0].removeModal=f})};e.fn.lightbox_me.defaults={appearEffect:"fadeIn",overlaySpeed:300,lightboxSpeed:"fast",disappearEffect:"fadeOut",overlayDisappearSpeed:300,lightboxDisappearSpeed:"fast",closeSelector:".close",closeClick:true,closeEsc:true,destroyOnClose:false,onLoad:function(){},onClose:function(){},classPrefix:"lb",zIndex:999,centered:false,modalCSS:{top:"40px"},overlayCSS:{background:"black",
opacity:0.4}}})(jQuery);(function(e){function g(c){var g=c||window.event,h=[].slice.call(arguments,1),l=0,n=0,j=0,c=e.event.fix(g);c.type="mousewheel";c.wheelDelta&&(l=c.wheelDelta/120);c.detail&&(l=-c.detail/3);j=l;g.axis!==void 0&&g.axis===g.HORIZONTAL_AXIS&&(j=0,n=-1*l);g.wheelDeltaY!==void 0&&(j=g.wheelDeltaY/120);g.wheelDeltaX!==void 0&&(n=-1*g.wheelDeltaX/120);h.unshift(c,l,n,j);return e.event.handle.apply(this,h)}var c=["DOMMouseScroll","mousewheel"];e.event.special.mousewheel={setup:function(){if(this.addEventListener)for(var e=
c.length;e;)this.addEventListener(c[--e],g,false);else this.onmousewheel=g},teardown:function(){if(this.removeEventListener)for(var e=c.length;e;)this.removeEventListener(c[--e],g,false);else this.onmousewheel=null}};e.fn.extend({mousewheel:function(c){return c?this.bind("mousewheel",c):this.trigger("mousewheel")},unmousewheel:function(c){return this.unbind("mousewheel",c)}})})(jQuery);/*
			http://opensource.org/licenses/mit-license.php
 @package			jQuery Plugins

 Usage with default values:
 ---------------------------------------------------------------------------------
 $('#star').raty();

 <div id="star"></div>


 $('.star').raty();

 <div class="star"></div>
 <div class="star"></div>
 <div class="star"></div>

*/
(function(e){function g(f,g,o){var j=f.attr("id"),m=e("input#"+j+"-score"),r=f.children("img."+j);f.mouseleave(function(){h(f,m.val(),g);if(o!==null){var c="";g.targetKeep&&(c=m.val(),g.targetType=="hint"&&(c=m.val()==""&&g.cancel?g.cancelHint:g.hintList[Math.ceil(m.val())-1]));i(o)?o.val(c):o.html(c)}});r.bind(g.half?"mousemove":"mouseover",function(h){c(j,this.alt,g);g.half?(h=parseFloat(((h.pageX-e(this).offset().left)/g.size).toFixed(1)),f.data("score",parseFloat(this.alt)+(h>=0&&h<0.5?0.5:1)-
1),n(f,f.data("score"),g)):c(j,this.alt,g);l(o,this.alt,g)}).click(function(c){m.val(g.half?f.data("score"):this.alt);g.click&&g.click.apply(f,[m.val(),c])})}function c(c,f,g){for(var h=e("img."+c).length,i=0,j=0,l,m,n=1;n<=h;n++)l=e("img#"+c+"-"+n),n<=f?g.iconRange&&g.iconRange.length>i?(m=g.iconRange[i][0],j=g.iconRange[i][1],n<=j&&l.attr("src",g.path+m),n==j&&i++):l.attr("src",g.path+g.starOn):l.attr("src",g.path+g.starOff)}function f(c,e,f){var g="";e!=0?(e=parseInt(e),g=e>0&&f.number<=f.hintList.length&&
f.hintList[e-1]!==null?f.hintList[e-1]:e):g=f.noRatedMsg;c.attr("title",g).children("img").attr("title",g)}function i(c){return c.is("input")||c.is("select")||c.is("textarea")}function h(g,h,i){var j=g.attr("id");if(isNaN(parseInt(h)))g.children("img."+j).attr("src",i.path+i.starOff),e("input#"+j+"-score").removeAttr("value");else{if(h<0)h=0;else if(h>i.number)h=i.number;c(j,h,i);h>0&&(e("input#"+j+"-score").val(h),(i.half||i.showHalf)&&n(g,h,i));(i.readOnly||g.css("cursor")=="default")&&f(g,h,i)}}
function l(c,e,f){if(c!==null){var g=e;f.targetType=="hint"&&(g=e==0&&f.cancel?f.cancelHint:f.hintList[e-1]);i(c)?c.val(g):c.html(g)}}function n(c,f,g){var c=c.attr("id"),h=Math.ceil(f),f=(h-f).toFixed(1);f>0.25&&f<=0.75?(h-=0.5,e("img#"+c+"-"+Math.ceil(h)).attr("src",g.path+g.starHalf)):f>0.75?h--:e("img#"+c+"-"+h).attr("src",g.path+g.starOn)}function j(c,f,g){var h=void 0;if(f==void 0)m("Specify an ID or class to be the target of the action.");else{if(f){if(f.indexOf(".")>=0){var i;return e(f).each(function(){i=
"#"+e(this).attr("id");g=="start"?e.fn.raty.start(c,i):g=="click"?e.fn.raty.click(c,i):g=="readOnly"&&e.fn.raty.readOnly(c,i)})}h=e(f);if(!h.length){m('"'+f+'" is a invalid identifier for the public funtion $.fn.raty.'+g+"().");return}}return h}}function m(c){window.console&&window.console.log&&window.console.log(c)}e.fn.raty=function(h){if(this.length==0)m("Selector invalid or missing!");else{if(this.length>1)return this.each(function(){e.fn.raty.apply(e(this),[h])});var i=e.extend({},e.fn.raty.defaults,
h),j=e(this),v=this.attr("id"),s=0,r=i.starOn,x="",q=i.target,t=i.width?i.width:i.number*i.size+i.number*4;v===void 0&&(v="raty-"+j.index(),j.attr("id",v));if(i.number>20)i.number=20;else if(i.number<0)i.number=0;i.path.substring(i.path.length-1,i.path.length)!="/"&&(i.path+="/");j.data("options",i);!isNaN(parseInt(i.start))&&i.start>0&&(s=i.start>i.number?i.number:i.start);for(var u=1;u<=i.number;u++)r=s>=u?i.starOn:i.starOff,x=u<=i.hintList.length&&i.hintList[u-1]!==null?i.hintList[u-1]:u,j.append('<img id="'+
v+"-"+u+'" src="'+i.path+r+'" alt="'+u+'" title="'+x+'" class="'+v+'"/>').append(u<i.number?"&nbsp;":"");i.iconRange&&s>0&&c(v,s,i);r=e("<input/>",{id:v+"-score",type:"hidden",name:i.scoreName}).appendTo(j);s>0&&r.val(s);(i.half||i.showHalf)&&n(j,e("input#"+v+"-score").val(),i);if(i.readOnly)j.css("cursor","default"),f(j,s,i);else{q!==null&&(q=e(q),q.length==0&&m("Target selector invalid or missing!"));if(i.cancel){var w=e("img."+v),s='<img src="'+i.path+i.cancelOff+'" alt="x" title="'+i.cancelHint+
'" class="button-cancel"/>';i.cancelPlace=="left"?j.prepend(s+"&nbsp;"):j.append("&nbsp;").append(s);e("#"+v+" img.button-cancel").mouseenter(function(){e(this).attr("src",i.path+i.cancelOn);w.attr("src",i.path+i.starOff);l(q,"",i)}).mouseleave(function(){e(this).attr("src",i.path+i.cancelOff);j.mouseout()}).click(function(c){e("input#"+v+"-score").removeAttr("value");i.click&&i.click.apply(j,[null,c])});j.css("width",t+i.size+4)}else j.css("width",t);j.css("cursor","pointer");g(j,i,q)}return j}};
e.fn.raty.cancel=function(c,f){return f!==void 0?e.fn.raty.click("",c,"cancel"):e.fn.raty.start("",c,"cancel")};e.fn.raty.click=function(c,f){var g=j(c,f,"click"),i=e(f).data("options");if(!(f.indexOf(".")>=0))return h(g,c,i),i.click?i.click.apply(g,[c]):m('You must add the "click: function(score, evt) { }" callback.'),g};e.fn.raty.readOnly=function(c,f){var h=j(c,f,"readOnly"),i=e(f).data("options"),l=h.children("img.button-cancel");if(!(f.indexOf(".")>=0))return l[0]&&(c?l.hide():l.show()),c?(e("img."+
h.attr("id")).unbind(),h.css("cursor","default").unbind()):(g(h,i),h.css("cursor","pointer")),h};e.fn.raty.start=function(c,f){var g=j(c,f,"start"),i=e(f).data("options");if(!(f.indexOf(".")>=0))return h(g,c,i),g};e.fn.raty.defaults={cancel:false,cancelHint:"cancel this rating!",cancelOff:"cancel-off.png",cancelOn:"cancel-on.png",cancelPlace:"left",click:null,half:false,hintList:["bad","poor","regular","good","gorgeous"],noRatedMsg:"not rated yet",number:5,path:"img/",iconRange:[],readOnly:false,
scoreName:"score",size:16,starHalf:"star-half.png",starOff:"star-off.png",starOn:"star-on.png",start:0,target:null,targetKeep:false,targetType:"hint",width:null}})(jQuery);(function(e){function g(c){return typeof c=="object"?c:{top:c,left:c}}var c=e.scrollTo=function(c,g,h){e(window).scrollTo(c,g,h)};c.defaults={axis:"xy",duration:parseFloat(e.fn.jquery)>=1.3?0:1};c.window=function(){return e(window)._scrollable()};e.fn._scrollable=function(){return this.map(function(){if(this.nodeName&&e.inArray(this.nodeName.toLowerCase(),["iframe","#document","html","body"])==-1)return this;var c=(this.contentWindow||this).document||this.ownerDocument||this;return e.browser.safari||
c.compatMode=="BackCompat"?c.body:c.documentElement})};e.fn.scrollTo=function(f,i,h){typeof i=="object"&&(h=i,i=0);typeof h=="function"&&(h={onAfter:h});f=="max"&&(f=9E9);h=e.extend({},c.defaults,h);i=i||h.speed||h.duration;h.queue=h.queue&&h.axis.length>1;h.queue&&(i/=2);h.offset=g(h.offset);h.over=g(h.over);return this._scrollable().each(function(){function l(c){j.animate(p,i,h.easing,c&&function(){c.call(this,f,h)})}var n=this,j=e(n),m=f,k,p={},o=j.is("html,body");switch(typeof m){case "number":case "string":if(/^([+-]=)?\d+(\.\d+)?(px|%)?$/.test(m)){m=
g(m);break}m=e(m,this);case "object":if(m.is||m.style)k=(m=e(m)).offset()}e.each(h.axis.split(""),function(e,f){var g=f=="x"?"Left":"Top",i=g.toLowerCase(),q="scroll"+g,t=n[q],u=c.max(n,f);k?(p[q]=k[i]+(o?0:t-j.offset()[i]),h.margin&&(p[q]-=parseInt(m.css("margin"+g))||0,p[q]-=parseInt(m.css("border"+g+"Width"))||0),p[q]+=h.offset[i]||0,h.over[i]&&(p[q]+=m[f=="x"?"width":"height"]()*h.over[i])):(g=m[i],p[q]=g.slice&&g.slice(-1)=="%"?parseFloat(g)/100*u:g);/^\d+$/.test(p[q])&&(p[q]=p[q]<=0?0:Math.min(p[q],
u));!e&&h.queue&&(t!=p[q]&&l(h.onAfterFirst),delete p[q])});l(h.onAfter)}).end()};c.max=function(c,g){var h=g=="x"?"Width":"Height",l="scroll"+h;if(!e(c).is("html,body"))return c[l]-e(c)[h.toLowerCase()]();var h="client"+h,n=c.ownerDocument.documentElement,j=c.ownerDocument.body;return Math.max(n[l],j[l])-Math.min(n[h],j[h])}})(jQuery);jQuery.fn.extend({everyTime:function(e,g,c,f){return this.each(function(){jQuery.timer.add(this,e,g,c,f)})},oneTime:function(e,g,c){return this.each(function(){jQuery.timer.add(this,e,g,c,1)})},stopTime:function(e,g){return this.each(function(){jQuery.timer.remove(this,e,g)})}});
jQuery.extend({timer:{global:[],guid:1,dataKey:"jQuery.timer",regex:/^([0-9]+(?:\.[0-9]*)?)\s*(.*s)?$/,powers:{ms:1,cs:10,ds:100,s:1E3,das:1E4,hs:1E5,ks:1E6},timeParse:function(e){if(e==void 0||e==null)return null;var g=this.regex.exec(jQuery.trim(e.toString()));return g[2]?parseFloat(g[1])*(this.powers[g[2]]||1):e},add:function(e,g,c,f,i){var h=0;jQuery.isFunction(c)&&(i||(i=f),f=c,c=g);g=jQuery.timer.timeParse(g);if(!(typeof g!="number"||isNaN(g)||g<0)){if(typeof i!="number"||isNaN(i)||i<0)i=0;
var i=i||0,l=jQuery.data(e,this.dataKey)||jQuery.data(e,this.dataKey,{});l[c]||(l[c]={});f.timerID=f.timerID||this.guid++;var n=function(){(++h>i&&i!==0||f.call(e,h)===false)&&jQuery.timer.remove(e,c,f)};n.timerID=f.timerID;l[c][f.timerID]||(l[c][f.timerID]=window.setInterval(n,g));this.global.push(e)}},remove:function(e,g,c){var f=jQuery.data(e,this.dataKey),i;if(f){if(g){if(f[g]){if(c)c.timerID&&(window.clearInterval(f[g][c.timerID]),delete f[g][c.timerID]);else for(c in f[g])window.clearInterval(f[g][c]),
delete f[g][c];for(i in f[g])break;i||(i=null,delete f[g])}}else for(g in f)this.remove(e,g,c);for(i in f)break;i||jQuery.removeData(e,this.dataKey)}}}});jQuery(window).bind("unload",function(){jQuery.each(jQuery.timer.global,function(e,g){jQuery.timer.remove(g)})});jQuery.fn.prettyCheckboxes=function(e){e=jQuery.extend({checkboxWidth:13,checkboxHeight:13,className:"prettyCheckbox",display:"list"},e);$(this).each(function(){$label=$('label[for="'+$(this).attr("id")+'"]');$label.prepend("<span class='holderWrap'><span class='holder'></span></span>");$(this).is(":checked")&&$label.addClass("checked");$label.addClass(e.className).addClass($(this).attr("type")).addClass(e.display);$label.find("span.holderWrap").width(e.checkboxWidth).height(e.checkboxHeight);$label.find("span.holder").width(e.checkboxWidth);
$(this).addClass("hiddenCheckbox");$label.bind("click",function(){$("input#"+$(this).attr("for")).triggerHandler("click");$("input#"+$(this).attr("for")).is(":checkbox")?($(this).toggleClass("checked"),$("input#"+$(this).attr("for")).checked=true,$(this).find("span.holder").css("top",0)):($toCheck=$("input#"+$(this).attr("for")),$('input[name="'+$toCheck.attr("name")+'"]').each(function(){$('label[for="'+$(this).attr("id")+'"]').removeClass("checked")}),$(this).addClass("checked"),$toCheck.checked=
true)});$("input#"+$label.attr("for")).bind("keypress",function(e){if(e.keyCode==32)return $.browser.msie?$('label[for="'+$(this).attr("id")+'"]').toggleClass("checked"):$(this).trigger("click"),false})})};
checkAllPrettyCheckboxes=function(e,g){$(e).is(":checked")?$(g).find("input[type=checkbox]:not(:checked)").each(function(){$('label[for="'+$(this).attr("id")+'"]').trigger("click");$.browser.msie?$(this).attr("checked","checked"):$(this).trigger("click")}):$(g).find("input[type=checkbox]:checked").each(function(){$('label[for="'+$(this).attr("id")+'"]').trigger("click");$.browser.msie?$(this).attr("checked",""):$(this).trigger("click")})};(function(e){e.fn.typewriter=function(g,c){typeof c!=="function"&&(c=function(){});var f=function(c,g,l){var n=e(c).text().length+1;n<=g.length?(e(c).text(g.substr(0,n)),setTimeout(function(){f(c,g,l)},l)):c.callback()};return this.each(function(){this.callback=c;var i=e(this).text(),h=g/i.length;e(this).text("");f(this,i,h)})}})(jQuery);(function(e){function g(c,e){if(!(c.originalEvent.touches.length>1)){c.preventDefault();var f=c.originalEvent.changedTouches[0],g=document.createEvent("MouseEvents");g.initMouseEvent(e,true,true,window,1,f.screenX,f.screenY,f.clientX,f.clientY,false,false,false,false,0,null);c.target.dispatchEvent(g)}}e.support.touch="ontouchend"in document;if(e.support.touch){var c=e.ui.mouse.prototype,f=c._mouseInit,i;c._touchStart=function(c){if(!i&&this._mouseCapture(c.originalEvent.changedTouches[0]))i=true,
this._touchMoved=false,g(c,"mouseover"),g(c,"mousemove"),g(c,"mousedown")};c._touchMove=function(c){if(i)this._touchMoved=true,g(c,"mousemove")};c._touchEnd=function(c){i&&(g(c,"mouseup"),g(c,"mouseout"),this._touchMoved||g(c,"click"),i=false)};c._mouseInit=function(){this.element.bind("touchstart",e.proxy(this,"_touchStart")).bind("touchmove",e.proxy(this,"_touchMove")).bind("touchend",e.proxy(this,"_touchEnd"));f.call(this)}}})(jQuery);(function(e){var g=(e.browser.msie?"paste":"input")+".mask",c=window.orientation!=void 0;e.mask={definitions:{9:"[0-9]",a:"[A-Za-z]","*":"[A-Za-z0-9]"},dataName:"rawMaskFn"};e.fn.extend({caret:function(c,e){if(this.length!=0)if(typeof c=="number")return e=typeof e=="number"?e:c,this.each(function(){if(this.setSelectionRange)this.setSelectionRange(c,e);else if(this.createTextRange){var g=this.createTextRange();g.collapse(true);g.moveEnd("character",e);g.moveStart("character",c);g.select()}});else{if(this[0].setSelectionRange)c=
this[0].selectionStart,e=this[0].selectionEnd;else if(document.selection&&document.selection.createRange)var g=document.selection.createRange(),c=0-g.duplicate().moveStart("character",-1E5),e=c+g.text.length;return{begin:c,end:e}}},unmask:function(){return this.trigger("unmask")},mask:function(f,i){if(!f&&this.length>0)return e(this[0]).data(e.mask.dataName)();var i=e.extend({placeholder:"_",completed:null},i),h=e.mask.definitions,l=[],n=f.length,j=null,m=f.length;e.each(f.split(""),function(c,e){e==
"?"?(m--,n=c):h[e]?(l.push(RegExp(h[e])),j==null&&(j=l.length-1)):l.push(null)});return this.trigger("unmask").each(function(){function k(c){for(;++c<=m&&!l[c];);return c}function p(c,e){if(!(c<0)){for(var f=c,g=k(e);f<m;f++)if(l[f]){if(g<m&&l[f].test(t[g]))t[f]=t[g],t[g]=i.placeholder;else break;g=k(g)}r();q.caret(Math.max(j,c))}}function o(e){e=e.which;if(e==8||e==46||c&&e==127){var f=q.caret(),g=f.begin,f=f.end;if(f-g==0){if(e!=46)for(;--g>=0&&!l[g];);else g=f=k(g-1);f=e==46?k(f):f}s(g,f);p(g,
f-1);return false}else if(e==27)return q.val(u),q.caret(0,x()),false}function v(c){var e=c.which,f=q.caret();if(c.ctrlKey||c.altKey||c.metaKey||e<32)return true;else if(e){f.end-f.begin!=0&&(s(f.begin,f.end),p(f.begin,f.end-1));c=k(f.begin-1);if(c<m&&(e=String.fromCharCode(e),l[c].test(e))){for(var f=c,g=i.placeholder;f<m;f++)if(l[f]){var h=k(f),j=t[f];t[f]=g;if(h<m&&l[h].test(j))g=j;else break}t[c]=e;r();c=k(c);q.caret(c);i.completed&&c>=m&&i.completed.call(q)}return false}}function s(c,e){for(var f=
c;f<e&&f<m;f++)if(l[f])t[f]=i.placeholder}function r(){return q.val(t.join("")).val()}function x(c){for(var e=q.val(),f=-1,g=0,h=0;g<m;g++)if(l[g]){for(t[g]=i.placeholder;h++<e.length;){var k=e.charAt(h-1);if(l[g].test(k)){t[g]=k;f=g;break}}if(h>e.length)break}else t[g]==e.charAt(h)&&g!=n&&(h++,f=g);if(!c&&f+1<n)q.val(""),s(0,m);else if(c||f+1>=n)r(),c||q.val(q.val().substring(0,f+1));return n?g:j}var q=e(this),t=e.map(f.split(""),function(c){if(c!="?")return h[c]?i.placeholder:c}),u=q.val();q.data(e.mask.dataName,
function(){return e.map(t,function(c,e){return l[e]&&c!=i.placeholder?c:null}).join("")});q.attr("readonly")||q.one("unmask",function(){q.unbind(".mask").removeData(e.mask.dataName)}).bind("focus.mask",function(){u=q.val();var c=x();r();var g=function(){c==f.length?q.caret(0,c):q.caret(c)};(e.browser.msie?g:function(){setTimeout(g,0)})()}).bind("blur.mask",function(){x();q.val()!=u&&q.change()}).bind("keydown.mask",o).bind("keypress.mask",v).bind(g,function(){setTimeout(function(){q.caret(x(true))},
0)});x()})}})})(jQuery);
