var checkboxHeight="14",radioHeight="20",selectWidth="190";document.write('<style type="text/css">input.styled { display: none; } select.styled { position: relative; width: '+selectWidth+"px; opacity: 0; filter: alpha(opacity=0); z-index: 5; } .styled.disabled { opacity: 0.5; filter: alpha(opacity=50); }</style>");
var Custom={init:function(){var e=document.getElementsByTagName("input"),n=[],k,c;for(a=0;a<e.length;a++)if(("checkbox"==e[a].type||"radio"==e[a].type)&&"styled"==e[a].className)n[a]=document.createElement("span"),n[a].className=e[a].type,!0==e[a].checked&&(position="checkbox"==e[a].type?"0 -"+2*checkboxHeight+"px":"0 -"+2*radioHeight+"px",n[a].style.backgroundPosition=position),e[a].parentNode.insertBefore(n[a],e[a]),e[a].onchange=Custom.clear,e[a].getAttribute("disabled")?n[a].className=n[a].className+=
" disabled":(n[a].onmousedown=Custom.pushed,n[a].onmouseup=Custom.check);e=document.getElementsByTagName("select");for(a=0;a<e.length;a++)if("styled"==e[a].className){c=e[a].getElementsByTagName("option");k=c[0]?c[0].innerHTML:"-";k=document.createTextNode(k);for(b=0;b<c.length;b++)!0==c[b].selected&&(k=document.createTextNode(c[b].innerHTML));n[a]=document.createElement("span");n[a].className="select";n[a].id="select"+e[a].name;n[a].appendChild(k);e[a].parentNode.insertBefore(n[a],e[a]);e[a].getAttribute("disabled")?
e[a].previousSibling.className=e[a].previousSibling.className+=" disabled":e[a].onchange=Custom.choose}document.onmouseup=Custom.clear},pushed:function(){element=this.nextSibling;this.style.backgroundPosition=!0==element.checked&&"checkbox"==element.type?"0 -"+3*checkboxHeight+"px":!0==element.checked&&"radio"==element.type?"0 -"+3*radioHeight+"px":!0!=element.checked&&"checkbox"==element.type?"0 -"+checkboxHeight+"px":"0 -"+radioHeight+"px"},check:function(){element=this.nextSibling;if(!0==element.checked&&
"checkbox"==element.type)this.style.backgroundPosition="0 0",element.checked=!1;else{if("checkbox"==element.type)this.style.backgroundPosition="0 -"+2*checkboxHeight+"px";else{this.style.backgroundPosition="0 -"+2*radioHeight+"px";group=this.nextSibling.name;inputs=document.getElementsByTagName("input");for(a=0;a<inputs.length;a++)inputs[a].name==group&&inputs[a]!=this.nextSibling&&(inputs[a].previousSibling.style.backgroundPosition="0 0")}element.checked=!0}},clear:function(){inputs=document.getElementsByTagName("input");
for(var e=0;e<inputs.length;e++)"checkbox"==inputs[e].type&&!0==inputs[e].checked&&"styled"==inputs[e].className?inputs[e].previousSibling.style.backgroundPosition="0 -"+2*checkboxHeight+"px":"checkbox"==inputs[e].type&&"styled"==inputs[e].className?inputs[e].previousSibling.style.backgroundPosition="0 0":"radio"==inputs[e].type&&!0==inputs[e].checked&&"styled"==inputs[e].className?inputs[e].previousSibling.style.backgroundPosition="0 -"+2*radioHeight+"px":"radio"==inputs[e].type&&"styled"==inputs[e].className&&
(inputs[e].previousSibling.style.backgroundPosition="0 0")},choose:function(){option=this.getElementsByTagName("option");for(d=0;d<option.length;d++)!0==option[d].selected&&(document.getElementById("select"+this.name).innerHTML=option[d].innerHTML)}};Custom.init();(function(e,n){function k(g,f){var h=g.nodeName.toLowerCase();if("area"===h){var h=g.parentNode,q=h.name;if(!g.href||!q||"map"!==h.nodeName.toLowerCase())return!1;h=e("img[usemap=#"+q+"]")[0];return!!h&&c(h)}return(/input|select|textarea|button|object/.test(h)?!g.disabled:"a"==h?g.href||f:f)&&c(g)}function c(c){return!e(c).parents().andSelf().filter(function(){return"hidden"===e.curCSS(this,"visibility")||e.expr.filters.hidden(this)}).length}e.ui=e.ui||{};e.ui.version||(e.extend(e.ui,{version:"1.8.20",
keyCode:{ALT:18,BACKSPACE:8,CAPS_LOCK:20,COMMA:188,COMMAND:91,COMMAND_LEFT:91,COMMAND_RIGHT:93,CONTROL:17,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,MENU:93,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,WINDOWS:91}}),e.fn.extend({propAttr:e.fn.prop||e.fn.attr,_focus:e.fn.focus,focus:function(c,f){return"number"===typeof c?this.each(function(){var h=
this;setTimeout(function(){e(h).focus();f&&f.call(h)},c)}):this._focus.apply(this,arguments)},scrollParent:function(){var c;c=e.browser.msie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(e.curCSS(this,"position",1))&&/(auto|scroll)/.test(e.curCSS(this,"overflow",1)+e.curCSS(this,"overflow-y",1)+e.curCSS(this,"overflow-x",1))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(e.curCSS(this,
"overflow",1)+e.curCSS(this,"overflow-y",1)+e.curCSS(this,"overflow-x",1))}).eq(0);return/fixed/.test(this.css("position"))||!c.length?e(document):c},zIndex:function(c){if(c!==n)return this.css("zIndex",c);if(this.length){c=e(this[0]);for(var f;c.length&&c[0]!==document;){f=c.css("position");if("absolute"===f||"relative"===f||"fixed"===f)if(f=parseInt(c.css("zIndex"),10),!isNaN(f)&&0!==f)return f;c=c.parent()}}return 0},disableSelection:function(){return this.bind((e.support.selectstart?"selectstart":
"mousedown")+".ui-disableSelection",function(e){e.preventDefault()})},enableSelection:function(){return this.unbind(".ui-disableSelection")}}),e.each(["Width","Height"],function(c,f){function h(c,p,m,g){e.each(q,function(){p-=parseFloat(e.curCSS(c,"padding"+this,!0))||0;m&&(p-=parseFloat(e.curCSS(c,"border"+this+"Width",!0))||0);g&&(p-=parseFloat(e.curCSS(c,"margin"+this,!0))||0)});return p}var q="Width"===f?["Left","Right"]:["Top","Bottom"],l=f.toLowerCase(),k={innerWidth:e.fn.innerWidth,innerHeight:e.fn.innerHeight,
outerWidth:e.fn.outerWidth,outerHeight:e.fn.outerHeight};e.fn["inner"+f]=function(c){return c===n?k["inner"+f].call(this):this.each(function(){e(this).css(l,h(this,c)+"px")})};e.fn["outer"+f]=function(c,p){return"number"!==typeof c?k["outer"+f].call(this,c):this.each(function(){e(this).css(l,h(this,c,!0,p)+"px")})}}),e.extend(e.expr[":"],{data:function(c,f,h){return!!e.data(c,h[3])},focusable:function(c){return k(c,!isNaN(e.attr(c,"tabindex")))},tabbable:function(c){var f=e.attr(c,"tabindex"),h=isNaN(f);
return(h||0<=f)&&k(c,!h)}}),e(function(){var c=document.body,f=c.appendChild(f=document.createElement("div"));f.offsetHeight;e.extend(f.style,{minHeight:"100px",height:"auto",padding:0,borderWidth:0});e.support.minHeight=100===f.offsetHeight;e.support.selectstart="onselectstart"in f;c.removeChild(f).style.display="none"}),e.extend(e.ui,{plugin:{add:function(c,f,h){c=e.ui[c].prototype;for(var q in h)c.plugins[q]=c.plugins[q]||[],c.plugins[q].push([f,h[q]])},call:function(e,c,h){if((c=e.plugins[c])&&
e.element[0].parentNode)for(var q=0;q<c.length;q++)e.options[c[q][0]]&&c[q][1].apply(e.element,h)}},contains:function(e,c){return document.compareDocumentPosition?e.compareDocumentPosition(c)&16:e!==c&&e.contains(c)},hasScroll:function(c,f){if("hidden"===e(c).css("overflow"))return!1;var h=f&&"left"===f?"scrollLeft":"scrollTop",q=!1;if(0<c[h])return!0;c[h]=1;q=0<c[h];c[h]=0;return q},isOverAxis:function(e,c,h){return e>c&&e<c+h},isOver:function(c,f,h,q,l,k){return e.ui.isOverAxis(c,h,l)&&e.ui.isOverAxis(f,
q,k)}}))})(jQuery);(function(e,n){if(e.cleanData){var k=e.cleanData;e.cleanData=function(c){for(var f=0,h;null!=(h=c[f]);f++)try{e(h).triggerHandler("remove")}catch(q){}k(c)}}else{var c=e.fn.remove;e.fn.remove=function(g,f){return this.each(function(){f||(!g||e.filter(g,[this]).length)&&e("*",this).add([this]).each(function(){try{e(this).triggerHandler("remove")}catch(c){}});return c.call(e(this),g,f)})}}e.widget=function(c,f,h){var q=c.split(".")[0],l;c=c.split(".")[1];l=q+"-"+c;h||(h=f,f=e.Widget);e.expr[":"][l]=
function(f){return!!e.data(f,c)};e[q]=e[q]||{};e[q][c]=function(e,c){arguments.length&&this._createWidget(e,c)};f=new f;f.options=e.extend(!0,{},f.options);e[q][c].prototype=e.extend(!0,f,{namespace:q,widgetName:c,widgetEventPrefix:e[q][c].prototype.widgetEventPrefix||c,widgetBaseClass:l},h);e.widget.bridge(c,e[q][c])};e.widget.bridge=function(c,f){e.fn[c]=function(h){var q="string"===typeof h,l=Array.prototype.slice.call(arguments,1),k=this;h=!q&&l.length?e.extend.apply(null,[!0,h].concat(l)):h;
if(q&&"_"===h.charAt(0))return k;q?this.each(function(){var f=e.data(this,c),p=f&&e.isFunction(f[h])?f[h].apply(f,l):f;if(p!==f&&p!==n)return k=p,!1}):this.each(function(){var l=e.data(this,c);l?l.option(h||{})._init():e.data(this,c,new f(h,this))});return k}};e.Widget=function(e,c){arguments.length&&this._createWidget(e,c)};e.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",options:{disabled:!1},_createWidget:function(c,f){e.data(f,this.widgetName,this);this.element=e(f);this.options=e.extend(!0,
{},this.options,this._getCreateOptions(),c);var h=this;this.element.bind("remove."+this.widgetName,function(){h.destroy()});this._create();this._trigger("create");this._init()},_getCreateOptions:function(){return e.metadata&&e.metadata.get(this.element[0])[this.widgetName]},_create:function(){},_init:function(){},destroy:function(){this.element.unbind("."+this.widgetName).removeData(this.widgetName);this.widget().unbind("."+this.widgetName).removeAttr("aria-disabled").removeClass(this.widgetBaseClass+
"-disabled ui-state-disabled")},widget:function(){return this.element},option:function(c,f){var h=c;if(0===arguments.length)return e.extend({},this.options);if("string"===typeof c){if(f===n)return this.options[c];h={};h[c]=f}this._setOptions(h);return this},_setOptions:function(c){var f=this;e.each(c,function(e,c){f._setOption(e,c)});return this},_setOption:function(e,c){this.options[e]=c;"disabled"===e&&this.widget()[c?"addClass":"removeClass"](this.widgetBaseClass+"-disabled ui-state-disabled").attr("aria-disabled",
c);return this},enable:function(){return this._setOption("disabled",!1)},disable:function(){return this._setOption("disabled",!0)},_trigger:function(c,f,h){var q,l=this.options[c];h=h||{};f=e.Event(f);f.type=(c===this.widgetEventPrefix?c:this.widgetEventPrefix+c).toLowerCase();f.target=this.element[0];if(c=f.originalEvent)for(q in c)q in f||(f[q]=c[q]);this.element.trigger(f,h);return!(e.isFunction(l)&&!1===l.call(this.element[0],f,h)||f.isDefaultPrevented())}}})(jQuery);(function(e,n){e.ui=e.ui||{};var k=/left|center|right/,c=/top|center|bottom/,g={},f=e.fn.position,h=e.fn.offset;e.fn.position=function(h){if(!h||!h.of)return f.apply(this,arguments);h=e.extend({},h);var l=e(h.of),r=l[0],s=(h.collision||"flip").split(" "),p=h.offset?h.offset.split(" "):[0,0],m,v,u;9===r.nodeType?(m=l.width(),v=l.height(),u={top:0,left:0}):r.setTimeout?(m=l.width(),v=l.height(),u={top:l.scrollTop(),left:l.scrollLeft()}):r.preventDefault?(h.at="left top",m=v=0,u={top:h.of.pageY,left:h.of.pageX}):
(m=l.outerWidth(),v=l.outerHeight(),u=l.offset());e.each(["my","at"],function(){var e=(h[this]||"").split(" ");1===e.length&&(e=k.test(e[0])?e.concat(["center"]):c.test(e[0])?["center"].concat(e):["center","center"]);e[0]=k.test(e[0])?e[0]:"center";e[1]=c.test(e[1])?e[1]:"center";h[this]=e});1===s.length&&(s[1]=s[0]);p[0]=parseInt(p[0],10)||0;1===p.length&&(p[1]=p[0]);p[1]=parseInt(p[1],10)||0;"right"===h.at[0]?u.left+=m:"center"===h.at[0]&&(u.left+=m/2);"bottom"===h.at[1]?u.top+=v:"center"===h.at[1]&&
(u.top+=v/2);u.left+=p[0];u.top+=p[1];return this.each(function(){var c=e(this),f=c.outerWidth(),l=c.outerHeight(),k=parseInt(e.curCSS(this,"marginLeft",!0))||0,r=parseInt(e.curCSS(this,"marginTop",!0))||0,n=f+k+(parseInt(e.curCSS(this,"marginRight",!0))||0),D=l+r+(parseInt(e.curCSS(this,"marginBottom",!0))||0),y=e.extend({},u),B;"right"===h.my[0]?y.left-=f:"center"===h.my[0]&&(y.left-=f/2);"bottom"===h.my[1]?y.top-=l:"center"===h.my[1]&&(y.top-=l/2);g.fractions||(y.left=Math.round(y.left),y.top=
Math.round(y.top));B={left:y.left-k,top:y.top-r};e.each(["left","top"],function(c,g){if(e.ui.position[s[c]])e.ui.position[s[c]][g](y,{targetWidth:m,targetHeight:v,elemWidth:f,elemHeight:l,collisionPosition:B,collisionWidth:n,collisionHeight:D,offset:p,my:h.my,at:h.at})});e.fn.bgiframe&&c.bgiframe();c.offset(e.extend(y,{using:h.using}))})};e.ui.position={fit:{left:function(c,f){var g=e(window),g=f.collisionPosition.left+f.collisionWidth-g.width()-g.scrollLeft();c.left=0<g?c.left-g:Math.max(c.left-
f.collisionPosition.left,c.left)},top:function(c,f){var g=e(window),g=f.collisionPosition.top+f.collisionHeight-g.height()-g.scrollTop();c.top=0<g?c.top-g:Math.max(c.top-f.collisionPosition.top,c.top)}},flip:{left:function(c,f){if("center"!==f.at[0]){var g=e(window),g=f.collisionPosition.left+f.collisionWidth-g.width()-g.scrollLeft(),h="left"===f.my[0]?-f.elemWidth:"right"===f.my[0]?f.elemWidth:0,p="left"===f.at[0]?f.targetWidth:-f.targetWidth,m=-2*f.offset[0];c.left+=0>f.collisionPosition.left?h+
p+m:0<g?h+p+m:0}},top:function(c,f){if("center"!==f.at[1]){var g=e(window),g=f.collisionPosition.top+f.collisionHeight-g.height()-g.scrollTop(),h="top"===f.my[1]?-f.elemHeight:"bottom"===f.my[1]?f.elemHeight:0,p="top"===f.at[1]?f.targetHeight:-f.targetHeight,m=-2*f.offset[1];c.top+=0>f.collisionPosition.top?h+p+m:0<g?h+p+m:0}}}};e.offset.setOffset||(e.offset.setOffset=function(c,f){/static/.test(e.curCSS(c,"position"))&&(c.style.position="relative");var g=e(c),h=g.offset(),p=parseInt(e.curCSS(c,"top",
!0),10)||0,m=parseInt(e.curCSS(c,"left",!0),10)||0,h={top:f.top-h.top+p,left:f.left-h.left+m};"using"in f?f.using.call(c,h):g.css(h)},e.fn.offset=function(c){var f=this[0];return!f||!f.ownerDocument?null:c?this.each(function(){e.offset.setOffset(this,c)}):h.call(this)});(function(){var c=document.getElementsByTagName("body")[0],f=document.createElement("div"),h,k;h=document.createElement(c?"div":"body");k={visibility:"hidden",width:0,height:0,border:0,margin:0,background:"none"};c&&e.extend(k,{position:"absolute",
left:"-1000px",top:"-1000px"});for(var p in k)h.style[p]=k[p];h.appendChild(f);k=c||document.documentElement;k.insertBefore(h,k.firstChild);f.style.cssText="position: absolute; left: 10.7432222px; top: 10.432325px; height: 30px; width: 201px;";f=e(f).offset(function(c,e){return e}).offset();h.innerHTML="";k.removeChild(h);c=f.top+f.left+(c?2E3:0);g.fractions=21<c&&22>c})()})(jQuery);(function(e,n){var k=!1;e(document).mouseup(function(c){k=!1});e.widget("ui.mouse",{options:{cancel:":input,option",distance:1,delay:0},_mouseInit:function(){var c=this;this.element.bind("mousedown."+this.widgetName,function(e){return c._mouseDown(e)}).bind("click."+this.widgetName,function(g){if(!0===e.data(g.target,c.widgetName+".preventClickEvent"))return e.removeData(g.target,c.widgetName+".preventClickEvent"),g.stopImmediatePropagation(),!1});this.started=!1},_mouseDestroy:function(){this.element.unbind("."+
this.widgetName);e(document).unbind("mousemove."+this.widgetName,this._mouseMoveDelegate).unbind("mouseup."+this.widgetName,this._mouseUpDelegate)},_mouseDown:function(c){if(!k){this._mouseStarted&&this._mouseUp(c);this._mouseDownEvent=c;var g=this,f=1==c.which,h="string"==typeof this.options.cancel&&c.target.nodeName?e(c.target).closest(this.options.cancel).length:!1;if(!f||h||!this._mouseCapture(c))return!0;this.mouseDelayMet=!this.options.delay;this.mouseDelayMet||(this._mouseDelayTimer=setTimeout(function(){g.mouseDelayMet=
!0},this.options.delay));if(this._mouseDistanceMet(c)&&this._mouseDelayMet(c)&&(this._mouseStarted=!1!==this._mouseStart(c),!this._mouseStarted))return c.preventDefault(),!0;!0===e.data(c.target,this.widgetName+".preventClickEvent")&&e.removeData(c.target,this.widgetName+".preventClickEvent");this._mouseMoveDelegate=function(c){return g._mouseMove(c)};this._mouseUpDelegate=function(c){return g._mouseUp(c)};e(document).bind("mousemove."+this.widgetName,this._mouseMoveDelegate).bind("mouseup."+this.widgetName,
this._mouseUpDelegate);c.preventDefault();return k=!0}},_mouseMove:function(c){if(e.browser.msie&&!(9<=document.documentMode)&&!c.button)return this._mouseUp(c);if(this._mouseStarted)return this._mouseDrag(c),c.preventDefault();this._mouseDistanceMet(c)&&this._mouseDelayMet(c)&&((this._mouseStarted=!1!==this._mouseStart(this._mouseDownEvent,c))?this._mouseDrag(c):this._mouseUp(c));return!this._mouseStarted},_mouseUp:function(c){e(document).unbind("mousemove."+this.widgetName,this._mouseMoveDelegate).unbind("mouseup."+
this.widgetName,this._mouseUpDelegate);this._mouseStarted&&(this._mouseStarted=!1,c.target==this._mouseDownEvent.target&&e.data(c.target,this.widgetName+".preventClickEvent",!0),this._mouseStop(c));return!1},_mouseDistanceMet:function(c){return Math.max(Math.abs(this._mouseDownEvent.pageX-c.pageX),Math.abs(this._mouseDownEvent.pageY-c.pageY))>=this.options.distance},_mouseDelayMet:function(c){return this.mouseDelayMet},_mouseStart:function(c){},_mouseDrag:function(c){},_mouseStop:function(c){},_mouseCapture:function(c){return!0}})})(jQuery);(function(e,n){var k=0;e.widget("ui.autocomplete",{options:{appendTo:"body",autoFocus:!1,delay:300,minLength:1,position:{my:"left top",at:"left bottom",collision:"none"},source:null},pending:0,_create:function(){var c=this,g=this.element[0].ownerDocument,f;this.isMultiLine=this.element.is("textarea");this.element.addClass("ui-autocomplete-input").attr("autocomplete","off").attr({role:"textbox","aria-autocomplete":"list","aria-haspopup":"true"}).bind("keydown.autocomplete",function(g){if(!c.options.disabled&&
!c.element.propAttr("readOnly")){f=!1;var k=e.ui.keyCode;switch(g.keyCode){case k.PAGE_UP:c._move("previousPage",g);break;case k.PAGE_DOWN:c._move("nextPage",g);break;case k.UP:c._keyEvent("previous",g);break;case k.DOWN:c._keyEvent("next",g);break;case k.ENTER:case k.NUMPAD_ENTER:c.menu.active&&(f=!0,g.preventDefault());case k.TAB:if(!c.menu.active)break;c.menu.select(g);break;case k.ESCAPE:c.element.val(c.term);c.close(g);break;default:clearTimeout(c.searching),c.searching=setTimeout(function(){c.term!=
c.element.val()&&(c.selectedItem=null,c.search(null,g))},c.options.delay)}}}).bind("keypress.autocomplete",function(c){f&&(f=!1,c.preventDefault())}).bind("focus.autocomplete",function(){c.options.disabled||(c.selectedItem=null,c.previous=c.element.val())}).bind("blur.autocomplete",function(e){c.options.disabled||(clearTimeout(c.searching),c.closing=setTimeout(function(){c.close(e);c._change(e)},150))});this._initSource();this.menu=e("<ul></ul>").addClass("ui-autocomplete").appendTo(e(this.options.appendTo||
"body",g)[0]).mousedown(function(f){var g=c.menu.element[0];e(f.target).closest(".ui-menu-item").length||setTimeout(function(){e(document).one("mousedown",function(f){f.target!==c.element[0]&&(f.target!==g&&!e.ui.contains(g,f.target))&&c.close()})},1);setTimeout(function(){clearTimeout(c.closing)},13)}).menu({focus:function(e,f){var g=f.item.data("item.autocomplete");!1!==c._trigger("focus",e,{item:g})&&/^key/.test(e.originalEvent.type)&&c.element.val(g.value)},selected:function(e,f){var k=f.item.data("item.autocomplete"),
n=c.previous;c.element[0]!==g.activeElement&&(c.element.focus(),c.previous=n,setTimeout(function(){c.previous=n;c.selectedItem=k},1));!1!==c._trigger("select",e,{item:k})&&c.element.val(k.value);c.term=c.element.val();c.close(e);c.selectedItem=k},blur:function(e,f){c.menu.element.is(":visible")&&c.element.val()!==c.term&&c.element.val(c.term)}}).zIndex(this.element.zIndex()+1).css({top:0,left:0}).hide().data("menu");e.fn.bgiframe&&this.menu.element.bgiframe();c.beforeunloadHandler=function(){c.element.removeAttr("autocomplete")};
e(window).bind("beforeunload",c.beforeunloadHandler)},destroy:function(){this.element.removeClass("ui-autocomplete-input").removeAttr("autocomplete").removeAttr("role").removeAttr("aria-autocomplete").removeAttr("aria-haspopup");this.menu.element.remove();e(window).unbind("beforeunload",this.beforeunloadHandler);e.Widget.prototype.destroy.call(this)},_setOption:function(c,g){e.Widget.prototype._setOption.apply(this,arguments);"source"===c&&this._initSource();"appendTo"===c&&this.menu.element.appendTo(e(g||
"body",this.element[0].ownerDocument)[0]);"disabled"===c&&(g&&this.xhr)&&this.xhr.abort()},_initSource:function(){var c=this,g,f;e.isArray(this.options.source)?(g=this.options.source,this.source=function(c,f){f(e.ui.autocomplete.filter(g,c.term))}):"string"===typeof this.options.source?(f=this.options.source,this.source=function(g,k){c.xhr&&c.xhr.abort();c.xhr=e.ajax({url:f,data:g,dataType:"json",success:function(c,e){k(c)},error:function(){k([])}})}):this.source=this.options.source},search:function(c,
e){c=null!=c?c:this.element.val();this.term=this.element.val();if(c.length<this.options.minLength)return this.close(e);clearTimeout(this.closing);if(!1!==this._trigger("search",e))return this._search(c)},_search:function(c){this.pending++;this.element.addClass("ui-autocomplete-loading");this.source({term:c},this._response())},_response:function(){var c=this,e=++k;return function(f){e===k&&c.__response(f);c.pending--;c.pending||c.element.removeClass("ui-autocomplete-loading")}},__response:function(c){!this.options.disabled&&
c&&c.length?(c=this._normalize(c),this._suggest(c),this._trigger("open")):this.close()},close:function(c){clearTimeout(this.closing);this.menu.element.is(":visible")&&(this.menu.element.hide(),this.menu.deactivate(),this._trigger("close",c))},_change:function(c){this.previous!==this.element.val()&&this._trigger("change",c,{item:this.selectedItem})},_normalize:function(c){return c.length&&c[0].label&&c[0].value?c:e.map(c,function(c){return"string"===typeof c?{label:c,value:c}:e.extend({label:c.label||
c.value,value:c.value||c.label},c)})},_suggest:function(c){var g=this.menu.element.empty().zIndex(this.element.zIndex()+1);this._renderMenu(g,c);this.menu.deactivate();this.menu.refresh();g.show();this._resizeMenu();g.position(e.extend({of:this.element},this.options.position));this.options.autoFocus&&this.menu.next(new e.Event("mouseover"))},_resizeMenu:function(){var c=this.menu.element;c.outerWidth(Math.max(c.width("").outerWidth()+1,this.element.outerWidth()))},_renderMenu:function(c,g){var f=
this;e.each(g,function(e,g){f._renderItem(c,g)})},_renderItem:function(c,g){return e("<li></li>").data("item.autocomplete",g).append(e("<a></a>").text(g.label)).appendTo(c)},_move:function(c,e){if(this.menu.element.is(":visible"))if(this.menu.first()&&/^previous/.test(c)||this.menu.last()&&/^next/.test(c))this.element.val(this.term),this.menu.deactivate();else this.menu[c](e);else this.search(null,e)},widget:function(){return this.menu.element},_keyEvent:function(c,e){if(!this.isMultiLine||this.menu.element.is(":visible"))this._move(c,
e),e.preventDefault()}});e.extend(e.ui.autocomplete,{escapeRegex:function(c){return c.replace(/[-[\]{}()*+?.,\\^$|#\s]/g,"\\$&")},filter:function(c,g){var f=RegExp(e.ui.autocomplete.escapeRegex(g),"i");return e.grep(c,function(c){return f.test(c.label||c.value||c)})}})})(jQuery);
(function(e){e.widget("ui.menu",{_create:function(){var n=this;this.element.addClass("ui-menu ui-widget ui-widget-content ui-corner-all").attr({role:"listbox","aria-activedescendant":"ui-active-menuitem"}).click(function(k){e(k.target).closest(".ui-menu-item a").length&&(k.preventDefault(),n.select(k))});this.refresh()},refresh:function(){var n=this;this.element.children("li:not(.ui-menu-item):has(a)").addClass("ui-menu-item").attr("role","menuitem").children("a").addClass("ui-corner-all").attr("tabindex",
-1).mouseenter(function(k){n.activate(k,e(this).parent())}).mouseleave(function(){n.deactivate()})},activate:function(e,k){this.deactivate();if(this.hasScroll()){var c=k.offset().top-this.element.offset().top,g=this.element.scrollTop(),f=this.element.height();0>c?this.element.scrollTop(g+c):c>=f&&this.element.scrollTop(g+c-f+k.height())}this.active=k.eq(0).children("a").addClass("ui-state-hover").attr("id","ui-active-menuitem").end();this._trigger("focus",e,{item:k})},deactivate:function(){this.active&&
(this.active.children("a").removeClass("ui-state-hover").removeAttr("id"),this._trigger("blur"),this.active=null)},next:function(e){this.move("next",".ui-menu-item:first",e)},previous:function(e){this.move("prev",".ui-menu-item:last",e)},first:function(){return this.active&&!this.active.prevAll(".ui-menu-item").length},last:function(){return this.active&&!this.active.nextAll(".ui-menu-item").length},move:function(e,k,c){this.active?(e=this.active[e+"All"](".ui-menu-item").eq(0),e.length?this.activate(c,
e):this.activate(c,this.element.children(k))):this.activate(c,this.element.children(k))},nextPage:function(n){if(this.hasScroll())if(!this.active||this.last())this.activate(n,this.element.children(".ui-menu-item:first"));else{var k=this.active.offset().top,c=this.element.height(),g=this.element.children(".ui-menu-item").filter(function(){var f=e(this).offset().top-k-c+e(this).height();return 10>f&&-10<f});g.length||(g=this.element.children(".ui-menu-item:last"));this.activate(n,g)}else this.activate(n,
this.element.children(".ui-menu-item").filter(!this.active||this.last()?":first":":last"))},previousPage:function(n){if(this.hasScroll())if(!this.active||this.first())this.activate(n,this.element.children(".ui-menu-item:last"));else{var k=this.active.offset().top,c=this.element.height(),g=this.element.children(".ui-menu-item").filter(function(){var f=e(this).offset().top-k+c-e(this).height();return 10>f&&-10<f});g.length||(g=this.element.children(".ui-menu-item:first"));this.activate(n,g)}else this.activate(n,
this.element.children(".ui-menu-item").filter(!this.active||this.first()?":last":":first"))},hasScroll:function(){return this.element.height()<this.element[e.fn.prop?"prop":"attr"]("scrollHeight")},select:function(e){this._trigger("selected",e,{item:this.active})}})})(jQuery);(function(e,n){e.widget("ui.slider",e.ui.mouse,{widgetEventPrefix:"slide",options:{animate:!1,distance:0,max:100,min:0,orientation:"horizontal",range:!1,step:1,value:0,values:null},_create:function(){var k=this,c=this.options,g=this.element.find(".ui-slider-handle").addClass("ui-state-default ui-corner-all"),f=c.values&&c.values.length||1,h=[];this._mouseSliding=this._keySliding=!1;this._animateOff=!0;this._handleIndex=null;this._detectOrientation();this._mouseInit();this.element.addClass("ui-slider ui-slider-"+
this.orientation+" ui-widget ui-widget-content ui-corner-all"+(c.disabled?" ui-slider-disabled ui-disabled":""));this.range=e([]);c.range&&(!0===c.range&&(c.values||(c.values=[this._valueMin(),this._valueMin()]),c.values.length&&2!==c.values.length&&(c.values=[c.values[0],c.values[0]])),this.range=e("<div></div>").appendTo(this.element).addClass("ui-slider-range ui-widget-header"+("min"===c.range||"max"===c.range?" ui-slider-range-"+c.range:"")));for(var q=g.length;q<f;q+=1)h.push("<a class='ui-slider-handle ui-state-default ui-corner-all' href='#'></a>");
this.handles=g.add(e(h.join("")).appendTo(k.element));this.handle=this.handles.eq(0);this.handles.add(this.range).filter("a").click(function(c){c.preventDefault()}).hover(function(){c.disabled||e(this).addClass("ui-state-hover")},function(){e(this).removeClass("ui-state-hover")}).focus(function(){c.disabled?e(this).blur():(e(".ui-slider .ui-state-focus").removeClass("ui-state-focus"),e(this).addClass("ui-state-focus"))}).blur(function(){e(this).removeClass("ui-state-focus")});this.handles.each(function(c){e(this).data("index.ui-slider-handle",
c)});this.handles.keydown(function(c){var f=e(this).data("index.ui-slider-handle"),g,p,m;if(!k.options.disabled){switch(c.keyCode){case e.ui.keyCode.HOME:case e.ui.keyCode.END:case e.ui.keyCode.PAGE_UP:case e.ui.keyCode.PAGE_DOWN:case e.ui.keyCode.UP:case e.ui.keyCode.RIGHT:case e.ui.keyCode.DOWN:case e.ui.keyCode.LEFT:if(c.preventDefault(),!k._keySliding&&(k._keySliding=!0,e(this).addClass("ui-state-active"),g=k._start(c,f),!1===g))return}m=k.options.step;g=k.options.values&&k.options.values.length?
p=k.values(f):p=k.value();switch(c.keyCode){case e.ui.keyCode.HOME:p=k._valueMin();break;case e.ui.keyCode.END:p=k._valueMax();break;case e.ui.keyCode.PAGE_UP:p=k._trimAlignValue(g+(k._valueMax()-k._valueMin())/5);break;case e.ui.keyCode.PAGE_DOWN:p=k._trimAlignValue(g-(k._valueMax()-k._valueMin())/5);break;case e.ui.keyCode.UP:case e.ui.keyCode.RIGHT:if(g===k._valueMax())return;p=k._trimAlignValue(g+m);break;case e.ui.keyCode.DOWN:case e.ui.keyCode.LEFT:if(g===k._valueMin())return;p=k._trimAlignValue(g-
m)}k._slide(c,f,p)}}).keyup(function(c){var f=e(this).data("index.ui-slider-handle");k._keySliding&&(k._keySliding=!1,k._stop(c,f),k._change(c,f),e(this).removeClass("ui-state-active"))});this._refreshValue();this._animateOff=!1},destroy:function(){this.handles.remove();this.range.remove();this.element.removeClass("ui-slider ui-slider-horizontal ui-slider-vertical ui-slider-disabled ui-widget ui-widget-content ui-corner-all").removeData("slider").unbind(".slider");this._mouseDestroy();return this},
_mouseCapture:function(k){var c=this.options,g,f,h,q,l;if(c.disabled)return!1;this.elementSize={width:this.element.outerWidth(),height:this.element.outerHeight()};this.elementOffset=this.element.offset();g=this._normValueFromMouse({x:k.pageX,y:k.pageY});f=this._valueMax()-this._valueMin()+1;q=this;this.handles.each(function(c){var k=Math.abs(g-q.values(c));f>k&&(f=k,h=e(this),l=c)});!0===c.range&&this.values(1)===c.min&&(l+=1,h=e(this.handles[l]));if(!1===this._start(k,l))return!1;this._mouseSliding=
!0;q._handleIndex=l;h.addClass("ui-state-active").focus();c=h.offset();this._clickOffset=!e(k.target).parents().andSelf().is(".ui-slider-handle")?{left:0,top:0}:{left:k.pageX-c.left-h.width()/2,top:k.pageY-c.top-h.height()/2-(parseInt(h.css("borderTopWidth"),10)||0)-(parseInt(h.css("borderBottomWidth"),10)||0)+(parseInt(h.css("marginTop"),10)||0)};this.handles.hasClass("ui-state-hover")||this._slide(k,l,g);return this._animateOff=!0},_mouseStart:function(e){return!0},_mouseDrag:function(e){var c=
this._normValueFromMouse({x:e.pageX,y:e.pageY});this._slide(e,this._handleIndex,c);return!1},_mouseStop:function(e){this.handles.removeClass("ui-state-active");this._mouseSliding=!1;this._stop(e,this._handleIndex);this._change(e,this._handleIndex);this._clickOffset=this._handleIndex=null;return this._animateOff=!1},_detectOrientation:function(){this.orientation="vertical"===this.options.orientation?"vertical":"horizontal"},_normValueFromMouse:function(e){var c;"horizontal"===this.orientation?(c=this.elementSize.width,
e=e.x-this.elementOffset.left-(this._clickOffset?this._clickOffset.left:0)):(c=this.elementSize.height,e=e.y-this.elementOffset.top-(this._clickOffset?this._clickOffset.top:0));c=e/c;1<c&&(c=1);0>c&&(c=0);"vertical"===this.orientation&&(c=1-c);e=this._valueMax()-this._valueMin();c=this._valueMin()+c*e;return this._trimAlignValue(c)},_start:function(e,c){var g={handle:this.handles[c],value:this.value()};this.options.values&&this.options.values.length&&(g.value=this.values(c),g.values=this.values());
return this._trigger("start",e,g)},_slide:function(e,c,g){var f;if(this.options.values&&this.options.values.length){f=this.values(c?0:1);if(2===this.options.values.length&&!0===this.options.range&&(0===c&&g>f||1===c&&g<f))g=f;g!==this.values(c)&&(f=this.values(),f[c]=g,e=this._trigger("slide",e,{handle:this.handles[c],value:g,values:f}),this.values(c?0:1),!1!==e&&this.values(c,g,!0))}else g!==this.value()&&(e=this._trigger("slide",e,{handle:this.handles[c],value:g}),!1!==e&&this.value(g))},_stop:function(e,
c){var g={handle:this.handles[c],value:this.value()};this.options.values&&this.options.values.length&&(g.value=this.values(c),g.values=this.values());this._trigger("stop",e,g)},_change:function(e,c){if(!this._keySliding&&!this._mouseSliding){var g={handle:this.handles[c],value:this.value()};this.options.values&&this.options.values.length&&(g.value=this.values(c),g.values=this.values());this._trigger("change",e,g)}},value:function(e){if(arguments.length)this.options.value=this._trimAlignValue(e),this._refreshValue(),
this._change(null,0);else return this._value()},values:function(k,c){var g,f,h;if(1<arguments.length)this.options.values[k]=this._trimAlignValue(c),this._refreshValue(),this._change(null,k);else if(arguments.length)if(e.isArray(arguments[0])){g=this.options.values;f=arguments[0];for(h=0;h<g.length;h+=1)g[h]=this._trimAlignValue(f[h]),this._change(null,h);this._refreshValue()}else return this.options.values&&this.options.values.length?this._values(k):this.value();else return this._values()},_setOption:function(k,
c){var g,f=0;e.isArray(this.options.values)&&(f=this.options.values.length);e.Widget.prototype._setOption.apply(this,arguments);switch(k){case "disabled":c?(this.handles.filter(".ui-state-focus").blur(),this.handles.removeClass("ui-state-hover"),this.handles.propAttr("disabled",!0),this.element.addClass("ui-disabled")):(this.handles.propAttr("disabled",!1),this.element.removeClass("ui-disabled"));break;case "orientation":this._detectOrientation();this.element.removeClass("ui-slider-horizontal ui-slider-vertical").addClass("ui-slider-"+
this.orientation);this._refreshValue();break;case "value":this._animateOff=!0;this._refreshValue();this._change(null,0);this._animateOff=!1;break;case "values":this._animateOff=!0;this._refreshValue();for(g=0;g<f;g+=1)this._change(null,g);this._animateOff=!1}},_value:function(){var e=this.options.value;return e=this._trimAlignValue(e)},_values:function(e){var c,g;if(arguments.length)return c=this.options.values[e],c=this._trimAlignValue(c);c=this.options.values.slice();for(g=0;g<c.length;g+=1)c[g]=
this._trimAlignValue(c[g]);return c},_trimAlignValue:function(e){if(e<=this._valueMin())return this._valueMin();if(e>=this._valueMax())return this._valueMax();var c=0<this.options.step?this.options.step:1,g=(e-this._valueMin())%c;e-=g;2*Math.abs(g)>=c&&(e+=0<g?c:-c);return parseFloat(e.toFixed(5))},_valueMin:function(){return this.options.min},_valueMax:function(){return this.options.max},_refreshValue:function(){var k=this.options.range,c=this.options,g=this,f=!this._animateOff?c.animate:!1,h,q=
{},l,n,s,p;if(this.options.values&&this.options.values.length)this.handles.each(function(m,p){h=100*((g.values(m)-g._valueMin())/(g._valueMax()-g._valueMin()));q["horizontal"===g.orientation?"left":"bottom"]=h+"%";e(this).stop(1,1)[f?"animate":"css"](q,c.animate);if(!0===g.options.range)if("horizontal"===g.orientation){if(0===m)g.range.stop(1,1)[f?"animate":"css"]({left:h+"%"},c.animate);if(1===m)g.range[f?"animate":"css"]({width:h-l+"%"},{queue:!1,duration:c.animate})}else{if(0===m)g.range.stop(1,
1)[f?"animate":"css"]({bottom:h+"%"},c.animate);if(1===m)g.range[f?"animate":"css"]({height:h-l+"%"},{queue:!1,duration:c.animate})}l=h});else{n=this.value();s=this._valueMin();p=this._valueMax();h=p!==s?100*((n-s)/(p-s)):0;q["horizontal"===g.orientation?"left":"bottom"]=h+"%";this.handle.stop(1,1)[f?"animate":"css"](q,c.animate);if("min"===k&&"horizontal"===this.orientation)this.range.stop(1,1)[f?"animate":"css"]({width:h+"%"},c.animate);if("max"===k&&"horizontal"===this.orientation)this.range[f?
"animate":"css"]({width:100-h+"%"},{queue:!1,duration:c.animate});if("min"===k&&"vertical"===this.orientation)this.range.stop(1,1)[f?"animate":"css"]({height:h+"%"},c.animate);if("max"===k&&"vertical"===this.orientation)this.range[f?"animate":"css"]({height:100-h+"%"},{queue:!1,duration:c.animate})}}});e.extend(e.ui.slider,{version:"1.8.20"})})(jQuery);jQuery.effects||function(e,n){function k(c){var m;return c&&c.constructor==Array&&3==c.length?c:(m=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(c))?[parseInt(m[1],10),parseInt(m[2],10),parseInt(m[3],10)]:(m=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(c))?[2.55*parseFloat(m[1]),2.55*parseFloat(m[2]),2.55*parseFloat(m[3])]:(m=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(c))?[parseInt(m[1],16),parseInt(m[2],
16),parseInt(m[3],16)]:(m=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(c))?[parseInt(m[1]+m[1],16),parseInt(m[2]+m[2],16),parseInt(m[3]+m[3],16)]:/rgba\(0, 0, 0, 0\)/.exec(c)?l.transparent:l[e.trim(c).toLowerCase()]}function c(){var c=document.defaultView?document.defaultView.getComputedStyle(this,null):this.currentStyle,e={},f,g;if(c&&c.length&&c[0]&&c[c[0]])for(var h=c.length;h--;)f=c[h],"string"==typeof c[f]&&(g=f.replace(/\-(\w)/g,function(c,e){return e.toUpperCase()}),e[g]=c[f]);else for(f in c)"string"===
typeof c[f]&&(e[f]=c[f]);return e}function g(c){var m,f;for(m in c)f=c[m],(null==f||e.isFunction(f)||m in s||/scrollbar/.test(m)||!/color/i.test(m)&&isNaN(parseFloat(f)))&&delete c[m];return c}function f(c,e){var f={_:0},g;for(g in e)c[g]!=e[g]&&(f[g]=e[g]);return f}function h(c,m,f,g){"object"==typeof c&&(g=m,f=null,m=c,c=m.effect);e.isFunction(m)&&(g=m,f=null,m={});if("number"==typeof m||e.fx.speeds[m])g=f,f=m,m={};e.isFunction(f)&&(g=f,f=null);m=m||{};f=f||m.duration;f=e.fx.off?0:"number"==typeof f?
f:f in e.fx.speeds?e.fx.speeds[f]:e.fx.speeds._default;g=g||m.complete;return[c,m,f,g]}function q(c){return!c||("number"===typeof c||e.fx.speeds[c])||"string"===typeof c&&!e.effects[c]?!0:!1}e.effects={};e.each("backgroundColor borderBottomColor borderLeftColor borderRightColor borderTopColor borderColor color outlineColor".split(" "),function(c,m){e.fx.step[m]=function(c){if(!c.colorInit){var f;f=c.elem;var p=m,g;do{g=e.curCSS(f,p);if(""!=g&&"transparent"!=g||e.nodeName(f,"body"))break;p="backgroundColor"}while(f=
f.parentNode);f=k(g);c.start=f;c.end=k(c.end);c.colorInit=!0}c.elem.style[m]="rgb("+Math.max(Math.min(parseInt(c.pos*(c.end[0]-c.start[0])+c.start[0],10),255),0)+","+Math.max(Math.min(parseInt(c.pos*(c.end[1]-c.start[1])+c.start[1],10),255),0)+","+Math.max(Math.min(parseInt(c.pos*(c.end[2]-c.start[2])+c.start[2],10),255),0)+")"}});var l={aqua:[0,255,255],azure:[240,255,255],beige:[245,245,220],black:[0,0,0],blue:[0,0,255],brown:[165,42,42],cyan:[0,255,255],darkblue:[0,0,139],darkcyan:[0,139,139],
darkgrey:[169,169,169],darkgreen:[0,100,0],darkkhaki:[189,183,107],darkmagenta:[139,0,139],darkolivegreen:[85,107,47],darkorange:[255,140,0],darkorchid:[153,50,204],darkred:[139,0,0],darksalmon:[233,150,122],darkviolet:[148,0,211],fuchsia:[255,0,255],gold:[255,215,0],green:[0,128,0],indigo:[75,0,130],khaki:[240,230,140],lightblue:[173,216,230],lightcyan:[224,255,255],lightgreen:[144,238,144],lightgrey:[211,211,211],lightpink:[255,182,193],lightyellow:[255,255,224],lime:[0,255,0],magenta:[255,0,255],
maroon:[128,0,0],navy:[0,0,128],olive:[128,128,0],orange:[255,165,0],pink:[255,192,203],purple:[128,0,128],violet:[128,0,128],red:[255,0,0],silver:[192,192,192],white:[255,255,255],yellow:[255,255,0],transparent:[255,255,255]},r=["add","remove","toggle"],s={border:1,borderBottom:1,borderColor:1,borderLeft:1,borderRight:1,borderTop:1,borderWidth:1,margin:1,padding:1};e.effects.animateClass=function(p,m,h,u){e.isFunction(h)&&(u=h,h=null);return this.queue(function(){var k=e(this),l=k.attr("style")||
" ",s=g(c.call(this)),q,n=k.attr("class")||"";e.each(r,function(c,e){if(p[e])k[e+"Class"](p[e])});q=g(c.call(this));k.attr("class",n);k.animate(f(s,q),{queue:!1,duration:m,easing:h,complete:function(){e.each(r,function(c,e){if(p[e])k[e+"Class"](p[e])});"object"==typeof k.attr("style")?(k.attr("style").cssText="",k.attr("style").cssText=l):k.attr("style",l);u&&u.apply(this,arguments);e.dequeue(this)}})})};e.fn.extend({_addClass:e.fn.addClass,addClass:function(c,m,f,g){return m?e.effects.animateClass.apply(this,
[{add:c},m,f,g]):this._addClass(c)},_removeClass:e.fn.removeClass,removeClass:function(c,m,f,g){return m?e.effects.animateClass.apply(this,[{remove:c},m,f,g]):this._removeClass(c)},_toggleClass:e.fn.toggleClass,toggleClass:function(c,m,f,g,h){return"boolean"==typeof m||m===n?f?e.effects.animateClass.apply(this,[m?{add:c}:{remove:c},f,g,h]):this._toggleClass(c,m):e.effects.animateClass.apply(this,[{toggle:c},m,f,g])},switchClass:function(c,m,f,g,h){return e.effects.animateClass.apply(this,[{add:m,
remove:c},f,g,h])}});e.extend(e.effects,{version:"1.8.20",save:function(c,e){for(var f=0;f<e.length;f++)null!==e[f]&&c.data("ec.storage."+e[f],c[0].style[e[f]])},restore:function(c,e){for(var f=0;f<e.length;f++)null!==e[f]&&c.css(e[f],c.data("ec.storage."+e[f]))},setMode:function(c,e){"toggle"==e&&(e=c.is(":hidden")?"show":"hide");return e},getBaseline:function(c,e){var f,g;switch(c[0]){case "top":f=0;break;case "middle":f=0.5;break;case "bottom":f=1;break;default:f=c[0]/e.height}switch(c[1]){case "left":g=
0;break;case "center":g=0.5;break;case "right":g=1;break;default:g=c[1]/e.width}return{x:g,y:f}},createWrapper:function(c){if(c.parent().is(".ui-effects-wrapper"))return c.parent();var m={width:c.outerWidth(!0),height:c.outerHeight(!0),"float":c.css("float")},f=e("<div></div>").addClass("ui-effects-wrapper").css({fontSize:"100%",background:"transparent",border:"none",margin:0,padding:0}),g=document.activeElement;c.wrap(f);(c[0]===g||e.contains(c[0],g))&&e(g).focus();f=c.parent();"static"==c.css("position")?
(f.css({position:"relative"}),c.css({position:"relative"})):(e.extend(m,{position:c.css("position"),zIndex:c.css("z-index")}),e.each(["top","left","bottom","right"],function(e,f){m[f]=c.css(f);isNaN(parseInt(m[f],10))&&(m[f]="auto")}),c.css({position:"relative",top:0,left:0,right:"auto",bottom:"auto"}));return f.css(m).show()},removeWrapper:function(c){var m,f=document.activeElement;return c.parent().is(".ui-effects-wrapper")?(m=c.parent().replaceWith(c),(c[0]===f||e.contains(c[0],f))&&e(f).focus(),
m):c},setTransition:function(c,m,f,g){g=g||{};e.each(m,function(e,m){var h=c.cssUnit(m);0<h[0]&&(g[m]=h[0]*f+h[1])});return g}});e.fn.extend({effect:function(c,m,f,g){var k=h.apply(this,arguments),l={options:k[1],duration:k[2],callback:k[3]},k=l.options.mode,s=e.effects[c];return e.fx.off||!s?k?this[k](l.duration,l.callback):this.each(function(){l.callback&&l.callback.call(this)}):s.call(this,l)},_show:e.fn.show,show:function(c){if(q(c))return this._show.apply(this,arguments);var e=h.apply(this,arguments);
e[1].mode="show";return this.effect.apply(this,e)},_hide:e.fn.hide,hide:function(c){if(q(c))return this._hide.apply(this,arguments);var e=h.apply(this,arguments);e[1].mode="hide";return this.effect.apply(this,e)},__toggle:e.fn.toggle,toggle:function(c){if(q(c)||"boolean"===typeof c||e.isFunction(c))return this.__toggle.apply(this,arguments);var f=h.apply(this,arguments);f[1].mode="toggle";return this.effect.apply(this,f)},cssUnit:function(c){var f=this.css(c),g=[];e.each(["em","px","%","pt"],function(c,
e){0<f.indexOf(e)&&(g=[parseFloat(f),e])});return g}});e.easing.jswing=e.easing.swing;e.extend(e.easing,{def:"easeOutQuad",swing:function(c,f,g,h,k){return e.easing[e.easing.def](c,f,g,h,k)},easeInQuad:function(c,e,f,g,h){return g*(e/=h)*e+f},easeOutQuad:function(c,e,f,g,h){return-g*(e/=h)*(e-2)+f},easeInOutQuad:function(c,e,f,g,h){return 1>(e/=h/2)?g/2*e*e+f:-g/2*(--e*(e-2)-1)+f},easeInCubic:function(c,e,f,g,h){return g*(e/=h)*e*e+f},easeOutCubic:function(c,e,f,g,h){return g*((e=e/h-1)*e*e+1)+f},
easeInOutCubic:function(c,e,f,g,h){return 1>(e/=h/2)?g/2*e*e*e+f:g/2*((e-=2)*e*e+2)+f},easeInQuart:function(c,e,f,g,h){return g*(e/=h)*e*e*e+f},easeOutQuart:function(c,e,f,g,h){return-g*((e=e/h-1)*e*e*e-1)+f},easeInOutQuart:function(c,e,f,g,h){return 1>(e/=h/2)?g/2*e*e*e*e+f:-g/2*((e-=2)*e*e*e-2)+f},easeInQuint:function(c,e,f,g,h){return g*(e/=h)*e*e*e*e+f},easeOutQuint:function(c,e,f,g,h){return g*((e=e/h-1)*e*e*e*e+1)+f},easeInOutQuint:function(c,e,f,g,h){return 1>(e/=h/2)?g/2*e*e*e*e*e+f:g/2*((e-=
2)*e*e*e*e+2)+f},easeInSine:function(c,e,f,g,h){return-g*Math.cos(e/h*(Math.PI/2))+g+f},easeOutSine:function(e,c,f,g,h){return g*Math.sin(c/h*(Math.PI/2))+f},easeInOutSine:function(c,e,f,g,h){return-g/2*(Math.cos(Math.PI*e/h)-1)+f},easeInExpo:function(e,c,f,g,h){return 0==c?f:g*Math.pow(2,10*(c/h-1))+f},easeOutExpo:function(c,e,f,g,h){return e==h?f+g:g*(-Math.pow(2,-10*e/h)+1)+f},easeInOutExpo:function(e,c,f,g,h){return 0==c?f:c==h?f+g:1>(c/=h/2)?g/2*Math.pow(2,10*(c-1))+f:g/2*(-Math.pow(2,-10*--c)+
2)+f},easeInCirc:function(c,e,f,g,h){return-g*(Math.sqrt(1-(e/=h)*e)-1)+f},easeOutCirc:function(c,e,f,g,h){return g*Math.sqrt(1-(e=e/h-1)*e)+f},easeInOutCirc:function(e,c,f,g,h){return 1>(c/=h/2)?-g/2*(Math.sqrt(1-c*c)-1)+f:g/2*(Math.sqrt(1-(c-=2)*c)+1)+f},easeInElastic:function(c,e,f,g,h){c=1.70158;var k=0,l=g;if(0==e)return f;if(1==(e/=h))return f+g;k||(k=0.3*h);l<Math.abs(g)?(l=g,c=k/4):c=k/(2*Math.PI)*Math.asin(g/l);return-(l*Math.pow(2,10*(e-=1))*Math.sin((e*h-c)*2*Math.PI/k))+f},easeOutElastic:function(c,
e,f,g,h){c=1.70158;var k=0,l=g;if(0==e)return f;if(1==(e/=h))return f+g;k||(k=0.3*h);l<Math.abs(g)?(l=g,c=k/4):c=k/(2*Math.PI)*Math.asin(g/l);return l*Math.pow(2,-10*e)*Math.sin((e*h-c)*2*Math.PI/k)+g+f},easeInOutElastic:function(c,e,f,g,h){c=1.70158;var k=0,l=g;if(0==e)return f;if(2==(e/=h/2))return f+g;k||(k=h*0.3*1.5);l<Math.abs(g)?(l=g,c=k/4):c=k/(2*Math.PI)*Math.asin(g/l);return 1>e?-0.5*l*Math.pow(2,10*(e-=1))*Math.sin((e*h-c)*2*Math.PI/k)+f:0.5*l*Math.pow(2,-10*(e-=1))*Math.sin((e*h-c)*2*Math.PI/
k)+g+f},easeInBack:function(e,c,f,g,h,k){k==n&&(k=1.70158);return g*(c/=h)*c*((k+1)*c-k)+f},easeOutBack:function(c,e,f,g,h,k){k==n&&(k=1.70158);return g*((e=e/h-1)*e*((k+1)*e+k)+1)+f},easeInOutBack:function(e,c,f,g,h,k){k==n&&(k=1.70158);return 1>(c/=h/2)?g/2*c*c*(((k*=1.525)+1)*c-k)+f:g/2*((c-=2)*c*(((k*=1.525)+1)*c+k)+2)+f},easeInBounce:function(c,f,g,h,k){return h-e.easing.easeOutBounce(c,k-f,0,h,k)+g},easeOutBounce:function(c,e,f,g,h){return(e/=h)<1/2.75?g*7.5625*e*e+f:e<2/2.75?g*(7.5625*(e-=
1.5/2.75)*e+0.75)+f:e<2.5/2.75?g*(7.5625*(e-=2.25/2.75)*e+0.9375)+f:g*(7.5625*(e-=2.625/2.75)*e+0.984375)+f},easeInOutBounce:function(c,f,g,h,k){return f<k/2?0.5*e.easing.easeInBounce(c,2*f,0,h,k)+g:0.5*e.easing.easeOutBounce(c,2*f-k,0,h,k)+0.5*h+g}})}(jQuery);(function(e){e.fn.lightbox_me=function(n){return this.each(function(){function k(c){var f=e(window).height()-80;500>f&&(f=500);c.css("height",f)}function c(c){s[l.disappearEffect](l.lightboxDisappearSpeed,function(){c&&g();l.destroyOnClose?s.remove():s.hide();l.reallyBig&&e(".bPopupWrap").remove();s.find(l.closeSelector).unbind("click");s.unbind(".lme");e(window).unbind("scroll",q);e(window).unbind("resize",q);e("body").removeClass("showModal")})}function g(){r.fadeOut(l.overlayDisappearSpeed,function(){e(window).unbind("resize",
f);r.remove();r.unbind("click");l.onClose()})}function f(){e(window).height()<e(document).height()?r.css({height:e(document).height()+"px"}):(r.css({height:"100%"}),m&&e("html,body").css("height","100%"))}function h(c){var e=c[0].style,f=window.pageYOffset;f||(f=document.documentElement.scrollTop);c.css({position:"absolute",top:1*(f+40)+"px",marginTop:0});m&&e.removeExpression("top")}function q(){var c=s[0].style;if(s.height()+80>=e(window).height()&&("absolute"!=s.css("position")||m)){var f=e(document).scrollTop()+
40;s.css({position:"absolute",top:f+"px",marginTop:0});m&&c.removeExpression("top")}else s.height()+80<e(window).height()&&(m?(c.position="absolute",l.centered?(c.setExpression("top",'(document.documentElement.clientHeight || document.body.clientHeight) / 2 - (this.offsetHeight / 2) + (blah = document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop) + "px"'),c.marginTop=0):(f=l.modalCSS&&l.modalCSS.top?parseInt(l.modalCSS.top):0,c.setExpression("top","((blah = document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop) + "+
f+') + "px"'))):l.centered?s.css({position:"fixed",top:"50%",marginTop:-1*(s.outerHeight()/2)}):s.css({position:"fixed"}).css(l.modalCSS))}var l=e.extend({},e.fn.lightbox_me.defaults,n),r=e("div."+l.classPrefix+"_overlay"),s=e(this),p=e("iframe#lb_iframe"),m=e.browser.msie&&7>e.browser.version;0<r.length?r[0].removeModal():r=e('<div class="'+l.classPrefix+'_overlay" style="display:none;"/>');p=0<p.length?p:p=e('<iframe id="lb_iframe" style="z-index: '+(l.zIndex+1)+'; display: none; border: none; margin: 0; padding: 0; position: absolute; width: 100%; height: 100%; top: 0; left: 0;"/>');
if(m){var v=/^https/i.test(window.location.href||"")?"javascript:false":"about:blank";p.attr("src",v);e("body").append(p)}l.reallyBig?e("body").append(e("<div>").addClass("bPopupWrap").append(s)).append(r):e("body").append(s).append(r);l.reallyBig?(s.css({marginLeft:"50px",marginRight:"50px"}),h(s.parent()),k(s)):(s.css({position:"fixed"}),q(),s.css({left:"50%",marginLeft:-1*(s.outerWidth()/2),zIndex:l.zIndex+3}));f();r.css({position:"fixed",width:"100%",height:"100%",top:0,left:0,zIndex:l.zIndex+
2}).css(l.overlayCSS);if(l.autofocus){var u=l.onLoad;l.onLoad=function(){u();s.find("input:text").first().focus()}}if(r.is(":hidden"))r.fadeIn(l.overlaySpeed,function(){s[l.appearEffect](l.lightboxSpeed,function(){f();l.onLoad()})});else s[l.appearEffect](l.lightboxSpeed,function(){f();l.onLoad()});e(window).resize(f).resize(function(){l.reallyBig?h(s.parent()):q()}).resize(function(){l.reallyBig&&k(s)}).scroll(function(){l.reallyBig||q()}).keydown(function(e){(27==e.keyCode||27==e.DOM_VK_ESCAPE&&
0==e.which)&&l.closeEsc&&c(!0)});e("body").addClass("showModal");s.find(l.closeSelector).click(function(){c(!0);return!1});r.click(function(c){c.preventDefault();return!1});setTimeout(function(){r.click(function(){if(l.closeClick)return c(!0),!1})},500);s.bind("close.lme",function(){c(!0)});s.bind("resize.lme",function(){l.reallyBig?h(s.parent()):q()});r[0].removeModal=c})};e.fn.lightbox_me.defaults={appearEffect:"fadeIn",overlaySpeed:300,lightboxSpeed:"fast",disappearEffect:"fadeOut",overlayDisappearSpeed:300,
lightboxDisappearSpeed:"fast",closeSelector:".close",closeClick:!0,closeEsc:!0,destroyOnClose:!1,onLoad:function(){},onClose:function(){},autofocus:!1,classPrefix:"lb",zIndex:999,centered:!1,modalCSS:{top:"40px"},overlayCSS:{background:"black",opacity:0.4}}})(jQuery);(function(e){function n(c){var g=c||window.event,f=[].slice.call(arguments,1),h=0,k=0,l=0;c=e.event.fix(g);c.type="mousewheel";c.wheelDelta&&(h=c.wheelDelta/120);c.detail&&(h=-c.detail/3);l=h;void 0!==g.axis&&g.axis===g.HORIZONTAL_AXIS&&(l=0,k=-1*h);void 0!==g.wheelDeltaY&&(l=g.wheelDeltaY/120);void 0!==g.wheelDeltaX&&(k=-1*g.wheelDeltaX/120);f.unshift(c,h,k,l);return e.event.handle.apply(this,f)}var k=["DOMMouseScroll","mousewheel"];e.event.special.mousewheel={setup:function(){if(this.addEventListener)for(var c=
k.length;c;)this.addEventListener(k[--c],n,!1);else this.onmousewheel=n},teardown:function(){if(this.removeEventListener)for(var c=k.length;c;)this.removeEventListener(k[--c],n,!1);else this.onmousewheel=null}};e.fn.extend({mousewheel:function(c){return c?this.bind("mousewheel",c):this.trigger("mousewheel")},unmousewheel:function(c){return this.unbind("mousewheel",c)}})})(jQuery);/*
			http://opensource.org/licenses/mit-license.php
 @package			jQuery Plugins

 Usage with default values:
 ---------------------------------------------------------------------------------
 $('#star').raty();

 <div id="star"></div>


 $('.star').raty();

 <div class="star"></div>
 <div class="star"></div>
 <div class="star"></div>

*/
(function(e){function n(c,p,m){var l=c.attr("id"),n=e("input#"+l+"-score"),r=c.children("img."+l);c.mouseleave(function(){f(c,n.val(),p);if(null!==m){var e="";p.targetKeep&&(e=n.val(),"hint"==p.targetType&&(e=""==n.val()&&p.cancel?p.cancelHint:p.hintList[Math.ceil(n.val())-1]));g(m)?m.val(e):m.html(e)}});r.bind(p.half?"mousemove":"mouseover",function(f){k(l,this.alt,p);p.half?(f=parseFloat(((f.pageX-e(this).offset().left)/p.size).toFixed(1)),c.data("score",parseFloat(this.alt)+(0<=f&&0.5>f?0.5:1)-
1),q(c,c.data("score"),p)):k(l,this.alt,p);h(m,this.alt,p)}).click(function(e){n.val(p.half?c.data("score"):this.alt);p.click&&p.click.apply(c,[n.val(),e])})}function k(c,f,g){for(var h=e("img."+c).length,k=0,l=0,n,q,r=1;r<=h;r++)n=e("img#"+c+"-"+r),r<=f?g.iconRange&&g.iconRange.length>k?(q=g.iconRange[k][0],l=g.iconRange[k][1],r<=l&&n.attr("src",g.path+q),r==l&&k++):n.attr("src",g.path+g.starOn):n.attr("src",g.path+g.starOff)}function c(c,e,f){var g="";0!=e?(e=parseInt(e),g=0<e&&f.number<=f.hintList.length&&
null!==f.hintList[e-1]?f.hintList[e-1]:e):g=f.noRatedMsg;c.attr("title",g).children("img").attr("title",g)}function g(c){return c.is("input")||c.is("select")||c.is("textarea")}function f(f,g,h){var l=f.attr("id");isNaN(parseInt(g))?(f.children("img."+l).attr("src",h.path+h.starOff),e("input#"+l+"-score").removeAttr("value")):(0>g?g=0:g>h.number&&(g=h.number),k(l,g,h),0<g&&(e("input#"+l+"-score").val(g),(h.half||h.showHalf)&&q(f,g,h)),(h.readOnly||"default"==f.css("cursor"))&&c(f,g,h))}function h(c,
e,f){if(null!==c){var h=e;"hint"==f.targetType&&(h=0==e&&f.cancel?f.cancelHint:f.hintList[e-1]);g(c)?c.val(h):c.html(h)}}function q(c,f,g){c=c.attr("id");var h=Math.ceil(f);f=(h-f).toFixed(1);0.25<f&&0.75>=f?e("img#"+c+"-"+Math.ceil(h-0.5)).attr("src",g.path+g.starHalf):0.75<f||e("img#"+c+"-"+h).attr("src",g.path+g.starOn)}function l(c,f,g){var h=void 0;if(void 0==f)r("Specify an ID or class to be the target of the action.");else{if(f){if(0<=f.indexOf(".")){var k;return e(f).each(function(){k="#"+
e(this).attr("id");"start"==g?e.fn.raty.start(c,k):"click"==g?e.fn.raty.click(c,k):"readOnly"==g&&e.fn.raty.readOnly(c,k)})}h=e(f);if(!h.length){r('"'+f+'" is a invalid identifier for the public funtion $.fn.raty.'+g+"().");return}}return h}}function r(c){window.console&&window.console.log&&window.console.log(c)}e.fn.raty=function(f){if(0==this.length)r("Selector invalid or missing!");else{if(1<this.length)return this.each(function(){e.fn.raty.apply(e(this),[f])});var g=e.extend({},e.fn.raty.defaults,
f),l=e(this),v=this.attr("id"),u=0,z=g.starOn,A="",t=g.target,w=g.width?g.width:g.number*g.size+4*g.number;void 0===v&&(v="raty-"+l.index(),l.attr("id",v));20<g.number?g.number=20:0>g.number&&(g.number=0);"/"!=g.path.substring(g.path.length-1,g.path.length)&&(g.path+="/");l.data("options",g);!isNaN(parseInt(g.start))&&0<g.start&&(u=g.start>g.number?g.number:g.start);for(var x=1;x<=g.number;x++)z=u>=x?g.starOn:g.starOff,A=x<=g.hintList.length&&null!==g.hintList[x-1]?g.hintList[x-1]:x,l.append('<img id="'+
v+"-"+x+'" src="'+g.path+z+'" alt="'+x+'" title="'+A+'" class="'+v+'"/>').append(x<g.number?"&nbsp;":"");g.iconRange&&0<u&&k(v,u,g);z=e("<input/>",{id:v+"-score",type:"hidden",name:g.scoreName}).appendTo(l);0<u&&z.val(u);(g.half||g.showHalf)&&q(l,e("input#"+v+"-score").val(),g);if(g.readOnly)l.css("cursor","default"),c(l,u,g);else{null!==t&&(t=e(t),0==t.length&&r("Target selector invalid or missing!"));if(g.cancel){var C=e("img."+v),u='<img src="'+g.path+g.cancelOff+'" alt="x" title="'+g.cancelHint+
'" class="button-cancel"/>';"left"==g.cancelPlace?l.prepend(u+"&nbsp;"):l.append("&nbsp;").append(u);e("#"+v+" img.button-cancel").mouseenter(function(){e(this).attr("src",g.path+g.cancelOn);C.attr("src",g.path+g.starOff);h(t,"",g)}).mouseleave(function(){e(this).attr("src",g.path+g.cancelOff);l.mouseout()}).click(function(c){e("input#"+v+"-score").removeAttr("value");g.click&&g.click.apply(l,[null,c])});l.css("width",w+g.size+4)}else l.css("width",w);l.css("cursor","pointer");n(l,g,t)}return l}};
e.fn.raty.cancel=function(c,f){return void 0===f?e.fn.raty.start("",c,"cancel"):e.fn.raty.click("",c,"cancel")};e.fn.raty.click=function(c,g){var h=l(c,g,"click"),k=e(g).data("options");if(!(0<=g.indexOf(".")))return f(h,c,k),k.click?k.click.apply(h,[c]):r('You must add the "click: function(score, evt) { }" callback.'),h};e.fn.raty.readOnly=function(c,f){var g=l(c,f,"readOnly"),h=e(f).data("options"),k=g.children("img.button-cancel");if(!(0<=f.indexOf(".")))return k[0]&&(c?k.hide():k.show()),c?(e("img."+
g.attr("id")).unbind(),g.css("cursor","default").unbind()):(n(g,h),g.css("cursor","pointer")),g};e.fn.raty.start=function(c,g){var h=l(c,g,"start"),k=e(g).data("options");if(!(0<=g.indexOf(".")))return f(h,c,k),h};e.fn.raty.defaults={cancel:!1,cancelHint:"cancel this rating!",cancelOff:"cancel-off.png",cancelOn:"cancel-on.png",cancelPlace:"left",click:null,half:!1,hintList:["bad","poor","regular","good","gorgeous"],noRatedMsg:"not rated yet",number:5,path:"img/",iconRange:[],readOnly:!1,scoreName:"score",
size:16,starHalf:"star-half.png",starOff:"star-off.png",starOn:"star-on.png",start:0,target:null,targetKeep:!1,targetType:"hint",width:null}})(jQuery);(function(e){function n(c){return"object"==typeof c?c:{top:c,left:c}}var k=e.scrollTo=function(c,g,f){e(window).scrollTo(c,g,f)};k.defaults={axis:"xy",duration:1.3<=parseFloat(e.fn.jquery)?0:1};k.window=function(c){return e(window)._scrollable()};e.fn._scrollable=function(){return this.map(function(){if(this.nodeName&&-1==e.inArray(this.nodeName.toLowerCase(),["iframe","#document","html","body"]))return this;var c=(this.contentWindow||this).document||this.ownerDocument||this;return e.browser.safari||
"BackCompat"==c.compatMode?c.body:c.documentElement})};e.fn.scrollTo=function(c,g,f){"object"==typeof g&&(f=g,g=0);"function"==typeof f&&(f={onAfter:f});"max"==c&&(c=9E9);f=e.extend({},k.defaults,f);g=g||f.speed||f.duration;f.queue=f.queue&&1<f.axis.length;f.queue&&(g/=2);f.offset=n(f.offset);f.over=n(f.over);return this._scrollable().each(function(){function h(e){l.animate(p,g,f.easing,e&&function(){e.call(this,c,f)})}var q=this,l=e(q),r=c,s,p={},m=l.is("html,body");switch(typeof r){case "number":case "string":if(/^([+-]=)?\d+(\.\d+)?(px|%)?$/.test(r)){r=
n(r);break}r=e(r,this);case "object":if(r.is||r.style)s=(r=e(r)).offset()}e.each(f.axis.split(""),function(c,e){var g="x"==e?"Left":"Top",n=g.toLowerCase(),t="scroll"+g,w=q[t],x=k.max(q,e);s?(p[t]=s[n]+(m?0:w-l.offset()[n]),f.margin&&(p[t]-=parseInt(r.css("margin"+g))||0,p[t]-=parseInt(r.css("border"+g+"Width"))||0),p[t]+=f.offset[n]||0,f.over[n]&&(p[t]+=r["x"==e?"width":"height"]()*f.over[n])):(g=r[n],p[t]=g.slice&&"%"==g.slice(-1)?parseFloat(g)/100*x:g);/^\d+$/.test(p[t])&&(p[t]=0>=p[t]?0:Math.min(p[t],
x));!c&&f.queue&&(w!=p[t]&&h(f.onAfterFirst),delete p[t])});h(f.onAfter)}).end()};k.max=function(c,g){var f="x"==g?"Width":"Height",h="scroll"+f;if(!e(c).is("html,body"))return c[h]-e(c)[f.toLowerCase()]();var f="client"+f,k=c.ownerDocument.documentElement,l=c.ownerDocument.body;return Math.max(k[h],l[h])-Math.min(k[f],l[f])}})(jQuery);(function(e){function n(c){this.input=c;"password"==c.attr("type")&&this.handlePassword();e(c[0].form).submit(function(){c.hasClass("placeholder")&&c[0].value==c.attr("placeholder")&&(c[0].value="")})}n.prototype={show:function(c){if(""===this.input[0].value||c&&this.valueIsPlaceholder()){if(this.isPassword)try{this.input[0].setAttribute("type","text")}catch(e){this.input.before(this.fakePassword.show()).hide()}this.input.addClass("placeholder");this.input[0].value=this.input.attr("placeholder")}},
hide:function(){if(this.valueIsPlaceholder()&&this.input.hasClass("placeholder")&&(this.input.removeClass("placeholder"),this.input[0].value="",this.isPassword)){try{this.input[0].setAttribute("type","password")}catch(c){}this.input.show();this.input[0].focus()}},valueIsPlaceholder:function(){return this.input[0].value==this.input.attr("placeholder")},handlePassword:function(){var c=this.input;c.attr("realType","password");this.isPassword=!0;if(e.browser.msie&&c[0].outerHTML){var g=e(c[0].outerHTML.replace(/type=(['"])?password\1/gi,
"type=$1text$1"));this.fakePassword=g.val(c.attr("placeholder")).addClass("placeholder").focus(function(){c.trigger("focus");e(this).hide()});e(c[0].form).submit(function(){g.remove();c.show()})}}};var k=!!("placeholder"in document.createElement("input"));e.fn.placeholder=function(){return k?this:this.each(function(){var c=e(this),g=new n(c);g.show(!0);c.focus(function(){g.hide()});c.blur(function(){g.show(!1)});e.browser.msie&&(e(window).load(function(){c.val()&&c.removeClass("placeholder");g.show(!0)}),
c.focus(function(){if(""==this.value){var c=this.createTextRange();c.collapse(!0);c.moveStart("character",0);c.select()}}))})}})(jQuery);jQuery.fn.prettyCheckboxes=function(e){e=jQuery.extend({checkboxWidth:13,checkboxHeight:13,className:"prettyCheckbox",display:"list"},e);$(this).each(function(){$label=$('label[for="'+$(this).attr("id")+'"]');$label.prepend("<span class='holderWrap'><span class='holder'></span></span>");$(this).is(":checked")&&$label.addClass("checked");$label.addClass(e.className).addClass($(this).attr("type")).addClass(e.display);$label.find("span.holderWrap").width(e.checkboxWidth).height(e.checkboxHeight);$label.find("span.holder").width(e.checkboxWidth);
$(this).addClass("hiddenCheckbox");$label.bind("click",function(){$("input#"+$(this).attr("for")).triggerHandler("click");$("input#"+$(this).attr("for")).is(":checkbox")?($(this).toggleClass("checked"),$("input#"+$(this).attr("for")).checked=!0,$(this).find("span.holder").css("top",0)):($toCheck=$("input#"+$(this).attr("for")),$('input[name="'+$toCheck.attr("name")+'"]').each(function(){$('label[for="'+$(this).attr("id")+'"]').removeClass("checked")}),$(this).addClass("checked"),$toCheck.checked=
!0)});$("input#"+$label.attr("for")).bind("keypress",function(e){if(32==e.keyCode)return $.browser.msie?$('label[for="'+$(this).attr("id")+'"]').toggleClass("checked"):$(this).trigger("click"),!1})})};
checkAllPrettyCheckboxes=function(e,n){$(e).is(":checked")?$(n).find("input[type=checkbox]:not(:checked)").each(function(){$('label[for="'+$(this).attr("id")+'"]').trigger("click");$.browser.msie?$(this).attr("checked","checked"):$(this).trigger("click")}):$(n).find("input[type=checkbox]:checked").each(function(){$('label[for="'+$(this).attr("id")+'"]').trigger("click");$.browser.msie?$(this).attr("checked",""):$(this).trigger("click")})};$.fn.infiniteCarousel=function(){return this.each(function(){function e(c){var e=c<h?-1:1,k=Math.abs(h-c),e=g*e*f*k;n.filter(":not(:animated)").animate({scrollLeft:"+="+e},500,function(){0==c?(n.scrollLeft(g*f*q),c=q):c>q&&(n.scrollLeft(g*f),c=1);h=c});return!1}var n=$("> div",this).css("overflow","hidden"),k=n.find("> ul"),c=k.find("> li"),g=c.filter(":first").outerWidth(),f=Math.ceil(n.innerWidth()/g),h=1,q=Math.ceil(c.length/f);0!=c.length%f&&(k.append(Array(f-c.length%f+1).join('<li class="empty" />')),
c=k.find("> li"));c.filter(":first").before(c.slice(-f).clone().addClass("cloned"));c.filter(":last").after(c.slice(0,f).clone().addClass("cloned"));c=k.find("> li");n.scrollLeft(g*f);n.after('<a class="arrow back" title="\u041d\u0430\u0437\u0430\u0434">&lt;</a><a class="arrow forward" title="\u0412\u043f\u0435\u0440\u0435\u0434">&gt;</a>');$("a.back",this).click(function(){return e(h-1)});$("a.forward",this).click(function(){return e(h+1)});$(this).bind("goto",function(c,f){e(f)})})};(function(e){e.fn.typewriter=function(n,k){"function"!==typeof k&&(k=function(){});var c=function(g,f,h){var k=e(g).text().length+1;k<=f.length?(e(g).text(f.substr(0,k)),setTimeout(function(){c(g,f,h)},h)):g.callback()};return this.each(function(){this.callback=k;var g=e(this).text(),f=n/g.length;e(this).text("");c(this,g,f)})}})(jQuery);(function(e){function n(c,e){if(!(1<c.originalEvent.touches.length)){c.preventDefault();var g=c.originalEvent.changedTouches[0],k=document.createEvent("MouseEvents");k.initMouseEvent(e,!0,!0,window,1,g.screenX,g.screenY,g.clientX,g.clientY,!1,!1,!1,!1,0,null);c.target.dispatchEvent(k)}}e.support.touch="ontouchend"in document;if(e.support.touch){var k=e.ui.mouse.prototype,c=k._mouseInit,g;k._touchStart=function(c){!g&&this._mouseCapture(c.originalEvent.changedTouches[0])&&(g=!0,this._touchMoved=!1,
n(c,"mouseover"),n(c,"mousemove"),n(c,"mousedown"))};k._touchMove=function(c){g&&(this._touchMoved=!0,n(c,"mousemove"))};k._touchEnd=function(c){g&&(n(c,"mouseup"),n(c,"mouseout"),this._touchMoved||n(c,"click"),g=!1)};k._mouseInit=function(){this.element.bind("touchstart",e.proxy(this,"_touchStart")).bind("touchmove",e.proxy(this,"_touchMove")).bind("touchend",e.proxy(this,"_touchEnd"));c.call(this)}}})(jQuery);(function(e){var n=(e.browser.msie?"paste":"input")+".mask",k=void 0!=window.orientation;e.mask={definitions:{9:"[0-9]",a:"[A-Za-z]","*":"[A-Za-z0-9]"},dataName:"rawMaskFn"};e.fn.extend({caret:function(c,e){if(0!=this.length){if("number"==typeof c)return e="number"==typeof e?e:c,this.each(function(){if(this.setSelectionRange)this.setSelectionRange(c,e);else if(this.createTextRange){var f=this.createTextRange();f.collapse(!0);f.moveEnd("character",e);f.moveStart("character",c);f.select()}});if(this[0].setSelectionRange)c=
this[0].selectionStart,e=this[0].selectionEnd;else if(document.selection&&document.selection.createRange){var f=document.selection.createRange();c=0-f.duplicate().moveStart("character",-1E5);e=c+f.text.length}return{begin:c,end:e}}},unmask:function(){return this.trigger("unmask")},mask:function(c,g){if(!c&&0<this.length)return e(this[0]).data(e.mask.dataName)();g=e.extend({placeholder:"_",completed:null,maxlength:100},g);var f=e.mask.definitions,h=[],q=c.length,l=null,r=c.length;e.each(c.split(""),
function(c,e){"?"==e?(r--,q=c):f[e]?(h.push(RegExp(f[e])),null==l&&(l=h.length-1)):h.push(null)});return this.trigger("unmask").each(function(){function s(c){for(;++c<=r&&!h[c];);return c}function p(c,e){if(!(0>c)){for(var f=c,k=s(e);f<r;f++)if(h[f]){if(k<r&&h[f].test(w[k]))w[f]=w[k],w[k]=g.placeholder;else break;k=s(k)}z();t.caret(Math.max(l,c))}}function m(c){c=c.which;if(8==c||46==c||k&&127==c){var e=t.caret(),f=e.begin,e=e.end;if(0==e-f){if(46!=c)for(;0<=--f&&!h[f];);else f=e=s(f-1);e=46==c?s(e):
e}u(f,e);p(f,e-1);return!1}if(27==c)return t.val(x),t.caret(0,A()),!1}function v(c){var e=c.which,f=t.caret();if(c.ctrlKey||c.altKey||c.metaKey||32>e)return!0;if(e){0!=f.end-f.begin&&(u(f.begin,f.end),p(f.begin,f.end-1));c=s(f.begin-1);if(w.join().replace(/[^0-9]/g,"").length>g.maxlength)return!1;if(c<r&&(e=String.fromCharCode(e),h[c].test(e))){for(var f=c,k=g.placeholder;f<r;f++)if(h[f]){var l=s(f),m=w[f];w[f]=k;if(l<r&&h[l].test(m))k=m;else break}w[c]=e;z();c=s(c);t.caret(c);g.completed&&c>=r&&
g.completed.call(t)}return!1}}function u(c,e){for(var f=c;f<e&&f<r;f++)h[f]&&(w[f]=g.placeholder)}function z(){return t.val(w.join("")).val()}function A(c){for(var e=t.val(),f=-1,k=0,m=0;k<r;k++)if(h[k]){for(w[k]=g.placeholder;m++<e.length;){var n=e.charAt(m-1);if(h[k].test(n)){w[k]=n;f=k;break}}if(m>e.length)break}else w[k]==e.charAt(m)&&k!=q&&(m++,f=k);if(!c&&f+1<q)t.val(""),u(0,r);else if(c||f+1>=q)z(),c||t.val(t.val().substring(0,f+1));return q?k:l}var t=e(this),w=e.map(c.split(""),function(c,
e){if("?"!=c)return f[c]?g.placeholder:c}),x=t.val();t.data(e.mask.dataName,function(){return e.map(w,function(c,e){return h[e]&&c!=g.placeholder?c:null}).join("")});t.attr("readonly")||t.one("unmask",function(){t.unbind(".mask").removeData(e.mask.dataName)}).bind("focus.mask",function(){x=t.val();var f=A();z();var g=function(){f==c.length?t.caret(0,f):t.caret(f)};(e.browser.msie?g:function(){setTimeout(g,0)})()}).bind("blur.mask",function(){A();t.val()!=x&&t.change()}).bind("keydown.mask",m).bind("keypress.mask",
v).bind(n,function(){setTimeout(function(){t.caret(A(!0))},0)});A()})}})})(jQuery);(function(e){jQuery.fn.putCursorAtEnd=function(){return this.each(function(){if(this.setSelectionRange){var n=2*e(this).val().length;this.setSelectionRange(n,n)}else e(this).val(e(this).val());this.scrollTop=999999})}})(jQuery);
