all:
  is_secure: false

index:
  is_secure: true
  layout: layout

new:
  is_secure: true

confirm:
  is_secure: true

updateField:
  is_secure: true

edit:
  is_secure: true

cancel:
  is_secure: true

create:
  is_secure: true

show:
  is_secure: true
