response_code:
  AS000: 'Авторизация успешно завершена'
  AS100: 'Отказ в авторизации'
  AS101: 'Отказ в авторизации. Ошибочный номер карты'
  AS102: 'Отказ в авторизации. Недостаточно средств'
  AS104: 'Отказ в авторизации. Неверный срок действия карты'
  AS105: 'Отказ в авторизации. Превышен лимит'
  AS107: 'Отказ в авторизации. Ошибка приема данных'
  AS108: 'Отказ в авторизации. Подозрение на мошенничество'
  AS109: 'Отказ в авторизации. Превышен лимит операций Uniteller'
  AS200: 'Повторите авторизацию'
  AS998: 'Ошибка системы. Свяжитесь с Uniteller'

stage:
  success:
    name: 'Успешное завершение'
    code: success
    response_code: []
  progress:
    name: 'Обработка'
    code: progress
    response_code:
     - AS000
  fail:
    name: 'Ошибка'
    code: fail
    response_code:
      - AS001
      - AS102
      - AS105
      - AS107
      - AS108
      - AS109
      - AS200
      - AS998