all:
  stylesheets:
    - jquery.autocomplete.css
    - jquery-ui-custom/jquery-ui-custom.css
    - colorbox/colorbox.css

  javascripts:
    - -*
    - jquery
    - jslib/prettyCheckboxes
    - jquery-ui-1.8.16.custom.min.js
    - jquery.form.js
    - jquery.colorbox.js
    - jquery.autocomplete-dev.js
    - app.order.js
    - jslib/custom-form-elements
    - main
  layout: order
