all:
  stylesheets:
    - jquery.autocomplete.css
    - jquery-ui-custom/jquery-ui-custom.css
    - colorbox/colorbox.css

  javascripts:
    - -*
    - jquery-1.6.4.min.js
    - prettyCheckboxes.js
    #- jquery-ui-1.8.16.custom.min.js
    - jquery.form.js
    - jquery.lightbox_me.js
    - typewriter.js
    #- jquery.colorbox.js
    - shelf/jquery.autocomplete-dev.js
    - jquery.scrollto.js
    - app.order.js
    - custom-form-elements.js
    - main.js
    - app.auth.js
  layout: order

index:
  layout: layout

