all:
  welcome:
    cookie_name: enter_code
    secret: Выход!
    enabled: false

  doctrine:
    result_cache:        true   # кешировать результаты запросов
    result_cache_prefix: 'dql:' # префикс ключей в кеше

  media_host:
    url:
      - 'http://fs01.enter.ru'
      - 'http://fs02.enter.ru'
      - 'http://fs03.enter.ru'
      - 'http://fs04.enter.ru'
      - 'http://fs05.enter.ru'
      - 'http://fs06.enter.ru'
      - 'http://fs07.enter.ru'
      - 'http://fs08.enter.ru'
      - 'http://fs09.enter.ru'
      - 'http://fs10.enter.ru'

  banner:
    timeout: 6000
    image_url:
      - 'http://fs01.enter.ru/4/1/230x302/'
      - 'http://fs01.enter.ru/4/1/768x302/'
      - 'http://fs01.enter.ru/4/1/920x320/'
#      - 'http://core.ent3.ru/upload/4/1/230x302/'
#      - 'http://core.ent3.ru/upload/4/1/768x302/'
    adfox: true

  product:
    max_items:              10                      # максимально количество записей для списка товаров (по умолчанию)
    max_items_on_category:  18                      # максимально количество записей для списка товаров в категории
    comment_helpful_cookie: product_comment_helpful
    photo_url:
      - '/1/1/60/'
      - '/1/1/120/'
      - '/1/1/163/'
      - '/1/1/500/'
      - '/1/1/2500/'
    photo_3d_url:
      - '/1/2/500/'
      - '/1/2/2500/'

  product_label:
    photo_url:
      - 'http://fs01.enter.ru/7/1/66x23/'
      - 'http://fs01.enter.ru/7/1/124x38/'

  category:
    photo_url:
      - 'http://fs01.enter.ru/6/1/163/'
    empty_photo_url:
      - ''

  service:
    photo_url:
      - 'http://fs01.enter.ru/11/1/160/'
      - 'http://fs01.enter.ru/11/1/500/'
      - 'http://fs01.enter.ru/11/1/120/'


  shop:
    photo_url:
      - 'http://fs01.enter.ru/8/1/40/'
      - 'http://fs01.enter.ru/8/1/120/'
      - 'http://fs01.enter.ru/8/1/163/'
      - 'http://fs01.enter.ru/8/1/500/'
      - 'http://fs01.enter.ru/8/1/2500/'
      - 'http://fs01.enter.ru/8/1/original/'

  guard:
    remember_cookie_name: remember
    cache_cookie_name: enter_auth
    allow_login_with_email: true
    signout_url: '@user'
    signin_url: '@user'
    #remember_key_expiration_age: 1296000

  admitad:
    cookie_name: 'admitad_uid'

  online_call:
    enabled: false

  related_product:
    additional: true


  core:
    config:
      api_url: 'http://core.ent3.ru/v1/json'
      userapi_url: 'http://core.ent3.ru/index.php/v2/'
      client_code: site
      consumer_key: test
      signature: test
      log_enabled: true
      log_file: %SF_LOG_DIR%/core_client_2.log
      log_response: false # логировать ответ

  cache_eraser:
    config:
      file: %SF_ROOT_DIR%/erase_barcode.cmd
      prefix: 'CACHETAG::'

  cache:
    enabled: true
    config:
      automatic_cleaning_factor: 0
      lifetime: 2592000
      prefix: cache

  payment:
    enabled: true # общий переключатель для всех видов методов online оплат
    default_provider: psbank
    provider:
      psbank:
        enabled: true
        terminal: '79036768'
        merchant: '790367686219999'
        merchant_name: 'Enter'
        key: 'C50E41160302E0F5D6D59F1AA3925C45'
        url: 'http://193.200.10.117:8080/cgi-bin/cgi_link'
      psbank_invoice:
        enabled: true
        contractor_id: 14
        url: 'https://retail-tst.payment.ru/dn/Invoices/ReceiveUniversalInvoices.aspx'
        key:  %SF_DATA_DIR%/keys/privkey.pem
      uniteller:
        enabled: false
        login: 125
        password: 'OYOTEEl5Fp3YXQSSHKEWeuWM4Gh0IObjAm64RWFHeHtdCsgZ0ChccMmWOpIWNlw0qaa3PshWepTW6WH8'
        pay_url: 'https://wpay.uniteller.ru/pay/'
        result_url: 'https://wpay.uniteller.ru/results/'
        shop_id: '35974-134'
        return_url: '@payment_callback'

  smartengine:
    push: true # отправлять данные на сервер smartengine
    pull: true # запрашивать данные с сервера smartengine
    config:
      api_url: 'https://selightstage.smartengine.at/se-light/api/1.0/json/'
      # api_url: 'https://selightstage.smartengine.at/se-light/api/1.0/json/' # для demo
      api_key: 'c41851b19511c20acc84f47b7816fb8e'
      tenantid: 'ENojUTRcD8'
      log_file: %SF_LOG_DIR%/smartengine.log
      log_enabled: true
      log_data_enabled: true

  js_combine:
    file:     %SF_WEB_DIR%/js/combine.js
    compiler: %SF_LIB_DIR%/vendor/google-closure/compiler.jar

  open_auth:
    provider:
      vkontakte:
        title: 'ВКонтакте'
        app_id: 2450355
        core_id: 5
        secret_key: pOhjShAyp3e9HrL1X1QV
        api_url: https://api.vkontakte.ru
        permissions: ''
      facebook:
        title: 'Facebook'
        app_id: 226981847349938
        core_id: 4
        secret_key: e9b8bd45490396ff8ee0da18c777323b
        api_url: https://graph.facebook.com
        permissions: 'user_birthday,user_location,email'
      twitter:
        title: 'Twitter'
        core_id: 6
        consumer_key: WdGeIjFTAci0tHh3t7W7Yg
        consumer_secret: UvQpJLwQo9Yp4ZWZBDBOudWxcJPurflOULLjI
        request_token_url: https://api.twitter.com/oauth/request_token
        authorize_url: https://api.twitter.com/oauth/authorize
        access_token_url: https://api.twitter.com/oauth/access_token
      odnoklassniki:
        title: 'Odnoklassniki.ru'
        app_id: 3982080
        core_id: 7
        public_key: 'CBAEMNDBABABABABA'
        private_key: '10EABF50D830F7FE507D3376'
        access_token_url: 'http://api.odnoklassniki.ru/oauth/token.do'
        app_url: 'http://www.odnoklassniki.ru/games/ent3'
        api_url: 'http://api.odnoklassniki.ru'
        permissions: 'VALUABLE+ACCESS'
      mailru:
        title: 'Mail.ru'
        app_id: 641483
        core_id: 3
        private_key: 'fe2314f2fee03350ee54d5f71cff37d9'
        secret_key: 'a47cc49da1835cf1f010ced1ac7be318'
        api_url: 'http://www.appsmail.ru/platform/api'

  wp:
    url: 'http://content.ent3.ru/'


live:
  open_auth:
    provider:
      vkontakte:
        app_id: 2659726
        secret_key: v4uMoJ3Fhne9R5SmHTiq
      facebook:
        app_id: 226981847349938 #
        secret_key: e9b8bd45490396ff8ee0da18c777323b #
      twitter:
        consumer_key: IyHijpaPPEtzcXNB1a5lTw
        consumer_secret: xAn2bD2Q90GrlU2DMS5upjteR2dgKhEQCFhijGopWw
      odnoklassniki:
        app_id: 5061376
        public_key: 'CBAMDOEBABABABABA'
        private_key: '37B3909065A020F45A9D073C'
        app_url: 'http://www.odnoklassniki.ru/games/enter'
      mailru:
        app_id: 648413
        private_key: '1d32486472b6d1ed5efe36070ac4f23c'
        secret_key: '60ca8f63a5fa1c90d72f0be0f80e4037'

  core:
    config:
      api_url: 'http://api.enter.ru/v1/json'
      userapi_url: 'http://api.enter.ru/v2/'
      client_code: site
      consumer_key: s7urupe7Efrus8un
      signature: mEbradRUBruprUT7ukuvAxupraCrEcuk

  payment:
    provider:
      psbank:
        terminal: '20097201'
        merchant: '000541120097201'
        merchant_name: 'Enter'
        key: 'FD5AAE47574BB8EEFBF8C6C14CBCA453'
        url: 'https://3ds.payment.ru/cgi-bin/cgi_link'
      psbank_invoice:
        enabled: true
        contractor_id: 14
        url: 'https://retail.payment.ru/invoice.aspx'
        key:  %SF_DATA_DIR%/keys/live.privkey.pem

  smartengine:
    api_url: 'https://selightprod.smartengine.at/se-light/api/1.0/json/'
    push: true  # отправлять данные на сервер smartengine
    pull: false # запрашивать данные с сервера smartengine
    cert: %SF_DATA_DIR%/cert/smartengine-server2.crt
    log_enabled: false
    log_data_enabled: false

  rediska:
    default:
      servers:
        main:
          host: 10.20.30.33
          persistent: true

  cache_eraser:
    config:
      file: /opt/WWWRoot/enter.ru/ccontrol/erase_barcode.cmd
      prefix: 'CACHETAG::'

  cache:
    enabled: true

  banner:
    adfox: false

  welcome:
    enabled: true

  wp:
    url: 'http://content.enter.ru/'

live_dev:
  open_auth:
    provider:
      vkontakte:
        app_id: 2659726
        secret_key: v4uMoJ3Fhne9R5SmHTiq
      facebook:
        app_id: 226981847349938 #
        secret_key: e9b8bd45490396ff8ee0da18c777323b #
      twitter:
        consumer_key: IyHijpaPPEtzcXNB1a5lTw
        consumer_secret: xAn2bD2Q90GrlU2DMS5upjteR2dgKhEQCFhijGopWw
      odnoklassniki:
        app_id: 5061376
        public_key: 'CBAMDOEBABABABABA'
        private_key: '37B3909065A020F45A9D073C'
        app_url: 'http://www.odnoklassniki.ru/games/enter'
      mailru:
        app_id: 648413
        private_key: '1d32486472b6d1ed5efe36070ac4f23c'
        secret_key: '60ca8f63a5fa1c90d72f0be0f80e4037'

  core:
    config:
      api_url: 'http://api.enter.ru/v1/json'
      userapi_url: 'http://api.enter.ru/v2/'
      client_code: site
      consumer_key: s7urupe7Efrus8un
      signature: mEbradRUBruprUT7ukuvAxupraCrEcuk

  rediska:
    default:
      servers:
        main:
          host: 10.20.30.33
          persistent: true

  cache_eraser:
    config:
      file: /opt/WWWRoot/enter.ru/ccontrol/erase_barcode.cmd
      prefix: 'CACHETAG::'

  cache:
    enabled: true

  banner:
    adfox: false

  welcome:
    enabled: true

alpha:
  doctrine:
    result_cache:        true  # кешировать результаты запросов
    result_cache_prefix: 'dql:' # префикс ключей в кеше

  core:
    config:
      api_url: 'http://core.ent3.ru/v1/json'
      consumer_key: test
      signature: test

alpha_dev:
  doctrine:
    result_cache:        false  # кешировать результаты запросов
    result_cache_prefix: 'dql:' # префикс ключей в кеше

  core:
    config:
      api_url: 'http://core.ent3.ru/v1/json'
      consumer_key: test
      signature: test
