all:
  rediska:
    default:
      servers:
        main:
          host: 127.0.0.1
          persistent: true

  doctrine:
    result_cache:         true  # кешировать результаты запросов
    result_cache_prefix: 'dql:' # префикс ключей в кеше

  product:
    max_items:              10                      # максимально количество записей для списка товаров (по умолчанию)
    max_items_on_category:  10                      # максимально количество записей для списка товаров в категории
    comment_helpful_cookie: product_comment_helpful

  guard:
    remember_cookie_name: remember
    allow_login_with_email: true
    signout_url: '@user'
    signin_url: '@user'
    #remember_key_expiration_age: 1296000

  open_auth:
    callback_url: openAuth_callback
    provider:
      vkontakte:
        title: 'ВКонтакте'
        app_id: 2450355
        secret_key: pOhjShAyp3e9HrL1X1QV
        api_url: https://api.vkontakte.ru
      facebook:
        title: 'Facebook'
        app_id: 226981847349938
        secret_key: e9b8bd45490396ff8ee0da18c777323b
        api_url: https://graph.facebook.com