all:
  rediska:
    default:
      servers:
        main:
          host: 127.0.0.1
          persistent: true

  sf_guard_plugin:
    routes_register: false

  doctrine:
    result_cache:         true  # кешировать результаты запросов
    result_cache_prefix: 'dql:' # префикс ключей в кеше

  product:
    max_items:              10                      # максимально количество записей для списка товаров (по умолчанию)
    max_items_on_category:  10                      # максимально количество записей для списка товаров в категории
    comment_helpful_cookie: product_comment_helpful

  guard:
    remember_cookie_name: remember
    allow_login_with_email: true
    signout_url: '@user'
    signin_url: '@user'
    #remember_key_expiration_age: 1296000