all:
  rediska:
    default:
      servers:
        main:
          host: 127.0.0.1
          persistent: true

  doctrine:
    result_cache:         true  # кешировать результаты запросов
    result_cache_prefix: 'dql:' # префикс ключей в кеше

  product:
    max_items:              10                      # максимально количество записей для списка товаров (по умолчанию)
    max_items_on_category:  10                      # максимально количество записей для списка товаров в категории
    comment_helpful_cookie: product_comment_helpful

  guard:
    remember_cookie_name: remember
    allow_login_with_email: true
    signout_url: '@user'
    signin_url: '@user'
    #remember_key_expiration_age: 1296000

  open_auth:
    callback_url: openAuth_callback
    provider:
      vkontakte:
        title: 'ВКонтакте'
        app_id: 2450355
        secret_key: pOhjShAyp3e9HrL1X1QV
        api_url: https://api.vkontakte.ru
      facebook:
        title: 'Facebook'
        app_id: 226981847349938
        secret_key: e9b8bd45490396ff8ee0da18c777323b
        api_url: https://graph.facebook.com
      twitter:
        title: 'Twitter'
        consumer_key: WdGeIjFTAci0tHh3t7W7Yg
        consumer_secret: UvQpJLwQo9Yp4ZWZBDBOudWxcJPurflOULLjI
        request_token_url: https://api.twitter.com/oauth/request_token
        authorize_url: https://api.twitter.com/oauth/authorize
        access_token_url: https://api.twitter.com/oauth/access_token
        callback_url: '@openAuth_signin?provider=twitter'
      odnoklassniki:
        title: 'Odnoklassniki.ru'
        app_id: 3982080
        public_key: 'CBAEMNDBABABABABA'
        private_key: '10EABF50D830F7FE507D3376'
        access_token_url: 'http://api.odnoklassniki.ru/oauth/token.do'
        app_url: 'http://www.odnoklassniki.ru/games/ent3'
        api_url: 'http://api.odnoklassniki.ru'
        return_url: '@openAuth_signin?provider=odnoklassniki'
      mailru:
        title: 'Mail.ru'
        app_id: 641483
        private_key: 'fe2314f2fee03350ee54d5f71cff37d9'
        secret_key: 'a47cc49da1835cf1f010ced1ac7be318'
        redirect_uri: '@openAuth_signin?provider=mailru'
        api_url: 'http://www.appsmail.ru/platform/api'
