all:
  welcome:
    cookie_name: enter_code
    secret: Выход!
    enabled: false

  rediska:
    default:
      servers:
        main:
          host: 127.0.0.1
          persistent: true

  doctrine:
    result_cache:        true   # кешировать результаты запросов
    result_cache_prefix: 'dql:' # префикс ключей в кеше

  product:
    max_items:              10                      # максимально количество записей для списка товаров (по умолчанию)
    max_items_on_category:  18                      # максимально количество записей для списка товаров в категории
    comment_helpful_cookie: product_comment_helpful
    photo_url:
      - 'http://fs01.enter.ru/1/1/40/'
      - 'http://fs01.enter.ru/1/1/120/'
      - 'http://fs01.enter.ru/1/1/163/'
      - 'http://fs01.enter.ru/1/1/500/'
      - 'http://fs01.enter.ru/1/1/2500/'
    photo_3d_url:
      - 'http://fs01.enter.ru/1/2/500/'
      - 'http://fs01.enter.ru/1/2/2500/'

  category:
    photo_url:
      - 'http://fs01.enter.ru/6/1/163/'
    empty_photo_url:
      - ''

  service:
    photo_url:
      - 'http://fs01.enter.ru/11/1/160/'
      - 'http://fs01.enter.ru/11/1/500/'
      - 'http://fs01.enter.ru/11/1/120/'
      
      
  shop:
    photo_url:
      - 'http://fs01.enter.ru/8/1/40/'
      - 'http://fs01.enter.ru/8/1/120/'
      - 'http://fs01.enter.ru/8/1/163/'
      - 'http://fs01.enter.ru/8/1/500/'
      - 'http://fs01.enter.ru/8/1/2500/'
      - 'http://fs01.enter.ru/8/1/original/'

  guard:
    remember_cookie_name: remember
    cache_cookie_name: enter_auth
    allow_login_with_email: true
    signout_url: '@user'
    signin_url: '@user'
    #remember_key_expiration_age: 1296000

  core:
    config:
      api_url: 'http://core.ent3.ru/v1/json'
      consumer_key: test
      signature: test

  cache_eraser:
    config:
      file: %SF_ROOT_DIR%/erase_barcode.cmd
      prefix: 'CACHETAG::'

  payment:
   default_provider: uniteller
   provider:
     uniteller:
       login: 125
       password: 'DErlW8GnwZTCDYLD9kj7zKHxpEXpHrSNCRWQXuOOonMYQEdKoKXk8OkDgx7CcRBAoCrM1LAwESnHugUW'
       pay_url: 'https://wpay.uniteller.ru/pay/'
       result_url: 'https://wpay.uniteller.ru/results/'
       shop_id: '35974-134'
       return_url: '@payment_callback'
  # TODO: перенести в модель, чтобы не захламлять память
  open_auth:
    provider:
      vkontakte:
        title: 'ВКонтакте'
        app_id: 2450355
        core_id: 5
        secret_key: pOhjShAyp3e9HrL1X1QV
        api_url: https://api.vkontakte.ru
        permissions: ''
      facebook:
        title: 'Facebook'
        app_id: 226981847349938
        core_id: 4
        secret_key: e9b8bd45490396ff8ee0da18c777323b
        api_url: https://graph.facebook.com
        permissions: 'user_birthday,user_location,email'
      twitter:
        title: 'Twitter'
        core_id: 6
        consumer_key: WdGeIjFTAci0tHh3t7W7Yg
        consumer_secret: UvQpJLwQo9Yp4ZWZBDBOudWxcJPurflOULLjI
        request_token_url: https://api.twitter.com/oauth/request_token
        authorize_url: https://api.twitter.com/oauth/authorize
        access_token_url: https://api.twitter.com/oauth/access_token
      odnoklassniki:
        title: 'Odnoklassniki.ru'
        app_id: 3982080
        core_id: 7
        public_key: 'CBAEMNDBABABABABA'
        private_key: '10EABF50D830F7FE507D3376'
        access_token_url: 'http://api.odnoklassniki.ru/oauth/token.do'
        app_url: 'http://www.odnoklassniki.ru/games/ent3'
        api_url: 'http://api.odnoklassniki.ru'
        permissions: 'VALUABLE+ACCESS'
      mailru:
        title: 'Mail.ru'
        app_id: 641483
        core_id: 3
        private_key: 'fe2314f2fee03350ee54d5f71cff37d9'
        secret_key: 'a47cc49da1835cf1f010ced1ac7be318'
        api_url: 'http://www.appsmail.ru/platform/api'

  sfCombinePlugin:
    enabled:        false          # enabling the plugin will combine script and css files into a single file
    asset_version:  0             # key to the asset version
    client_cache_max_age: 10      # enable the browser to keep a copy of the files for x days (false to disable)
    gzip:           true          # allow PHP gzipping of the combined JavaScript and CSS files to reduce bandwidth usage
    url_type:       key           # can be key, files, or base64 (note files can be buggy without an asset version)
    filter_include_unused_groups: true # whether to use the filter to include groups that havent been output
    timestamp:
      enabled: true               # suffix a timestamp where available to files for their asset version
      uncombinable: true          # timestamp files that aren't combinable
    js:
      combine: true               # whether or not to perform combining actions
      combine_skip: ~             # these files will not be combined (necessary when js code is based on js file name)
      include: true               # whether to allow the including of files
      include_suffixes:           # suffixes of files that can be included
        - .php
      include_skip: ~             # files that should be skipped on includes
      minify:       true          # process js files to shrink them
      minify_method: [sfCombineMinifierJsMin, minify]
      minify_method_options: []
      minify_skip_suffixes:       # files with this suffix will not be minified
        - .min.js
      minify_skip: ~              # these files will not be minified (useful when code is already minified)
      filename_comments: true     # include filenames of combined files in comments
      group_files: true           # minify all available files together in one minify action
      cache_minified_files: true  # cache minified versions of files (to not minify multiple times)
      route: sfCombineJs          # the route name js files will use
      inline_minify_method: ~
      inline_minify_method_options: ~
    css:
      combine: true               # whether or not to perform combining actions
      combine_skip: ~             # these files will not be combined
      include: true               # whether to allow the including of files
      include_suffixes:           # suffixes of files that can be included
        - .php
      include_skip: ~             # files that should be skipped on includes
      minify:       true          # process js files to shrink them
      minify_method: [sfCombineMinifierCssMin, minify]
      minify_method_options: []
      minify_skip_suffixes:       # files with this suffix should not be minified
        - .min.css
      minify_skip: ~              # these files will not be minified (useful when code is already minified)
      filename_comments: true     # include filenames of combined files in comments
      group_files: true           # minify all available files together in one minify action
      route: sfCombineCss         # the route name css files will use
      cache_minified_files: true  # cache minified versions of files (to not minify multiple times)
      keep_charset: true          # if there is a charset in a css file keep it
      prepend_imports: true       # move all imports to the top of a css file
      prepend_imports_warning:    # if imports are moved a warning to output
        Imports may be incorrectly placed, please remove for ideal combining
      inline_minify_method: ~
      inline_minify_method_options: ~


dev:
    sfCombinePlugin:
      enabled: false


live:
  open_auth:
    provider:
      vkontakte:
        app_id: 2659726
        secret_key: v4uMoJ3Fhne9R5SmHTiq
      facebook:
        app_id: 226981847349938 #
        secret_key: e9b8bd45490396ff8ee0da18c777323b #
      twitter:
        consumer_key: IyHijpaPPEtzcXNB1a5lTw
        consumer_secret: xAn2bD2Q90GrlU2DMS5upjteR2dgKhEQCFhijGopWw
      odnoklassniki:
        app_id: 5061376
        public_key: 'CBAMDOEBABABABABA'
        private_key: '37B3909065A020F45A9D073C'
        app_url: 'http://www.odnoklassniki.ru/games/enter'
      mailru:
        app_id: 648413
        private_key: '1d32486472b6d1ed5efe36070ac4f23c'
        secret_key: '60ca8f63a5fa1c90d72f0be0f80e4037'

  core:
    config:
      api_url: 'http://62.231.27.40/v1/json'
      consumer_key: v6Q4UiTaQ6jWPHtJ
      signature: FGZuEsnRew3EIoTdsKhn2bxThRQ7yjRd

  rediska:
    default:
      servers:
        main:
          host: site-db
          persistent: true

  cache_eraser:
    config:
      file: /opt/WWWRoot/enter.ru/ccontrol/erase_barcode.cmd
      prefix: 'CACHETAG::'


alpha:
  doctrine:
    result_cache:        true  # кешировать результаты запросов
    result_cache_prefix: 'dql:' # префикс ключей в кеше

  core:
    config:
      api_url: 'http://core.ent3.ru/v1/json'
      consumer_key: test
      signature: test

alpha_dev:
  doctrine:
    result_cache:        false  # кешировать результаты запросов
    result_cache_prefix: 'dql:' # префикс ключей в кеше

  core:
    config:
      api_url: 'http://core.ent3.ru/v1/json'
      consumer_key: test
      signature: test
