all:
  layout: info  
  

indexSuccess:
  metas:
    title:        Личный кабинет
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow  
    
ordersSuccess:
  metas:
    title:        Мои заказы - Личный кабинет
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow     
 

