Creator:
  - brand
  - Brands
Order:
  - order
Product:
  - product
ProductCategory:
  - product_category
  - ItemHierarchy
ProductProperty:
  - product_property
ProductPropertyGroup:
  - product_property_group
  - ProductPropertyGroups
ProductPropertyOption:
  - product_option
Region:
  - geo
  - GEOs
Shop:
  - shop
  - Stores
Tag:
  - tag
  - Tags
TagGroup:
  - tag_group
  - GroupsTags