Creator:
  - brand
  - Brands
Order:
  - order
Product:
  - product
ProductCategory:
  - product_category
  - ItemHierarchy
ProductpropertyGroup:
  - ProductPropertyGroups
Region:
  - geo
  - GEOs
Shop:
  - shop
Shop:
  - Stores
Tag:
  - tag
  - Tags
TagGroup:
  - tag_group
  - GroupsTags