Creator:
  - brand
  - Brands
Order:
  - order
Product:
  - product
ProductCategory:
  - product_category
  - ItemHierarchy
ProductComment:
  - product_opinion
ProductProperty:
  - product_property
ProductPropertyGroup:
  - product_property_group
  - ProductPropertyGroups
ProductPropertyOption:
  - product_option
ProductType:
  - product_type
#Region:
#  - geo
#  - GEOs
Shop:
  - shop
  - Stores
Tag:
  - tag
  - Tags
TagGroup:
  - tag_group
  - GroupsTags
#User:
#  - user
ProductPriceList:
  - product_price_list
ServiceCategory:
  - service_category
ProductPrice:
  - product_price
Service:
  - service