CallbackCategory:
  - user_callback_category
Creator:
  - brand
  - Brands
DeliveryPeriod:
  - delivery_interval
Order:
  - order
OrderProductRelation:
  - order_product_relation
Product:
  - product
ProductCategory:
  - product_category
  - ItemHierarchy
ProductComment:
  - product_opinion
ProductLine:
  - product_line
ProductPrice:
  - product_price
ProductPriceList:
  - product_price_list
ProductProperty:
  - product_property
ProductPropertyGroup:
  - product_property_group
  - ProductPropertyGroups
ProductPropertyOption:
  - product_option
ProductType:
  - product_type
Qrcode:
  - qrcode
Region:
  - geo
  - GEOs
Shop:
  - shop
  - Stores
Tag:
  - tag
  - Tags
TagGroup:
  - tag_group
  - GroupsTags
ServiceCategory:
  - service_category
Service:
  - service
ServicePrice:
  - service_price  
ServiceProductRelation:
  - service_product_relation    
#DeliveryType:
#  - delivery_type
#PaymentMethod:
#  - payment_method
StockProductRelation:
  - product_stock
Stock:
  - store
User:
  - user
UserAddress:
  - user_address
UserProductRatingTotal:
  - user_product_rating
UserProfile:
  - user_network