Creator:
  - brand
  - Brands
DeliveryPeriod:
  - delivery_interval
Order:
  - order
Product:
  - product
ProductCategory:
  - product_category
  - ItemHierarchy
ProductComment:
  - product_opinion
ProductPrice:
  - product_price
ProductPriceList:
  - product_price_list
ProductProperty:
  - product_property
ProductPropertyGroup:
  - product_property_group
  - ProductPropertyGroups
ProductPropertyOption:
  - product_option
ProductType:
  - product_type
Region:
  - geo
  - GEOs
Shop:
  - shop
  - Stores
Tag:
  - tag
  - Tags
TagGroup:
  - tag_group
  - GroupsTags
ServiceCategory:
  - service_category
Service:
  - service
#DeliveryType:
#  - delivery_type
#PaymentMethod:
#  - payment_method
StockProductRelation:
  - product_stock
Stock:
  - store
User:
  - user