all:
  is_secure: true

forgotPassword:
  is_secure: false

resetPassword:
  is_secure: false

signin:
  is_secure: false

signinajax:
  is_secure: false

register:
  is_secure: false

quickRegister:
  is_secure: false

basicRegister:
  is_secure: false

oauthSignin:
  is_secure: false

oauthCallback:
  is_secure: false

corporateRegister:
  is_secure: false