
;(function($){var buyButtonBinding=function(element,valueAccessor){var cart=ko.unwrap(valueAccessor()),$elem=$(element);$.each(cart,function(i,val){if(val.id==$elem.data('group'))$elem.text('В корзине').addClass('mBought').attr('href','/cart');})};var buySpinnerBinding=function(element,valueAccessor){var cart=ko.unwrap(valueAccessor()),$elem=$(element);$elem.removeClass('mDisabled').find('input').attr('disabled',false);$.each(cart,function(i,val){if(val.id==$elem.data('product-id')){$elem.addClass('mDisabled');$elem.find('input').val(val.quantity).attr('disabled',true);}})};var compareButtonBinding=function(element,valueAccessor){var compare=ko.unwrap(valueAccessor()),$elem=$(element),id=$elem.data('id'),categoryId=$elem.data('category-id'),comparableProducts;if($.grep(compare,function(val){return id==val.id;}).length==0){$elem.removeClass('btnCmpr-act').find('a.btnCmpr_lk').removeClass('btnCmpr_lk-act').attr('href',$elem.data('add-url')).find('span').text('Добавить к сравнению');return;}
$.each(compare,function(i,val){if(val.id==id){$elem.addClass('btnCmpr-act').find('a.btnCmpr_lk').addClass('btnCmpr_lk-act').attr('href',$elem.data('delete-url')).find('span').text('Убрать из сравнения');}});comparableProducts=$.grep(compare,function(val){return categoryId==val.categoryId;});if(comparableProducts.length>1){$elem.find('.btnCmpr_more').show().find('.btnCmpr_more_qn').text(comparableProducts.length);}};var compareListBinding=function(element,valueAccessor){var compare=ko.unwrap(valueAccessor()),$elem=$(element);if($.grep(compare,function(val){return val.id==$elem.data('id')}).length>0){$elem.addClass('btnCmprb-act').attr('href','/compare/delete-product/'+$elem.data('id'));}else{$elem.removeClass('btnCmprb-act').attr('href','/compare/add-product/'+$elem.data('id'));}};ko.bindingHandlers.compareListBinding={init:compareListBinding,update:compareListBinding};ko.bindingHandlers.buyButtonBinding={init:buyButtonBinding,update:buyButtonBinding};ko.bindingHandlers.buySpinnerBinding={init:buySpinnerBinding,update:buySpinnerBinding};ko.bindingHandlers.compareButtonBinding={init:compareButtonBinding,update:compareButtonBinding};}(jQuery));
;(function($){var $body=$(document.body),userInfoURL=ENTER.config.pageConfig.userUrl+'?ts='+new Date().getTime()+Math.floor(Math.random()*1000),User=function(){var self=this;self.name=ko.observable();self.link=ko.observable();self.hasEnterprizeCoupon=ko.observable(false);self.cart=ko.observableArray();self.compare=ko.observableArray();self.isProductInCompare=function(elem){console.log('isProductInCompare',elem);return $.grep(self.compare,function(val){return val.id==$(elem).data('id')}).length==0};self.cartProductQuantity=ko.computed(function(){return self.cart().length;});self.ajaxUserInfo=function(data){if(data.user){if(data.user.name)self.name(data.user.name);if(data.user.link)self.link(data.user.link);if(data.user.hasEnterprizeCoupon)self.hasEnterprizeCoupon(true);}
if(data.cartProducts&&$.isArray(data.cartProducts)){$.each(data.cartProducts,function(i,val){self.cart.unshift(val)});}
if(data.compare){$.each(data.compare,function(i,val){self.compare.push(val)})}}},startTime,endTime,spendTime;ENTER.UserModel=new User();$('.topbarfix, .bWidgetBuy, .bListing').each(function(){ko.applyBindings(ENTER.UserModel,this)});$.ajax({url:userInfoURL,beforeSend:function(){startTime=new Date().getTime();},success:function(data){endTime=new Date().getTime();spendTime=endTime-startTime;ENTER.UserModel.ajaxUserInfo(data);if(typeof ga=='function'){ga('send','timing','userInfo','Load User Info',spendTime);console.log('[Google Analytics] Send user/info timing: %s ms',spendTime)}
ENTER.config.userInfo=data;var authorized_cookie='_authorized';if(!docCookies.hasItem(authorized_cookie)){if(data&&null!==data.id){docCookies.setItem(authorized_cookie,1,60*60,'/');}else{docCookies.setItem(authorized_cookie,0,60*60,'/');}}
$body.trigger('userLogged',[data]);}});$('.jsCompareLink, .jsCompareList').on('click',function(e){var url=this.href;if($(this).hasClass('jsCompareList')){url=$(this).hasClass('btnCmprb-act')?'/compare/delete-product/'+$(this).data('id'):'/compare/add-product/'+$(this).data('id');}
e.preventDefault();$.ajax({url:url,success:function(data){if(data.compare){ENTER.UserModel.compare.removeAll();$.each(data.compare,function(i,val){ENTER.UserModel.compare.push(val)})}}})});}(jQuery));
;(function(window,document,$,ENTER){$.ajaxSetup({timeout:10000,statusCode:{404:function(){var ajaxUrl=this.url,data={event:'ajax_error',type:'404 ошибка',ajaxUrl:ajaxUrl};if(typeof _gaq!=='undefined'){_gaq.push(['_trackEvent','Errors','Ajax Errors','404 ошибка, страница не найдена']);}},401:function(){if($('#auth-block').length){$('#auth-block').lightbox_me({centered:true,onLoad:function(){$('#auth-block').find('input:first').focus();}});}
else{if(typeof _gaq!=='undefined'){_gaq.push(['_trackEvent','Errors','Ajax Errors','401 ошибка, авторизуйтесь заново']);}}},500:function(){var ajaxUrl=this.url,data={event:'ajax_error',type:'500 ошибка',ajaxUrl:ajaxUrl};if(typeof _gaq!=='undefined'){_gaq.push(['_trackEvent','Errors','Ajax Errors','500 сервер перегружен']);}},503:function(){var ajaxUrl=this.url,data={event:'ajax_error',type:'503 ошибка',ajaxUrl:ajaxUrl};if(typeof _gaq!=='undefined'){_gaq.push(['_trackEvent','Errors','Ajax Errors','503 ошибка, сервер перегружен']);}},504:function(){var ajaxUrl=this.url,data={event:'ajax_error',type:'504 ошибка',ajaxUrl:ajaxUrl};if(typeof _gaq!=='undefined'){_gaq.push(['_trackEvent','Errors','Ajax Errors','504 ошибка, проверьте соединение с интернетом']);}}},error:function(jqXHR,textStatus,errorThrown){var ajaxUrl=this.url,data={event:'ajax_error',type:'неизвестная ajax ошибка',ajaxUrl:ajaxUrl};if(jqXHR.statusText==='error'){if(typeof _gaq!=='undefined'){_gaq.push(['_trackEvent','Errors','Ajax Errors','неизвестная ajax ошибка']);}}
else if(textStatus==='timeout'){return;}}});}(this,this.document,this.jQuery,this.ENTER));
;(function($){var body=$(document.body),ga=this.ga,_gaq=this._gaq,trackGoogleEvent=function trackGoogleEventF(jQueryEvent,eventObject){var e={},universalEvent={hitType:'event'},classicEvent=['_trackEvent'],props=['category','action','label','value','nonInteraction','hitCallback'];if(arguments.length==2&&typeof eventObject=='object'){$.each(props,function(i,elem){if(eventObject.hasOwnProperty(elem))e[elem]=eventObject[elem];})}else if(arguments.length>2&&typeof eventObject=='string'){for(var i=1,l=arguments.length;i<l;i++){e[props[i-1]]=arguments[i];}}
$.each(props,function(i,elem){if(e.hasOwnProperty(elem)){switch(elem){case'category':e[elem]=e[elem].slice(0,150);break;case'action':case'label':e[elem]=e[elem].slice(0,500);break;case'value':e[elem]=parseInt(e[elem].slice,10);break;case'nonInteraction':e[elem]=Boolean(e[elem]);break;}}});if(typeof _gaq==='object'){classicEvent.push(e.category,e.action);if(e.label)classicEvent.push(e.label);if(e.value)classicEvent.push(e.value);if(e.nonInteraction)classicEvent.push(e.nonInteraction);_gaq.push(classicEvent);}else{console.warn('No Google Analytics object found')}
if(typeof ga==='function'&&ga.getAll().length!=0){universalEvent.eventCategory=e.category;universalEvent.eventAction=e.action;if(e.label)universalEvent.eventLabel=e.label;if(e.value)universalEvent.eventValue=e.value;if(e.hitCallback)universalEvent.hitCallback=e.hitCallback;if(e.nonInteraction)ga('set','nonInteraction',true);ga('send',universalEvent);}else{console.warn('No Universal Google Analytics function found');if(typeof e.hitCallback=='function')e.hitCallback();}
console.info('[Google Analytics] Send event:',e);},GoogleTransaction=function GoogleTransactionF(data){this.id=data.id?data.id:false;this.affiliation=data.affiliation;this.total=data.total;this.shipping=data.shipping?data.shipping:'0';this.tax=data.tax?data.tax:'0';this.city=data.city?data.city:'';if(!this.id)throw'Некорректный ID транзакции';if(!this.total)throw'Некорректная сумма заказа';this.toObject=function toObjectF(){return{'id':this.id,'affiliation':this.affiliation,'revenue':this.total,'shipping':this.shipping,'tax':this.tax}};this.toArray=function toArrayF(){return[this.id,this.affiliation,this.total,this.tax,this.shipping,this.city]};return this;},GoogleProduct=function GoogleProductF(data){this.id=data.id?String(data.id):'';this.name=data.name?String(data.name):'';this.category=data.category?String(data.category):'';this.sku=data.sku?String(data.sku):'';this.price=data.price?String(data.price):'';this.quantity=data.quantity?String(data.quantity):'';if(!this.id)throw'Некорректный ID товара';if(!this.name)throw'Некорректное название товара';if(!this.price)throw'Некорректная цена товара';if(!this.quantity)throw'Некорректное количество товара';this.toObject=function toObjectF(){return{'id':this.id,'name':this.name,'sku':this.sku,'category':this.category,'price':this.price,'quantity':this.quantity}};this.toArray=function toArrayF(){return[this.id,this.sku,this.name,this.category,this.price,this.quantity];};return this;},trackGoogleTransaction=function trackGoogleTransactionF(jQueryEvent,eventObject){var googleTrans,googleProducts;try{googleTrans=new GoogleTransaction(eventObject.transaction);googleProducts=$.map(eventObject.products,function(elem){return new GoogleProduct(elem)});if(typeof _gaq==='object'){_gaq.push(['_addTrans'].concat(googleTrans.toArray()));$.each(googleProducts,function(i,product){_gaq.push(['_addItem'].concat(product.toArray()))});_gaq.push(['_trackTrans']);}else{console.warn('No Google Analytics object found')}
if(typeof ga==='function'&&ga.getAll().length!=0){ga('require','ecommerce','ecommerce.js');ga('ecommerce:addTransaction',googleTrans.toObject());$.each(googleProducts,function(i,product){ga('ecommerce:addItem',product.toObject())});ga('ecommerce:send');}else{console.warn('No Universal Google Analytics function found');}}catch(exception){console.error('[Google Analytics Ecommerce] %s',exception)}};if(typeof ga==='undefined')ga=window[window['GoogleAnalyticsObject']];body.on('trackGoogleEvent',trackGoogleEvent);body.on('trackGoogleTransaction',trackGoogleTransaction);if(typeof ga==='function'&&ga.getAll().length==0){ga('create','UA-25485956-5','enter.ru');}})(jQuery);
(function(){var checkedSms=false;var checkedEmail=false;var handleSubscribeSms=function(){if(checkedSms){$('#mobilePhoneWrapper').hide();$('#mobilePhoneWrapper').parent().find('.red').html('');checkedSms=false;}else{$('#mobilePhoneWrapper').show();checkedSms=true;}};var handleSubscribeEmail=function(){if(checkedEmail){$('#emailWrapper').hide();$('#emailWrapper').parent().find('.red').html('');checkedEmail=false;}else{$('#emailWrapper').show();checkedEmail=true;}};$(document).ready(function(){checkedSms=$('.smsCheckbox').hasClass('checked');if(!$('#user_mobile_phone').val()){$('.smsCheckbox').bind('click',handleSubscribeSms);}
checkedEmail=$('.emailCheckbox').hasClass('checked');if(!$('#user_email').val()){$('.emailCheckbox').bind('click',handleSubscribeEmail);}});}());

(function(ENTER){var body=$('body');$(function(){body.on('click','.jsBuyButton',function(){var button=$(this);if(button.hasClass('mDisabled')){return false;}
if(button.hasClass('mBought')){document.location.href(button.attr('href'));return false;}
button.addClass('mLoading');$.get(button.attr('href'),function(data){var
upsale=button.data('upsale')?button.data('upsale'):null,product=button.parents('.jsSliderItem').data('product');if(!data.success){return;}
button.removeClass('mLoading');if(data.product){data.product.isUpsale=product&&product.isUpsale?true:false;data.product.fromUpsale=upsale&&upsale.fromUpsale?true:false;}
body.trigger('addtocart',[data]);body.trigger('getupsale',[data,upsale]);});return false;});});body.on('addtocart',function(event,data){if(data.redirect){console.warn('redirect');document.location.href=data.redirect;}else{if(data.product){ENTER.UserModel.cart.unshift(data.product);}
if(data.products){$.each(data.products,function(){ENTER.UserModel.cart.unshift(this);});}}});body.on('addtocart',function(event,data){var
kissAnalytics=function kissAnalytics(event,data){var productData=data.product,serviceData=data.service,warrantyData=data.warranty,nowUrl=window.location.href,toKISS={};if(typeof _kmq==='undefined'){return;}
if(productData){toKISS={'Add to Cart SKU':productData.article,'Add to Cart SKU Quantity':productData.quantity,'Add to Cart Product Name':productData.name,'Add to Cart Root category':productData.category[0].name,'Add to Cart Root ID':productData.category[0].id,'Add to Cart Category name':(productData.category)?productData.category[productData.category.length-1].name:0,'Add to Cart Category ID':(productData.category)?productData.category[productData.category.length-1].id:0,'Add to Cart SKU Price':productData.price,'Add to Cart Page URL':nowUrl,'Add to Cart F1 Quantity':productData.serviceQuantity};_kmq.push(['record','Add to Cart',toKISS]);productData.isUpsale&&_kmq.push(['record','cart rec added from rec',{'SKU cart added from rec':productData.article}]);productData.fromUpsale&&_kmq.push(['record','cart recommendation added',{'SKU cart rec added':productData.article}]);}
if(serviceData){toKISS={'Add F1 F1 Name':serviceData.name,'Add F1 F1 Price':serviceData.price,'Add F1 SKU':productData.article,'Add F1 Product Name':productData.name,'Add F1 Root category':productData.category[0].name,'Add F1 Root ID':productData.category[0].id,'Add F1 Category name':(productData.category)?productData.category[productData.category.length-1].name:0,'Add F1 Category ID':(productData.category)?productData.category[productData.category.length-1].id:0};_kmq.push(['record','Add F1',toKISS]);}
if(warrantyData){toKISS={'Add Warranty Warranty Name':warrantyData.name,'Add Warranty Warranty Price':warrantyData.price,'Add Warranty SKU':productData.article,'Add Warranty Product Name':productData.name,'Add Warranty Root category':productData.category[0].name,'Add Warranty Root ID':productData.category[0].id,'Add Warranty Category name':(productData.category)?productData.category[productData.category.length-1].name:0,'Add Warranty Category ID':(productData.category)?productData.category[productData.category.length-1].id:0};_kmq.push(['record','Add Warranty',toKISS]);}},googleAnalytics=function googleAnalytics(event,data){var
productData=data.product;var
tchiboGA=function(){if(typeof window.ga==="undefined"||!productData.hasOwnProperty("isTchiboProduct")||!productData.isTchiboProduct){return;}
console.log("TchiboGA: tchiboTracker.send event Add2Basket product [%s, %s]",productData.name,productData.article);ga("tchiboTracker.send","event","Add2Basket",productData.name,productData.article);};if(!productData||typeof _gaq==='undefined'){return;}
tchiboGA();console.log("_gaq: _trackEvent Add2Basket product %s",productData.article);_gaq.push(['_trackEvent','Add2Basket','product',productData.article]);productData.isUpsale&&_gaq.push(['_trackEvent','cart_recommendation','cart_rec_added_from_rec',productData.article]);productData.fromUpsale&&_gaq.push(['_trackEvent','cart_recommendation','cart_rec_added_to_cart',productData.article]);},adAdriver=function adAdriver(event,data){var productData=data.product,offer_id=productData.id,category_id=(productData.category)?productData.category[productData.category.length-1].id:0,s='http://ad.adriver.ru/cgi-bin/rle.cgi?sid=182615&sz=add_basket&custom=10='+offer_id+';11='+category_id+'&bt=55&pz=0&rnd=![rnd]',d=document,i=d.createElement('IMG'),b=d.body;s=s.replace(/!\[rnd\]/,Math.round(Math.random()*9999999))+'&tail256='+escape(d.referrer||'unknown');i.style.position='absolute';i.style.width=i.style.height='0px';i.onload=i.onerror=function(){b.removeChild(i);i=b=null;};i.src=s;b.insertBefore(i,b.firstChild);},addToRetailRocket=function addToRetailRocket(event,data){var product=data.product;if(typeof rcApi==='object'){try{rcApi.addToBasket(product.id);}
catch(err){}}},addToRuTarget=function addToRuTarget(event,data){var
product=data.product,regionId=data.regionId,result,_rutarget=window._rutarget||[];if(!product||!regionId){return;}
result={'event':'addToCart','sku':product.id,'qty':product.quantity,'regionId':regionId};console.info('RuTarget addToCart');console.log(result);_rutarget.push(result);},addToLamoda=function addToLamoda(event,data){var
product=data.product;if('undefined'==typeof(product)||!product.hasOwnProperty('id')||'undefined'==typeof(JSREObject)){return;}
console.info('Lamoda addToCart');console.log('product_id='+product.id);JSREObject('cart_add',product.id);};try{if(data.product){kissAnalytics(event,data);googleAnalytics(event,data);adAdriver(event,data);addToRetailRocket(event,data);}
if(data.products){console.groupCollapsed('Аналитика для набора продуктов');for(var i in data.products){googleAnalytics(event,{product:data.products[i]});if(typeof window.ga!='undefined'){console.log("GA: send event Add2Basket product %s",data.products[i].article);window.ga('send','event','Add2Basket','product',data.products[i].article);}}
console.groupEnd();}
addToRuTarget(event,data);addToLamoda(event,data);}
catch(e){console.warn('addtocartAnalytics error');console.log(e);}});}(window.ENTER));
;(function(global){var body=$('body'),regionWindow=$('.popupRegion'),inputRegion=$('#jscity'),formRegionSubmitBtn=$('#jschangecity'),clearBtn=regionWindow.find('.inputClear'),changeRegionBtn=$('.jsChangeRegion'),changeRegionAnalyticsBtn=$('.jsChangeRegionAnalytics'),slidesWrap=regionWindow.find('.regionSlidesWrap'),moreCityBtn=regionWindow.find('.moreCity'),leftArrow=regionWindow.find('.leftArr'),rightArrow=regionWindow.find('.rightArr'),citySlides=regionWindow.find('.regionSlides'),slideWithCity=regionWindow.find('.regionSlides_slide');inputRegion.autocomplete({autoFocus:true,appendTo:'#jscities',source:function(request,response){$.ajax({url:inputRegion.data('url-autocomplete'),dataType:'json',data:{q:request.term},success:function(data){var res=data.data.slice(0,15);response($.map(res,function(item){return{label:item.name,value:item.name,url:item.url};}));}});},minLength:2,select:function(event,ui){formRegionSubmitBtn.data('url',ui.item.url);submitBtnEnable();},open:function(){$(this).removeClass('ui-corner-all').addClass('ui-corner-top');},close:function(){$(this).removeClass('ui-corner-top').addClass('ui-corner-all');}});var showRegionPopup=function showRegionPopup(){regionWindow.lightbox_me({autofocus:true,onLoad:function(){if(inputRegion.val().length){inputRegion.putCursorAtEnd();submitBtnEnable();}},onClose:function(){var id=changeRegionBtn.data('region-id');if(!global.docCookies.hasItem('geoshop')){global.docCookies.setItem('geoshop',id,31536e3,'/');}}});if(document.location.pathname==='/'){console.info('run analytics for main page');if(typeof _gaq!=='undefined'){_gaq.push(['_trackEvent','citySelector','viewed']);}}},changeRegionHandler=function changeRegionHandler(){var self=$(this),autoResolve=self.data('autoresolve-url');var authFromServer=function authFromServer(res){if(!res.data.length){$('.popupRegion .mAutoresolve').html('');return false;}
var url=res.data[0].url,name=res.data[0].name,id=res.data[0].id;if(id===14974||id===108136){return false;}
if($('.popupRegion .mAutoresolve').length){$('.popupRegion .mAutoresolve').html('<a href="'+url+'">'+name+'</a>');}
else{$('.popupRegion .cityInline').prepend('<div class="cityItem mAutoresolve"><a href="'+url+'">'+name+'</a></div>');}};if(typeof autoResolve!=='undefined'){$.ajax({type:'GET',url:autoResolve,success:authFromServer});}
showRegionPopup();return false;},nextCitySlide=function nextCitySlide(){var regionSlideW=slideWithCity.width()*1,sliderW=citySlides.width()*1,sliderLeft=parseInt(citySlides.css('left'),10);leftArrow.show();citySlides.animate({'left':sliderLeft-regionSlideW});if(sliderLeft-(regionSlideW*2)<=-sliderW){rightArrow.hide();}
return false;},prevCitySlide=function prevCitySlide(){var regionSlideW=slideWithCity.width()*1,sliderW=citySlides.width()*1,sliderLeft=parseInt(citySlides.css('left'),10);rightArrow.show();citySlides.animate({'left':sliderLeft+regionSlideW});if(sliderLeft+(regionSlideW*2)>=0){leftArrow.hide();}
return false;},expandCityList=function expandCityList(){$(this).toggleClass('mExpand');slidesWrap.slideToggle(300);return false;},clearInputHandler=function clearInputHandler(){inputRegion.val('');submitBtnDisable();clearBtn.hide();return false;},inputRegionChangeHandler=function inputRegionChangeHandler(){if($(this).val()){submitBtnEnable();clearBtn.show();}
else{submitBtnDisable();clearBtn.hide();}},changeRegionAnalytics=function changeRegionAnalytics(regionName){if(document.location.pathname==='/'){console.info('run analytics for main page '+regionName);if(typeof _gaq!=='undefined'){_gaq.push(['_trackEvent','citySelector','selected',regionName]);}}},changeRegionAnalyticsHandler=function changeRegionAnalyticsHandler(){var regionName=$(this).text();changeRegionAnalytics(regionName);},submitCityHandler=function submitCityHandler(){var url=$(this).data('url'),regionName=inputRegion.val();changeRegionAnalytics(regionName);if(url){global.location=url;}
else{regionWindow.trigger('close');}
return false;},submitBtnDisable=function(){formRegionSubmitBtn.addClass('mDisabled');formRegionSubmitBtn.attr('disabled','disabled');},submitBtnEnable=function(){formRegionSubmitBtn.removeClass('mDisabled');formRegionSubmitBtn.removeAttr('disabled');};formRegionSubmitBtn.on('click',submitCityHandler);moreCityBtn.on('click',expandCityList);clearBtn.on('click',clearInputHandler);rightArrow.on('click',nextCitySlide);leftArrow.on('click',prevCitySlide);inputRegion.on('keyup',inputRegionChangeHandler);body.on('click','.jsChangeRegion',changeRegionHandler);changeRegionAnalyticsBtn.on('click',changeRegionAnalyticsHandler);if(!global.docCookies.hasItem('geoshop')){showRegionPopup();}}(this));
;(function(){var inputs=$('input.bCustomInput'),body=$('body');var updateState=function updateState(){if(!$(this).is('[type=checkbox]')&&!$(this).is('[type=radio]')){return;}
var $self=$(this),id=$self.attr('id'),type=($self.is('[type=checkbox]'))?'checkbox':'radio',groupName=$self.attr('name')||'',label=$('label[for="'+id+'"]');if(type==='checkbox'){if($self.is(':checked')){label.addClass('mChecked');}
else{label.removeClass('mChecked');}}
if(type==='radio'&&$self.is(':checked')){$('input[name="'+groupName+'"]').each(function(){var currElement=$(this),currId=currElement.attr('id');$('label[for="'+currId+'"]').removeClass('mChecked');});label.addClass('mChecked');}};body.on('updateState','.bCustomInput',updateState);body.on('change','.bCustomInput',function(){$(this).trigger('updateState');});inputs.trigger('updateState');}());
$(document).ready(function(){if($('#similarGoodsSlider').length){var similarSlider=$('#similarGoodsSlider'),similarWrap=similarSlider.find('.bSimilarGoodsSlider_eWrap'),similarArrow=similarSlider.find('.bSimilarGoodsSlider_eArrow'),slidesW=0,sliderW=0,slidesCount=0,wrapW=0,left=0;var kissSimilar=function kissSimilar(){var clicked=$(this),toKISS={'Recommended Item Clicked Similar Recommendation Place':'product','Recommended Item Clicked Similar Clicked SKU':clicked.data('article'),'Recommended Item Clicked Similar Clicked Product Name':clicked.data('name'),'Recommended Item Clicked Similar Product Position':clicked.data('pos')};if(typeof(_kmq)!=='undefined'){_kmq.push(['record','Recommended Item Clicked Similar',toKISS]);}},init=function init(data){var similarGoods=similarSlider.find('.bSimilarGoodsSlider_eGoods');for(var item in data){var similarGood=tmpl('similarGoodTmpl',data[item]);similarWrap.append(similarGood);}
slidesW=similarGoods.width()+parseInt(similarGoods.css('paddingLeft'),10)*2;slidesCount=similarGoods.length;wrapW=slidesW*slidesCount;similarWrap.width(wrapW);if(slidesCount>0){$('.bSimilarGoods').fadeIn(300,function(){sliderW=similarSlider.width();});}
if(slidesCount<4){$('.bSimilarGoodsSlider_eArrow.mRight').hide();}};$.getJSON($('#similarGoodsSlider').data('url'),function(data){if(!($.isEmptyObject(data))){var initData=data;init(initData);}}).done(function(){var similarGoods=similarSlider.find('.bSimilarGoodsSlider_eGoods');slidesCount=similarGoods.length;wrapW=slidesW*slidesCount;similarWrap.width(wrapW);if(slidesCount>0){$('.bSimilarGoods').fadeIn(300,function(){sliderW=similarSlider.width();});}});similarArrow.bind('click',function(){if($(this).hasClass('mLeft')){left+=(slidesW*2);}
else{left-=(slidesW*2);}
if((left<=sliderW-wrapW)){left=sliderW-wrapW;$('.bSimilarGoodsSlider_eArrow.mRight').hide();$('.bSimilarGoodsSlider_eArrow.mLeft').show();}
else if(left>=0){left=0;$('.bSimilarGoodsSlider_eArrow.mLeft').hide();$('.bSimilarGoodsSlider_eArrow.mRight').show();}
else{similarArrow.show();}
similarWrap.animate({'left':left});return false;});$('.bSimilarGoods.mProduct .bSimilarGoodsSlider_eGoods').on('click',kissSimilar);}
if(window.navigator.userAgent.indexOf('MSIE')>=0){$('.allpageinner').on('hover','.goodsbox__inner',function(){$(this).toggleClass('hover');});}
$('body').on('click','.goodsbox__inner',function(e){if($(this).attr('data-url')){window.location.href=$(this).attr('data-url');}});var kissForCategory=function kissForCategory(){var data=$('#_categoryData').data('category'),toKISS={'Viewed Category Category Type':data.type,'Viewed Category Category Level':data.level,'Viewed Category Parent category':data.parent_category,'Viewed Category Category name':data.category,'Viewed Category Category ID':data.id};if(typeof(_kmq)!=='undefined'){_kmq.push(['record','Viewed Category',toKISS]);}};var kissForProductOfCategory=function kissForProductOfCategory(event){var t=$(this),box,datap,toKISS=false,datac=$('#_categoryData').data('category');box=t.parents('div.goodsbox__inner');if(!box.length){box=t.parents('div.goodsboxlink');}
datap=box.length?box.data('add'):false;if(datap&&datac){toKISS={'Category Results Clicked Category Type':datac.type,'Category Results Clicked Category Level':datac.level,'Category Results Clicked Parent category':datac.parent_category,'Category Results Clicked Category name':datac.category,'Category Results Clicked Category ID':datac.id,'Category Results Clicked SKU':datap.article,'Category Results Clicked Product Name':datap.name,'Category Results Clicked Page Number':datap.page,'Category Results Clicked Product Position':datap.position};}
if(toKISS&&typeof _kmq!=='undefined'){_kmq.push(['record','Category Results Clicked',toKISS]);}};if($('#_categoryData').length){kissForCategory();$('body').delegate('div.goodsbox a','click',kissForProductOfCategory);}
var kissForSearchResultPage=function kissForSearchResultPage(){var data=$('#_searchKiss').data('search'),toKISS={'Search String':data.query,'Search Page URL':data.url,'Search Items Found':data.count};if(typeof(_kmq)!=='undefined'){_kmq.push(['record','Search',toKISS]);}
var KISSsearchClick=function(){var productData=$(this).data('add'),prToKISS={'Search Results Clicked Search String':data.query,'Search Results Clicked SKU':productData.article,'Search Results Clicked Product Name':productData.name,'Search Results Clicked Page Number':productData.page,'Search Results Clicked Product Position':productData.position};if(typeof(_kmq)!=='undefined'){_kmq.push(['record','Search Results Clicked',prToKISS]);}};$('.goodsbox__inner').on('click',KISSsearchClick);$('.goodsboxlink').on('click',KISSsearchClick);};if($('#_searchKiss').length){kissForSearchResultPage();}});
(function(){var goToId=function goToId(){var to=$(this).data('goto');$(document).stop().scrollTo($('#'+to),800);return false;};$(document).ready(function(){$('.jsGoToId').bind('click',goToId);});}());
(function(){var handleHotLinksToggle=function(){var toggle=$(this);if(toggle.hasClass('expanded')){toggle.parent().parent().find('.toHide').hide();toggle.html('Все метки');toggle.removeClass('expanded');}else{toggle.parent().parent().find('.toHide').show();toggle.html('Основные метки');toggle.addClass('expanded');}
return false;};$(document).ready(function(){$('.hotlinksToggle').bind('click',handleHotLinksToggle);});}());
;(function(){$.ajax({url:'https://jira.enter.ru/s/ru_RU-istibo/773/3/1.2.4/_/download/batch/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector.js?collectorId=2e17c5d6',type:'get',cache:true,dataType:'script'});window.ATL_JQ_PAGE_PROPS={'triggerFunction':function(showCollectorDialog){$('#jira').click(function(e){e.preventDefault();showCollectorDialog();});}};}());
;(function(ENTER){var
$authBlock=$('#auth-block'),init=function(){$authBlock.on('changeState',function(e,state){var
$el=$(this);console.info({'message':'authBlock.changeState','state':state});if(state){var
oldClass=$el.attr('data-state')?('state_'+$el.attr('data-state')):null,newClass='state_'+state;oldClass&&$el.removeClass(oldClass);$el.addClass(newClass);$el.attr('data-state',state);}
$('.js-resetForm, .js-authForm, .js-registerForm').trigger('clearError');});$authBlock.find('.js-link').on('click',function(e){var
$el=$(e.target),$target=$($el.data('value').target),state=$el.data('value').state;console.info({'$target':$target,'state':state});$target.trigger('changeState',[state]);});$('.js-resetForm, .js-authForm, .js-registerForm').on('submit',function(e){var
$el=$(e.target),data=$el.serializeArray();$.post($el.attr('action'),data).done(function(response){function getFieldValue(fieldName){for(var i=0;i<data.length;i++){if(data[i]['name']==fieldName){return data[i]['value'];}}
return null;}
if($el.hasClass('js-registerForm')&&getFieldValue('subscribe')&&typeof _gaq!='undefined'){_gaq.push(['_trackEvent','subscription','subscribe_registration',getFieldValue('register[email]')]);}
if(response.data&&response.data.link){window.location.href=response.data.link?response.data.link:window.location.href;return true;}
$el.trigger('clearError');var message=response.message;if(!message&&response.notice&&response.notice.message){message=response.notice.message;}
if(message){$el.find('.js-message').html(message);}
response.form&&response.form.error&&$.each(response.form.error,function(i,error){console.warn(error);$el.trigger('fieldError',[error]);});});e.preventDefault();}).on('fieldError',function(e,error){var
$el=$(e.target),$field=$el.find('[name*="'+error.field+'"]');if($field.length){$field.prev('.js-fieldError').remove();if(error.message){$field.before('<div class="js-fieldError bErrorText"><div class="bErrorText__eInner">'+error.message+'</div></div>');}}}).on('clearError',function(){var $el=$(this);$el.find('.js-message').html('');$el.find('input').each(function(i,el){$el.trigger('fieldError',[{field:$(el).attr('name')}]);});}).on('focus','input',function(){var $el=$(this);$el.closest('form').trigger('fieldError',[{field:$el.attr('name')}])});$.mask.definitions['n']='[0-9]';$('.js-registerForm .js-phoneField').mask('+7 (nnn) nnn-nn-nn');};;$(document).ready(function(){init();});}(window.ENTER));
;(function(ENTER){var constructors=ENTER.constructors,body=$('body'),authBlock=$('#auth-block'),registerMailPhoneField=$('.jsRegisterUsername'),resetPwdForm=$('.jsResetPwdForm'),registerForm=$('.jsRegisterForm'),loginForm=$('.jsLoginForm'),completeRegister=$('.jsRegisterFormComplete'),showLoginFormLink=$('.jsShowLoginForm'),signinValidationConfig={fields:[{fieldNode:$('.jsSigninUsername',authBlock),require:true,customErr:'Не указан логин'},{fieldNode:$('.jsSigninPassword',authBlock),require:true,customErr:'Не указан пароль'}]},signinValidator=new FormValidator(signinValidationConfig),registerValidationConfig={fields:[{fieldNode:$('.jsRegisterFirstName',authBlock),require:true,customErr:'Не указано имя'},{fieldNode:registerMailPhoneField,validBy:'isEmail',require:true,customErr:'Некорректно введен e-mail'}]},registerValidator=new FormValidator(registerValidationConfig),forgotPwdValidationConfig={fields:[{fieldNode:$('.jsForgotPwdLogin',authBlock),require:true,customErr:'Не указан email или мобильный телефон',validateOnChange:true}]},forgotValidator=new FormValidator(forgotPwdValidationConfig);var
setValidatorSettings=function(){ENTER.utils.signinValidationConfig=signinValidationConfig;ENTER.utils.signinValidator=signinValidator;ENTER.utils.registerValidationConfig=registerValidationConfig;ENTER.utils.registerValidator=registerValidator;ENTER.utils.forgotPwdValidationConfig=forgotPwdValidationConfig;ENTER.utils.forgotValidator=forgotValidator;};setValidatorSettings();constructors.Login=(function(){'use strict';function Login(){if(!(this instanceof Login)){return new Login();}
this.form=null;this.redirect_to=null;body.on('click','.registerAnotherWayBtn',$.proxy(this.registerAnotherWay,this));body.on('click','.bAuthLink',this.openAuth);$('.jsLoginForm, .jsRegisterForm, .jsResetPwdForm').data('redirect',true).on('submit',$.proxy(this.formSubmit,this));body.on('click','.jsForgotPwdTrigger, .jsRememberPwdTrigger',this.forgotFormToggle);body.on('click','#bUserlogoutLink',this.logoutLinkClickLog);if(showLoginFormLink.length){loginForm.hide();body.on('click','.jsShowLoginForm',this.showLoginForm);}}
Login.prototype.showError=function(msg,callback){var error=$('ul.error_list',this.form);if(callback!==undefined){callback();}
if(error.length){error.html('<li>'+msg+'</li>');}
else{$('.bFormLogin__ePlaceTitle',this.form).after($('<ul class="error_list" />').append('<li>'+msg+'</li>'));}
return false;};Login.prototype.formErrorHandler=function(formError){var validator=this.getFormValidator(),field=$('[name="'+this.getFormName()+'['+formError.field+']"]');var clearError=function clearError(){validator._unmarkFieldError($(this));};console.warn('Ошибка в поле');validator._markFieldError(field,formError.message);field.bind('focus',clearError);return false;};Login.serverErrorHandler={'default':function(res){console.log('Обработчик ошибки');if(!res.redirect){res.redirect=window.location.href;}
if(res.error&&res.error.message){this.showError(res.error.message,function(){document.location.href=res.redirect;});return false;}
document.location.href=res.redirect;},0:function(res){var formError=null;console.warn('Обработка ошибок формы');if(res.redirect){this.showError(res.error.message,function(){document.location.href=res.redirect;});return;}
if($('ul.error_list',this.form).length){$('ul.error_list',this.form).html('');}
for(var i=res.form.error.length-1;i>=0;i--){formError=res.form.error[i];console.warn(formError);if(formError.field!=='global'&&formError.message!==null){$.proxy(this.formErrorHandler,this)(formError);}
else if(formError.field==='global'&&formError.message!==null){this.showError(formError.message);}}
return false;}};Login.prototype.checkEmail=function(){return registerMailPhoneField.hasClass('jsRegisterPhone')?false:true;};Login.prototype.registerAnotherWay=function(){var label=$('.registerAnotherWay'),btn=$('.registerAnotherWayBtn');registerMailPhoneField.val('');if(this.checkEmail()){label.html('Ваш мобильный телефон:');btn.html('Ввести e-mail');registerMailPhoneField.addClass('jsRegisterPhone');registerValidator.setValidate(registerMailPhoneField,{validBy:'isPhone',customErr:'Некорректно введен телефон'});$.mask.definitions['n']='[0-9]';registerMailPhoneField.mask('+7 (nnn) nnn-nn-nn');}
else{label.html('Ваш e-mail:');btn.html('У меня нет e-mail');registerMailPhoneField.removeClass('jsRegisterPhone');registerValidator.setValidate(registerMailPhoneField,{validBy:'isEmail',customErr:'Некорректно введен e-mail'});registerMailPhoneField.unmask();}
return false;};Login.prototype.openAuth=function(){var
removeErrors=function(){var
validators=['signin','register','forgot'],validator,config,self,i,j;for(j in validators){validator=eval('ENTER.utils.'+validators[j]+'Validator');config=eval('ENTER.utils.'+validators[j]+'ValidationConfig');if(!config||!config.fields||!validator){continue;}
for(i in config.fields){self=config.fields[i].fieldNode;self&&validator._unmarkFieldError(self);}}};setValidatorSettings();authBlock.lightbox_me({centered:true,autofocus:true,onLoad:function(){authBlock.find('input:first').focus();},onClose:function(){removeErrors();authBlock.trigger('changeState',['default']);}});return false;};Login.prototype.submitBtnLoadingDisplay=function(btn){if(btn.length){var value1=btn.val(),value2=btn.data('loading-value');btn.attr('disabled',(btn.attr('disabled')==='disabled'?false:true)).val(value2).data('loading-value',value1);}
return false;};Login.prototype.getFormValidator=function(){return eval('ENTER.utils.'+this.getFormName()+'Validator');};Login.prototype.getFormName=function(){return(this.form.hasClass('jsLoginForm'))?'signin':(this.form.hasClass('jsRegisterForm')?'register':(this.form.hasClass('jsResetPwdForm')?'forgot':''));};Login.prototype.formSubmit=function(e,param){e.preventDefault();this.form=$(e.target);var formData=this.form.serializeArray(),validator=this.getFormValidator(),formSubmit=$('.jsSubmit',this.form),forgotPwdLogin=$('.jsForgotPwdLogin',this.form),urlParams=this.getUrlParams(),timeout;this.redirect_to=window.location.href;if(urlParams['redirect_to']){this.redirect_to=urlParams['redirect_to'];}
var responseFromServer=function(response){clearTimeout(timeout);if(response.error){console.warn('Form has error');if(Login.serverErrorHandler.hasOwnProperty(response.error.code)){console.log('Есть обработчик');$.proxy(Login.serverErrorHandler[response.error.code],this)(response);}
else{console.log('Стандартный обработчик');Login.serverErrorHandler['default'](response);}
this.submitBtnLoadingDisplay(formSubmit);return false;}
$.proxy(this.formSubmitLog,this);if(forgotPwdLogin.length&&forgotPwdLogin.is(':visible')){this.submitBtnLoadingDisplay(formSubmit);forgotPwdLogin.hide();$('.jsForgotPwdLoginLabel',this.form).hide();formSubmit.hide();this.showError(response.notice.message);}
console.log(this.form.data('redirect'));console.log(response.data.link);if(typeof(gaRun)!='undefined'&&typeof(gaRun.register)==='function'){gaRun.register();}
if(this.form.data('redirect')){if(typeof(response.data.link)!=='undefined'){console.info('try to redirect to2 '+response.data.link);console.log(typeof response.data.link);document.location.href=response.data.link.replace(/#.*$/,'');return false;}
else{completeRegister.html(response.message);completeRegister.show();registerForm.hide();this.showLoginForm();}}
else{authBlock.trigger('close');}
if($('#order-form').length){$('#user-block').html('Привет, <strong><a href="'+response.data.link+'">'+response.data.user.first_name+'</a></strong>');$('#order_recipient_first_name').val(response.data.user.first_name);$('#order_recipient_last_name').val(response.data.user.last_name);$('#order_recipient_phonenumbers').val(response.data.user.mobile_phone.slice(1));$('#qiwi_phone').val(response.data.user.mobile_phone.slice(1));}},requestToServer=function(){this.submitBtnLoadingDisplay(formSubmit);formData.push({name:'redirect_to',value:this.redirect_to});$.post(this.form.attr('action'),formData,$.proxy(responseFromServer,this),'json');timeout=setTimeout($.proxy(function(){document.location.href=this.redirect_to;},this),5000);};validator.validate({onInvalid:function(err){console.warn('invalid');console.log(err);},onValid:$.proxy(requestToServer,this)});return false;};Login.prototype.showLoginForm=function(){showLoginFormLink.hide();loginForm.slideDown(300);$.scrollTo(loginForm,500);};Login.prototype.forgotFormToggle=function(){if(resetPwdForm.is(':visible')){resetPwdForm.hide();loginForm.show();}
else{resetPwdForm.show();loginForm.hide();}
return false;};Login.prototype.formSubmitLog=function(){var type='';if(typeof(gaRun)&&typeof(gaRun.login)==='function'){gaRun.login();}
if('signin'===this.getFormName()){if(typeof(_gaq)!=='undefined'){type=((this.form.find('.jsSigninUsername').val().search('@'))!==-1)?'email':'mobile';_gaq.push(['_trackEvent','Account','Log in',type,window.location.href]);}
if(typeof(_kmq)!=='undefined'){_kmq.push(['identify',this.form.find('.jsSigninUsername').val()]);}}
else if('register'===this.getFormName()){if(typeof(_gaq)!=='undefined'){type=(this.checkEmail())?'email':'mobile';_gaq.push(['_trackEvent','Account','Create account',type]);}
if(typeof(_kmq)!=='undefined'){_kmq.push(['identify',this.form.find('.jsRegisterUsername').val()]);}}
else if('forgot'===this.getFormName()){if(typeof(_gaq)!=='undefined'){type=((this.form.find('.jsForgotPwdLogin').val().search('@'))!==-1)?'email':'mobile';_gaq.push(['_trackEvent','Account','Forgot password',type]);}}};Login.prototype.logoutLinkClickLog=function(){if(typeof(_kmq)!=='undefined'){_kmq.push(['clearIdentity']);}};Login.prototype.getUrlParams=function(){var $_GET={},__GET=window.location.search.substring(1).split('&'),getVar,i;for(i=0;i<__GET.length;i++){getVar=__GET[i].split('=');$_GET[getVar[0]]=typeof(getVar[1])==='undefined'?'':getVar[1];}
return $_GET;};return Login;}());$(document).ready(function(){var login=new ENTER.constructors.Login();});}(window.ENTER));
$(document).ready(function(){$('body').on('click','.bSubscibe',function(){if($(this).hasClass('checked')){$(this).removeClass('checked');$(this).find('.subscibe').removeAttr('checked');$(this).find('input[name="subscribe"]').val(0);}else{$(this).addClass('checked');$(this).find('.subscibe').attr('checked','checked');$(this).find('input[name="subscribe"]').val(1);}
return false;});function categoriesSpy(e){if(typeof(_gaq)!=='undefined'){_gaq.push(['_trackEvent','CategoryClick',e.data,window.location.pathname]);}
return true;}
$('.bMainMenuLevel-1__eLink').bind('click','Верхнее меню',categoriesSpy);$('.bMainMenuLevel-2__eLink').bind('click','Верхнее меню',categoriesSpy);$('.bMainMenuLevel-3__eLink').bind('click','Верхнее меню',categoriesSpy);$('.breadcrumbs').first().find('a').bind('click','Хлебные крошки сверху',categoriesSpy);$('.breadcrumbs-footer').find('a').bind('click','Хлебные крошки снизу',categoriesSpy);$('.bCtg__eMore').bind('click',function(e){e.preventDefault();var el=$(this);el.parent().find('li.hf').slideToggle();var link=el.find('a');link.text('еще...'==link.text()?'скрыть':'еще...');});$('.product_buy-container').each(function(){var order=$(this).data('order');if(typeof(order)=='object'&&!$.isEmptyObject(order)){$.ajax({url:($(this).data('url')),data:order,type:'POST',timeout:20000});}});if($('.searchtextClear').length){$('.searchtextClear').each(function(){if(!$(this).val().length){$(this).addClass('vh');}
else{$(this).removeClass('vh');}});$('.searchtextClear').click(function(){$(this).siblings('.searchtext').val('');$(this).addClass('vh');if($('#searchAutocomplete').length){$('#searchAutocomplete').html('');}});}
$('.enterPrizeDesc').click(function(){$(this).next('.enterPrizeListWrap').toggle('fast');});});
;(function($){var EnterPaginator=function(domID,totalPages,visPages,activePage){var self=this;self.inputVars={domID:domID,totalPages:totalPages,visPages:visPages?visPages:10,activePage:activePage?activePage:1};var pag=$('#'+self.inputVars.domID),pagW=pag.width(),eSliderFillW=(pagW*self.inputVars.visPages)/self.inputVars.totalPages,onePageOnSlider=eSliderFillW/self.inputVars.visPages,onePage=pagW/self.inputVars.visPages,center=Math.round(self.inputVars.visPages/2);var scrollingByBar=function scrollingByBar(left){var pagLeft=Math.round(left/onePageOnSlider);$('.bPaginator_eWrap',pag).css('left',-(onePage*pagLeft));};var enableHandlers=function enableHandlers(){var clicked=false,startX=0,nowLeft=0;$('.bPaginatorSlider',pag).bind('mousedown',function(e){startX=e.pageX;nowLeft=parseInt($('.bPaginatorSlider_eFill',pag).css('left'),10);clicked=true;});$('.bPaginatorSlider',pag).bind('mouseup',function(){clicked=false;});pag.bind('mouseout',function(){clicked=false;});$('.bPaginatorSlider',pag).bind('mousemove',function(e){if(clicked){var newLeft=nowLeft+(e.pageX-startX);if((newLeft>=0)&&(newLeft<=pagW-eSliderFillW)){$('.bPaginatorSlider_eFill',pag).css('left',nowLeft+(e.pageX-startX));scrollingByBar(newLeft);}}});};var init=function init(){pag.append('<div class="bPaginator_eWrap"></div>');pag.append('<div class="bPaginatorSlider"><div class="bPaginatorSlider_eWrap"><div class="bPaginatorSlider_eFill" style="width:'+eSliderFillW+'px"></div></div></div>');for(var i=0;i<self.inputVars.totalPages;i++){$('.bPaginator_eWrap',pag).append('<a class="bPaginator_eLink" href="#'+i+'">'+(i+1)+'</a>');if((i+1)===self.inputVars.activePage){$('.bPaginator_eLink',pag).eq(i).addClass('active');}}
var realLinkW=$('.bPaginator_eLink',pag).width();$('.bPaginator_eLink',pag).css({'marginLeft':(onePage-realLinkW-2)/2,'marginRight':(onePage-realLinkW-2)/2});$('.bPaginator_eWrap',pag).addClass('clearfix').width(onePage*self.inputVars.totalPages);};self.setActive=function(page){var left=parseInt($('.bPaginator_eWrap',pag).css('left'),10),barLeft=parseInt($('.bPaginatorSlider_eFill',pag).css('left'),10),nowLeftElH=Math.round(left/onePage)*(-1),diff=-(center-(page-nowLeftElH));$('.bPaginator_eLink',pag).removeClass('active');$('.bPaginator_eLink',pag).eq(page).addClass('active');if(left-(diff*onePage)>0){left=0;barLeft=0;}
else if(page>self.inputVars.totalPages-center){left=Math.round(self.inputVars.totalPages-self.inputVars.visPages)*onePage*(-1);barLeft=Math.round(self.inputVars.totalPages-self.inputVars.visPages)*onePageOnSlider;}
else{left=left-(diff*onePage);barLeft=barLeft+(diff*onePageOnSlider);}
$('.bPaginator_eWrap').animate({'left':left});$('.bPaginatorSlider_eFill',pag).animate({'left':barLeft});};init();enableHandlers();};if($('#promoCatalog').length){console.log('promoCatalog promoSlider');var
body=$('body'),promoCatalog=$('#promoCatalog'),data=promoCatalog.data('slides'),slider_SlideCount=data.length,catalogPaginator=new EnterPaginator('promoCatalogPaginator',slider_SlideCount,12,1),activeInterval=promoCatalog.data('use-interval')!==undefined?promoCatalog.data('use-interval'):false,interval=null,toSlide=0,nowSlide=0,activeHash=promoCatalog.data('use-hash')!==undefined?promoCatalog.data('use-hash'):true,hash,scrollingDuration=500,activeCarousel=promoCatalog.data('use-carousel')!==undefined?promoCatalog.data('use-carousel'):false,slideId,shift=0,slider_SlideW,slider_WrapW,disabledBtns=false,analyticsConfig=typeof promoCatalog.data('analytics-config')!=="undefined"?promoCatalog.data('analytics-config'):false,tchiboAnalyticsBuffer=[],categoryToken=typeof promoCatalog.data('category-token')!=="undefined"?promoCatalog.data('category-token'):'',documentHidden=false;var
initSlider=function initSlider(){var
slide,slideTmpl;if(activeCarousel){$('.bPromoCatalogSlider_eArrow.mArLeft').show();$('.bPromoCatalogSlider_eArrow.mArRight').show();}
for(slide=0;slide<data.length;slide++){slideTmpl=tmpl('slide_tmpl',data[slide]);if($(slideTmpl).length){slideTmpl=$(slideTmpl).attr("id",'slide_id_'+slide);}
$('.bPromoCatalogSliderWrap').append(slideTmpl);if($('.bPromoCatalogSliderWrap_eSlideLink').eq(slide).attr('href')===''){$('.bPromoCatalogSliderWrap_eSlideLink').eq(slide).removeAttr('href');}
$('.bPromoCatalogNav').append('<a id="promoCatalogSlide'+slide+'" href="#'+slide+'" class="bPromoCatalogNav_eLink">'+((slide*1)+1)+'</a>');}
slider_SlideW=$('.bPromoCatalogSliderWrap_eSlide').width();slider_WrapW=$('.bPromoCatalogSliderWrap').width(slider_SlideW*slider_SlideCount+(940/2-slider_SlideW/2));},setScrollInterval=function setScrollInterval(slide){var
time=3000,additionalTime=0;if(!activeInterval){return;}
if(slide==undefined){slide=0;}
else{additionalTime=scrollingDuration;}
if(data.hasOwnProperty(slide)&&data[slide].hasOwnProperty('time')){time=data[slide]['time'];}
time=time+additionalTime;interval=setTimeout(function(){slide++;if(!activeCarousel){if(slider_SlideCount<=slide){slide=0;}}
moveSlide(slide);setScrollInterval(slide);},time);},removeScrollInterval=function removeScrollInterval(){if(!interval){return;}
clearTimeout(interval);},btnsClick=function(e){var
pos=($(this).hasClass('mArLeft'))?'-1':'1',slide=nowSlide+pos*1;e.preventDefault();if(disabledBtns){return false;}
removeScrollInterval();moveSlide(slide);setScrollInterval(slide);},paginatorClick=function(e){var
link;e.preventDefault();if($(this).hasClass('active')){return false;}
if(disabledBtns){return false;}
link=$(this).attr('href').slice(1)*1;removeScrollInterval();if(activeCarousel){moveToSlideId(link);}
else{moveSlide(link);}
setScrollInterval(link);},moveToSlideId=function(id){var
slidesWrap=$(".jsPromoCatalogSliderWrap"),slides=$(".bPromoCatalogSliderWrap_eSlide",slidesWrap),slide;if(id===undefined){id=0;}
slide=slides.index($('#slide_id_'+id,slidesWrap));moveSlide(slide);},moveSlide=function moveSlide(slide){var
leftBtn=$('.bPromoCatalogSlider_eArrow.mArLeft'),rightBtn=$('.bPromoCatalogSlider_eArrow.mArRight'),slidesWrap=$(".jsPromoCatalogSliderWrap"),buff,slideData;var
moveLastSlideToStart=function(){var
slides=$(".bPromoCatalogSliderWrap_eSlide",slidesWrap);buff=slides.last();slides.last().remove();slidesWrap.prepend(buff);slidesWrap.css({left:slidesWrap.position().left-slider_SlideW});},moveFirstSlideToEnd=function(){var
slides=$(".bPromoCatalogSliderWrap_eSlide",slidesWrap);buff=slides.first();slides.first().remove();slidesWrap.append(buff);slidesWrap.css({left:slidesWrap.position().left+slider_SlideW});};slideId=slide;nowSlide=slide;if(!activeCarousel){if(slide===0)leftBtn.hide();else leftBtn.show();if(slide===slider_SlideCount-1)rightBtn.hide();else rightBtn.show();}
else{if(slide>slider_SlideCount-1){moveFirstSlideToEnd();shift++;slide=0;nowSlide=slider_SlideCount-1;}
else if(slide<0){moveLastSlideToStart();shift--;slide=slider_SlideCount-1;nowSlide=0;}
slideId=$(".jsPromoCatalogSliderWrap .bPromoCatalogSliderWrap_eSlide").eq(nowSlide).attr("id").replace('slide_id_','');}
disabledBtns=true;$('.bPromoCatalogSliderWrap').animate({'left':-(slider_SlideW*nowSlide)},scrollingDuration,function(){disabledBtns=false;});catalogPaginator.setActive(slideId);if(activeHash){window.location.hash='slide'+((slideId*1)+1);}
slideData=data[slideId];if((slideData.hasOwnProperty('title')&&slideData.hasOwnProperty('time'))&&tchiboAnalytics.checkRule('collection_view')){tchiboAnalytics.collectionShow(slideData.title,(slideId*1)+1,slideData.time);}},tchiboAnalytics={init:function(){if(!tchiboAnalytics.isAnalyticsEnabled){return;}
var
collectionClickHandler=function(){var
self=$(this),slide=self.parent('.bPromoCatalogSliderWrap_eSlide'),slideId,slideData;if(!slide.length||!slide.attr('id')){return;}
slideId=slide.attr('id').replace('slide_id_','');slideData=data[slideId];if(slideData.hasOwnProperty('title')){tchiboAnalytics.collectionClick(slideData.title,(slideId*1)+1);}},productClickHandler=function(){var
self=$(this),slide=self.parents('.bPromoCatalogSliderWrap_eSlide'),slideElementId,slideId,slideData,productIndex;if(!slide.length||!slide.attr('id')){return;}
slideElementId=slide.attr('id');slideId=slideElementId.replace('slide_id_','');slideData=data[slideId];productIndex=$('.mTchiboSlider #'+slideElementId+' .prodItem > a').index(this);if(-1==productIndex){return;}
if(slideData.hasOwnProperty('title')&&undefined!=typeof(slideData.products[productIndex].name)){tchiboAnalytics.productClick(slideData.title,slideData.products[productIndex].name,(productIndex*1)+1);}};if(tchiboAnalytics.checkRule('collection_click')){body.on('click','.mTchiboSlider .bPromoCatalogSliderWrap_eSlideLink',collectionClickHandler);}
if(tchiboAnalytics.checkRule('product_click')){body.on('click','.mTchiboSlider .prodItem > a',productClickHandler);}
tchiboAnalytics.pageVisibility();},pageVisibility:function(){var
hidden,visibilityChange;var
handleVisibilityChange=function(){documentHidden=document[hidden]?true:false;};if(!tchiboAnalytics.isAnalyticsEnabled||!analyticsConfig.hasOwnProperty('use_page_visibility')||true!=analyticsConfig.use_page_visibility){return;}
if(typeof document.hidden!=="undefined"){hidden="hidden";visibilityChange="visibilitychange";}else if(typeof document.mozHidden!=="undefined"){hidden="mozHidden";visibilityChange="mozvisibilitychange";}else if(typeof document.msHidden!=="undefined"){hidden="msHidden";visibilityChange="msvisibilitychange";}else if(typeof document.webkitHidden!=="undefined"){hidden="webkitHidden";visibilityChange="webkitvisibilitychange";}
handleVisibilityChange();if(typeof document.addEventListener==="undefined"||typeof hidden==="undefined"){}else{document.addEventListener(visibilityChange,handleVisibilityChange,false);}},collectionShow:function(collection_name,collection_position,delay){},collectionClick:function(collection_name,collection_position){var item;if(!tchiboAnalytics.isAnalyticsEnabled||'undefined'==typeof(_gaq)||'undefined'==typeof(collection_name)||'undefined'==typeof(collection_position)){return;}
item=['_trackEvent','collection_click',collection_name+'_'+collection_position]
console.info('TchiboSliderAnalytics collection_click');console.log(item);_gaq.push(item);},productClick:function(collection_name,item_name,position){var item;if(!tchiboAnalytics.isAnalyticsEnabled||'undefined'==typeof(_gaq)||'undefined'==typeof(collection_name)||'undefined'==typeof(item_name)||'undefined'==typeof(position)){return;}
item=['_trackEvent','item_click',collection_name+'_'+item_name,position.toString()];console.info('TchiboSliderAnalytics item_click');console.log(item);_gaq.push(item);},isAnalyticsEnabled:function(){return analyticsConfig&&analyticsConfig.hasOwnProperty('enabled')&&true==analyticsConfig.enabled;},checkRule:function(rule){if(tchiboAnalytics.isAnalyticsEnabled&&typeof rule!=="undefined"&&analyticsConfig.hasOwnProperty(rule)&&true==analyticsConfig[rule].enabled&&((true==analyticsConfig[rule].tchiboOnly&&'tchibo'===categoryToken)||(true!=analyticsConfig[rule].tchiboOnly))){return true;}
return false;}};initSlider();tchiboAnalytics.init();body.on('click','.bPromoCatalogSlider_eArrow',btnsClick);body.on('click','.bPaginator_eLink',paginatorClick);if(activeHash){hash=window.location.hash;if(hash.indexOf('slide')+1){toSlide=parseInt(hash.slice(6),10)-1;moveSlide(toSlide);}}
setScrollInterval(toSlide);if(data.hasOwnProperty(toSlide)&&data[toSlide].hasOwnProperty('title')&&data[toSlide].hasOwnProperty('time')&&tchiboAnalytics.checkRule('collection_view')){tchiboAnalytics.collectionShow(data[toSlide].title,((toSlide*1)+1),data[toSlide].time);}}})(jQuery);
;(function(){var authBlock;$.ajaxSetup({error:function(jqXHR,textStatus,errorThrown){if(403==jqXHR.status){authBlock=$('#auth-block');if(!authBlock.length){return;}
authBlock.lightbox_me({centered:true,autofocus:true,onLoad:function(){authBlock.find('input:first').focus();}});}}});}());
;(function(){var
body=$('body'),subscribeCookieName='subscribed';var
lboxCheckSubscribe=function lboxCheckSubscribe(event){var
notNowShield=$('.bSubscribeLightboxPopupNotNow'),subPopup=$('.bSubscribeLightboxPopup'),input=$('.bSubscribeLightboxPopup__eInput'),submitBtn=$('.bSubscribeLightboxPopup__eBtn'),subscribe={'show':!window.docCookies.hasItem(subscribeCookieName),'agreed':1===window.docCookies.getItem(subscribeCookieName)},inputValidator=new FormValidator({fields:[{fieldNode:input,customErr:'Неправильный емейл',require:true,validBy:'isEmail'}]});var
subscribing=function subscribing(){var
email=input.val(),url=$(this).data('url');var
serverResponseHandler=function serverResponseHandler(res){if(!res.success){return false;}
subPopup.html('<span class="bSubscribeLightboxPopup__eTitle mType">Спасибо! подтверждение подписки отправлено на указанный e-mail</span>');window.docCookies.setItem('subscribed',1,157680000,'/');setTimeout(function(){subPopup.slideUp(300);},3000);if(typeof _gaq!=='undefined'){_gaq.push(['_trackEvent','Account','Emailing sign up','Page top']);}};if(submitBtn.hasClass('mDisabled')){return false;}
inputValidator.validate({onInvalid:function(err){console.log('Email is invalid');console.log(err);},onValid:function(){console.log('Email is valid');$.post(url,{email:email},serverResponseHandler);}});return false;},subscribeNow=function subscribeNow(){var
notNow=$('.bSubscribeLightboxPopup__eNotNow');var
notNowClickHandler=function(e){e.preventDefault();var url=$(this).data('url');subPopup.slideUp(300,subscribeLater);window.docCookies.setItem('subscribed',0,157680000,'/');$.post(url);};subPopup.slideDown(300);submitBtn.bind('click',subscribing);notNow.off('click');notNow.bind('click',notNowClickHandler);},subscribeLater=function subscribeLater(){notNowShield.slideDown(300);notNowShield.bind('click',function(){$(this).slideUp(300);subscribeNow();});};input.placeholder();if(!subscribe.show){if(!subscribe.agreed){subscribeLater();}
return false;}
else{subscribeNow();}};body.bind('showsubscribe',lboxCheckSubscribe);body.trigger('showsubscribe');}());
;(function(){$('.js-siteVersionSwitcher').click(function(e){e.preventDefault();var domain=window.location.host;var domainParts=domain.split(".");if(domainParts.length>2){domain=domainParts[domainParts.length-2]+"."+domainParts[domainParts.length-1];}
var config=$(e.currentTarget).data('config');document.cookie=config.cookieName+"=1; expires="+(new Date(Date.now()+config.cookieLifetime*1000)).toUTCString()+"; domain="+domain+"; path=/";location=e.currentTarget.href;});}());
;(function(){var
body=$('body'),searchForm=$('div.searchbox form'),searchInput=searchForm.find('input.searchtext'),suggestWrapper=$('#searchAutocomplete'),suggestItem=$('.bSearchSuggest__eRes'),nowSelectSuggest=-1,suggestLen=0,suggestCache={},tID=null;var
suggestAnalytics=function suggestAnalytics(){var
link=suggestItem.eq(nowSelectSuggest).attr('href'),type=(suggestItem.eq(nowSelectSuggest).hasClass('bSearchSuggest__eCategoryRes'))?'suggest_category':'suggest_product';if(typeof(_gaq)!=='undefined'){_gaq.push(['_trackEvent','Search',type,link]);}},loadResponse=function loadResponse(){var
text=searchInput.val(),renderResponse=function renderResponse(response){if(!response.success){return;}
suggestCache[text]=response.content;suggestWrapper.html(response.content);suggestItem=$('.bSearchSuggest__eRes');suggestLen=suggestItem.length;if(suggestLen){setTimeout(searchInputFocusin,99);}},getResFromServer=function getResFromServer(){var
url='/search/autocomplete?q=';if(text.length<3){return false;}
url+=encodeURI(text);$.ajax({type:'GET',url:url,success:renderResponse});};if(text.length===0){suggestWrapper.empty();return false;}
clearTimeout(tID);if(suggestCache[text]){renderResponse(suggestCache[text]);return false;}
tID=setTimeout(getResFromServer,300);},escapeSearchQuery=function escapeSearchQuery(){var s=searchInput.val().replace(/(^\s*)|(\s*$)/g,'').replace(/(\s+)/g,' ');searchInput.val(s);}
suggestKeyUp=function suggestKeyUp(event){var
keyCode=event.which;if((keyCode>=37&&keyCode<=40)||keyCode===27||keyCode===13){return false;}
loadResponse();},suggestKeyDown=function suggestKeyDown(event){var
keyCode=event.which;var
markSuggestItem=function markSuggestItem(){suggestItem.removeClass('hover').eq(nowSelectSuggest).addClass('hover');},selectUpItem=function selectUpItem(){if(nowSelectSuggest-1>=0){nowSelectSuggest--;markSuggestItem();}
else{nowSelectSuggest=-1;suggestItem.removeClass('hover');$(this).focus();}},selectDownItem=function selectDownItem(){if(nowSelectSuggest+1<=suggestLen-1){nowSelectSuggest++;markSuggestItem();}},enterSelectedItem=function enterSelectedItem(){var link=suggestItem.eq(nowSelectSuggest).attr('href');suggestAnalytics();document.location.href=link;};if(keyCode===38){selectUpItem();return false;}
else if(keyCode===40){selectDownItem();return false;}
else if(keyCode===27){suggestWrapper.empty();return false;}
else if(keyCode===13){escapeSearchQuery();if(nowSelectSuggest!==-1){enterSelectedItem();return false;}}},searchSubmit=function searchSubmit(){var text=searchInput.attr('value');if(text.length===0){return false;}
escapeSearchQuery();},searchInputFocusin=function searchInputFocusin(){suggestWrapper.show();},suggestCloser=function suggestCloser(e){var
targ=e.target.className;if(!(targ.indexOf('bSearchSuggest')+1||targ.indexOf('searchtext')+1)){suggestWrapper.hide();}},hoverForItem=function hoverForItem(){var index=0;suggestItem.removeClass('hover');index=$(this).addClass('hover').index();nowSelectSuggest=index-1;},searchHintSelect=function searchHintSelect(){var
hintValue=$(this).text();searchInput.val(hintValue+' ').focus();if(typeof(_gaq)!=='undefined'){_gaq.push(['_trackEvent','tooltip',hintValue]);}
loadResponse();};$(document).ready(function(){searchInput.bind('keydown',suggestKeyDown);searchInput.bind('keyup',suggestKeyUp);searchInput.bind('focus',searchInputFocusin);searchForm.bind('submit',searchSubmit);searchInput.placeholder();body.bind('click',suggestCloser);body.on('mouseenter','.bSearchSuggest__eRes',hoverForItem);body.on('click','.bSearchSuggest__eRes',suggestAnalytics);body.on('click','.sHint_value',searchHintSelect);});}());
;(function(){if(/catalog\/tchibo/.test(document.location.href)&&window.history){var history=window.history;$(window).on('beforeunload',function(){history.replaceState({pageYOffset:pageYOffset},'');});if(history&&history.state.pageYOffset){window.scrollTo(0,history.state.pageYOffset);}}}());
(function(){var menuDelayLvl1=300;var menuDelayLvl2=600;var triangleOffset=15;var lastHoverLvl1=null;var checkedItemLvl1=null;var hoverNowLvl1=false;var lastHoverLvl2=null;var checkedItemLvl2=null;var currentMenuItemDimensions=null;var menuLevel2Dimensions=null;var menuLevel3Dimensions=null;var pointA={x:0,y:0};var pointB={x:0,y:0};var pointC={x:0,y:0};var cursorNow={x:0,y:0};var activateItemLvl1=function(el){lastHoverLvl1=new Date();checkedItemLvl1=el;$('.bMainMenuLevel-2__eItem').removeClass('hover');el.addClass('hover');};var menuHoverInLvl1=function(){var el=$(this);if(el.hasClass('jsEmptyChild')){return;}
lastHoverLvl1=new Date();hoverNowLvl1=true;setTimeout(function(){if(hoverNowLvl1&&(new Date()-lastHoverLvl1>menuDelayLvl1)){activateItemLvl1(el);}},menuDelayLvl1+20);el.find('.lazyMenuImg').each(function(i,elem){var $el=$(elem);$el.attr('src',$el.data('src'))})};var menuMouseLeaveLvl1=function(){var el=$(this);el.removeClass('hover');hoverNowLvl1=false;};var createTriangle=function(){pointA={x:cursorNow.x,y:cursorNow.y-$(window).scrollTop()};pointB={x:menuLevel3Dimensions.left-triangleOffset,y:menuLevel3Dimensions.top-$(window).scrollTop()};pointC={x:menuLevel3Dimensions.left-triangleOffset,y:menuLevel3Dimensions.top+menuLevel3Dimensions.height-$(window).scrollTop()};};var menuCheckTriangle=function(){var res1=(pointA.x-cursorNow.x)*(pointB.y-pointA.y)-(pointB.x-pointA.x)*(pointA.y-cursorNow.y);var res2=(pointB.x-cursorNow.x)*(pointC.y-pointB.y)-(pointC.x-pointB.x)*(pointB.y-cursorNow.y);var res3=(pointC.x-cursorNow.x)*(pointA.y-pointC.y)-(pointA.x-pointC.x)*(pointC.y-cursorNow.y);if((res1>=0&&res2>=0&&res3>=0)||(res1<=0&&res2<=0&&res3<=0)||(cursorNow.x>=pointB.x&&cursorNow.x<=(pointB.x+triangleOffset)&&cursorNow.y>=pointB.y&&cursorNow.y<=pointC.y)){return true;}else{return false;}};var menuMoveLvl2=function(e){cursorNow={x:e.pageX,y:e.pageY-$(window).scrollTop()};var el=$(this);if(checkedItemLvl2){if(el.attr('class')===checkedItemLvl2.attr('class')){buildTriangle(el);lastHoverLvl2=new Date();}}
checkHoverLvl2(el);};var activateItemLvl2=function(el){checkedItemLvl2=el;el.addClass('hover');lastHoverLvl2=new Date();buildTriangle(el);};var menuHoverInLvl2=function(){var el=$(this);checkHoverLvl2(el);el.addClass('hoverNowLvl2');if(lastHoverLvl2&&(new Date()-lastHoverLvl2<=menuDelayLvl2)&&menuCheckTriangle()){setTimeout(function(){if(el.hasClass('hoverNowLvl2')&&(new Date()-lastHoverLvl2>menuDelayLvl2)){checkHoverLvl2(el);}},menuDelayLvl2+20);}};var menuMouseLeaveLvl2=function(){var el=$(this);el.removeClass('hoverNowLvl2');};var checkHoverLvl2=function(el){if(!lastHoverLvl2){activateItemLvl2(el);}else if(!menuCheckTriangle()||(lastHoverLvl2&&(new Date()-lastHoverLvl2>menuDelayLvl2)&&menuCheckTriangle())){checkedItemLvl2.removeClass('hover');activateItemLvl2(el);}};var buildTriangle=function(el){currentMenuItemDimensions=getDimensions(el);menuLevel2Dimensions=getDimensions(el.find('.bMainMenuLevel-3'));var dropMenuWidth=el.find('.bMainMenuLevel-2__eTitle')[0].offsetWidth;menuLevel3Dimensions={top:menuLevel2Dimensions.top,left:menuLevel2Dimensions.left+dropMenuWidth,width:menuLevel2Dimensions.width-dropMenuWidth,height:menuLevel2Dimensions.height};createTriangle();};var getDimensions=function(el){var width=$(el).width();var height=$(el).height();el=el[0];var x=0;var y=0;while(el&&!isNaN(el.offsetLeft)&&!isNaN(el.offsetTop)){x+=el.offsetLeft-el.scrollLeft;y+=el.offsetTop-el.scrollTop;el=el.offsetParent;}
return{top:y,left:x,width:width,height:height};};$('.bMainMenuLevel-1__eItem').mouseenter(menuHoverInLvl1);$('.bMainMenuLevel-1__eItem').mouseleave(menuMouseLeaveLvl1);$('.bMainMenuLevel-2__eItem').mouseenter(menuHoverInLvl2);$('.bMainMenuLevel-2__eItem').mousemove(menuMoveLvl2);$('.bMainMenuLevel-2__eItem').mouseleave(menuMouseLeaveLvl2);})();
;(function(){var upper=$('#upper'),trigger=false;var pageScrolling=function pageScrolling(){if($(window).scrollTop()>600&&!trigger){trigger=true;upper.animate({'marginTop':'0'},400);}
else if($(window).scrollTop()<600&&trigger){trigger=false;upper.animate({'marginTop':'-55px'},400);}},goUp=function goUp(){$(window).scrollTo('0px',400);return false;};$(window).scroll(pageScrolling);upper.bind('click',goUp);}());
;(function(ENTER){var
utils=ENTER.utils,userBar=utils.extendApp('ENTER.userBar'),userBarFixed=userBar.userBarFixed=$('.topbarfix-fx'),userbarStatic=userBar.userBarStatic=$('.topbarfix-stc'),topBtn=userBarFixed.find('.topbarfix_upLink'),userbarConfig=userBarFixed.data('value'),body=$('body'),w=$(window),infoShowing=false,overlay=$('<div>').css({position:'fixed',display:'none',width:'100%',height:'100%',top:0,left:0,zIndex:900,background:'black',opacity:0.4}),newOverlay=false,scrollTarget,scrollTargetOffset;userBar.showOverlay=false;var
showUserbar=function showUserbar(){console.log('showUserbar');userBarFixed.slideDown();userbarStatic.css('visibility','hidden');},hideUserbar=function hideUserbar(){console.log('hideUserbar');userBarFixed.slideUp();userbarStatic.css('visibility','visible');},checkScroll=function checkScroll(){var
nowScroll=w.scrollTop();if(infoShowing){return;}
if(nowScroll>=scrollTargetOffset){showUserbar();}
else{hideUserbar();}},upToFilter=function upToFilter(){$.scrollTo(scrollTarget,500);ENTER.catalog.filter.openFilter();return false;},closeBuyInfo=function closeBuyInfo(){var
wrap=userBarFixed.find('.topbarfix_cart'),wrapLogIn=userBarFixed.find('.topbarfix_log'),openClass='mOpenedPopup',upsaleWrap=wrap.find('.hintDd');var
removeBuyInfoBlock=function removeBuyInfoBlock(){var
buyInfo=$('.topbarfix_cartOn');if(!buyInfo.length){return;}
buyInfo.slideUp(300,function(){infoShowing=false;});},removeOverlay=function removeOverlay(){overlay.fadeOut(100,function(){userBar.showOverlay=false;if(newOverlay){newOverlay=false;return;}
overlay.off('click');overlay.remove();userBar.showOverlay=false;checkScroll();});};if(!upsaleWrap.hasClass('mhintDdOn')){removeBuyInfoBlock();if(userBar.showOverlay){removeOverlay();}
return;}
upsaleWrap.removeClass('mhintDdOn');wrapLogIn.removeClass(openClass);wrap.removeClass(openClass);if(infoShowing){removeBuyInfoBlock();}
if(userBar.showOverlay){removeOverlay();}
return false;},showBuyInfo=function showBuyInfo(e){console.info('userbar::showBuyInfo');var	buyInfo=$('.topbarfix_cartOn');if(!userBar.showOverlay){body.append(overlay);overlay.fadeIn(300);userBar.showOverlay=true;}
if(e){buyInfo.slideDown(300);}
else{buyInfo.show();}
showUserbar();infoShowing=true;overlay.on('click',closeBuyInfo);},deleteProductHandler=function deleteProductHandler(){console.log('deleteProductHandler click!');var
btn=$(this),deleteUrl=btn.attr('href');var
deleteFromRutarget=function deleteFromRutarget(data){var
region=$('.jsChangeRegion'),regionId=region.length?region.data('region-id'):false,result,_rutarget=window._rutarget||[];if(!regionId||!data.hasOwnProperty('product')||!data.product.hasOwnProperty('id')){return;}
result={'event':'removeFromCart','sku':data.product.id,'regionId':regionId};console.info('RuTarget removeFromCart');console.log(result);_rutarget.push(result);},deleteFromLamoda=function deleteFromLamoda(data){if('undefined'==typeof(JSREObject)||!data.hasOwnProperty('product')||!data.product.hasOwnProperty('id')){return;}
console.info('Lamoda removeFromCart');console.log('product_id='+data.product.id);JSREObject('cart_remove',data.product.id);},deleteFromRetailRocket=function deleteFromRetailRocket(data){if(!data.hasOwnProperty('product')||!data.product.hasOwnProperty('id')){return;}
console.info('RetailRocket removeFromCart');console.log('product_id='+data.product.id);window.rrApiOnReady.push(function(){window.rrApi.removeFromBasket(data.product.id)});},deleteProductAnalytics=function deleteProductAnalytics(data){if('undefined'==typeof(data)){return;}
deleteFromRetailRocket(data);deleteFromRutarget(data);deleteFromLamoda(data);},authFromServer=function authFromServer(res,data){console.warn(res);if(!res.success){console.warn('удаление не получилось :(');return;}
deleteProductAnalytics(res);ENTER.UserModel.cart.remove(function(item){return item.id==res.product.id});if(ENTER.UserModel.cart().length!==0){showBuyInfo();}
if(ENTER.UserModel.cart().length==0){overlay.fadeOut(300,function(){overlay.off('click');overlay.remove();userBar.showOverlay=false;});infoShowing=false;checkScroll();}
var
addUrl=res.product.addUrl;addBtnBuy=res.product.cartButton.id;$('.'+addBtnBuy).html('Купить').removeClass('mBought').attr('href',addUrl);};$.ajax({type:'GET',url:deleteUrl,success:authFromServer});return false;},showUpsell=function showUpsell(event,data,upsale){console.info('userbar::showUpsell');var
cartWrap=userBarFixed.find('.topbarfix_cart'),upsaleWrap=cartWrap.find('.hintDd'),slider;var
responseFromServer=function responseFromServer(response){console.log(response);if(!response.success){return;}
console.info('Получены рекомендации "С этим товаром также покупают" от RetailRocket');upsaleWrap.find('.bGoodsSlider').remove();slider=$(response.content)[0];upsaleWrap.append(slider);upsaleWrap.addClass('mhintDdOn');$(slider).goodsSlider();ko.applyBindings(ENTER.UserModel,slider);body.append(overlay);newOverlay=true;overlay.fadeIn(300);overlay.on('click',closeBuyInfo);userBar.showOverlay=true;if(!data.product)return;if(!data.product.article){console.warn('Не получен article продукта');return;}
console.log('Трекинг товара при показе блока рекомендаций');if(response.data){try{rrApi.recomTrack(response.data.method,response.data.id,response.data.recommendations);}catch(e){console.warn('showUpsell() Retailrocket error');console.log(e);}}
typeof _gaq=='function'&&_gaq.push(['_trackEvent','cart_recommendation','cart_rec_shown',data.product.article]);typeof _kmq=='function'&&_kmq.push(['record','cart recommendation shown',{'SKU cart rec shown':data.product.article}]);};console.log(upsale);if(!upsale.url){console.log('if upsale.url');return;}
$.ajax({type:'GET',url:upsale.url,success:responseFromServer});},upsaleProductClick=function upsaleProductClick(){var
product=$(this).parents('.jsSliderItem').data('product');if(!product.article){console.warn('Не получен article продукта');return;}
console.log('Трекинг при клике по товару из списка рекомендаций');_gaq&&_gaq.push(['_trackEvent','cart_recommendation','cart_rec_clicked',product.article]);_kmq&&_kmq.push(['record','cart recommendation clicked',{'SKU cart rec clicked':product.article}]);};console.info('Init userbar module');console.log(userbarConfig);body.on('click','.jsUpsaleProduct',upsaleProductClick);body.on('getupsale',showUpsell);userbarStatic.on('click','.jsCartDelete',deleteProductHandler);if(userBarFixed.length){body.on('addtocart',showBuyInfo);userBarFixed.on('click','.jsCartDelete',deleteProductHandler);scrollTarget=$(userbarConfig.target);if(topBtn.length){topBtn.on('click',upToFilter);}
if(scrollTarget.length){scrollTargetOffset=scrollTarget.offset().top+userBarFixed.height()-scrollTarget.height();w.on('scroll',checkScroll);}}
else{overlay.remove();overlay=false;}}(window.ENTER));
//@ sourceMappingURL=common.js.map