
;$(function(){$('.js-product-3d-html5-opener').bind('click',function(e){e.preventDefault();$LAB.script('/maybe3dPlayer/player.min.js').wait(function(){$('.js-product-3d-html5-popup').lightbox_me({centered:true,closeSelector:'.jsPopupCloser',onLoad:function(){var $popup=$('.js-product-3d-html5-popup');Maybe3D.Starter.setModelPathHTML5($popup.data('url'));Maybe3D.Starter.embed($popup.data('id'),'js-product-3d-html5-popup-model');},onClose:function(){$('#js-product-3d-html5-popup-model').empty();}});});});$('.js-product-3d-swf-opener').bind('click',function(e){e.preventDefault();$LAB.script('swfobject.min.js').wait(function(){try{if(!$('#js-product-3d-swf-popup-model').length){$('.js-product-3d-swf-popup-container').append('<div id="js-product-3d-swf-popup-model"></div>');}
var
swfId='js-product-3d-swf-popup-object',$popup=$('.js-product-3d-swf-popup');swfobject.embedSWF($popup.data('url'),'js-product-3d-swf-popup-model','700px','500px','10.0.0','js/vendor/expressInstall.swf',{language:'auto'},{menu:'false',scale:'noScale',allowFullscreen:'true',allowScriptAccess:'always',wmode:'direct'},{id:swfId});$popup.lightbox_me({centered:true,closeSelector:'.jsPopupCloser',onClose:function(){swfobject.removeSWF(swfId);}});}
catch(err){}});});$('.js-product-3d-img-opener').bind('click',function(e){e.preventDefault();$LAB.script('DAnimFramePlayer.min.js').wait(function(){var
$element=$('.js-product-3d-img-popup'),data=$element.data('value'),host=$element.data('host');try{if(!$('#js-product-3d-img-container').length){(new DAnimFramePlayer($element[0],host)).DoLoadModel(data);}
$element.lightbox_me({centered:true,closeSelector:'.jsPopupCloser'});}
catch(err){}});});});
+function($){'use strict';function ScrollSpy(element,options){this.$body=$(document.body)
this.$scrollElement=$(element).is(document.body)?$(window):$(element)
this.options=$.extend({},ScrollSpy.DEFAULTS,options)
this.selector=(this.options.target||'')+' .nav li > a'
this.offsets=[]
this.targets=[]
this.activeTarget=null
this.scrollHeight=0
this.$scrollElement.on('scroll.bs.scrollspy',$.proxy(this.process,this))
this.refresh()
this.process()}
ScrollSpy.VERSION='3.3.4'
ScrollSpy.DEFAULTS={offset:10}
ScrollSpy.prototype.getScrollHeight=function(){return this.$scrollElement[0].scrollHeight||Math.max(this.$body[0].scrollHeight,document.documentElement.scrollHeight)}
ScrollSpy.prototype.refresh=function(){var that=this
var offsetMethod='offset'
var offsetBase=0
this.offsets=[]
this.targets=[]
this.scrollHeight=this.getScrollHeight()
if(!$.isWindow(this.$scrollElement[0])){offsetMethod='position'
offsetBase=this.$scrollElement.scrollTop()}
this.$body.find(this.selector).map(function(){var $el=$(this)
var href=$el.data('target')||$el.attr('href')
var $href=/^#./.test(href)&&$(href)
return($href&&$href.length&&$href.is(':visible')&&[[$href[offsetMethod]().top+offsetBase,href]])||null}).sort(function(a,b){return a[0]-b[0]}).each(function(){that.offsets.push(this[0])
that.targets.push(this[1])})}
ScrollSpy.prototype.process=function(){var scrollTop=this.$scrollElement.scrollTop()+this.options.offset
var scrollHeight=this.getScrollHeight()
var maxScroll=this.options.offset+scrollHeight-this.$scrollElement.height()
var offsets=this.offsets
var targets=this.targets
var activeTarget=this.activeTarget
var i
if(this.scrollHeight!=scrollHeight){this.refresh()}
if(scrollTop>=maxScroll){return activeTarget!=(i=targets[targets.length-1])&&this.activate(i)}
if(activeTarget&&scrollTop<offsets[0]){this.activeTarget=null
return this.clear()}
for(i=offsets.length;i--;){activeTarget!=targets[i]&&scrollTop>=offsets[i]&&(offsets[i+1]===undefined||scrollTop<offsets[i+1])&&this.activate(targets[i])}}
ScrollSpy.prototype.activate=function(target){this.activeTarget=target
this.clear()
var selector=this.selector+'[data-target="'+target+'"],'+
this.selector+'[href="'+target+'"]'
var active=$(selector).parents('li').addClass('active')
if(active.parent('.dropdown-menu').length){active=active.closest('li.dropdown').addClass('active')}
active.trigger('activate.bs.scrollspy')}
ScrollSpy.prototype.clear=function(){$(this.selector).parentsUntil(this.options.target,'.active').removeClass('active')}
function Plugin(option){return this.each(function(){var $this=$(this)
var data=$this.data('bs.scrollspy')
var options=typeof option=='object'&&option
if(!data)$this.data('bs.scrollspy',(data=new ScrollSpy(this,options)))
if(typeof option=='string')data[option]()})}
var old=$.fn.scrollspy
$.fn.scrollspy=Plugin
$.fn.scrollspy.Constructor=ScrollSpy
$.fn.scrollspy.noConflict=function(){$.fn.scrollspy=old
return this}
$(window).on('load.bs.scrollspy.data-api',function(){$('[data-spy="scroll"]').each(function(){var $spy=$(this)
Plugin.call($spy,$spy.data())})})}(jQuery);
;(function(){var creditBoxNode=$('.creditbox');if(creditBoxNode.length>0){var	$body=$(document.body),priceNode=creditBoxNode.find('.creditbox__sum strong');window.creditBox={init:function(){var	creditd=$('input[name=dc_buy_on_credit]').data('model'),label=creditBoxNode.find('label');$('.jsProductCreditRadio').on('change',function(){var status=$(this).val(),$link=$('.js-WidgetBuy .jsBuyButton');if($link.length>0){$link.attr('href',ENTER.utils.setURLParam('credit',status,$link.attr('href')));$link.attr('href',ENTER.utils.setURLParam('sender2','credit',$link.attr('href')));}});if(typeof window.dc_getCreditForTheProduct=='function')dc_getCreditForTheProduct(4427,window.docCookies.getItem('enter_auth'),'getPayment',{price:creditd.price,count:1,type:creditd.product_type},function(result){if(!'payment'in result){return;}
if(result.payment>0){priceNode.html(printPrice(Math.ceil(result.payment)));creditBoxNode.show();}});}};$body.on('userLogged',function(e,data){if($.isArray(data.cartProducts)){var product_id=$('#jsProductCard').data('value')['id'];$.each(data.cartProducts,function(i,val){if(val['isCredit']&&val['id']==product_id){$('#creditinput').attr('checked',true).trigger('change')}})}});$body.on('click','.jsProductCreditRadio',function(){$body.trigger('trackGoogleEvent',['Credit','Выбор опции','Карточка товара']);});creditBox.init();}
else{var	productDesc=$('.bProductDesc');if(productDesc.length&&!productDesc.hasClass('mNoCredit')){productDesc.addClass('mNoCredit');}}}());
(function(){$('.js-show-shops').on('click',function(){var popup=$('.shopsPopup'),buyButtons=$('.shopsPopup .jsBuyButton');popup.lightbox_me({centered:true,autofocus:true});buyButtons.on('click',function(){popup.trigger('close')});});}());
;(function(){var initFotoSlider=function(){var slider=$('.js-photoslider');var fotoBox=slider.find('.js-photoslider-gal');var leftArr=slider.find('.js-photoslider-btn-prev');var rightArr=slider.find('.js-photoslider-btn-next');var photos=fotoBox.find('.js-photoslider-gal-i');if(!photos.length){return false;}
var itemW=photos.width()+parseInt(photos.css('marginLeft'),10)+parseInt(photos.css('marginRight'),10);var nowLeft=0;fotoBox.css({'width':photos.length*itemW,'left':nowLeft});var checkArrow=function(){if(nowLeft>0){leftArr.show();}
else{leftArr.hide();}
if(nowLeft<fotoBox.width()-slider.width()){rightArr.show();}
else{rightArr.hide();}};var prevFoto=function(){nowLeft=nowLeft-itemW;fotoBox.animate({'left':-nowLeft});checkArrow();return false;};var nextFoto=function(){nowLeft=nowLeft+itemW;fotoBox.animate({'left':-nowLeft});checkArrow();return false;};checkArrow();leftArr.bind('click',prevFoto);rightArr.bind('click',nextFoto);};$(document).ready(function(){if($('.js-photoslider').length){initFotoSlider();}});})();
(function(){var hintShower=function(){var hintPopup=$('.bHint_ePopup');var hintLnk=$('.bHint_eLink');var hintCloseLnk=$('.bHint_ePopup .close');var hintAnalytics=function(data){if(typeof(_gaq)!=='undefined'){_gaq.push(['_trackEvent','Hints',data.hintTitle,data.url]);}};var hintShow=function(){hintPopup.hide();$(this).parent().find('.bHint_ePopup').fadeIn(150);var analyticsData={hintTitle:$(this).html(),url:window.location.href};hintAnalytics(analyticsData);return false;};var hintClose=function(){hintPopup.fadeOut(150);return false;};hintLnk.bind('click',hintShow);hintCloseLnk.bind('click',hintClose);};$(document).ready(function(){if($('.bHint').length){hintShower();}});}());
;(function(global){global.Planner3dKupeConstructor=null;global.Planner3d_Init=function(ApiIds){};global.Planner3d_UpdatePrice=function(IdsWithInfo){var url=$('#planner3D').data('cart-sum-url'),product={};product.product={};var authFromServer=function(res){if(!res.success){return false;}
$('.jsPrice').html(printPrice(res.sum));};for(var i=0,len=IdsWithInfo.length;i<len;i++){var prodID=IdsWithInfo[i].id;if(IdsWithInfo[i].error!==''){$('.jsBuyButton').addClass('mDisabled');$('#coupeError').html('Вставки продаются только парами!').show();return false;}
$('.jsBuyButton').removeClass('mDisabled');$('#coupeError').hide();if(product.product[prodID+'']!==undefined){product.product[prodID+''].quantity++;}
else{product.product[prodID+'']={id:prodID,quantity:1};}}
$.ajax({type:'POST',url:url,data:product,success:authFromServer});};var kupe2basket=function(){if($(this).hasClass('mDisabled')){return false;}
var structure=global.Planner3dKupeConstructor.GetBasketContent(),url=$(this).attr('href'),product={};var resFromServer=function(res){if(!res.success){return false;}
$('.jsBuyButton').html('В корзине').addClass('mBought').attr('href','/cart');res.product.name=$('.bMainContainer__eHeader-title').html();res.product.price=$('.jsPrice').eq('1').html();res.product.article=$('.bMainContainer__eHeader-article').html();$('body').trigger('addtocart',[res]);};product.product=structure;$.ajax({type:'POST',url:url,data:product,success:resFromServer});return false;};var initPlanner=function(){try{var coupeInfo=$('#planner3D').data('product');global.Planner3dKupeConstructor=new DKupe3dConstructor(document.getElementById('planner3D'),'/css/item/coupe_img/','/css/item/coupe_tex/','/css/item/test_coupe_icons/');global.Planner3dKupeConstructor.Initialize('/js/KupeConstructorData.json',coupeInfo.id);}
catch(err){var dataToLog={event:'Kupe3dConstructor error',type:'ошибка загрузки Kupe3dConstructor',err:err};global.ENTER.utils.logError(dataToLog);}
$('.jsBuyButton').off();$('.jsBuyButton').bind('click',kupe2basket);};$(document).ready(function(){if($('#planner3D').length){$LAB.script('KupeConstructorScript.min.js').script('three.min.js').wait(initPlanner);}});}(this));
;(function(){var lowPriceNotifer=function lowPriceNotifer(){var
notiferWrapper=$('.priceSale'),notiferButton=$('.jsLowPriceNotifer'),submitBtn=$('.bLowPriceNotiferPopup__eSubmitEmail'),input=$('.bLowPriceNotiferPopup__eInputEmail'),notiferPopup=$('.bLowPriceNotiferPopup'),error=$('.bLowPriceNotiferPopup__eError'),subscribe=$('.jsSubscribe');var
lowPriceNitiferHide=function lowPriceNitiferHide(){notiferPopup.fadeOut(300);return false;},userLogged=function userLogin(event,userInfo){if(userInfo){if(userInfo.name){notiferWrapper.show();}
if(userInfo.email){input.val(userInfo.email);}}},lowPriceNitiferShow=function lowPriceNitiferShow(){notiferPopup.fadeIn(300);notiferPopup.find('.close').bind('click',lowPriceNitiferHide);return false;},resFromServer=function resFromServer(res){if(!res.success){input.addClass('red');if(res.error.message){error.show().html(res.error.message);}
return false;}
if(subscribe[0]&&subscribe[0].checked&&typeof _gaq!='undefined'){_gaq.push(['_trackEvent','subscription','subscribe_price_alert',input.val()]);}
lowPriceNitiferHide();notiferPopup.remove();notiferButton.remove();},checkSubscribe=function checkSubscribe(){if(subscribe.length&&subscribe.is(':checked')){return true;}
return false;},lowPriceNotiferSubmit=function lowPriceNotiferSubmit(){var
submitUrl=submitBtn.data('url');submitUrl+=encodeURI('?email='+input.val()+'&subscribe='+(checkSubscribe()?1:0));$.get(submitUrl,resFromServer);return false;};submitBtn.bind('click',lowPriceNotiferSubmit);notiferButton.bind('click',lowPriceNitiferShow);$('body').bind('userLogged',userLogged);};$(document).ready(function(){if($('.jsLowPriceNotifer').length){lowPriceNotifer();}});}());
;(function($){var $window=$(window),$body=$(document.body),$creditButton=$body.find('.jsProductCreditButton'),$userbar=$('.js-topbar-fixed'),$tabs=$('.jsProductTabs'),tabsOffset,popupDefaults={centered:true,closeSelector:'.jsPopupCloser'};if(!$body.hasClass('product-card-new'))return;tabsOffset=$tabs.offset().top;$body.on('click','.jsOpenProductImgPopup',function(){$body.find('.jsProductImgPopup').lightbox_me(popupDefaults);});$body.find('.jsProductPhotoThumb').on('click',function(){$body.find('.jsProductPopupBigPhoto').attr('src',$(this).data('big-img'));});$body.on('click','.jsProductPopupZoom',function(){});$body.on('click','.jsProductPopupSlide',function(){});$body.on('click','.jsProductMediaButton',function(e){var $popup=$(e.target).next(),$iframe=$popup.find('iframe'),src=$iframe.data('src'),$3dContainer=$popup.find('.jsProduct3DContainer'),$3DJSONContainer=$popup.find('.jsProduct3DJSON');if(src)$iframe.attr('src',src);if($3dContainer.length==0&&$3DJSONContainer.length==0){$popup.lightbox_me($.extend(popupDefaults,{destroyOnClose:true,onClose:function(){$iframe.removeAttr('src');$(e.target).parent().append($popup.clone().hide());}}))}else{if($3dContainer.data('type')=='swf'){$LAB.script('swfobject.min.js').wait(function(){var id='js-product-3d-swf-popup-object';swfobject.embedSWF($3dContainer.data('url'),'js-product-3d-swf-popup-model','700px','500px','10.0.0','js/vendor/expressInstall.swf',{language:'auto'},{menu:'false',scale:'noScale',allowFullscreen:'true',allowScriptAccess:'always',wmode:'direct'},{id:id});$popup.lightbox_me($.extend(popupDefaults,{onClose:function(){$(e.target).parent().append($popup.clone().hide());}}))});}else if($3DJSONContainer.length>0){$LAB.script('DAnimFramePlayer.min.js').wait(function(){var data=$3DJSONContainer.data('value'),host=$3DJSONContainer.data('host');try{if(!$('#js-product-3d-img-container').length){(new DAnimFramePlayer($3DJSONContainer[0],host)).DoLoadModel(data);}
$popup.lightbox_me($.extend(popupDefaults,{onClose:function(){$(e.target).parent().append($popup.clone().hide());}}));}
catch(err){console.error(err)}});}}});if($creditButton.length>0&&typeof window['dc_getCreditForTheProduct']=='function'){window['dc_getCreditForTheProduct'](4427,window.docCookies.getItem('enter_auth'),'getPayment',{price:$creditButton.data('credit')['price'],count:1,type:$creditButton.data('credit')['product_type']},function(result){if(typeof result['payment']!='undefined'&&result['payment']>0){$creditButton.find('.jsProductCreditPrice').text(printPrice(Math.ceil(result['payment'])));$creditButton.show();}})}
$body.on('click','.jsReviewAdd',function(){$('.jsReviewForm').lightbox_me($.extend(popupDefaults,{onLoad:function(){},onClose:function(){}}));});$body.on('click','.jsShowMoreReviews',function(){var productUi=$(this).data('ui'),totalNum=$(this).data('total-num'),$hiddenReviews=$('.jsReviewItem:hidden'),currentCount;if($hiddenReviews.length>0){$hiddenReviews.show();if($('.jsReviewItem').length==totalNum)$('.jsShowMoreReviews').hide();}else{currentCount=$('.jsReviewItem').length;$.ajax('/product-reviews/'+productUi,{data:{page:currentCount/10,numOnPage:10}}).done(function(data){if(data.content){$('.jsReviewsList').append(data.content);if($('.jsReviewItem').length==totalNum)$('.jsShowMoreReviews').hide();}});}});if($tabs.length){$window.on('scroll',function(){var fixedClass='pp-fixed';if($window.scrollTop()-60>tabsOffset){$tabs.addClass(fixedClass);$userbar.addClass(fixedClass);}else{$tabs.removeClass(fixedClass);$userbar.removeClass(fixedClass);}});}
$body.scrollspy({target:'#jsScrollSpy'});$body.on('click','.jsOneClickButtonOnDeliveryMap',function(){$('.jsProductPointsMap').trigger('close');});$body.on('click','.jsShowDeliveryMap',function(){var productId=$(this).data('product-id'),$div=$('.jsProductPointsMap');if($div.find('.jsDeliveryMapPoints').length>0){$div.lightbox_me({centered:true,preventScroll:true});return;}
$.ajax('/ajax/product/map/'+productId,{dataType:'json',beforeSend:function(){$div.lightbox_me({centered:true,preventScroll:true})}}).done(function(data){if(!data.success){console.error('product/map response: %s',data.error);}else{var $mapContainer=$(data.html),mapData=$.parseJSON($mapContainer.find('.jsMapData').html()),mapDivId=$mapContainer.find('.js-order-map').first().attr('id'),yMap,pointsModel;$div.html(data.html);$body.on('click','.jsCloseFl',function(){$div.trigger('close');});if(mapData){yMap=new ymaps.Map(mapDivId,{center:[mapData.latitude,mapData.longitude],zoom:mapData.zoom},{autoFitToViewport:'always'});yMap.controls.remove('searchControl');yMap.geoObjects.removeAll();yMap.container.fitToViewport();pointsModel=new ENTER.DeliveryPoints(mapData.points,yMap);yMap.events.add('boundschange',function(event){var bounds;if(event.get('newBounds')){bounds=event.get('target').getBounds();pointsModel.latitudeMin(bounds[0][0]);pointsModel.latitudeMax(bounds[1][0]);pointsModel.longitudeMin(bounds[0][1]);pointsModel.longitudeMax(bounds[1][1]);}});$.each(mapData.points,function(i,point){try{yMap.geoObjects.add(new ENTER.Placemark(point,true,'jsOneClickButtonOnDeliveryMap jsOneClickButton-new'));}catch(e){console.error('Ошибка добавления точки на карту',e);}});if(yMap.geoObjects.getLength()===1){yMap.setCenter(yMap.geoObjects.get(0).geometry.getCoordinates(),15);yMap.geoObjects.get(0).options.set('visible',true);}else{yMap.setBounds(yMap.geoObjects.getBounds());yMap.events.once('boundschange',function(event){if(event.get('oldZoom')<event.get('newZoom')){yMap.geoObjects.each(function(point){point.options.set('visible',true)})}})}
ko.applyBindings(pointsModel,$div[0]);$body.on('click','.jsOrderV3Dropbox',function(){$(this).siblings().removeClass('opn').find('.jsOrderV3DropboxInner').hide();$(this).find('.jsOrderV3DropboxInner').toggle();$(this).hasClass('opn')?$(this).removeClass('opn'):$(this).addClass('opn');});}}})});$('.js-slider-2').goodsSlider({leftArrowSelector:'.goods-slider__btn--prev',rightArrowSelector:'.goods-slider__btn--next',sliderWrapperSelector:'.goods-slider__inn',sliderSelector:'.goods-slider-list',itemSelector:'.goods-slider-list__i',onLoad:function(goodsSlider){ko.applyBindings(ENTER.UserModel,goodsSlider);if($(goodsSlider).data('position')=='ProductSimilar')$('.jsSimilarTab').show();}});})(jQuery);
$(document).ready(function(){var $productDescriptionToggle=$('#productDescriptionToggle');+function(){var image=$('.js-photo-zoomedImg');if(!image.length){console.warn('Нет изображения для elevateZoom');return;}
var
zoomDisable=(image.data('zoom-disable')!==undefined)?image.data('zoom-disable'):true,zoomConfig={gallery:'productImgGallery',galleryActiveClass:'prod-photoslider__gal__link--active',zoomWindowOffety:0,zoomWindowOffetx:19,zoomWindowWidth:image.data('is-slot')?344:519,borderSize:1,borderColour:'#C7C7C7',disableZoom:zoomDisable};var
photoGalleryLinkClick=function(){if($(this).data("zoom-disable")==undefined){return;}
if($(this).data("zoom-disable")==zoomDisable){return;}
zoomDisable=$(this).data("zoom-disable");if(!zoomDisable){zoomConfig.disableZoom=zoomDisable;image.elevateZoom(zoomConfig);}
else{$.removeData(image,'elevateZoom');$('.zoomContainer').remove();}
return false;};image.elevateZoom(zoomConfig);$('.jsPhotoGalleryLink').on('click',photoGalleryLinkClick);}();$('.bCountSection').goodsCounter({onChange:function(count){var spinnerFor=this.attr('data-spinner-for'),bindButton=$('.'+spinnerFor),bindOneClickButton=$('.'+spinnerFor+'-oneClick'),newHref=bindButton.attr('href')||'';bindButton.attr('href',newHref.addParameterToUrl('quantity',count));bindOneClickButton.data('quantity',count);}});$('.js-slider').goodsSlider({onLoad:function(goodsSlider){ko.applyBindings(ENTER.UserModel,goodsSlider);}});$('.bDescSelectItem').customDropDown({changeHandler:function(option){document.location.href=option.data('url');}});if($productDescriptionToggle.length){$productDescriptionToggle.toggle(function(e){e.preventDefault();$(this).parent().parent().find('.descriptionlist:not(.short)').show();$(this).html('Скрыть все характеристики');},function(e){e.preventDefault();$(this).parent().parent().find('.descriptionlist:not(.short)').hide();$(this).html('Показать все характеристики');});}
try{var
productId=ENTER.config.pageConfig.product?ENTER.config.pageConfig.product.id:null,cookieValue=docCookies.getItem('product_viewed')||'',viewed=[];if(productId){viewed=cookieValue?ENTER.utils.arrayUnique(cookieValue.split(',')):[];viewed.push(productId);docCookies.setItem('product_viewed',viewed.slice(-20).join(','),7*24*60*60,'/');}}catch(e){console.error(e);}});
(function(){var
productInfo=$('#jsProductCard').data('value')||{},reviewsYandexClick=function(e){console.log('reviewsYandexClick');var
link=this;if('undefined'!==productInfo.article){_gaq.push(['_trackEvent','YM_link',productInfo.article]);e.preventDefault();if('undefined'!==link){setTimeout(function(){link.click();},500);}}};if(!$('#jsProductCard').length){return false;}
if(typeof _gaq!=='undefined'){$('a.reviewLink.yandex').each(function(){$(this).one("click",reviewsYandexClick);});}})();
;(function(){var reviewCurrentPage={user:-1,pro:-1},reviewPageCount={user:0,pro:0},reviewsProductUi=null,reviewsType=null,reviewsContainerClass=null,moreReviewsButton=$('.jsGetReviews'),reviewTab=$('.bReviewsTabs__eTab'),reviewWrap=$('.bReviewsWrapper'),reviewContent=$('.bReviewsContent');var getReviews=function(productId,type,containerClass){var page=reviewCurrentPage[type]+1,layout=false,url='/product-reviews/'+productId,dataToSend;var reviewsResponse=function reviewsResponse(data){$('.'+containerClass).html($('.'+containerClass).html()+data.content);reviewCurrentPage[type]++;reviewPageCount[type]=data.pageCount;if(reviewCurrentPage[type]+1>=reviewPageCount[type]){moreReviewsButton.hide();}
else{moreReviewsButton.show();}};if($('body').hasClass('jewel')){layout='jewel';}
dataToSend={page:page,type:type,layout:layout};$.ajax({type:'GET',data:dataToSend,url:url,success:reviewsResponse});};if(reviewTab.length){var initialType=reviewWrap.attr('data-reviews-type');reviewCurrentPage[initialType]++;reviewPageCount[initialType]=reviewWrap.attr('data-page-count');if(reviewPageCount[initialType]>1){moreReviewsButton.show();}
reviewsProductUi=reviewWrap.attr('data-product-ui');reviewsType=reviewWrap.attr('data-reviews-type');reviewsContainerClass=reviewWrap.attr('data-container');reviewTab.click(function(){reviewsContainerClass=$(this).attr('data-container');if(reviewsContainerClass===undefined){return;}
reviewsType=$(this).attr('data-reviews-type');reviewTab.removeClass('active');$(this).addClass('active');reviewContent.hide();$('.'+reviewsContainerClass).show();moreReviewsButton.hide();if(reviewsType==='user'){moreReviewsButton.html('Показать ещё отзывы');}
if(!$('.'+reviewsContainerClass).html()){getReviews(reviewsProductUi,reviewsType,reviewsContainerClass);}
else{if(reviewCurrentPage[reviewsType]+1>=reviewPageCount[reviewsType]){moreReviewsButton.hide();}
else{moreReviewsButton.show();}}});moreReviewsButton.click(function(){getReviews(reviewsProductUi,reviewsType,reviewsContainerClass);});}}());(function(){var body=$('body'),reviewPopup=$('.jsReviewPopup'),form=reviewPopup.find('.jsReviewForm'),submitReviewButton=$('.jsFormSubmit'),submitReviewButtonText=submitReviewButton.val(),reviewStar=form.find('.starsList__item'),reviewStarCount=form.find('.jsReviewStarsCount'),starStateClass={fill:'mFill',empty:'mEmpty'},advantageField=$('.jsAdvantage'),disadvantageField=$('.jsDisadvantage'),extractField=$('.jsExtract'),authorNameField=$('.jsAuthorName'),authorEmailField=$('.jsAuthorEmail'),validationConfig={fields:[{fieldNode:advantageField,require:true,customErr:'Не указаны достоинства'},{fieldNode:disadvantageField,require:true,customErr:'Не указаны недостатки'},{fieldNode:extractField,require:true,customErr:'Не указан комментарий'},{fieldNode:authorNameField,require:true,customErr:'Не указано имя'},{fieldNode:authorEmailField,require:true,customErr:'Не указан e-mail',validBy:'isEmail'}]},validator=new FormValidator(validationConfig);var
openPopup=function openPopup(){reviewPopup.lightbox_me({centered:true,autofocus:true,onLoad:function(){}});return false;},formErrorHandler=function formErrorHandler(formError){var field=$('[name="review['+formError.field+']"]');var clearError=function clearError(){validator._unmarkFieldError($(this));};console.warn('Ошибка в поле');validator._markFieldError(field,formError.message);field.bind('focus',clearError);return false;},showError=function showError(msg){var error=$('ul.error_list',form);if(error.length){error.html('<li>'+msg+'</li>');}
else{$('.bFormLogin__ePlaceTitle',form).after($('<ul class="error_list" />').append('<li>'+msg+'</li>'));$(form).prepend($('<ul class="error_list" />').append('<li>'+msg+'</li>'));}
return false;},serverErrorHandler=function serverErrorHandler(res){var formError=null;console.warn('Обработка ошибок формы');for(var i=res.form.error.length-1;i>=0;i--){formError=res.form.error[i];console.warn(formError);if(formError.field!=='global'&&formError.message!==null){formErrorHandler(formError);}
else if(formError.field==='global'&&formError.message!==null){showError(formError.message);}}
return false;},responseFromServer=function responseFromServer(response){console.log('Ответ от сервера');if(response.error){console.warn('Form has error');serverErrorHandler(response);return false;}
if(response.success){if(response.notice.message){form.before(response.notice.message);}
form.hide();}
return false;},formSubmit=function formSubmit(){if(form.data('disabled')){return false;}
form.data('disabled',true);submitReviewButton.attr('disabled','disabled');submitReviewButton.addClass('mDisabled');submitReviewButton.val('Сохраняю…');if($('ul.error_list',form).length){$('ul.error_list',form).html('');}
function enableSubmitReviewButton(){form.data('disabled',false);submitReviewButton.removeAttr('disabled');submitReviewButton.removeClass('mDisabled');submitReviewButton.val(submitReviewButtonText);}
validator.validate({onInvalid:function(err){console.warn('invalid');console.log(err);enableSubmitReviewButton();},onValid:function(){$.ajax({type:'post',url:form.attr('action'),data:form.serializeArray(),dataType:'json',success:responseFromServer,complete:function(){enableSubmitReviewButton();}});console.log('Сабмит формы "Отзыв о товаре"');return false;}});return false;},fillStars=function fillStars(count){reviewStar.removeClass(starStateClass['fill']).removeClass(starStateClass['empty']);reviewStar.each(function(index){if(index+1<=count){$(this).addClass(starStateClass['fill']);}
else{$(this).addClass(starStateClass['empty']);}});},hoverStar=function hoverStar(){var nowStar=$(this),starIndex=nowStar.index()+1;fillStars(starIndex);},unhoverStar=function unhoverStar(){var nowStarCount=reviewStarCount.val();fillStars(nowStarCount);},markStar=function markStar(){var nowStar=$(this),starIndex=nowStar.index()+1;reviewStarCount.val(starIndex);fillStars(starIndex);},fillUserData=function fillUserData(e,userInfo){if(userInfo){if(userInfo.name){authorNameField.val(userInfo.name);authorNameField.parent('.jsPlace2Col').hide();}
if(userInfo.email){authorEmailField.val(userInfo.email);authorEmailField.parent('.jsPlace2Col').hide();}
if(userInfo.name&&userInfo.email){authorNameField.parents('.jsFormFieldset').hide();}}};body.on('click','.jsReviewSend',openPopup);body.on('submit','.jsReviewForm',formSubmit);body.on('userLogged',fillUserData);reviewStar.hover(hoverStar,unhoverStar);reviewStar.on('unhover',unhoverStar);reviewStar.on('click',markStar);if('#add-review'==location.hash){openPopup();}}());$(function(){if(!$('#spk-widget-reviews').length){return;}
if('#add-review'==location.hash){location.href='?spkPreState=addReview';}
$('.sprosikupiRating .spk-good-rating a').live('click',function(e){$(document).stop().scrollTo($(e.currentTarget).attr('href'),800);return false;});$.getScript("//static.sprosikupi.ru/js/widget/sprosikupi.bootstrap.js");});$(function(){var reviewsContainer=$('#shoppilot-reviews-container');if(!reviewsContainer.length){return;}
_shoppilot=window._shoppilot||[];_shoppilot.push(['_setStoreId','535a852cec8d830a890000a6']);_shoppilot.push(['_setOnReady',function(Shoppilot){(new Shoppilot.ProductWidget({name:'product-rating',styles:'product-reviews',product_id:reviewsContainer.data('productId')})).appendTo('#shoppilot-rating-container');(new Shoppilot.ProductWidget({name:'product-reviews',styles:'product-reviews',product_id:reviewsContainer.data('productId')})).appendTo(reviewsContainer[0]);if('#add-review'==location.hash){(new Shoppilot.Surveybox({product_id:reviewsContainer.data('productId')})).open();}}]);(function(){var script=document.createElement('script');script.type='text/javascript';script.async=true;script.src='//ugc.shoppilot.ru/javascripts/require.js';script.setAttribute('data-main','//ugc.shoppilot.ru/javascripts/social-apps.js');var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(script,s);})();$('#shoppilot-rating-container').on('click','a.sp-product-inline-rating-label',function(e){$(document).stop().scrollTo($(e.currentTarget).attr('href').replace(/^.*?#/,'#'),800);return false;});});
;$(function(){var $body=$('body');$('.js-product-similarProducts-link').on('click',function(event){try{$body.trigger('trackGoogleEvent',{category:'RR_взаимодействие',action:'Перешел на карточку товара',label:'SEO',hitCallback:$(this).attr('href')});event.stopPropagation();}catch(e){console.error(e);}});});
;$(function(){var $video=$('.js-product-video');if(!$video.length||!$('.js-product-video-container').length){return;}
var
videoStartTime=0,videoEndTime=0,productUrl=document.location.href,$iframeContainer=$('.js-product-video-iframeContainer'),iframeHtml=$iframeContainer.html();$iframeContainer.empty();$video.bind('click',function(){var $iframeContainer=$('.js-product-video-iframeContainer');$iframeContainer.append(iframeHtml);var $iframe=$('iframe',$iframeContainer);$iframe.attr('src',$iframe.data('src'));$('.js-product-video-container').lightbox_me({centered:true,onLoad:function(){videoStartTime=new Date().getTime();if(typeof(_gaq)!=='undefined'){_gaq.push(['_trackEvent','Video','Play',productUrl]);}},onClose:function(){$('.js-product-video-iframeContainer').empty();videoEndTime=new Date().getTime();var videoSpent=videoEndTime-videoStartTime;if(typeof _gaq!=='undefined'){_gaq.push(['_trackEvent','Video','Stop',productUrl,videoSpent]);}}});return false;});});
//@ sourceMappingURL=product.js.map