
;(function(){if($('.creditbox').length){console.log('## Product has creditbox');var
creditBoxNode=$('.creditbox'),priceNode=creditBoxNode.find('.creditbox__sum strong');window.creditBox={cookieTimeout:null,toggleCookie:function(state){clearTimeout(this.cookieTimeout);this.cookieTimeout=setTimeout(function(){window.docCookies.setItem('credit_on',state?1:0,60*60,'/');},200);},init:function(){var
self=this,creditd=$('input[name=dc_buy_on_credit]').data('model'),label=$('.creditbox label');$('input[type=radio][name=price_or_credit]').change(function(e){e.preventDefault();if(!label.length){return;}
label.toggleClass('checked');self.toggleCookie(label.hasClass('checked'));});if(this.getState()===1){$('.creditbox label').addClass('checked');}
creditd.count=1;creditd.cart='/cart';dc_getCreditForTheProduct(4427,window.docCookies.getItem('enter_auth'),'getPayment',{price:creditd.price,count:creditd.count,type:creditd.product_type},function(result){if(!'payment'in result){return;}
if(result.payment>0){priceNode.html(printPrice(Math.ceil(result.payment)));creditBoxNode.show();}});},getState:function(){if(!window.docCookies.hasItem('credit_on')){return 0;}
return window.docCookies.getItem('credit_on');}};creditBox.init();}
else{console.log('## Product does not have creditbox');var
productDesc=$('.bProductDesc');if(productDesc.length&&!productDesc.hasClass('mNoCredit')){productDesc.addClass('mNoCredit');}}}());
(function(){if($('.bDeliveryNowClick').length){var shopToggle=function shopToggle(){var nowBox=$(this).parent('.mDeliveryNow'),ulBox=nowBox.find('ul.bDeliveryFreeAddress');nowBox.toggleClass('mOpen');nowBox.toggleClass('mClose');if(nowBox.hasClass('mOpen')){ulBox.slideDown();}
else{ulBox.slideUp();}};$('.bDeliveryNowClick').on('click',shopToggle);}}());
;(function(){var initFotoSlider=function(){var slider=$('.bPhotoSlider');var fotoBox=slider.find('.bPhotoSliderGallery');var leftArr=slider.find('.bPhotoSlider__eBtn.mPrev');var rightArr=slider.find('.bPhotoSlider__eBtn.mNext');var photos=fotoBox.find('.bPhotoSliderGallery__eItem');if(!photos.length){return false;}
var itemW=photos.width()+parseInt(photos.css('marginLeft'),10)+parseInt(photos.css('marginRight'),10);var nowLeft=0;fotoBox.css({'width':photos.length*itemW,'left':nowLeft});var checkArrow=function(){if(nowLeft>0){leftArr.show();}
else{leftArr.hide();}
if(nowLeft<fotoBox.width()-slider.width()){rightArr.show();}
else{rightArr.hide();}};var prevFoto=function(){nowLeft=nowLeft-itemW;fotoBox.animate({'left':-nowLeft});checkArrow();return false;};var nextFoto=function(){nowLeft=nowLeft+itemW;fotoBox.animate({'left':-nowLeft});checkArrow();return false;};checkArrow();leftArr.bind('click',prevFoto);rightArr.bind('click',nextFoto);};$(document).ready(function(){if($('.bPhotoSlider').length){initFotoSlider();}});})();
;(function(global){var pageConfig=global.ENTER.config.pageConfig,utils=global.ENTER.utils;var loadFurniture3D=function loadFurniture3D(){var furnitureAfterLoad=function furnitureAfterLoad(){var object=$('#3dModelImg'),data=object.data('value'),host=object.data('host'),AnimFramePlayer=null;var furniture3dPopupShow=function furniture3dPopupShow(){$('#3dModelImg').lightbox_me({centered:true,closeSelector:'.close'});return false;};try{if(!$('#3dImgContainer').length){AnimFramePlayer=new DAnimFramePlayer(document.getElementById('3dModelImg'),host);AnimFramePlayer.DoLoadModel(data);$('.mGrad360.3dimg').bind('click',furniture3dPopupShow);}}
catch(err){var dataToLog={event:'3dimg',type:'ошибка загрузки 3dimg для мебели',err:err};utils.logError(dataToLog);}};$LAB.script('DAnimFramePlayer.min.js').wait(furnitureAfterLoad);};$(document).ready(function(){if(pageConfig['product.img3d']){loadFurniture3D();}});}(this));
(function(){var hintShower=function(){var hintPopup=$('.bHint_ePopup');var hintLnk=$('.bHint_eLink');var hintCloseLnk=$('.bHint_ePopup .close');var hintAnalytics=function(data){if(typeof(_gaq)!=='undefined'){_gaq.push(['_trackEvent','Hints',data.hintTitle,data.url]);}};var hintShow=function(){hintPopup.hide();$(this).parent().find('.bHint_ePopup').fadeIn(150);var analyticsData={hintTitle:$(this).html(),url:window.location.href};hintAnalytics(analyticsData);return false;};var hintClose=function(){hintPopup.fadeOut(150);return false;};hintLnk.bind('click',hintShow);hintCloseLnk.bind('click',hintClose);};$(document).ready(function(){if($('.bHint').length){hintShower();}});}());
;(function(global){global.Planner3dKupeConstructor=null;global.Planner3d_Init=function(ApiIds){};global.Planner3d_UpdatePrice=function(IdsWithInfo){var url=$('#planner3D').data('cart-sum-url'),product={};product.product={};var authFromServer=function(res){if(!res.success){return false;}
$('.jsPrice').html(printPrice(res.sum));};for(var i=0,len=IdsWithInfo.length;i<len;i++){var prodID=IdsWithInfo[i].id;if(IdsWithInfo[i].error!==''){$('.jsBuyButton').addClass('mDisabled');$('#coupeError').html('Вставки продаются только парами!').show();return false;}
$('.jsBuyButton').removeClass('mDisabled');$('#coupeError').hide();if(product.product[prodID+'']!==undefined){product.product[prodID+''].quantity++;}
else{product.product[prodID+'']={id:prodID,quantity:1};}}
$.ajax({type:'POST',url:url,data:product,success:authFromServer});};var kupe2basket=function(){if($(this).hasClass('mDisabled')){return false;}
var structure=global.Planner3dKupeConstructor.GetBasketContent(),url=$(this).attr('href'),product={};var resFromServer=function(res){if(!res.success){return false;}
$('.jsBuyButton').html('В корзине').addClass('mBought').attr('href','/cart');res.product.name=$('.bMainContainer__eHeader-title').html();res.product.price=$('.jsPrice').eq('1').html();res.product.article=$('.bMainContainer__eHeader-article').html();$('body').trigger('addtocart',[res]);};product.product=structure;$.ajax({type:'POST',url:url,data:product,success:resFromServer});return false;};var initPlanner=function(){try{var coupeInfo=$('#planner3D').data('product');global.Planner3dKupeConstructor=new DKupe3dConstructor(document.getElementById('planner3D'),'/css/item/coupe_img/','/css/item/coupe_tex/','/css/item/test_coupe_icons/');global.Planner3dKupeConstructor.Initialize('/js/KupeConstructorData.json',coupeInfo.id);}
catch(err){var dataToLog={event:'Kupe3dConstructor error',type:'ошибка загрузки Kupe3dConstructor',err:err};global.ENTER.utils.logError(dataToLog);}
$('.jsBuyButton').off();$('.jsBuyButton').bind('click',kupe2basket);};$(document).ready(function(){if($('#planner3D').length){$LAB.script('KupeConstructorScript.min.js').script('three.min.js').wait(initPlanner);}});}(this));
;(function(){var lowPriceNotifer=function lowPriceNotifer(){var
notiferWrapper=$('.priceSale'),notiferButton=$('.jsLowPriceNotifer'),submitBtn=$('.bLowPriceNotiferPopup__eSubmitEmail'),input=$('.bLowPriceNotiferPopup__eInputEmail'),notiferPopup=$('.bLowPriceNotiferPopup'),error=$('.bLowPriceNotiferPopup__eError'),subscribe=$('.jsSubscribe');var
lowPriceNitiferHide=function lowPriceNitiferHide(){notiferPopup.fadeOut(300);return false;},userLogged=function userLogin(event,userInfo){if(userInfo){if(userInfo.name){if(userInfo.isSubscribed){subscribe.parent('label').hide();}
notiferWrapper.show();}
if(userInfo.email){input.val(userInfo.email);}}},lowPriceNitiferShow=function lowPriceNitiferShow(){notiferPopup.fadeIn(300);notiferPopup.find('.close').bind('click',lowPriceNitiferHide);return false;},resFromServer=function resFromServer(res){if(!res.success){input.addClass('red');if(res.error.message){error.show().html(res.error.message);}
return false;}
lowPriceNitiferHide();notiferPopup.remove();notiferButton.remove();},checkSubscribe=function checkSubscribe(){if(subscribe.length&&subscribe.is(':checked')){return true;}
return false;},lowPriceNotiferSubmit=function lowPriceNotiferSubmit(){var
submitUrl=submitBtn.data('url');submitUrl+=encodeURI('?email='+input.val()+'&subscribe='+(checkSubscribe()?1:0));$.get(submitUrl,resFromServer);return false;};submitBtn.bind('click',lowPriceNotiferSubmit);notiferButton.bind('click',lowPriceNitiferShow);$('body').bind('userLogged',userLogged);};$(document).ready(function(){if($('.jsLowPriceNotifer').length){lowPriceNotifer();}});}());
;(function(global){var pageConfig=global.ENTER.config.pageConfig,utils=global.ENTER.utils,swfobjectLoaded=false;var
loadWithSWF=function(functionName){if('function'!==typeof(functionName))return false;if(!swfobjectLoaded){$LAB.script('swfobject.min.js').wait(functionName);swfobjectLoaded=true;}
else{functionName();}
return true;},loadMaybe3D=function(){var
data=$('#maybe3dModelPopup').data('value');var
afterLoad=function(){var
maybe3dPopupShow=function(e){e.stopPropagation();try{if(!$('#maybe3dModel').length){$('#maybe3dModelPopup_inner').append('<div id="maybe3dModel"></div>');}
swfobject.embedSWF(data.init.swf,data.init.container,data.init.width,data.init.height,data.init.version,data.init.install,data.flashvars,data.params,data.attributes);$('#maybe3dModelPopup').lightbox_me({centered:true,closeSelector:'.close',onClose:function(){swfobject.removeSWF(data.attributes.id);}});}
catch(err){var
dataToLog={event:'swfobject_error',type:'ошибка загрузки swf maybe3d',err:err};utils.logError(dataToLog);}
return false;};$('.mGrad360.maybe3d').bind('click',maybe3dPopupShow);};loadWithSWF(afterLoad);},loadFitting=function loadFitting(){console.log('### LoadFitting BEGIN');var
f_afterLoad=function f_afterLoad()
{var
ARPluginLoad=function ARPluginLoad(){if('undefined'===typeof(ARPlugin)){console.warn('ARPlugin is not defined');$('li.vFitting').hide();return false;}
console.log('ARPlugin is defined');ARPlugin.init({type:"simple",js:"/js/prod/",css:"/styles/ARPlugin/",img:"/styles/ARPlugin/img/",swf:"/styles/ARPlugin/swf/",resources:pageConfig['product.resources'],meshes_path:pageConfig['product.meshes'],textures_path:pageConfig['product.textures'],marker_path:pageConfig['product.marker']});fittingPopupShow=function(e){e.preventDefault();if(typeof _gaq!=='undefined'){_gaq.push(['_trackEvent','3D-primerochnaya',pageConfig['product.name'],'click']);}
ARPlugin.show(pageConfig['product.article']+'.obj',pageConfig['product.article']+'.png');};$('.vFitting').bind('click',fittingPopupShow);};$LAB.script('ARPluginOrigin.js').wait(ARPluginLoad);};loadWithSWF(f_afterLoad);};$(document).ready(function(){if(pageConfig['product.maybe3d']){loadMaybe3D();}
if(pageConfig['product.vFitting']){loadFitting();}});}(this));
;$(document).ready(function(ENTER){if($('.packageSet').length===0)return;var packageSetBtn=$('.jsChangePackageSet'),packageSetWindow=$('.jsPackageSetPopup'),packageProducts=$('.mPackageSetEdit').data('value'),knockoutUrl=ENTER.config.debug?'/js/vendor/knockout.js':'/js/prod/knockout.min.js';var showPackageSetPopup=function showPackageSetPopup(event){event.preventDefault();$('.bCountSection').goodsCounter('destroy');packageSetWindow.lightbox_me({autofocus:true});};packageSetBtn.on('click',showPackageSetPopup);if(!window.ko)$.getScript(knockoutUrl,init);else init();function init(){var ko=window.ko;function ProductModel(product){var self=this;self.id=product.id;self.url=product.url;self.name=product.name;self.line=product.lineName;self.price=product.price;self.prettyPrice=window.printPrice(self.price);self.image=product.image;self.height=product.height;self.width=product.width;self.depth=product.depth;self.count=ko.observable(product.count);self.maxCount=ko.observable(Infinity);self.deliveryDate=ko.observable(product.deliveryDate);self.plusClick=function(){if(self.maxCount()>self.count()){self.count(parseInt(self.count())+1);$.post('/ajax/product/delivery',{product:[{id:self.id,quantity:self.count()}]},function(data){if(data.success){self.deliveryDate(data.product[0].delivery[0].date.value);console.log('Delivery: id=',self.id,' quantity=',self.count(),' date: ',data.product[0].delivery)}else{self.count(self.count()-1);self.maxCount(self.count());}})}};self.minusClick=function(){if(self.count()>0)self.count(self.count()-1);};self.countKeydown=function(item,e){e.stopPropagation();if(e.which===38){item.plusClick();return false;}
else if(e.which===40){item.minusClick();return false;}
else if((((e.which>=48)&&(e.which<=57))||((e.which>=96)&&(e.which<=105))||(e.which===8)||(e.which===46))){return true;}
return false;};}
function ProductList(){var self=this;self.products=ko.observableArray([]);self.isBaseKit=ko.computed(function(){var isEqual=true;ko.utils.arrayForEach(self.products(),function(item){if(packageProducts[item.id].count!=item.count())isEqual=false;});return isEqual;});self.totalPrice=ko.computed(function(){var total=0;ko.utils.arrayForEach(self.products(),function(item){total+=parseInt(item.count())*parseInt(item.price)});return window.printPrice(total);});self.totalCount=ko.computed(function(){var total=0;ko.utils.arrayForEach(self.products(),function(item){total+=parseInt(item.count())});return total;});self.buyLink=ko.computed(function(){var link='/cart/set-products?',id=0;ko.utils.arrayForEach(self.products(),function(item){if(item.count()>0){link+='product['+id+'][id]='+item.id+'&product['+id+'][quantity]='+item.count()+'&';id+=1;}});return link;});self.addProduct=function(product){self.products.push(new ProductModel(product))};self.populateWithObj=function(obj){self.products($.map(obj,function(item){return new ProductModel(item)}));self.products.sort(function(a,b){return a.line==b.line?0:(a.line<b.line?-1:1)});};self.resetToBaseKit=function(){self.populateWithObj(packageProducts);};self.populateWithObj(packageProducts);}
window.prod=new ProductList();ko.applyBindings(window.prod);}}(window.ENTER));
$(document).ready(function(){(function(){if(!$('.bZoomedImg').length){console.warn('Нет изображения для elevateZoom');return;}
var
image=$('.bZoomedImg'),zoomDisable=(image.data('zoom-disable')!==undefined)?image.data('zoom-disable'):true,zoomConfig={gallery:'productImgGallery',galleryActiveClass:'mActive',zoomWindowOffety:0,zoomWindowOffetx:19,zoomWindowWidth:519,borderSize:1,borderColour:'#C7C7C7',disableZoom:zoomDisable};var
photoGalleryLinkClick=function(){if($(this).data("zoom-disable")==undefined){return;}
if($(this).data("zoom-disable")==zoomDisable){return;}
zoomDisable=$(this).data("zoom-disable");if(!zoomDisable){zoomConfig.disableZoom=zoomDisable;image.elevateZoom(zoomConfig);}
else{$.removeData(image,'elevateZoom');$('.zoomContainer').remove();}
return false;};image.elevateZoom(zoomConfig);$('.jsPhotoGalleryLink').on('click',photoGalleryLinkClick);})();$('.bCountSection').goodsCounter({onChange:function(count){var spinnerFor=this.attr('data-spinner-for'),bindButton=$('.'+spinnerFor),newHref=bindButton.attr('href')||'';console.log('counter change');console.log(bindButton);bindButton.attr('href',newHref.addParameterToUrl('quantity',count));}});$('.bGoodsSlider').goodsSlider();$('.bDescSelectItem').customDropDown({changeHandler:function(option){var url=option.data('url');document.location.href=url;}});(function(){var successHandler=function successHandler(res){console.info('payPal ajax complete');if(!res.success||!res.redirect){window.ENTER.utils.blockScreen.unblock();return;}
document.location.href=res.redirect;},buyOneClickAndRedirect=function buyOneClickAndRedirect(){console.info('payPal click');var button=$(this),url=button.attr('href'),quantityBlock=$('.bCountSection__eNum'),data={};window.ENTER.utils.blockScreen.block('Загрузка');if(quantityBlock.length&&$.isNumeric(quantityBlock.val())&&quantityBlock.val()*1>1){data.quantity=quantityBlock.val();}
$.get(url,data,successHandler);return false;};$('.jsPayPalButton').bind('click',buyOneClickAndRedirect);$('.jsLifeGiftButton').bind('click',buyOneClickAndRedirect);$('.jsOneClickButton').bind('click',buyOneClickAndRedirect);})();if($('#productDescriptionToggle').length){$('#productDescriptionToggle').toggle(function(e){e.preventDefault();$(this).parent().parent().find('.descriptionlist:not(.short)').show();$(this).html('Скрыть все характеристики');},function(e){e.preventDefault();$(this).parent().parent().find('.descriptionlist:not(.short)').hide();$(this).html('Показать все характеристики');});}});
(function(){var
productInfo=$('#jsProductCard').data('value')||{},toKISS={'Viewed Product SKU':productInfo.article,'Viewed Product Product Name':productInfo.name,'Viewed Product Product Status':productInfo.stockState},reviewsYandexClick=function(e){console.log('reviewsYandexClick');var
link=this;if('undefined'!==productInfo.article){_gaq.push(['_trackEvent','YM_link',productInfo.article]);e.preventDefault();if('undefined'!==link){setTimeout(function(){link.click();},500);}}};if(!$('#jsProductCard').length){return false;}
if(typeof _kmq!=='undefined'){_kmq.push(['record','Viewed Product',toKISS]);}
if(typeof _gaq!=='undefined'){$('a.reviewLink.yandex').each(function(){$(this).one("click",reviewsYandexClick);});}})();(function(){var trackAs={accessorize:function(productData){console.log(productData);var toKISS={'Recommended Item Clicked Accessorize Recommendation Place':'product','Recommended Item Clicked Accessorize Clicked SKU':productData.article,'Recommended Item Clicked Accessorize Clicked Product Name':productData.name,'Recommended Item Clicked Accessorize Product Position':productData.position};if(typeof _kmq!=='undefined'){_kmq.push(['record','Recommended Item Clicked Accessorize',toKISS]);}},alsoBought:function(productData){console.log(productData);var toKISS={'Recommended Item Clicked Also Bought Recommendation Place':'product','Recommended Item Clicked Also Bought Clicked SKU':productData.article,'Recommended Item Clicked Also Bought Clicked Product Name':productData.name,'Recommended Item Clicked Also Bought Product Position':productData.position};if(typeof _kmq!=='undefined'){_kmq.push(['record','Recommended Item Clicked Also Bought',toKISS]);}},alsoViewed:function(productData){console.log(productData);var toKISS={'Recommended Item Clicked Also Viewed Recommendation Place':'product','Recommended Item Clicked Also Viewed Clicked SKU':productData.article,'Recommended Item Clicked Also Viewed Clicked Product Name':productData.name,'Recommended Item Clicked Also Viewed Product Position':productData.position};if(typeof _kmq!=='undefined'){_kmq.push(['record','Recommended Item Clicked Also Viewed',toKISS]);}}},sliderAnalytics=function sliderAnalytics(){console.info('click!');var sliderData=$(this).parents('.bGoodsSlider').data('slider'),sliderType=sliderData.type,productData=$(this).data('product');console.log(sliderType);productData.position=$(this).index();if(trackAs.hasOwnProperty(sliderType)){trackAs[sliderType](productData);}};$('.bGoodsSlider').on('click','.bSliderAction__eItem',sliderAnalytics);}());
;(function(){var reviewCurrentPage={user:-1,pro:-1},reviewPageCount={user:0,pro:0},reviewsProductId=null,reviewsType=null,reviewsContainerClass=null,moreReviewsButton=$('.jsGetReviews'),reviewTab=$('.bReviewsTabs__eTab'),reviewWrap=$('.bReviewsWrapper'),reviewContent=$('.bReviewsContent');var getReviews=function(productId,type,containerClass){var page=reviewCurrentPage[type]+1,layout=false,url='/product-reviews/'+productId,dataToSend={};var reviewsResponse=function reviewsResponse(data){$('.'+containerClass).html($('.'+containerClass).html()+data.content);reviewCurrentPage[type]++;reviewPageCount[type]=data.pageCount;if(reviewCurrentPage[type]+1>=reviewPageCount[type]){moreReviewsButton.hide();}
else{moreReviewsButton.show();}};if($('body').hasClass('jewel')){layout='jewel';}
dataToSend={page:page,type:type,layout:layout};$.ajax({type:'GET',data:dataToSend,url:url,success:reviewsResponse});};if(reviewTab.length){var initialType=reviewWrap.attr('data-reviews-type');reviewCurrentPage[initialType]++;reviewPageCount[initialType]=reviewWrap.attr('data-page-count');if(reviewPageCount[initialType]>1){moreReviewsButton.show();}
reviewsProductId=reviewWrap.attr('data-product-id');reviewsType=reviewWrap.attr('data-reviews-type');reviewsContainerClass=reviewWrap.attr('data-container');reviewTab.click(function(){reviewsContainerClass=$(this).attr('data-container');if(reviewsContainerClass===undefined){return;}
reviewsType=$(this).attr('data-reviews-type');reviewTab.removeClass('active');$(this).addClass('active');reviewContent.hide();$('.'+reviewsContainerClass).show();moreReviewsButton.hide();if(reviewsType==='user'){moreReviewsButton.html('Показать ещё отзывы');}
if(!$('.'+reviewsContainerClass).html()){getReviews(reviewsProductId,reviewsType,reviewsContainerClass);}
else{if(reviewCurrentPage[reviewsType]+1>=reviewPageCount[reviewsType]){moreReviewsButton.hide();}
else{moreReviewsButton.show();}}});moreReviewsButton.click(function(){getReviews(reviewsProductId,reviewsType,reviewsContainerClass);});}}());;(function(){var body=$('body'),reviewPopup=$('.jsReviewPopup'),form=reviewPopup.find('.jsReviewForm'),reviewStar=form.find('.starsList__item'),reviewStarCount=form.find('.jsReviewStarsCount'),starStateClass={fill:'mFill',empty:'mEmpty'},advantageField=$('.jsAdvantage'),disadvantageField=$('.jsDisadvantage'),extractField=$('.jsExtract'),authorNameField=$('.jsAuthorName'),authorEmailField=$('.jsAuthorEmail'),validationConfig={fields:[{fieldNode:advantageField,require:true,customErr:'Не указаны достоинства'},{fieldNode:disadvantageField,require:true,customErr:'Не указаны недостатки'},{fieldNode:extractField,require:true,customErr:'Не указан комментарий'},{fieldNode:authorNameField,require:true,customErr:'Не указано имя'},{fieldNode:authorEmailField,require:true,customErr:'Не указан e-mail',validBy:'isEmail'}]},validator=new FormValidator(validationConfig);var
openPopup=function openPopup(){reviewPopup.lightbox_me({centered:true,autofocus:true,onLoad:function(){}});return false;},formErrorHandler=function formErrorHandler(formError){var field=$('[name="review['+formError.field+']"]');var clearError=function clearError(){validator._unmarkFieldError($(this));};console.warn('Ошибка в поле');validator._markFieldError(field,formError.message);field.bind('focus',clearError);return false;},showError=function showError(msg){var error=$('ul.error_list',form);if(error.length){error.html('<li>'+msg+'</li>');}
else{$('.bFormLogin__ePlaceTitle',form).after($('<ul class="error_list" />').append('<li>'+msg+'</li>'));$(form).prepend($('<ul class="error_list" />').append('<li>'+msg+'</li>'));}
return false;},serverErrorHandler=function serverErrorHandler(res){var formError=null;console.warn('Обработка ошибок формы');for(var i=res.form.error.length-1;i>=0;i--){formError=res.form.error[i];console.warn(formError);if(formError.field!=='global'&&formError.message!==null){formErrorHandler(formError);}
else if(formError.field==='global'&&formError.message!==null){showError(formError.message);}}
return false;},responseFromServer=function responseFromServer(response){console.log('Ответ от сервера');if(response.error){console.warn('Form has error');serverErrorHandler(response);return false;}
if(response.success){if(response.notice.message){form.before(response.notice.message);}
form.hide();}
return false;},formSubmit=function formSubmit(){var requestToServer=function requestToServer(){$.post(form.attr('action'),form.serializeArray(),responseFromServer,'json');console.log('Сабмит формы "Отзыв о товаре"');return false;};if($('ul.error_list',form).length){$('ul.error_list',form).html('');}
validator.validate({onInvalid:function(err){console.warn('invalid');console.log(err);},onValid:requestToServer});return false;},fillStars=function fillStars(count){reviewStar.removeClass(starStateClass['fill']).removeClass(starStateClass['empty']);reviewStar.each(function(index){if(index+1<=count){$(this).addClass(starStateClass['fill']);}
else{$(this).addClass(starStateClass['empty']);}});},hoverStar=function hoverStar(){var nowStar=$(this),starIndex=nowStar.index()+1;fillStars(starIndex);},unhoverStar=function unhoverStar(){var nowStarCount=reviewStarCount.val();fillStars(nowStarCount);},markStar=function markStar(){var nowStar=$(this),starIndex=nowStar.index()+1;reviewStarCount.val(starIndex);fillStars(starIndex);},fillUserData=function fillUserData(e,userInfo){if(userInfo){if(userInfo.name){authorNameField.val(userInfo.name);authorNameField.parent('.jsPlace2Col').hide();}
if(userInfo.email){authorEmailField.val(userInfo.email);authorEmailField.parent('.jsPlace2Col').hide();}
if(userInfo.name&&userInfo.email){authorNameField.parents('.jsFormFieldset').hide();}}};body.on('click','.jsReviewSend',openPopup);body.on('submit','.jsReviewForm',formSubmit);body.on('userLogged',fillUserData);reviewStar.hover(hoverStar,unhoverStar);reviewStar.on('unhover',unhoverStar);reviewStar.on('click',markStar);}());
;(function(){var initVideo=function(){if(!$('#productVideo').length){return false;}
var videoStartTime=0,videoEndTime=0,productUrl=document.location.href,shield=$('.mVideo'),iframe=$('#productVideo .productVideo_iframe').html();var openVideo=function(){$('#productVideo .productVideo_iframe').append(iframe);$('.productVideo_iframe iframe').attr('src',$('.productVideo_iframe iframe').attr('src')+'?autoplay=1');$('#productVideo').lightbox_me({centered:true,onLoad:function(){videoStartTime=new Date().getTime();if(typeof(_gaq)!=='undefined'){_gaq.push(['_trackEvent','Video','Play',productUrl]);}},onClose:function(){$('#productVideo .productVideo_iframe').empty();videoEndTime=new Date().getTime();var videoSpent=videoEndTime-videoStartTime;if(typeof _gaq!=='undefined'){_gaq.push(['_trackEvent','Video','Stop',productUrl,videoSpent]);}}});return false;};$('#productVideo .productVideo_iframe').empty();shield.bind('click',openVideo);};$(document).ready(function(){if($('.mVideo').length){initVideo();}});}());
//@ sourceMappingURL=product.js.map