
;$(function(){$('.js-product-3d-html5-opener').bind('click',function(e){e.preventDefault();$LAB.script('/maybe3dPlayer/player.min.js').wait(function(){$('.js-product-3d-html5-popup').lightbox_me({centered:true,closeSelector:'.jsPopupCloser',onLoad:function(){var $popup=$('.js-product-3d-html5-popup');Maybe3D.Starter.setModelPathHTML5($popup.data('url'));Maybe3D.Starter.embed($popup.data('id'),'js-product-3d-html5-popup-model');},onClose:function(){$('#js-product-3d-html5-popup-model').empty();}});});});$('.js-product-3d-swf-opener').bind('click',function(e){e.preventDefault();$LAB.script('swfobject.min.js').wait(function(){try{if(!$('#js-product-3d-swf-popup-model').length){$('.js-product-3d-swf-popup-container').append('<div id="js-product-3d-swf-popup-model"></div>');}
var
swfId='js-product-3d-swf-popup-object',$popup=$('.js-product-3d-swf-popup');swfobject.embedSWF($popup.data('url'),'js-product-3d-swf-popup-model','700px','500px','10.0.0','js/vendor/expressInstall.swf',{language:'auto'},{menu:'false',scale:'noScale',allowFullscreen:'true',allowScriptAccess:'always',wmode:'direct'},{id:swfId});$popup.lightbox_me({centered:true,closeSelector:'.jsPopupCloser',onClose:function(){swfobject.removeSWF(swfId);}});}
catch(err){}});});$('.js-product-3d-img-opener').bind('click',function(e){e.preventDefault();$LAB.script('DAnimFramePlayer.min.js').wait(function(){var
$element=$('.js-product-3d-img-popup'),data=$element.data('value'),host=$element.data('host');try{if(!$('#js-product-3d-img-container').length){(new DAnimFramePlayer($element[0],host)).DoLoadModel(data);}
$element.lightbox_me({centered:true,closeSelector:'.jsPopupCloser'});}
catch(err){}});});});
+function($){'use strict';function ScrollSpy(element,options){this.$body=$(document.body)
this.$scrollElement=$(element).is(document.body)?$(window):$(element)
this.options=$.extend({},ScrollSpy.DEFAULTS,options)
this.selector=(this.options.target||'')+' .nav li > a'
this.offsets=[]
this.targets=[]
this.activeTarget=null
this.scrollHeight=0
this.$scrollElement.on('scroll.bs.scrollspy',$.proxy(this.process,this))
this.refresh()
this.process()}
ScrollSpy.VERSION='3.3.4'
ScrollSpy.DEFAULTS={offset:10}
ScrollSpy.prototype.getScrollHeight=function(){return this.$scrollElement[0].scrollHeight||Math.max(this.$body[0].scrollHeight,document.documentElement.scrollHeight)}
ScrollSpy.prototype.refresh=function(){var that=this
var offsetMethod='offset'
var offsetBase=0
this.offsets=[]
this.targets=[]
this.scrollHeight=this.getScrollHeight()
if(!$.isWindow(this.$scrollElement[0])){offsetMethod='position'
offsetBase=this.$scrollElement.scrollTop()}
this.$body.find(this.selector).map(function(){var $el=$(this)
var href=$el.data('target')||$el.attr('href')
var $href=/^#./.test(href)&&$(href)
return($href&&$href.length&&$href.is(':visible')&&[[$href[offsetMethod]().top+offsetBase,href]])||null}).sort(function(a,b){return a[0]-b[0]}).each(function(){that.offsets.push(this[0])
that.targets.push(this[1])})}
ScrollSpy.prototype.process=function(){var scrollTop=this.$scrollElement.scrollTop()+this.options.offset
var scrollHeight=this.getScrollHeight()
var maxScroll=this.options.offset+scrollHeight-this.$scrollElement.height()
var offsets=this.offsets
var targets=this.targets
var activeTarget=this.activeTarget
var i
if(this.scrollHeight!=scrollHeight){this.refresh()}
if(scrollTop>=maxScroll){return activeTarget!=(i=targets[targets.length-1])&&this.activate(i)}
if(activeTarget&&scrollTop<offsets[0]){this.activeTarget=null
return this.clear()}
for(i=offsets.length;i--;){activeTarget!=targets[i]&&scrollTop>=offsets[i]&&(offsets[i+1]===undefined||scrollTop<offsets[i+1])&&this.activate(targets[i])}}
ScrollSpy.prototype.activate=function(target){this.activeTarget=target
this.clear()
var selector=this.selector+'[data-target="'+target+'"],'+
this.selector+'[href="'+target+'"]'
var active=$(selector).parents('li').addClass('active')
if(active.parent('.dropdown-menu').length){active=active.closest('li.dropdown').addClass('active')}
active.trigger('activate.bs.scrollspy')}
ScrollSpy.prototype.clear=function(){$(this.selector).parentsUntil(this.options.target,'.active').removeClass('active')}
function Plugin(option){return this.each(function(){var $this=$(this)
var data=$this.data('bs.scrollspy')
var options=typeof option=='object'&&option
if(!data)$this.data('bs.scrollspy',(data=new ScrollSpy(this,options)))
if(typeof option=='string')data[option]()})}
var old=$.fn.scrollspy
$.fn.scrollspy=Plugin
$.fn.scrollspy.Constructor=ScrollSpy
$.fn.scrollspy.noConflict=function(){$.fn.scrollspy=old
return this}
$(window).on('load.bs.scrollspy.data-api',function(){$('[data-spy="scroll"]').each(function(){var $spy=$(this)
Plugin.call($spy,$spy.data())})})}(jQuery);
$(function(){var $productCardData=$('#jsProductCard');if(!$productCardData.length||$('body').data('template')!='product_card'){return;}
var
product=$productCardData.data('value')||{},query=$.deparam((location.search||'').slice(1)),reviewsYandexClick=function(e){console.log('reviewsYandexClick');var
link=this;if('undefined'!==product.article){_gaq.push(['_trackEvent','YM_link',product.article]);e.preventDefault();if('undefined'!==link){setTimeout(function(){link.click();},500);}}};ENTER.utils.analytics.productPageSenders.add(product.ui,query.sender);ENTER.utils.analytics.productPageSenders2.add(product.ui,query.sender2);if(typeof _gaq!=='undefined'){$('a.reviewLink.yandex').each(function(){$(this).one("click",reviewsYandexClick);});}});
;(function(){var creditBoxNode=$('.creditbox');if(creditBoxNode.length>0){var	$body=$(document.body),priceNode=creditBoxNode.find('.creditbox__sum strong');window.creditBox={init:function(){var	creditd=$('input[name=dc_buy_on_credit]').data('model'),label=creditBoxNode.find('label');$('.jsProductCreditRadio').on('change',function(){var status=$(this).val(),$link=$('.js-WidgetBuy .jsBuyButton');if($link.length>0){$link.attr('href',ENTER.utils.setURLParam('credit',status,$link.attr('href')));$link.attr('href',ENTER.utils.setURLParam('sender2','credit',$link.attr('href')));}});if(typeof window.dc_getCreditForTheProduct=='function')dc_getCreditForTheProduct(4427,window.docCookies.getItem('enter_auth'),'getPayment',{price:creditd.price,count:1,type:creditd.product_type},function(result){if(!'payment'in result){return;}
if(result.payment>0){priceNode.html(printPrice(Math.ceil(result.payment)));creditBoxNode.show();}});}};if(ENTER.config.userInfo){if($.isArray(ENTER.config.userInfo.cartProducts)){var product_id=$('#jsProductCard').data('value')['id'];$.each(ENTER.config.userInfo.cartProducts,function(i,val){if(val['isCredit']&&val['id']==product_id){$('#creditinput').attr('checked',true).trigger('change')}})}}
$body.on('click','.jsProductCreditRadio',function(){$body.trigger('trackGoogleEvent',['Credit','Выбор опции','Карточка товара']);});creditBox.init();}
else{var	productDesc=$('.bProductDesc');if(productDesc.length&&!productDesc.hasClass('mNoCredit')){productDesc.addClass('mNoCredit');}}}());
(function(){$('.js-show-shops').on('click',function(){var popup=$('.shopsPopup'),buyButtons=$('.shopsPopup .jsBuyButton');popup.lightbox_me({centered:true,autofocus:true});buyButtons.on('click',function(){popup.trigger('close')});});}());
;(function(){var initFotoSlider=function(){var slider=$('.js-photoslider');var fotoBox=slider.find('.js-photoslider-gal');var leftArr=slider.find('.js-photoslider-btn-prev');var rightArr=slider.find('.js-photoslider-btn-next');var photos=fotoBox.find('.js-photoslider-gal-i');if(!photos.length){return false;}
var itemW=photos.width()+parseInt(photos.css('marginLeft'),10)+parseInt(photos.css('marginRight'),10);var nowLeft=0;fotoBox.css({'width':photos.length*itemW,'left':nowLeft});var checkArrow=function(){if(nowLeft>0){leftArr.show();}
else{leftArr.hide();}
if(nowLeft<fotoBox.width()-slider.width()){rightArr.show();}
else{rightArr.hide();}};var prevFoto=function(){nowLeft=nowLeft-itemW;fotoBox.animate({'left':-nowLeft});checkArrow();return false;};var nextFoto=function(){nowLeft=nowLeft+itemW;fotoBox.animate({'left':-nowLeft});checkArrow();return false;};checkArrow();leftArr.bind('click',prevFoto);rightArr.bind('click',nextFoto);};$(document).ready(function(){if($('.js-photoslider').length){initFotoSlider();}});})();
(function(){var hintShower=function(){var hintPopup=$('.bHint_ePopup');var hintLnk=$('.bHint_eLink');var hintCloseLnk=$('.bHint_ePopup .close');var hintAnalytics=function(data){if(typeof(_gaq)!=='undefined'){_gaq.push(['_trackEvent','Hints',data.hintTitle,data.url]);}};var hintShow=function(){hintPopup.hide();$(this).parent().find('.bHint_ePopup').fadeIn(150);var analyticsData={hintTitle:$(this).html(),url:window.location.href};hintAnalytics(analyticsData);return false;};var hintClose=function(){hintPopup.fadeOut(150);return false;};hintLnk.bind('click',hintShow);hintCloseLnk.bind('click',hintClose);};$(document).ready(function(){if($('.bHint').length){hintShower();}});}());
;$(function(){var $opener=$('.js-lowPriceNotifier-opener');if($opener.length){var
data=$('.js-lowPriceNotifier').data('values'),$popup,$email,$error,$subscribe;function showPopup(e){e.preventDefault();if(!$popup){$opener.after($(Mustache.render($('#tpl-lowPriceNotifier-popup').html(),{price:data.price,userOfficeUrl:data.userOfficeUrl,actionChannelName:data.actionChannelName,isSubscribedToActionChannel:ENTER.config.userInfo.user.isSubscribedToActionChannel,showUserEmailNotify:ENTER.config.userInfo.user.isLogined&&!ENTER.config.userInfo.user.email,userEmail:ENTER.config.userInfo.user.email})));$popup=$('.js-lowPriceNotifier-popup');$email=$('.js-lowPriceNotifier-popup-email');$error=$('.js-lowPriceNotifier-popup-error');$subscribe=$('.js-lowPriceNotifier-popup-subscribe');$('.js-lowPriceNotifier-popup-submit').on('click',submit);$popup.find('.js-lowPriceNotifier-popup-close').on('click',function(e){e.preventDefault();hidePopup();});}
$popup.fadeIn(300);}
function hidePopup(){$popup.fadeOut(300);}
function submit(e){e.preventDefault();$.get(data.submitUrl+(data.submitUrl.indexOf('?')==-1?'?':'&')+'email='+encodeURIComponent($email.val())+'&subscribe='+(checkSubscribe()?1:0),function(res){if(!res.success){$email.addClass('red');if(res.error.message){$error.show().html(res.error.message);}
return false;}
if($subscribe[0]&&$subscribe[0].checked&&typeof _gaq!='undefined'){_gaq.push(['_trackEvent','subscription','subscribe_price_alert',$email.val()]);}
hidePopup();$popup.remove();$opener.remove();});}
function checkSubscribe(){if($subscribe.length&&$subscribe.is(':checked')){return true;}
return false;}
$opener.on('click',showPopup);}});
;+function($){var $body=$(document.body),$imgPopup=$body.find('.jsProductImgPopup'),$popupPhoto=$body.find('.jsProductPopupBigPhoto'),$popupPhotoHolder=$('.jsProductPopupBigPhotoHolder'),$popupPhotoThumbs=$('.jsPopupPhotoThumb'),$productPhotoThumbs=$('.jsProductThumbList'),$productPhotoThumbsBtn=$('.jsProductThumbBtn'),productPhotoThumbsWidth=$productPhotoThumbs.width()-2,productPhotoThumbsFullWidth=$productPhotoThumbs.get(0)?$productPhotoThumbs.get(0).scrollWidth:0,thumbActiveClass='product-card-photo-thumbs__i--act',thumbBtnDisabledClass='product-card-photo-thumbs__btn--disabled',thumbsCount=$popupPhotoThumbs.length,popupDefaults={centered:true,closeSelector:'.jsPopupCloser',preventScroll:true,closeClick:true},setZoom=function(direction){var cssInc=direction<0?'+=':'-=',hInc=direction>0?'+=':'-=',dataZoom=$popupPhoto.data('zoom'),multiply=500;if(typeof dataZoom=='undefined'){if(direction<0)return;else $popupPhoto.data('zoom',direction);}else if(dataZoom==0&&direction<0){return;}else{$popupPhoto.data('zoom',dataZoom+direction)}
$popupPhoto.css('height',hInc+multiply).css('top',cssInc+multiply/2).css('left',cssInc+multiply/2);if(dataZoom==1&&direction<0)$popupPhoto.css('top','0px').css('left','0px');},setPhoto=function(index){$popupPhotoThumbs.removeClass(thumbActiveClass).eq(index).addClass(thumbActiveClass);$popupPhoto.css('top','0px').css('left','0px').css('height',$popupPhotoHolder.height()).data('zoom',0);$popupPhoto.attr('src',$popupPhotoThumbs.eq(index).data('big-img'));};$popupPhotoHolder.on('mousemove mouseleave wheel',function(e){var parentOffset=$(this).parent().offset(),relX=e.pageX-parentOffset.left,relY=e.pageY-parentOffset.top,hW=$(this).width(),hH=$(this).height(),iW=$popupPhoto.width(),iH=$popupPhoto.height();if(e.type=='wheel'){setZoom(e.originalEvent['deltaY']<0?1:-1);e.stopPropagation();}
if(typeof $popupPhoto.data('zoom')=='undefined'||$popupPhoto.data('zoom')==0)return;if(e.type=='mousemove')$popupPhoto.css('left',relX/hW*(hW-iW)).css('top',relY/hH*(hH-iH));if(e.type=='mouseleave')$popupPhoto.css('left',(hW-iW)/2).css('top',(hH-iH)/2);});$body.on('click','.jsOpenProductImgPopup',function(){var $activeThumb=$('.'+thumbActiveClass);$imgPopup.find('.jsProductPopupBigPhoto').attr('src',$activeThumb.data('big-img'));$popupPhotoThumbs.removeClass(thumbActiveClass).eq($activeThumb.index()).addClass(thumbActiveClass);$imgPopup.lightbox_me(popupDefaults);});$body.find('.jsProductPhotoThumb').on('click',function(){var $this=$(this);$this.siblings().removeClass('product-card-photo-thumbs__i--act');$this.addClass('product-card-photo-thumbs__i--act');$body.find('.jsProductMiddlePhoto').attr('src',$this.data('middle-img'));});$body.on('click','.jsProductPopupZoom',function(){var direction=parseInt($(this).data('dir'),10);setZoom(direction);});$body.on('click','.jsProductPopupSlide',function(){var direction=$(this).data('dir'),curIndex=$popupPhotoThumbs.index($imgPopup.find('.'+thumbActiveClass));if(curIndex+direction==thumbsCount)setPhoto(0);else setPhoto(curIndex+direction);});$popupPhotoThumbs.on('click',function(){setPhoto($popupPhotoThumbs.index($(this)));});$productPhotoThumbsBtn.on('click',function(){if(!$productPhotoThumbs.is(':animated'))
$productPhotoThumbs.animate({'margin-left':$(this).data('dir')+productPhotoThumbsWidth},function(){var margin=parseInt($productPhotoThumbs.css('margin-left'));$productPhotoThumbsBtn.removeClass(thumbBtnDisabledClass);if(productPhotoThumbsFullWidth+margin<productPhotoThumbsWidth)$productPhotoThumbsBtn.eq(1).addClass(thumbBtnDisabledClass);if(margin>0)$productPhotoThumbsBtn.eq(0).addClass(thumbBtnDisabledClass);});});$body.on('click','.jsProductMediaButton',function(e){var $popup=$(e.target).next(),$iframe=$popup.find('iframe'),src=$iframe.data('src'),$3dContainer=$popup.find('.jsProduct3DContainer'),$3DJSONContainer=$popup.find('.jsProduct3DJSON');if(src)$iframe.attr('src',src);if($3dContainer.length==0&&$3DJSONContainer.length==0){$popup.lightbox_me($.extend(popupDefaults,{destroyOnClose:true,onClose:function(){$iframe.removeAttr('src');$(e.target).parent().append($popup.clone().hide());}}))}else{if($3dContainer.data('type')=='swf'){$LAB.script('swfobject.min.js').wait(function(){var id='js-product-3d-swf-popup-object';swfobject.embedSWF($3dContainer.data('url'),'js-product-3d-swf-popup-model','700px','500px','10.0.0','js/vendor/expressInstall.swf',{language:'auto'},{menu:'false',scale:'noScale',allowFullscreen:'true',allowScriptAccess:'always',wmode:'direct'},{id:id});$popup.lightbox_me($.extend(popupDefaults,{onClose:function(){$(e.target).parent().append($popup.clone().hide());}}))});}else if($3DJSONContainer.length>0){$LAB.script('DAnimFramePlayer.min.js').wait(function(){var data=$3DJSONContainer.data('value'),host=$3DJSONContainer.data('host');try{if(!$('#js-product-3d-img-container').length){(new DAnimFramePlayer($3DJSONContainer[0],host)).DoLoadModel(data);}
$popup.lightbox_me($.extend(popupDefaults,{onClose:function(){$(e.target).parent().append($popup.clone().hide());}}));}
catch(err){console.error(err)}});}}});}(jQuery);
;(function($){var $window=$(window),$body=$(document.body),$creditButton=$body.find('.jsProductCreditButton'),$reviewFormStars=$('.jsReviewFormRating'),$userbar=$('.js-topbar-fixed'),$tabs=$('.jsProductTabs'),$epFishka=$('.js-pp-ep-fishka'),tabsOffset,popupDefaults={centered:true,closeSelector:'.jsPopupCloser',closeClick:true};if(!$body.hasClass('product-card-new'))return;tabsOffset=$tabs.offset().top;if($creditButton.length>0&&typeof window['dc_getCreditForTheProduct']=='function'){window['dc_getCreditForTheProduct'](4427,window.docCookies.getItem('enter_auth'),'getPayment',{price:$creditButton.data('credit')['price'],count:1,type:$creditButton.data('credit')['product_type']},function(result){if(typeof result['payment']!='undefined'&&result['payment']>0){$creditButton.find('.jsProductCreditPrice').text(printPrice(Math.ceil(result['payment'])));$creditButton.show();}})}
$body.on('click','.jsReviewAdd',function(){var user=ENTER.config.userInfo.user;if(user.name)$('[name=review\\[author_name\\]]').val(user.name);if(user.email)$('[name=review\\[author_email\\]]').val(user.email);$('.jsReviewForm2').lightbox_me($.extend(popupDefaults,{onLoad:function(){},onClose:function(){}}));});$body.on('click','.jsShowMoreReviews',function(){var productUi=$(this).data('ui'),totalNum=$(this).data('total-num'),$hiddenReviews=$('.jsReviewItem:hidden'),currentCount;if($hiddenReviews.length>0){$hiddenReviews.show();if($('.jsReviewItem').length==totalNum)$('.jsShowMoreReviews').hide();}else{currentCount=$('.jsReviewItem').length;$.ajax('/product-reviews/'+productUi,{data:{page:currentCount/10,numOnPage:10}}).done(function(data){if(data.content){$('.jsReviewsList').append(data.content);if($('.jsReviewItem').length==totalNum)$('.jsShowMoreReviews').hide();}});}});if($tabs.length){$window.on('scroll',function(){var fixedClass='pp-fixed';if($window.scrollTop()-100>tabsOffset){$tabs.addClass(fixedClass);$epFishka.addClass('fadeIn');$userbar.addClass(fixedClass);}else{$tabs.removeClass(fixedClass);$epFishka.removeClass('fadeIn');$userbar.removeClass(fixedClass);}});}
$body.scrollspy({target:'#jsScrollSpy',offset:120});$body.on('click','.jsProductTabs a',function(e){var hash=$(this).attr('href');e.preventDefault();window.location.hash=hash;window.scrollTo(0,$(hash).offset().top-105);});$body.on('click','.jsOneClickButtonOnDeliveryMap',function(){$('.jsProductPointsMap').trigger('close');});$body.on('click','.jsShowDeliveryMap',function(){var productId=$(this).data('product-id'),productUi=$(this).data('product-ui'),$div=$('.jsProductPointsMap');if($('.jsDeliveryPickupAvailable').length==0)return;if($div.find('.jsDeliveryMapPoints').length>0){$div.lightbox_me({centered:true,preventScroll:true});return;}
if($div.data('xhr'))return;$.ajax('/ajax/product/map/'+productId+'/'+productUi,{dataType:'json',beforeSend:function(){$div.data('xhr',true);$div.lightbox_me({centered:true,preventScroll:true})}}).always(function(){$div.data('xhr',false)}).done(function(data){if(!data.success){console.error('product/map response: %s',data.error);}else{var $mapContainer=$(data.html),mapData=$.parseJSON($mapContainer.find('.jsMapData').html()),mapDivId=$mapContainer.find('.js-order-map').first().attr('id'),yMap,pointsModel;$div.html(data.html);$body.on('click','.jsCloseFl',function(){$div.trigger('close');});if(mapData){yMap=new ymaps.Map(mapDivId,{center:[mapData.latitude,mapData.longitude],zoom:mapData.zoom},{autoFitToViewport:'always'});yMap.controls.remove('searchControl');yMap.geoObjects.removeAll();yMap.container.fitToViewport();pointsModel=new ENTER.DeliveryPoints(mapData.points,yMap);yMap.events.add('boundschange',function(event){var bounds;if(event.get('newBounds')){bounds=event.get('target').getBounds();pointsModel.latitudeMin(bounds[0][0]);pointsModel.latitudeMax(bounds[1][0]);pointsModel.longitudeMin(bounds[0][1]);pointsModel.longitudeMax(bounds[1][1]);}});$.each(mapData.points,function(i,point){try{yMap.geoObjects.add(new ENTER.Placemark(point,true,'jsOneClickButtonOnDeliveryMap jsOneClickButton-new'));}catch(e){console.error('Ошибка добавления точки на карту',e);}});if(yMap.geoObjects.getLength()===1){yMap.setCenter(yMap.geoObjects.get(0).geometry.getCoordinates(),15);yMap.geoObjects.get(0).options.set('visible',true);}else{yMap.setBounds(yMap.geoObjects.getBounds());yMap.events.once('boundschange',function(event){if(event.get('oldZoom')<event.get('newZoom')){yMap.geoObjects.each(function(point){point.options.set('visible',true)})}})}
ko.applyBindings(pointsModel,$div[0]);$body.on('click','.jsOrderV3Dropbox',function(){$(this).siblings().removeClass('opn').find('.jsOrderV3DropboxInner').hide();$(this).find('.jsOrderV3DropboxInner').toggle();$(this).hasClass('opn')?$(this).removeClass('opn'):$(this).addClass('opn');});}}})});$('.js-slider-2').goodsSlider({leftArrowSelector:'.goods-slider__btn--prev',rightArrowSelector:'.goods-slider__btn--next',sliderWrapperSelector:'.goods-slider__inn',sliderSelector:'.goods-slider-list',itemSelector:'.goods-slider-list__i',categoryItemSelector:'.js-product-accessoires-category',onLoad:function(goodsSlider){ko.applyBindings(ENTER.UserModel,goodsSlider);if($(goodsSlider).data('position')=='ProductSimilar')$('.jsSimilarTab').show();}});$reviewFormStars.on('click',function(){var activeClass='popup-rating__i--fill',rate=$(this).index();$reviewFormStars.removeClass(activeClass);$(this).addClass(activeClass).prevAll().addClass(activeClass);$('#reviewFormRating').val(++rate)});$('#reviewForm').on('submit',function(e){var $form=$(this),textareaErrClass='form-ctrl__textarea--err',inputErrClass='form-ctrl__input--err',textareaLblErrClass='form-ctrl__textarea-lbl--err';e.preventDefault();$.ajax({type:'post',url:$(this).attr('action'),data:$(this).serializeArray(),dataType:'json',success:function(data){if(data.error){console.log('errors in review form',data);$.each(data.form.error,function(i,val){var $field=$form.find('[name="review['+val.field+']"]');$field.removeClass(textareaErrClass).removeClass(inputErrClass);if(val.message){if($field.is('textarea')){$field.addClass(textareaErrClass);$field.siblings('.'+textareaLblErrClass).show();}
if($field.is('input'))$field.addClass(inputErrClass);}else{$field.siblings('.'+textareaLblErrClass).hide();}});}else if(data.success){var $successDiv=$('.jsReviewSuccessAdd');$('.jsReviewFormInner').hide();$('.jsReviewForm2').animate({'height':$successDiv.height()});$successDiv.fadeIn();}},complete:function(data){}});});$body.on('click','.jsReviewVote',function(e){var $button=$(e.target),buttonVote=$button.data('vote'),$voteDiv=$(this),userVote=$voteDiv.data('user-vote'),reviewUi=$voteDiv.closest('.jsReviewItem').data('review-ui'),$voteButtons=$voteDiv.find('.jsReviewVoteBtn'),activeClass='active',voteClass='voting';if($voteDiv.data('xhr'))return;$.ajax('/product-reviews/vote',{type:'post',data:{'review-ui':reviewUi,'vote':userVote==buttonVote?0:buttonVote},beforeSend:function(){$button.addClass(voteClass);$voteDiv.data('xhr',true);},success:function(data){if(data.success){$voteDiv.data('user-vote',data.vote);$voteDiv.find('.jsReviewVoteBtn').removeClass(activeClass);if(data.vote!=0)$voteButtons.eq(data.vote==1?0:1).addClass(activeClass);if(typeof data.positive!='undefined')$voteButtons.eq(0).text(data.positive);if(typeof data.negative!='undefined')$voteButtons.eq(1).text(data.negative);}else{console.error('Ошибка голосования: %s',data.error)}}}).always(function(){$button.removeClass(voteClass);$voteDiv.data('xhr',false);})});$('.jsProductPartnerOffer').on('click',function(e){e.preventDefault();var link=$(this).attr('href'),$offer=$('.jsProductPartnerOfferDiv');if(!link)return;link=link.replace(/^http:\/\/.*?\//,'/');if($offer.length==0){$.get(link).done(function(doc){$('<div class="jsProductPartnerOfferDiv partner-offer-popup"></div>').append($('<i class="closer jsPopupCloser">×</i>'),$('<div class="inn" />').append($(doc).find('h1'),$(doc).find('article'))).lightbox_me(popupDefaults)});}else{$offer.lightbox_me(popupDefaults)}});$body.on('click','.jsImageInLightBox',function(e){e.preventDefault();var imageLink=$(this).data('href');$('<div />',{'style':'background-color: #fff'}).append($('<img />',{src:imageLink})).lightbox_me({destroyOnClose:true,centered:true});});$body.on('click','.jsProductImgPopup .jsBuyButton',function(){$(this).closest('.jsProductImgPopup').trigger('close');});$('.js-description-expand').on('click',function(){$(this).removeClass('collapsed js-description-expand');});$body.on('click','.jsProductCardNewLabelInfo',function(){$('.jsProductCardNewLabelPopup').toggleClass('info-popup--open');});})(jQuery);!function(){var
countDownWrapper=$('.js-countdown'),countDownOut=$('.js-countdown-out'),expDate=countDownWrapper.attr('data-expires'),getDeclension=function(days){var
str=days+'',lastChar=str.slice(-1),lastNum=lastChar*1;if(days>4&&days<21){return'дней';}else if(lastNum>4&&days>20){return'дней';}else if(lastNum>1&&lastNum<5){return'дня';}
return'день';},tick=function(opts){var
mask=(opts.days>0)?'D '+getDeclension(opts.days)+' HH:MM:SS':'HH:MM:SS';mask=mask.replace(/(D+)/,function(str,d){return(d.length>1&&opts.days<10)?'0'+opts.days:opts.days});mask=mask.replace(/(H+)/,function(str,h){return(h.length>1&&opts.hours<10)?'0'+opts.hours:opts.hours});mask=mask.replace(/(M+)/,function(str,m){return(m.length>1&&opts.minutes<10)?'0'+opts.minutes:opts.minutes});mask=mask.replace(/(S+)/,function(str,s){return(s.length>1&&opts.seconds<10)?'0'+opts.seconds:opts.seconds});countDownOut.html(mask);},countDown;try{countDown=new CountDown({timestamp:expDate*1000,tick:tick});}catch(err){console.warn('Не удалось запустить обратный счетчик акции');console.warn(err);}}();
$(document).ready(function(){var $productDescriptionToggle=$('#productDescriptionToggle');(function(){var
thumbImageActiveClass='prod-photoslider__gal__link--active',$image=$('.js-photo-zoomedImg');if(!$image.length){console.warn('Нет изображения для elevateZoom');return;}
var zoomConfig={$imageContainer:$('.js-product-bigImg'),zoomWindowOffety:0,zoomWindowOffetx:19,zoomWindowWidth:$image.data('is-slot')?344:519,borderSize:1,borderColour:'#C7C7C7'};if($image.data('zoom-image')){$image.elevateZoom(zoomConfig);}
$('.jsPhotoGalleryLink').on('click',function(e){e.preventDefault();var $link=$(e.currentTarget);if($link.hasClass(thumbImageActiveClass)){return;}
$('.jsPhotoGalleryLink').removeClass(thumbImageActiveClass);$link.addClass(thumbImageActiveClass);if($image.data('elevateZoom')){$image.data('elevateZoom').destroy();}
if($link.data('zoom-image')){$image.data('zoom-image',$link.data('zoom-image'));$image.one('load',function(){$image.elevateZoom(zoomConfig);});}
$image.attr('src',$link.data('image'));});})();$('.bCountSection').goodsCounter({onChange:function(count){var spinnerFor=this.attr('data-spinner-for'),bindButton=$('.'+spinnerFor),bindOneClickButton=$('.'+spinnerFor+'-oneClick'),newHref=bindButton.attr('href')||'';bindButton.attr('href',newHref.addParameterToUrl('quantity',count));bindOneClickButton.data('quantity',count);}});$('.js-slider').goodsSlider({onLoad:function(goodsSlider){ko.applyBindings(ENTER.UserModel,goodsSlider);}});$('.bDescSelectItem').customDropDown({changeHandler:function(option){document.location.href=option.data('url');}});if($productDescriptionToggle.length){$productDescriptionToggle.toggle(function(e){e.preventDefault();$(this).parent().parent().find('.descriptionlist:not(.short)').show();$(this).html('Скрыть все характеристики');},function(e){e.preventDefault();$(this).parent().parent().find('.descriptionlist:not(.short)').hide();$(this).html('Показать все характеристики');});}
try{var
productId=ENTER.config.pageConfig.product?ENTER.config.pageConfig.product.id:null,cookieValue=docCookies.getItem('product_viewed')||'',viewed=[];if(productId){viewed=cookieValue?ENTER.utils.arrayUnique(cookieValue.split(',')):[];viewed.push(productId);docCookies.setItem('product_viewed',viewed.slice(-20).join(','),7*24*60*60,'/');}}catch(e){console.error(e);}});
;(function(){var
$window=$(window),$body=$(document.body),$reviewWrap=$('.js-reviews-wrapper'),$reviewList=$('.js-reviews-list'),$moreReviewsButton=$('.js-reviews-getMore'),reviewCurrentPage=0,reviewPageCount=$reviewWrap.attr('data-page-count'),productUi=$reviewWrap.attr('data-product-ui'),avgScore=$reviewWrap.data('avg-score'),firstPageAvgScore=$reviewWrap.data('first-page-avg-score'),categoryName=$reviewWrap.data('category-name');if(!$reviewWrap.length){return;}
$moreReviewsButton.click(function(){$.ajax({type:'GET',url:ENTER.utils.generateUrl('product.reviews.get',{productUi:productUi}),data:{page:reviewCurrentPage+1},success:function(data){$reviewList.html($reviewList.html()+data.content);reviewCurrentPage++;reviewPageCount=data.pageCount;if(reviewCurrentPage+1>=reviewPageCount){$moreReviewsButton.hide();}else{$moreReviewsButton.show();}}});});(function(){var timer;function checkReviewsShowing(){var windowHeight=$window.height();if($window.scrollTop()+windowHeight>$reviewWrap.offset().top){if(!timer){timer=setTimeout(function(){$window.unbind('scroll',checkReviewsShowing);$body.trigger('trackGoogleEvent',{category:'Items_review',action:'All_'+avgScore+'_Top_'+firstPageAvgScore,label:categoryName});ENTER.utils.analytics.reviews.add(productUi,avgScore,firstPageAvgScore,categoryName);},2000);}}else{if(timer){clearTimeout(timer);timer=null;}}}
$window.scroll(checkReviewsShowing);checkReviewsShowing();})();}());(function(){var body=$('body'),reviewPopup=$('.jsReviewPopup'),form=reviewPopup.find('.jsReviewForm'),submitReviewButton=$('.jsFormSubmit'),submitReviewButtonText=submitReviewButton.val(),reviewStar=form.find('.stars-list__item'),reviewStarCount=form.find('.jsReviewStarsCount'),starStateClass={fill:'star-fill',empty:'star-empty'},advantageField=$('.jsAdvantage'),disadvantageField=$('.jsDisadvantage'),extractField=$('.jsExtract'),authorNameField=$('.jsAuthorName'),authorEmailField=$('.jsAuthorEmail'),validationConfig={fields:[{fieldNode:advantageField,require:true,customErr:'Не указаны достоинства'},{fieldNode:disadvantageField,require:true,customErr:'Не указаны недостатки'},{fieldNode:extractField,require:true,customErr:'Не указан комментарий'},{fieldNode:authorNameField,require:true,customErr:'Не указано имя'},{fieldNode:authorEmailField,require:true,customErr:'Не указан e-mail',validBy:'isEmail'}]},validator=new FormValidator(validationConfig);var
openPopup=function openPopup(){reviewPopup.lightbox_me({centered:true,autofocus:true,onLoad:function(){}});return false;},formErrorHandler=function formErrorHandler(formError){var field=$('[name="review['+formError.field+']"]');var clearError=function clearError(){validator._unmarkFieldError($(this));};console.warn('Ошибка в поле');validator._markFieldError(field,formError.message);field.bind('focus',clearError);return false;},showError=function showError(msg){var error=$('ul.error_list',form);if(error.length){error.html('<li>'+msg+'</li>');}
else{$('.bFormLogin__ePlaceTitle',form).after($('<ul class="error_list" />').append('<li>'+msg+'</li>'));$(form).prepend($('<ul class="error_list" />').append('<li>'+msg+'</li>'));}
return false;},serverErrorHandler=function serverErrorHandler(res){var formError=null;console.warn('Обработка ошибок формы');for(var i=res.form.error.length-1;i>=0;i--){formError=res.form.error[i];console.warn(formError);if(formError.field!=='global'&&formError.message!==null){formErrorHandler(formError);}
else if(formError.field==='global'&&formError.message!==null){showError(formError.message);}}
return false;},responseFromServer=function responseFromServer(response){console.log('Ответ от сервера');if(response.error){console.warn('Form has error');serverErrorHandler(response);return false;}
if(response.success){if(response.notice.message){form.before(response.notice.message);}
form.hide();}
return false;},formSubmit=function formSubmit(){if(form.data('disabled')){return false;}
form.data('disabled',true);submitReviewButton.attr('disabled','disabled');submitReviewButton.addClass('mDisabled');submitReviewButton.val('Сохраняю…');if($('ul.error_list',form).length){$('ul.error_list',form).html('');}
function enableSubmitReviewButton(){form.data('disabled',false);submitReviewButton.removeAttr('disabled');submitReviewButton.removeClass('mDisabled');submitReviewButton.val(submitReviewButtonText);}
validator.validate({onInvalid:function(err){console.warn('invalid');console.log(err);enableSubmitReviewButton();},onValid:function(){$.ajax({type:'post',url:form.attr('action'),data:form.serializeArray(),dataType:'json',success:responseFromServer,complete:function(){enableSubmitReviewButton();}});console.log('Сабмит формы "Отзыв о товаре"');return false;}});return false;},fillStars=function fillStars(count){reviewStar.removeClass(starStateClass['fill']).removeClass(starStateClass['empty']);reviewStar.each(function(index){if(index+1<=count){$(this).addClass(starStateClass['fill']);}
else{$(this).addClass(starStateClass['empty']);}});},hoverStar=function hoverStar(){var nowStar=$(this),starIndex=nowStar.index()+1;fillStars(starIndex);},unhoverStar=function unhoverStar(){var nowStarCount=reviewStarCount.val();fillStars(nowStarCount);},markStar=function markStar(){var nowStar=$(this),starIndex=nowStar.index()+1;reviewStarCount.val(starIndex);fillStars(starIndex);},fillUserData=function fillUserData(userInfo){if(userInfo){if(userInfo.name){authorNameField.val(userInfo.name);authorNameField.parent('.jsPlace2Col').hide();}
if(userInfo.email){authorEmailField.val(userInfo.email);authorEmailField.parent('.jsPlace2Col').hide();}
if(userInfo.name&&userInfo.email){authorNameField.parents('.jsFormFieldset').hide();}}};body.on('click','.jsReviewSend',openPopup);body.on('submit','.jsReviewForm',formSubmit);fillUserData(ENTER.config.userInfo.user);reviewStar.hover(hoverStar,unhoverStar);reviewStar.on('unhover',unhoverStar);reviewStar.on('click',markStar);if('#add-review'==location.hash){openPopup();}}());
;$(function(){$('.js-product-similarProducts-link').on('click',function(){$('body').trigger('trackGoogleEvent',{category:'RR_взаимодействие',action:'Перешел на карточку товара',label:'SEO'});});});
;$(function(){var $video=$('.js-product-video');if(!$video.length||!$('.js-product-video-container').length){return;}
var
videoStartTime=0,videoEndTime=0,productUrl=document.location.href,$iframeContainer=$('.js-product-video-iframeContainer'),iframeHtml=$iframeContainer.html();$iframeContainer.empty();$video.bind('click',function(){var $iframeContainer=$('.js-product-video-iframeContainer');$iframeContainer.append(iframeHtml);var $iframe=$('iframe',$iframeContainer);$iframe.attr('src',$iframe.data('src'));$('.js-product-video-container').lightbox_me({centered:true,onLoad:function(){videoStartTime=new Date().getTime();if(typeof(_gaq)!=='undefined'){_gaq.push(['_trackEvent','Video','Play',productUrl]);}},onClose:function(){$('.js-product-video-iframeContainer').empty();videoEndTime=new Date().getTime();var videoSpent=videoEndTime-videoStartTime;if(typeof _gaq!=='undefined'){_gaq.push(['_trackEvent','Video','Stop',productUrl,videoSpent]);}}});return false;});});
//@ sourceMappingURL=product.js.map