Banner:
  options:
    comment: 'Баннер'
  actAs:
    Timestampable: ~
    Corable:       { push: disable }
  columns:
    id:                { type: integer(20), autoincrement: true, primary: true }
    slot_id:           { type: integer(20), notnull: false, default: null }
    token:             { type: string(255), unique: true, notnull: true, notblank: true }
    name:              { type: string(255), notnull: false, default: null, comment: 'название' }
    link:              { type: string(255), notnull: false, default: null, comment: 'ссылка' }
    image:             { type: string(255), notnull: false, default: null, comment: 'оригинальная картинка' }
    position:          { type: integer(4), notnull: true, default: 1, comment: 'Порядок сортировки' }
    is_active:         { type: boolean, notnull: true, default: false }
    is_dummy:          { type: boolean, notnull: true, default: false }
    start_at:          { type: timestamp, format: Y-m-d H:m:i }
    end_at:            { type: timestamp, format: Y-m-d H:m:i }
  relations:
    Slot:              { class: Slot, foreignAlias: Banner, local: slot_id, foreign: id, type: one, foreignType: many, onDelete: 'SET NULL' }

BannerItem:
  options:
    comment: 'Элемент баннера'
  actAs:
    Timestampable: ~
    Corable:       { push: disable }
  columns:
    id:                { type: integer(20), autoincrement: true, primary: true }
    banner_id:         { type: integer(20), notnull: true }
    type:              { type: enum, length: 20, values: [ product ], notnull: true }
    object_id:         { type: integer(20), notnull: false, default: null }
    timeout:           { type: integer(4), notnull: false, default: null }
  relations:
    Banner:            { class: Banner, foreignAlias: Item, local: banner_id, foreign: id, type: one, foreignType: many, onDelete: 'CASCADE' }