Banner:
  options:
    comment: 'Баннер'
  actAs: [ Timestampable ]
  columns:
    id:                { type: integer(20), autoincrement: true, primary: true }
    slot_id:           { type: integer(20), notnull: true }
    token:             { type: string(255), unique: true, notnull: true, notblank: true }
    name:              { type: string(255), notnull: false, default: null, comment: 'название' }
    link:              { type: string(255), notnull: false, default: null, comment: 'ссылка' }
    image:             { type: string(255), notnull: false, default: null, comment: 'оригинальная картинка' }
    image_preview:     { type: string(255), notnull: false, default: null, comment: 'уменьшенная картинка' }
    position:          { type: integer(4), notnull: true, default: 1, comment: 'Порядок сортировки' }
  relations:
    Slot:              { class: Slot, foreignAlias: Banner, local: slot_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }