Callback:
  options:
    comment: 'callback'
  actAs: [ Timestampable, Corable ]
  columns:
    id:                { type: integer(20), autoincrement: true, primary: true }
    category_id:           { type: integer(20), notnull: true }
    name:              { type: string(255), notnull: false, default: null, comment: '' }
    email:              { type: string(255), notnull: false, default: null, comment: '' }
    theme:              { type: string(255), notnull: false, default: null, comment: '' }
    text:              { type: string(255), notnull: false, default: null, comment: '' }