Callback:
  options:
    comment: 'Обратная связь'
  actAs: [ Timestampable, Corable ]
  columns:
    id:                { type: integer(20), autoincrement: true, primary: true }
    core_id:           { type: integer(20), notnull: false, default: null, comment: 'ид записи в Core' }
    category_id:       { type: integer(20), notnull: false }
    channel_id:        { type: integer(20), notnull: false, default: 1, comment: 'Id канала связи - что бы определять, кому отправлять callback на ядре (1- обычныая форма связи, 2 - юридические консультации в ЛК)'}
    user_id:           { type: integer(20), notnull: false, default: null }
    name:              { type: string(255), notnull: false, default: null, comment: '' }
    email:              { type: string(255), notnull: false, default: null, comment: '' }
    theme:              { type: string(255), notnull: false, default: null, comment: '' }
    text:              { type: string, notnull: false, default: null, comment: '' }
  relations:
    Category:      { class: CallbackCategory, foreignAlias: CallbackCategory, local: category_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }
    User:          { class: User, foreignAlias: CallbackUser, local: user_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }

CallbackCategory:
  options:
    comment: 'Категории обратной связи'
  actAs:
    Timestampable:  ~
    Corable:        { push: Disable }
  columns:
    id:             { type: integer(20), autoincrement: true, primary: true }
    name:           { type: string(255), notnull: false, default: null, comment: 'Название категории' }


IpadAction:
  options:
    comment: 'Обратная связь'
  columns:
    id:                { type: integer(20), autoincrement: true, primary: true }
    email:             { type: string(255), notnull: false, default: null, comment: '' }
    phone:             { type: string(255), notnull: false, default: null, comment: '' }
    name:              { type: string(255), notnull: false, default: null, comment: '' }
    product:           { type: string(255), notnull: false, default: null, comment: '' }
    article:           { type: string(255), notnull: false, default: null, comment: '' }
    region:            { type: integer(20), autoincrement: true, primary: true }
    added:             { type: timestamp, format: Y-m-d H:m:i }

