Service:
  options:
    comment: 'Услуга F1'
  actAs:
    Corable:           { push: disable }
  columns:
    id:                { type: integer(20), autoincrement: true, primary: true }
    token:             { type: string(255), unique: true, notnull: true, notblank: true }
    name:              { type: string(255), notnull: true, notblank: true }
    description:       { type: string }
    work:              { type: string }
    expendable:        { type: string }
    is_active:         { type: boolean, notnull: true, default: false }
  relations:
    Category:          { class: ServiceCategory, foreignAlias: Service, refClass: ServiceCategoryRelation, local: service_id, foreign: category_id, type: many, foreignType: many }

ServiceCategory:
  options:
    comment: 'Категория услуг F1'
  actAs:
    NestedSet:  { hasManyRoots: true, rootColumnName: root_id }
    Corable:    { push: disable }
  columns:
    id:                { type: integer(20), autoincrement: true, primary: true }
    root_id:           { type: integer(20), notnull: true }
    core_parent_id:    { type: integer(20), notnull: false, default: null, comment: 'ид родителя записи в Core' }
    lft:               { type: integer(20), notnull: true }
    rgt:               { type: integer(20), notnull: true }
    level:             { type: integer(4), notnull: true }
    token:             { type: string(255), unique: true, notnull: true, notblank: true }
    name:              { type: string(255), notnull: true, notblank: true }
    description:       { type: string }
    is_active:         { type: boolean, notnull: true, default: false }
  relations:
    ProductType:       { class: ProductType, foreignAlias: ServiceCategory, refClass: ServiceCategoryProductTypeRelation, local: category_id, foreign: product_type_id, type: many, foreignType: many }

ServicePrice:
  options:
    comment: 'Стоимость услуг F1 по регионам'
  columns:
    region_id:         { type: integer(20), notnull: true, primary: true }
    service_id:        { type: integer(20), notnull: true, primary: true }
    price:             { type: 'decimal(12,2)', notnull: true, default: 0, comment: 'Цена услуги' }
  relations:
    Service:           { class: Service, foreignAlias: Price, local: service_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }
    Region:            { class: Region, foreignAlias: ServicePrice, local: region_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }

ServiceCategoryProductTypeRelation:
  options:
    comment: 'Связь категории услуги с типом продукта'
  columns:
    category_id:       { type: integer(20), notnull: true, primary: true }
    product_type_id:   { type: integer(20), notnull: true, primary: true }
  relations:
    Category:          { class: ServiceCategory, foreignAlias: ProductTypeRelation, local: category_id, foreign: id, type: one, foreignType: many, onDelete: RESTRICT }
    ProductType:       { class: ProductType, foreignAlias: ServiceCategoryRelation, local: product_type_id, foreign: id, type: one, foreignType: many, onDelete: RESTRICT }

ServiceCategoryRelation:
  options:
    comment: 'Связь категории и услуги'
  columns:
    category_id:       { type: integer(20), notnull: true, primary: true }
    service_id:        { type: integer(20), notnull: true, primary: true }
  relations:
    Category:          { class: ServiceCategory, foreignAlias: ServiceRelation, local: category_id, foreign: id, type: one, foreignType: many, onDelete: RESTRICT }
    Service:           { class: Service, foreignAlias: CategoryRelation, local: service_id, foreign: id, type: one, foreignType: many, onDelete: RESTRICT }
