GuardGroup:
  actAs: [Timestampable]
  columns:
    name:
      type: string(255)
      unique: true
    description: string(1000)
  relations:
    User:
      class: GuardUser
      refClass: GuardUserGroup
      local: group_id
      foreign: user_id
      foreignAlias: Group
    Permission:
      class: GuardPermission
      local: group_id
      foreign: permission_id
      refClass: GuardGroupPermission
      foreignAlias: Group

GuardPermission:
  actAs: [Timestampable]
  columns:
    name:
      type: string(255)
      unique: true
    description: string(1000)

GuardGroupPermission:
  options:
    symfony:
      form:   false
      filter: false
  actAs: [Timestampable]
  columns:
    group_id:
      type: integer
      primary: true
    permission_id:
      type: integer
      primary: true
  relations:
    Group:
      class: GuardGroup
      local: group_id
      onDelete: CASCADE
    Permission:
      class: GuardPermission
      local: permission_id
      onDelete: CASCADE

GuardUser:
  actAs: [Timestampable]
  columns:
    first_name: string(255)
    last_name: string(255)
    email:
      type: string(255)
      notnull: true
      unique: true
    username:
      type: string(128)
      notnull: true
      unique: true
    algorithm:
      type: string(128)
      default: sha1
      notnull: true
    salt: string(128)
    password: string(128)
    is_active:
      type: boolean
      default: 1
    is_super_admin:
      type: boolean
      default: false
    last_login:
      type: timestamp
  indexes:
    is_active_idx:
      fields: [is_active]
  relations:
    Group:
      class: GuardGroup
      local: user_id
      foreign: group_id
      refClass: GuardUserGroup
      foreignAlias: User
    Permission:
      class: GuardPermission
      local: user_id
      foreign: permission_id
      refClass: GuardUserPermission
      foreignAlias: User

GuardUserPermission:
  options:
    symfony:
      form:   false
      filter: false
  actAs: [Timestampable]
  columns:
    user_id:
      type: integer
      primary: true
    permission_id:
      type: integer
      primary: true
  relations:
    User:
      class: GuardUser
      local: user_id
      onDelete: CASCADE
    Permission:
      class: GuardPermission
      local: permission_id
      onDelete: CASCADE

GuardUserGroup:
  options:
    symfony:
      form:   false
      filter: false
  actAs: [Timestampable]
  columns:
    user_id:
      type: integer
      primary: true
    group_id:
      type: integer
      primary: true
  relations:
    User:
      class: GuardUser
      local: user_id
      onDelete: CASCADE
    Group:
      class: GuardGroup
      local: group_id
      onDelete: CASCADE

GuardRememberKey:
  options:
    symfony:
      form:   false
      filter: false
  actAs: [Timestampable]
  columns:
    user_id: integer
    remember_key: string(32)
    ip_address: string(50)
  relations:
    User:
      class: GuardUser
      local: user_id
      foreignAlias: RememberKeys
      foreignType: one
      onDelete: CASCADE

GuardForgotPassword:
  options:
    symfony:
      form:   false
      filter: false
  actAs: [Timestampable]
  columns:
    user_id:
      type: integer
      notnull: true
    unique_key: string(255)
    expires_at:
      type: timestamp
      notnull: true
  relations:
    User:
      class: GuardUser
      local: user_id
      type: one
      foreignType: one
      foreignAlias: ForgotPassword
      onDelete: CASCADE