CacheEraserLog:
  options:
    comment: 'Лог сброса кеша'
  actAs: [ Timestampable ]
  columns:
    id:                { type: integer(20), autoincrement: true, primary: true }
    type:              { type: string(255) }
    entity_id:         { type: integer(20), notnull: true }
    region_id:         { type: integer(20), notnull: false, default: null }
    extra:             { type: string, notnull: false, default: null  }
  relations:
    Region:            { class: Region, local: region_id, foreign: id, type: one, onDelete: SET NULL }
