News:
  options:
    comment: 'Новости'
  actAs: [ Timestampable ]
  columns:
    id:                { type: integer(20), autoincrement: true, primary: true }
    category_id:       { type: integer(20), notnull: true }
    token:             { type: string(255), unique: true, notnull: true, notblank: true }
    name:              { type: string(255), notnull: true, notblank: true }
    preview:           { type: string(500), notnull: true, notblank: true }
    body:              { type: string, notnull: true, notblank: true }
    published_at:      { type: timestamp, format: Y-m-d H:m:i }
    is_active:         { type: boolean, notnull: true, default: false }
    position:          { type: integer(4), notnull: true, default: 1, comment: 'Порядок сортировки' }
  actAs:
    Timestampable:
      created_at:      { name: created_at, type: timestamp, format: Y-m-d H:m:i }
      updated_at:      { name: created_at, type: timestamp, format: Y-m-d H:m:i }
  relations:
    Category:          { class: NewsCategory, foreignAlias: News, local: category_id, foreign: id, type: one, foreignType: many, onDelete: RESTRICT }
    Product:           { class: Product, foreignAlias: News, refClass: NewsProductRelation, onDelete: RESTRICT }
    ProductCategory:   { class: ProductCategory, foreignAlias: News, refClass: NewsProductCategoryRelation, onDelete: RESTRICT }
    Creator:           { class: Creator, foreignAlias: News, refClass: NewsCreatorRelation, onDelete: RESTRICT }

NewsCategory:
  options:
    comment: 'Категория новости'
  actAs: [ Timestampable ]
  columns:
    id:                { type: integer(20), autoincrement: true, primary: true }
    token:             { type: string(255), unique: true, notnull: true, notblank: true }
    name:              { type: string(255), notnull: true, notblank: true }

NewsProductRelation:
  options:
    comment: 'Связь новости с продуктом'
  actAs: [ Timestampable ]
  columns:
    news_id:              { type: integer(20), primary: true }
    product_id:           { type: integer(20), primary: true }
  relations:
    News:                 { class: News, foreignAlias: ProductRelation, local: news_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }
    Product:              { class: Product, foreignAlias: NewsRelation, local: product_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }

NewsProductCategoryRelation:
  options:
    comment: 'Связь новости с категорией товаров'
  actAs: [ Timestampable ]
  columns:
    news_id:              { type: integer(20), primary: true }
    product_category_id:  { type: integer(20), primary: true }
  relations:
    News:                 { class: News, foreignAlias: ProductCategoryRelation, local: news_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }
    ProductCategory:      { class: ProductCategory, foreignAlias: NewsRelation, local: product_category_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }

NewsCreatorRelation:
  options:
    comment: 'Связь новости с производителем'
  actAs: [ Timestampable ]
  columns:
    news_id:              { type: integer(20), primary: true }
    creator_id:           { type: integer(20), primary: true }
  relations:
    News:                 { class: News, foreignAlias: CreatorRelation, local: news_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }
    Creator:              { class: Creator, foreignAlias: NewsRelation, local: creator_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }
