Page:
  options:
    comment: 'Страница'
  actAs:
    NestedSet: { hasManyRoots: true, rootColumnName: root_id }
  columns:
    id:                { type: integer(20), autoincrement: true, primary: true }
    root_id:           { type: integer(20), notnull: true }
    lft:               { type: integer(20), notnull: true }
    rgt:               { type: integer(20), notnull: true }
    level:             { type: integer(4), notnull: true }
    token:             { type: string(255), unique: true, notnull: true, notblank: true }
    name:              { type: string(255), notnull: true, notblank: true }
    title:             { type: string(500), notnull: false, default: null, comment: 'Заголовок страницы title' }
    header:            { type: string(500), notnull: false, default: null, comment: 'Заголовок страницы h1' }
    keywords:          { type: string(500), notnull: false, default: null, comment: 'Ключевые слова страницы meta keywords' }
    description:       { type: string(500), notnull: false, default: null, comment: 'Описание страницы meta description' }
    content:           { type: string, notnull: false, default: null, comment: 'Содержание страницы' }