Qrcode:
  options:
    comment: 'qr-код'
  actAs:
    Timestampable: ~
    Corable:       { push: disable }
  columns:
    id:                     { type: integer(20), autoincrement: true, primary: true }
    token:                  { type: string(255), unique: true, notnull: true, notblank: true }
    content:                { type: string, notnull: false, default: null, comment: '' }
