Region:
  options:
    comment: 'Регион'
  actAs:
    NestedSet: { hasManyRoots: true, rootColumnName: root_id }
  columns:
    id:                { type: integer(20), autoincrement: true, primary: true }
    core_id:           { type: integer(20), notnull: false, default: null, comment: 'ид записи в Core' }
    core_parent_id:    { type: integer(20), notnull: false, default: null, comment: 'ид родителя записи в Core' }
    root_id:           { type: integer(20), notnull: true }
    lft:               { type: integer(20), notnull: true }
    rgt:               { type: integer(20), notnull: true }
    level:             { type: integer(4), notnull: true }
    token:             { type: string(255), unique: true, notnull: true, notblank: true }
    name:              { type: string(255), notnull: true, notblank: true }
    type:              { type: set, length: 10, values: [country, area, city], notnull: true, default: 'city', comment: 'Тип региона: страна, административная единица, город' }