Region:
  options:
    comment: 'Регион'
  actAs:
    NestedSet: { hasManyRoots: true, rootColumnName: root_id }
  columns:
    id:                { type: integer(20), autoincrement: true, primary: true }
    root_id:           { type: integer(20), notnull: true }
    token:             { type: string(255), unique: true, notnull: true, notblank: true }
    name:              { type: string(255), notnull: true, notblank: true }
    type:              { type: set, length: 10, values: [country, area, city], notnull: true, comment: 'Тип региона: страна, административная единица, город' }