TagGroup:
  options:
    comment: 'Группа тега'
  actAs: [ Timestampable ]
  columns:
    id:                { type: integer(20), autoincrement: true, primary: true }
    core_id:           { type: integer(20), notnull: false, default: null, comment: 'ид записи в Core' }
    token:             { type: string(255), unique: true, notnull: true, notblank: true }
    name:              { type: string(255), notnull: true, notblank: true }
    type:              { type: set, length: 10, values: [gift], notnull: false, default: null, comment: 'Тип группы тега' }
    position:          { type: integer(4), notnull: true, default: 1, comment: 'Порядок сортировки' }

Tag:
  options:
    comment: 'Тег'
  actAs: [ Timestampable ]
  columns:
    id:                { type: integer(20), autoincrement: true, primary: true }
    core_id:           { type: integer(20), notnull: false, default: null, comment: 'ид записи в Core' }
    group_id:          { type: integer(20), notnull: false, default: null }
    token:             { type: string(255), unique: true, notnull: true, notblank: true }
    name:              { type: string(255), notnull: true, notblank: true }
  relations:
    Group:             { class: TagGroup, foreignAlias: Tag, local: group_id, foreign: id, type: one, foreignType: many, onDelete: SET NULL }

TagProductRelation:
  options:
    comment: 'Связь тега и товара'
  actAs: [ Timestampable ]
  columns:
    tag_id:            { type: integer(20), primary: true, notnull: true }
    product_id:        { type: integer(20), primary: true, notnull: true }
  relations:
    Tag:               { class: Tag, foreignAlias: ProductRelation, local: tag_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }
    Product:           { class: Product, foreignAlias: TagRelation, local: product_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }

TagProductCategoryRelation:
  options:
    comment: 'Связь тега и категории товара'
  actAs: [ Timestampable ]
  columns:
    tag_id:              { type: integer(20), primary: true, notnull: true }
    product_category_id: { type: integer(20), primary: true, notnull: true }
  relations:
    Tag:                 { class: Tag, foreignAlias: ProductCategoryRelation, local: tag_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }
    ProductCategory:     { class: ProductCategory, foreignAlias: TagRelation, local: product_category_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }