Task:
  options:
    comment: 'Задача'
  actAs:
    Timestampable: ~
  columns:
    id:                { type: integer(20), autoincrement: true, primary: true }
    core_id:           { type: integer(20), notnull: false, default: null, comment: 'ид записи в Core' }
    type:              { type: enum, length: 20, values: ['project.init', 'project.sync', 'project.load'], notnull: false, default: null }
    priority:          { type: integer(4), notnull: true, default: 1, comment: 'Приоритет' }
    status:            { type: enum, length: 10, values: [run, pause, fail, success], notnull: true, default: run }
    content:           { type: string, notnull: false, default: null }
    attempt:           { type: integer(4), notnull: true, default: 0, comment: 'Номер неудачной попытки' }
    error:             { type: string, notnull: false, default: null }