User:
  options:
    comment: 'Пользователь'
  inheritance: { type: simple, extends: GuardUser }
  actAs: [ Timestampable, Corable ]
  columns:
#    core_id:           { type: integer(20), notnull: false, default: null, comment: 'ид записи в Core' }
    region_id:         { type: integer(20), notnull: false, default: null }
    type:              { type: enum, length: 10, values: [admin, client, partner], notnull: true, default: client }
    gender:            { type: enum, length: 6, values: [ mail, femail ], notnull: false, default: null, comment: 'Пол' }
    birthday:          { type: date, notnull: false, default: null, comment: 'Дата рождения' }
    photo:             { type: string(255), notnull: false, default: null, comment: 'Фото' }
    phonenumber_city:  { type: string(20), notnull: false, default: null, comment: 'Городской номер телефона' }
    skype:             { type: string(255), notnull: false, default: null, comment: 'Skype' }
    address:           { type: string, notnull: false, default: null, comment: 'Домашний адрес' }
    occupation:        { type: string(255), notnull: true, notblank: true, comment: 'Профессия' }
    settings:          { type: string, notnull: false, default: null, comment: 'Настройки личного кабинета' }
  relations:
    Region:            { class: Region, foreignAlias: User, local: region_id, foreign: id, type: one, foreignType: many, onDelete: SET NULL }

UserProfile:
  options:
    comment: 'Профайл пользователя'
  actAs: [ Timestampable, Corable ]
  columns:
    id:                { type: integer(20), autoincrement: true, primary: true }
    source_id:         { type: string(255), notnull: true, comment: 'Идентификатор в социальной сети' }
    type:              { type: enum, length: 14, values: [ vkontakte, facebook, twitter, odnoklassniki, gmail, mailru, live_journal, yandex ], notnull: false, default: null, comment: 'Тип профайла' }
    user_id:           { type: integer(20), notnull: true }
    content:           { type: string, notnull: false, default: null, comment: 'Данные пользователя в формате yaml' }
  relations:
    User:              { class: User, foreignAlias: Profile, local: user_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }

UserTag:
  options:
    comment: 'Пользовательские теги'
  actAs: [ Timestampable ]
  columns:
    id:                { type: integer(20), autoincrement: true, primary: true }
    core_id:           { type: integer(20), notnull: false, default: null, comment: 'ид записи в Core' }
    name:              { type: string(255), notnull: true, notblank: true }
    user_id:           { type: integer(20), notnull: true }
    position:          { type: integer(4), notnull: true, default: 1, comment: 'Порядок сортировки' }
  relations:
    User:              { class: User, foreignAlias: Tag, local: user_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }

UserTagProductRelation:
  options:
    comment: 'Связь пользовательских тегов и товаров'
  actAs: [ Timestampable ]
  columns:
    tag_id:            { type: integer(20), primary: true, notnull: true }
    product_id:        { type: integer(20), primary: true, notnull: true }
    position:          { type: integer(4), notnull: true, default: 1, comment: 'Порядок сортировки' }
  relations:
    Tag:               { class: UserTag, foreignAlias: ProductRelation, local: tag_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }
    Product:           { class: Product, foreignAlias: UserTagRelation, local: product_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }

UserDelayedProduct:
  options:
    comment: 'Отложенные товары пользователя'
  actAs: [ Timestampable ]
  columns:
    user_id:           { type: integer(20), primary: true, notnull: true }
    product_id:        { type: integer(20), primary: true, notnull: true }
    is_wished:         { type: boolean, notnull: true, default: false }
  relations:
    User:              { class: User, foreignAlias: DelayedProduct, local: user_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }
    Product:           { class: Product, foreignAlias: UserDelayedProduct, local: product_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }

UserProductNotice:
  options:
    comment: 'Пользовательские уведомления о товаре'
  actAs: [ Timestampable ]
  columns:
    core_id:           { type: integer(20), notnull: false, default: null, comment: 'ид записи в Core' }
    type:              { type: enum, length: 10, primary: true, values: [ insale, price, comment ], notnull: true, comment: 'Тип уведомления: товар появился в магазинах, изменилась цена, появились отзывы' }
    email:             { type: string(50), primary: true, notnull: true }
    product_id:        { type: integer(20), primary: true, notnull: true }
    user_id:           { type: integer(20), notnull: false, default: null }
  relations:
    User:              { class: User, foreignAlias: ProductNotice, local: user_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }
    Product:           { class: Product, foreignAlias: UserNotice, local: product_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }

UserProductRating:
  options:
    comment: 'Пользовательские оценки товара'
  actAs: [ Timestampable ]
  columns:
    property_id:       { type: integer(20), primary: true, notnull: true }
    user_id:           { type: integer(20), primary: true, notnull: true }
    product_id:        { type: integer(20), primary: true, notnull: true }
    value:             { type: 'decimal(18,14)', notnull: true, default: 0, comment: 'Рейтинг товара' }
  relations:
    Property:          { class: ProductRatingTypeProperty, foreignAlias: ProductRatingTypeProperty, local: property_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }
    User:              { class: User, foreignAlias: ProductRating, local: user_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }
    Product:           { class: Product, foreignAlias: UserRating, local: product_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }

UserAddress:
  options:
    comment: 'Адрес пользователя для доставки'
  actAs: [ Timestampable, Corable ]
  columns:
    id:                { type: integer(20), autoincrement: true, primary: true }
    user_id:           { type: integer(20), notnull: true }
    city_id:           { type: integer(20), notnull: true }
    name:              { type: string(255), notnull: false, default: null }
    address:           { type: string, notnull: true }
  relations:
    User:              { class: User, foreignAlias: Address, local: user_id, foreign: id, type: one, foreignType: many, onDelete: CASCADE }
    City:              { class: Region, foreignAlias: UserAddress, local: city_id, foreign: id, type: one, foreignType: many, onDelete: RESTRICT }
