generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Task
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          task
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [ id, type, priority, status, _content, created_at, updated_at ]
        sort: [ updated_at, desc ]
        actions:
          init: { label: Перегрузить данные, action: init, params: { confirm: 'Выполнить перезагрузку?' } }
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
