generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Task
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          task
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [ core_id, type, token, priority, status, _content, created_at, updated_at ]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
